// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/analytics.proto

package admin

import (
	"context"
	"errors"

	"shop/api/gen/go/admin"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

// AnalyticsService Admin 数据分析服务
type AnalyticsService struct {
	admin.UnimplementedAnalyticsServiceServer
	analyticsCase *biz.AnalyticsCase
}

// NewAnalyticsService 创建 Admin 数据分析服务
func NewAnalyticsService(
	analyticsCase *biz.AnalyticsCase,
) *AnalyticsService {
	return &AnalyticsService{
		analyticsCase: analyticsCase,
	}
}

// AnalyticsCountUser 查询汇总数据（用户）
func (s *AnalyticsService) AnalyticsCountUser(ctx context.Context, req *admin.AnalyticsCountRequest) (*admin.AnalyticsCountResponse, error) {
	res, err := s.analyticsCase.AnalyticsCountUser(ctx, req)
	if err != nil {
		log.Error("AnalyticsCountUser err:", err.Error())
		return nil, errors.New("查询汇总数据（用户）失败")
	}
	return res, nil
}

// AnalyticsCountGoods 查询汇总数据（商品）
func (s *AnalyticsService) AnalyticsCountGoods(ctx context.Context, req *admin.AnalyticsCountRequest) (*admin.AnalyticsCountResponse, error) {
	res, err := s.analyticsCase.AnalyticsCountGoods(ctx, req)
	if err != nil {
		log.Error("AnalyticsCountGoods err:", err.Error())
		return nil, errors.New("查询汇总数据（商品）失败")
	}
	return res, nil
}

// AnalyticsCountOrder 查询汇总数据（订单）
func (s *AnalyticsService) AnalyticsCountOrder(ctx context.Context, req *admin.AnalyticsCountRequest) (*admin.AnalyticsCountResponse, error) {
	res, err := s.analyticsCase.AnalyticsCountOrder(ctx, req)
	if err != nil {
		log.Error("AnalyticsCountOrder err:", err.Error())
		return nil, errors.New("查询汇总数据（订单）失败")
	}
	return res, nil
}

// AnalyticsCountSale 查询汇总数据（销量）
func (s *AnalyticsService) AnalyticsCountSale(ctx context.Context, req *admin.AnalyticsCountRequest) (*admin.AnalyticsCountResponse, error) {
	res, err := s.analyticsCase.AnalyticsCountSale(ctx, req)
	if err != nil {
		log.Error("AnalyticsCountSale err:", err.Error())
		return nil, errors.New("查询汇总数据（销量）失败")
	}
	return res, nil
}

// AnalyticsBarOrder 查询订单销量（柱状图）
func (s *AnalyticsService) AnalyticsBarOrder(ctx context.Context, req *admin.AnalyticsBarOrderRequest) (*admin.AnalyticsBarResponse, error) {
	res, err := s.analyticsCase.AnalyticsBarOrder(ctx, req)
	if err != nil {
		log.Error("AnalyticsBarOrder err:", err.Error())
		return nil, errors.New("查询订单销量（柱状图）失败")
	}
	return res, nil
}

// AnalyticsBarGoods 查询商品销量（柱状图）
func (s *AnalyticsService) AnalyticsBarGoods(ctx context.Context, req *admin.AnalyticsBarGoodsRequest) (*admin.AnalyticsBarResponse, error) {
	res, err := s.analyticsCase.AnalyticsBarGoods(ctx, req)
	if err != nil {
		log.Error("AnalyticsBarGoods err:", err.Error())
		return nil, errors.New("查询商品销量（柱状图）失败")
	}
	return res, nil
}

// AnalyticsPieGoods 查询商品分类（饼状图）
func (s *AnalyticsService) AnalyticsPieGoods(ctx context.Context, req *admin.AnalyticsPieGoodsRequest) (*admin.AnalyticsPieResponse, error) {
	res, err := s.analyticsCase.AnalyticsPieGoods(ctx, req)
	if err != nil {
		log.Error("AnalyticsPieGoods err:", err.Error())
		return nil, errors.New("查询商品分类（饼状图）失败")
	}
	return res, nil
}

// AnalyticsRadarOrder 查询商品订单销量状态（雷达图）
func (s *AnalyticsService) AnalyticsRadarOrder(ctx context.Context, req *admin.AnalyticsRadarOrderRequest) (*admin.AnalyticsRadarResponse, error) {
	res, err := s.analyticsCase.AnalyticsRadarOrder(ctx, req)
	if err != nil {
		log.Error("AnalyticsRadarOrder err:", err.Error())
		return nil, errors.New("查询商品订单销量状态（雷达图）失败")
	}
	return res, nil
}
