// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/auth.proto

package admin

import (
	"context"
	"errors"
	"shop/api/gen/go/common"

	"shop/api/gen/go/admin"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// AuthService Admin用户登录认证服务
type AuthService struct {
	admin.UnimplementedAuthServiceServer
	authCase *biz.AuthCase
}

// NewAuthService 创建Admin用户登录认证服务
func NewAuthService(
	authCase *biz.AuthCase,
) *AuthService {
	return &AuthService{
		authCase: authCase,
	}
}

// GetUserInfo 获取已经登录的用户的数据
func (s *AuthService) GetUserInfo(ctx context.Context, req *emptypb.Empty) (*admin.UserInfo, error) {
	res, err := s.authCase.GetUserInfo(ctx)
	if err != nil {
		log.Error("GetUserInfo err:", err.Error())
		return nil, err
	}
	return res, nil
}

// GetUserMenu 获取已经登录的用户菜单
func (s *AuthService) GetUserMenu(ctx context.Context, req *emptypb.Empty) (*admin.TreeRouteResponse, error) {
	res, err := s.authCase.GetUserMenu(ctx)
	if err != nil {
		log.Error("GetUserMenu err:", err.Error())
		return nil, err
	}
	return res, nil
}

// GetUserButton 获取已经登录的用户按钮
func (s *AuthService) GetUserButton(ctx context.Context, req *emptypb.Empty) (*common.StringValues, error) {
	res, err := s.authCase.GetUserButton(ctx)
	if err != nil {
		log.Error("GetUserButton err:", err.Error())
		return nil, err
	}
	return res, nil
}

// GetUserProfile 获取个人中心用户信息
func (s *AuthService) GetUserProfile(ctx context.Context, req *emptypb.Empty) (*admin.UserProfileForm, error) {
	res, err := s.authCase.GetUserProfile(ctx)
	if err != nil {
		log.Error("GetUserProfile err:", err.Error())
		return nil, err
	}
	return res, nil
}

// UpdateUserProfile 修改个人中心用户信息
func (s *AuthService) UpdateUserProfile(ctx context.Context, req *admin.UserProfileForm) (*emptypb.Empty, error) {
	err := s.authCase.UpdateUserProfile(ctx, req)
	if err != nil {
		log.Error("UpdateUserProfile err:", err.Error())
		return nil, errors.New("修改个人中心用户信息失败")
	}
	return new(emptypb.Empty), nil
}

// SendUpdatePhoneCode 发送手机号验证码
func (s *AuthService) SendUpdatePhoneCode(ctx context.Context, req *admin.SendUpdatePhoneCodeForm) (*emptypb.Empty, error) {
	err := s.authCase.SendUpdatePhoneCode(ctx, req)
	if err != nil {
		log.Error("SendUpdatePhoneCode err:", err.Error())
		return nil, errors.New("发送手机号验证码错误")
	}
	return new(emptypb.Empty), nil
}

// UpdateUserPhone 修改个人中心手机号
func (s *AuthService) UpdateUserPhone(ctx context.Context, req *admin.UpdatePhoneForm) (*emptypb.Empty, error) {
	err := s.authCase.UpdateUserPhone(ctx, req)
	if err != nil {
		log.Error("UpdateUserPhone err:", err.Error())
		return nil, errors.New("修改个人中心手机号失败")
	}

	return new(emptypb.Empty), nil
}

// UpdateUserPwd 修改个人中心密码
func (s *AuthService) UpdateUserPwd(ctx context.Context, req *admin.UpdatePwdForm) (*emptypb.Empty, error) {
	err := s.authCase.UpdateUserPwd(ctx, req)
	if err != nil {
		log.Error("UpdateUserPwd err:", err.Error())
		return nil, errors.New("重置密码失败")
	}
	return new(emptypb.Empty), nil
}
