// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/auth.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	commonv1 "shop/api/gen/go/common/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// AuthService Admin用户登录认证服务
type AuthService struct {
	adminv1.UnimplementedAuthServiceServer
	authCase *biz.AuthCase
}

// NewAuthService 创建Admin用户登录认证服务
func NewAuthService(
	authCase *biz.AuthCase,
) *AuthService {
	return &AuthService{
		authCase: authCase,
	}
}

// GetUserInfo 获取已经登录的用户的数据
func (s *AuthService) GetUserInfo(ctx context.Context, req *adminv1.GetUserInfoRequest) (*adminv1.UserInfoForm, error) {
	res, err := s.authCase.GetUserInfo(ctx)
	if err != nil {
		log.Errorf("GetUserInfo %v", err)
		return nil, errorsx.WrapInternal(err, "获取用户信息失败")
	}
	return res, nil
}

// TreeUserMenus 获取已经登录的用户菜单
func (s *AuthService) TreeUserMenus(ctx context.Context, req *adminv1.TreeUserMenusRequest) (*adminv1.TreeRouteResponse, error) {
	res, err := s.authCase.TreeUserMenus(ctx)
	if err != nil {
		log.Errorf("TreeUserMenus %v", err)
		return nil, errorsx.WrapInternal(err, "获取用户菜单失败")
	}
	return res, nil
}

// ListUserButtons 获取已经登录的用户按钮
func (s *AuthService) ListUserButtons(ctx context.Context, req *adminv1.ListUserButtonsRequest) (*commonv1.StringValues, error) {
	res, err := s.authCase.ListUserButtons(ctx)
	if err != nil {
		log.Errorf("ListUserButtons %v", err)
		return nil, errorsx.WrapInternal(err, "获取用户按钮权限失败")
	}
	return res, nil
}

// GetUserProfile 获取个人中心用户信息
func (s *AuthService) GetUserProfile(ctx context.Context, req *adminv1.GetUserProfileRequest) (*adminv1.UserProfileForm, error) {
	res, err := s.authCase.GetUserProfile(ctx)
	if err != nil {
		log.Errorf("GetUserProfile %v", err)
		return nil, errorsx.WrapInternal(err, "获取个人资料失败")
	}
	return res, nil
}

// UpdateUserProfile 修改个人中心用户信息
func (s *AuthService) UpdateUserProfile(ctx context.Context, req *adminv1.UpdateUserProfileRequest) (*emptypb.Empty, error) {
	err := s.authCase.UpdateUserProfile(ctx, req.GetUserProfile())
	if err != nil {
		log.Errorf("UpdateUserProfile %v", err)
		return nil, errorsx.WrapInternal(err, "修改个人中心用户信息失败")
	}
	return new(emptypb.Empty), nil
}

// SendPhoneCode 发送手机号验证码
func (s *AuthService) SendPhoneCode(ctx context.Context, req *adminv1.SendPhoneCodeRequest) (*emptypb.Empty, error) {
	err := s.authCase.SendPhoneCode(ctx, req)
	if err != nil {
		log.Errorf("SendPhoneCode %v", err)
		return nil, errorsx.WrapInternal(err, "发送手机号验证码失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateUserPhone 修改个人中心手机号
func (s *AuthService) UpdateUserPhone(ctx context.Context, req *adminv1.UpdateUserPhoneRequest) (*emptypb.Empty, error) {
	err := s.authCase.UpdateUserPhone(ctx, req.GetUserPhone())
	if err != nil {
		log.Errorf("UpdateUserPhone %v", err)
		return nil, errorsx.WrapInternal(err, "修改个人中心手机号失败")
	}

	return new(emptypb.Empty), nil
}

// UpdateUserPassword 修改个人中心密码
func (s *AuthService) UpdateUserPassword(ctx context.Context, req *adminv1.UpdateUserPasswordRequest) (*emptypb.Empty, error) {
	err := s.authCase.UpdateUserPassword(ctx, req.GetUserPassword())
	if err != nil {
		log.Errorf("UpdateUserPassword %v", err)
		return nil, errorsx.WrapInternal(err, "重置密码失败")
	}
	return new(emptypb.Empty), nil
}
