// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_menu.proto

package admin

import (
	"context"
	"errors"

	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseMenuService Admin菜单管理服务
type BaseMenuService struct {
	admin.UnimplementedBaseMenuServiceServer
	baseMenuCase *biz.BaseMenuCase
}

// NewBaseMenuService 创建Admin菜单管理服务
func NewBaseMenuService(
	menuCase *biz.BaseMenuCase,
) *BaseMenuService {
	return &BaseMenuService{
		baseMenuCase: menuCase,
	}
}

// TreeBaseMenu 查询菜单树形列表
func (s *BaseMenuService) TreeBaseMenu(ctx context.Context, req *emptypb.Empty) (*admin.TreeBaseMenuResponse, error) {
	tree, err := s.baseMenuCase.TreeBaseMenu(ctx)
	if err != nil {
		log.Error("TreeBaseMenu err:", err.Error())
		return nil, errors.New("查询菜单树形列表失败")
	}
	return tree, nil
}

// OptionBaseMenu 查询菜单树形选择
func (s *BaseMenuService) OptionBaseMenu(ctx context.Context, req *admin.OptionBaseMenuRequest) (*common.TreeOptionResponse, error) {
	tree, err := s.baseMenuCase.OptionBaseMenu(ctx, req)
	if err != nil {
		log.Error("OptionBaseMenu err:", err.Error())
		return nil, errors.New("查询菜单树形选择失败")
	}
	return tree, nil
}

// GetBaseMenu 查询菜单
func (s *BaseMenuService) GetBaseMenu(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseMenuForm, error) {
	baseMenu, err := s.baseMenuCase.GetBaseMenu(ctx, req.GetValue())
	if err != nil {
		log.Error("GetBaseMenu err:", err.Error())
		return nil, errors.New("查询菜单失败")
	}
	return baseMenu, nil
}

// CreateBaseMenu 创建菜单
func (s *BaseMenuService) CreateBaseMenu(ctx context.Context, req *admin.BaseMenuForm) (*emptypb.Empty, error) {
	err := s.baseMenuCase.CreateBaseMenu(ctx, req)
	if err != nil {
		log.Error("CreateBaseMenu err:", err.Error())
		return nil, errors.New("创建菜单失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateBaseMenu 更新菜单
func (s *BaseMenuService) UpdateBaseMenu(ctx context.Context, req *admin.BaseMenuForm) (*emptypb.Empty, error) {
	err := s.baseMenuCase.UpdateBaseMenu(ctx, req)
	if err != nil {
		log.Error("UpdateBaseMenu err:", err.Error())
		return nil, errors.New("更新菜单失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteBaseMenu 删除菜单
func (s *BaseMenuService) DeleteBaseMenu(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	err := s.baseMenuCase.DeleteBaseMenu(ctx, req.GetValue())
	if err != nil {
		log.Error("DeleteBaseMenu err:", err.Error())
		return nil, errors.New("删除菜单失败")
	}
	return new(emptypb.Empty), nil
}

// SetBaseMenuStatus 设置状态
func (s *BaseMenuService) SetBaseMenuStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.baseMenuCase.SetBaseMenuStatus(ctx, req)
	if err != nil {
		log.Error("SetBaseMenuStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return new(emptypb.Empty), nil
}
