// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_user.proto

package admin

import (
	"context"

	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseUserService Admin用户管理服务
type BaseUserService struct {
	admin.UnimplementedBaseUserServiceServer
	baseUserCase *biz.BaseUserCase
}

// NewBaseUserService 创建Admin用户管理服务
func NewBaseUserService(
	userCase *biz.BaseUserCase,
) *BaseUserService {
	return &BaseUserService{
		baseUserCase: userCase,
	}
}

// OptionBaseUser 查询用户下拉选择
func (s *BaseUserService) OptionBaseUser(ctx context.Context, req *admin.OptionBaseUserRequest) (*common.SelectOptionResponse, error) {
	list, err := s.baseUserCase.OptionBaseUser(ctx, req)
	if err != nil {
		log.Errorf("OptionBaseUser %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户下拉选择失败")
	}
	return list, nil
}

// PageBaseUser 查询用户分页列表
func (s *BaseUserService) PageBaseUser(ctx context.Context, req *admin.PageBaseUserRequest) (*admin.PageBaseUserResponse, error) {
	page, err := s.baseUserCase.PageBaseUser(ctx, req)
	if err != nil {
		log.Errorf("PageBaseUser %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户分页列表失败")
	}
	return page, nil
}

// GetBaseUser 查询用户
func (s *BaseUserService) GetBaseUser(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseUserForm, error) {
	baseUser, err := s.baseUserCase.GetBaseUser(ctx, req.GetValue())
	if err != nil {
		log.Errorf("GetBaseUser %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户失败")
	}
	return baseUser, nil
}

// CreateBaseUser 创建用户
func (s *BaseUserService) CreateBaseUser(ctx context.Context, req *admin.BaseUserForm) (*emptypb.Empty, error) {
	err := s.baseUserCase.CreateBaseUser(ctx, req)
	if err != nil {
		log.Errorf("CreateBaseUser %v", err)
		return nil, errorsx.WrapInternal(err, "创建用户失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateBaseUser 更新用户
func (s *BaseUserService) UpdateBaseUser(ctx context.Context, req *admin.BaseUserForm) (*emptypb.Empty, error) {
	err := s.baseUserCase.UpdateBaseUser(ctx, req)
	if err != nil {
		log.Errorf("UpdateBaseUser %v", err)
		return nil, errorsx.WrapInternal(err, "更新用户失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteBaseUser 删除用户
func (s *BaseUserService) DeleteBaseUser(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	err := s.baseUserCase.DeleteBaseUser(ctx, req.GetValue())
	if err != nil {
		log.Errorf("DeleteBaseUser %v", err)
		return nil, errorsx.WrapInternal(err, "删除用户失败")
	}
	return new(emptypb.Empty), nil
}

// SetBaseUserStatus 设置状态
func (s *BaseUserService) SetBaseUserStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.baseUserCase.SetBaseUserStatus(ctx, req)
	if err != nil {
		log.Errorf("SetBaseUserStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}

// ResetBaseUserPassword 重置密码
func (s *BaseUserService) ResetBaseUserPassword(ctx context.Context, req *admin.ResetBaseUserPasswordRequest) (*emptypb.Empty, error) {
	err := s.baseUserCase.ResetBaseUserPassword(ctx, req)
	if err != nil {
		log.Errorf("ResetBaseUserPassword %v", err)
		return nil, errorsx.WrapInternal(err, "重置密码失败")
	}
	return new(emptypb.Empty), nil
}
