// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_config.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseConfigService Admin系统配置服务
type BaseConfigService struct {
	adminv1.UnimplementedBaseConfigServiceServer
	baseConfigCase *biz.BaseConfigCase
}

// NewBaseConfigService 创建Admin系统配置服务
func NewBaseConfigService(
	configCase *biz.BaseConfigCase,
) (*BaseConfigService, error) {
	var ss = BaseConfigService{
		baseConfigCase: configCase,
	}
	// 服务启动，刷新缓存
	_, err := ss.RefreshBaseConfigCache(context.Background(), new(adminv1.RefreshBaseConfigCacheRequest))
	if err != nil {
		log.Errorf("NewBaseConfigService %v", err)
		return nil, errorsx.WrapInternal(err, "初始化系统配置缓存失败")
	}
	return &ss, nil
}

// RefreshBaseConfigCache 刷新缓存
func (s *BaseConfigService) RefreshBaseConfigCache(ctx context.Context, req *adminv1.RefreshBaseConfigCacheRequest) (*emptypb.Empty, error) {
	err := s.baseConfigCase.RefreshBaseConfig(ctx)
	if err != nil {
		log.Errorf("RefreshBaseConfig %v", err)
		return nil, errorsx.WrapInternal(err, "刷新缓存失败")
	}
	return new(emptypb.Empty), nil
}

// PageBaseConfigs 查询系统配置分页列表
func (s *BaseConfigService) PageBaseConfigs(ctx context.Context, req *adminv1.PageBaseConfigsRequest) (*adminv1.PageBaseConfigsResponse, error) {
	page, err := s.baseConfigCase.PageBaseConfigs(ctx, req)
	if err != nil {
		log.Errorf("PageBaseConfigs %v", err)
		return nil, errorsx.WrapInternal(err, "查询系统配置分页列表失败")
	}

	return page, nil
}

// GetBaseConfig 查询系统配置
func (s *BaseConfigService) GetBaseConfig(ctx context.Context, req *adminv1.GetBaseConfigRequest) (*adminv1.BaseConfigForm, error) {
	config, err := s.baseConfigCase.GetBaseConfig(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetBaseConfig %v", err)
		return nil, errorsx.WrapInternal(err, "查询系统配置失败")
	}
	return config, nil
}

// CreateBaseConfig 创建系统配置
func (s *BaseConfigService) CreateBaseConfig(ctx context.Context, req *adminv1.CreateBaseConfigRequest) (*emptypb.Empty, error) {
	err := s.baseConfigCase.CreateBaseConfig(ctx, req.GetBaseConfig())
	if err != nil {
		log.Errorf("CreateBaseConfig %v", err)
		return nil, errorsx.WrapInternal(err, "创建系统配置失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateBaseConfig 更新系统配置
func (s *BaseConfigService) UpdateBaseConfig(ctx context.Context, req *adminv1.UpdateBaseConfigRequest) (*emptypb.Empty, error) {
	err := s.baseConfigCase.UpdateBaseConfig(ctx, req.GetBaseConfig())
	if err != nil {
		log.Errorf("UpdateBaseConfig %v", err)
		return nil, errorsx.WrapInternal(err, "更新系统配置失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteBaseConfig 删除系统配置
func (s *BaseConfigService) DeleteBaseConfig(ctx context.Context, req *adminv1.DeleteBaseConfigRequest) (*emptypb.Empty, error) {
	err := s.baseConfigCase.DeleteBaseConfig(ctx, req.GetId())
	if err != nil {
		log.Errorf("DeleteBaseConfig %v", err)
		return nil, errorsx.WrapInternal(err, "删除系统配置失败")
	}
	return new(emptypb.Empty), nil
}

// SetBaseConfigStatus 设置状态
func (s *BaseConfigService) SetBaseConfigStatus(ctx context.Context, req *adminv1.SetBaseConfigStatusRequest) (*emptypb.Empty, error) {
	err := s.baseConfigCase.SetBaseConfigStatus(ctx, req)
	if err != nil {
		log.Errorf("SetBaseConfigStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}
