// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_dept.proto

package admin

import (
	"context"
	"errors"

	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseDeptService Admin部门服务
type BaseDeptService struct {
	admin.UnimplementedBaseDeptServiceServer
	baseDeptCase *biz.BaseDeptCase
}

// NewBaseDeptService 创建Admin部门服务
func NewBaseDeptService(
	deptCase *biz.BaseDeptCase,
) *BaseDeptService {
	return &BaseDeptService{
		baseDeptCase: deptCase,
	}
}

// TreeBaseDept 查询部门树形列表
func (s *BaseDeptService) TreeBaseDept(ctx context.Context, req *emptypb.Empty) (*admin.TreeBaseDeptResponse, error) {
	tree, err := s.baseDeptCase.TreeBaseDept(ctx)
	if err != nil {
		log.Error("TreeBaseDept err:", err.Error())
		return nil, errors.New("查询部门树形列表失败")
	}

	return tree, nil
}

// OptionBaseDept 查询部门树形选择
func (s *BaseDeptService) OptionBaseDept(ctx context.Context, req *admin.OptionBaseDeptRequest) (*common.TreeOptionResponse, error) {
	tree, err := s.baseDeptCase.OptionBaseDept(ctx, req)
	if err != nil {
		log.Error("OptionBaseDept err:", err.Error())
		return nil, errors.New("查询部门树形选择失败")
	}
	return tree, nil
}

// GetBaseDept 查询部门
func (s *BaseDeptService) GetBaseDept(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseDeptForm, error) {
	baseDept, err := s.baseDeptCase.GetBaseDept(ctx, req.GetValue())
	if err != nil {
		log.Error("GetBaseDept err:", err.Error())
		return nil, errors.New("查询部门失败")
	}
	return baseDept, nil
}

// CreateBaseDept 创建部门
func (s *BaseDeptService) CreateBaseDept(ctx context.Context, req *admin.BaseDeptForm) (*emptypb.Empty, error) {
	err := s.baseDeptCase.CreateBaseDept(ctx, req)
	if err != nil {
		log.Error("CreateBaseDept err:", err.Error())
		return nil, errors.New("创建部门失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateBaseDept 更新部门
func (s *BaseDeptService) UpdateBaseDept(ctx context.Context, req *admin.BaseDeptForm) (*emptypb.Empty, error) {
	err := s.baseDeptCase.UpdateBaseDept(ctx, req)
	if err != nil {
		log.Error("UpdateBaseDept err:", err.Error())
		return nil, errors.New("更新部门失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteBaseDept 删除部门
func (s *BaseDeptService) DeleteBaseDept(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	err := s.baseDeptCase.DeleteBaseDept(ctx, req.GetValue())
	if err != nil {
		log.Error("DeleteBaseDept err:", err.Error())
		return nil, errors.New("删除部门失败")
	}
	return new(emptypb.Empty), nil
}

// SetBaseDeptStatus 设置状态
func (s *BaseDeptService) SetBaseDeptStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.baseDeptCase.SetBaseDeptStatus(ctx, req)
	if err != nil {
		log.Error("SetBaseDeptStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return new(emptypb.Empty), nil
}
