// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_log.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

// BaseLogService Admin日志服务
type BaseLogService struct {
	adminv1.UnimplementedBaseLogServiceServer
	baseLogCase *biz.BaseLogCase
}

// NewBaseLogService 创建Admin日志服务
func NewBaseLogService(
	logCase *biz.BaseLogCase,
) *BaseLogService {
	return &BaseLogService{
		baseLogCase: logCase,
	}
}

// PageBaseLogs 查询日志分页列表
func (s *BaseLogService) PageBaseLogs(ctx context.Context, req *adminv1.PageBaseLogsRequest) (*adminv1.PageBaseLogsResponse, error) {
	page, err := s.baseLogCase.PageBaseLogs(ctx, req)
	if err != nil {
		log.Errorf("PageBaseLogs %v", err)
		return nil, errorsx.WrapInternal(err, "查询日志分页列表失败")
	}

	return page, nil
}

// GetBaseLog 查询日志
func (s *BaseLogService) GetBaseLog(ctx context.Context, req *adminv1.GetBaseLogRequest) (*adminv1.BaseLog, error) {
	res, err := s.baseLogCase.GetBaseLog(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetBaseLog %v", err)
		return nil, errorsx.WrapInternal(err, "查询日志失败")
	}
	return res, nil
}
