// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_job.proto

package admin

import (
	"context"

	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseJobService Admin定时任务服务
type BaseJobService struct {
	admin.UnimplementedBaseJobServiceServer
	baseJobCase    *biz.BaseJobCase
	baseJobLogCase *biz.BaseJobLogCase
}

// NewBaseJobService 创建Admin定时任务服务
func NewBaseJobService(
	baseJobCase *biz.BaseJobCase,
	baseJobLogCase *biz.BaseJobLogCase,
) *BaseJobService {
	return &BaseJobService{
		baseJobCase:    baseJobCase,
		baseJobLogCase: baseJobLogCase,
	}
}

// PageBaseJob 查询定时任务分页列表
func (s *BaseJobService) PageBaseJob(ctx context.Context, req *admin.PageBaseJobRequest) (*admin.PageBaseJobResponse, error) {
	page, err := s.baseJobCase.PageBaseJob(ctx, req)
	if err != nil {
		log.Errorf("PageBaseJob %v", err)
		return nil, errorsx.WrapInternal(err, "查询定时任务分页列表失败")
	}
	return page, nil
}

// GetBaseJob 查询定时任务
func (s *BaseJobService) GetBaseJob(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseJobForm, error) {
	baseJob, err := s.baseJobCase.GetBaseJob(ctx, req.GetValue())
	if err != nil {
		log.Errorf("GetBaseJob %v", err)
		return nil, errorsx.WrapInternal(err, "查询定时任务失败")
	}
	return baseJob, nil
}

// CreateBaseJob 创建定时任务
func (s *BaseJobService) CreateBaseJob(ctx context.Context, req *admin.BaseJobForm) (*emptypb.Empty, error) {
	err := s.baseJobCase.CreateBaseJob(ctx, req)
	if err != nil {
		log.Errorf("CreateBaseJob %v", err)
		// 命中调用目标唯一索引冲突时，返回更明确的业务错误。
		if errorsx.IsMySQLDuplicateKey(err) {
			return nil, errorsx.UniqueConflict("调用目标重复", "base_job", "invoke_target", "unique_base_job").WithCause(err)
		}
		return nil, errorsx.WrapInternal(err, "创建定时任务失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateBaseJob 更新定时任务
func (s *BaseJobService) UpdateBaseJob(ctx context.Context, req *admin.BaseJobForm) (*emptypb.Empty, error) {
	err := s.baseJobCase.UpdateBaseJob(ctx, req)
	if err != nil {
		log.Errorf("UpdateBaseJob %v", err)
		// 命中调用目标唯一索引冲突时，返回更明确的业务错误。
		if errorsx.IsMySQLDuplicateKey(err) {
			return nil, errorsx.UniqueConflict("调用目标重复", "base_job", "invoke_target", "unique_base_job").WithCause(err)
		}
		return nil, errorsx.WrapInternal(err, "更新定时任务失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteBaseJob 删除定时任务
func (s *BaseJobService) DeleteBaseJob(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	err := s.baseJobCase.DeleteBaseJob(ctx, req.GetValue())
	if err != nil {
		log.Errorf("DeleteBaseJob %v", err)
		return nil, errorsx.WrapInternal(err, "删除定时任务失败")
	}
	return new(emptypb.Empty), nil
}

// SetBaseJobStatus 设置状态
func (s *BaseJobService) SetBaseJobStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.baseJobCase.SetBaseJobStatus(ctx, req)
	if err != nil {
		log.Errorf("SetBaseJobStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}

// StartBaseJob 启动任务
func (s *BaseJobService) StartBaseJob(ctx context.Context, req *admin.StartBaseJobRequest) (*emptypb.Empty, error) {
	err := s.baseJobCase.StartBaseJob(ctx, req)
	if err != nil {
		log.Errorf("StartBaseJob %v", err)
		return nil, errorsx.WrapInternal(err, "启动任务失败")
	}
	return new(emptypb.Empty), nil
}

// StopBaseJob 停止任务
func (s *BaseJobService) StopBaseJob(ctx context.Context, req *admin.StopBaseJobRequest) (*emptypb.Empty, error) {
	err := s.baseJobCase.StopBaseJob(ctx, req)
	if err != nil {
		log.Errorf("StopBaseJob %v", err)
		return nil, errorsx.WrapInternal(err, "停止任务失败")
	}
	return new(emptypb.Empty), nil
}

// ExecuteBaseJob 执行任务
func (s *BaseJobService) ExecuteBaseJob(ctx context.Context, req *admin.ExecuteBaseJobRequest) (*emptypb.Empty, error) {
	err := s.baseJobCase.ExecuteBaseJob(ctx, req)
	if err != nil {
		log.Errorf("ExecuteBaseJob %v", err)
		return nil, errorsx.WrapInternal(err, "执行任务失败")
	}
	return new(emptypb.Empty), nil
}

// PageBaseJobLog 查询定时任务日志分页列表
func (s *BaseJobService) PageBaseJobLog(ctx context.Context, req *admin.PageBaseJobLogRequest) (*admin.PageBaseJobLogResponse, error) {
	page, err := s.baseJobLogCase.PageBaseJobLog(ctx, req)
	if err != nil {
		log.Errorf("PageBaseJobLog %v", err)
		return nil, errorsx.WrapInternal(err, "查询定时任务日志分页列表失败")
	}

	return page, nil
}

// GetBaseJobLog 查询定时任务日志
func (s *BaseJobService) GetBaseJobLog(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseJobLog, error) {
	baseLog, err := s.baseJobLogCase.GetBaseJobLog(ctx, req.GetValue())
	if err != nil {
		log.Errorf("GetBaseJobLog %v", err)
		return nil, errorsx.WrapInternal(err, "查询定时任务日志失败")
	}
	return baseLog, nil
}
