// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_dict.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseDictService Admin字典服务
type BaseDictService struct {
	adminv1.UnimplementedBaseDictServiceServer
	baseDictCase     *biz.BaseDictCase
	baseDictItemCase *biz.BaseDictItemCase
}

// NewBaseDictService 创建Admin字典服务
func NewBaseDictService(
	dictCase *biz.BaseDictCase,
	baseDictItemCase *biz.BaseDictItemCase,
) *BaseDictService {
	return &BaseDictService{
		baseDictCase:     dictCase,
		baseDictItemCase: baseDictItemCase,
	}
}

// OptionBaseDicts 查询字典下拉选择
func (s *BaseDictService) OptionBaseDicts(ctx context.Context, req *adminv1.OptionBaseDictsRequest) (*adminv1.OptionBaseDictsResponse, error) {
	res, err := s.baseDictCase.OptionBaseDicts(ctx)
	if err != nil {
		log.Errorf("OptionBaseDicts %v", err)
		return nil, errorsx.WrapInternal(err, "查询失败")
	}
	return res, nil
}

// PageBaseDicts 查询字典分页列表
func (s *BaseDictService) PageBaseDicts(ctx context.Context, req *adminv1.PageBaseDictsRequest) (*adminv1.PageBaseDictsResponse, error) {
	page, err := s.baseDictCase.PageBaseDicts(ctx, req)
	if err != nil {
		log.Errorf("PageBaseDicts %v", err)
		return nil, errorsx.WrapInternal(err, "查询字典分页列表失败")
	}

	return page, nil
}

// GetBaseDict 查询字典
func (s *BaseDictService) GetBaseDict(ctx context.Context, req *adminv1.GetBaseDictRequest) (*adminv1.BaseDictForm, error) {
	baseDict, err := s.baseDictCase.GetBaseDict(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetBaseDict %v", err)
		return nil, errorsx.WrapInternal(err, "查询字典失败")
	}

	return baseDict, nil
}

// CreateBaseDict 创建字典
func (s *BaseDictService) CreateBaseDict(ctx context.Context, req *adminv1.CreateBaseDictRequest) (*emptypb.Empty, error) {
	err := s.baseDictCase.CreateBaseDict(ctx, req.GetBaseDict())
	if err != nil {
		log.Errorf("CreateBaseDict %v", err)
		return nil, errorsx.WrapInternal(err, "创建字典失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateBaseDict 更新字典
func (s *BaseDictService) UpdateBaseDict(ctx context.Context, req *adminv1.UpdateBaseDictRequest) (*emptypb.Empty, error) {
	err := s.baseDictCase.UpdateBaseDict(ctx, req.GetBaseDict())
	if err != nil {
		log.Errorf("UpdateBaseDict %v", err)
		return nil, errorsx.WrapInternal(err, "更新字典失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteBaseDict 删除字典
func (s *BaseDictService) DeleteBaseDict(ctx context.Context, req *adminv1.DeleteBaseDictRequest) (*emptypb.Empty, error) {
	err := s.baseDictCase.DeleteBaseDict(ctx, req.GetId())
	if err != nil {
		log.Errorf("DeleteBaseDict %v", err)
		return nil, errorsx.WrapInternal(err, "删除字典失败")
	}
	return new(emptypb.Empty), nil
}

// SetBaseDictStatus 设置状态
func (s *BaseDictService) SetBaseDictStatus(ctx context.Context, req *adminv1.SetBaseDictStatusRequest) (*emptypb.Empty, error) {
	err := s.baseDictCase.SetBaseDictStatus(ctx, req)
	if err != nil {
		log.Errorf("SetBaseDictStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}

// PageBaseDictItems 查询字典属性分页列表
func (s *BaseDictService) PageBaseDictItems(ctx context.Context, req *adminv1.PageBaseDictItemsRequest) (*adminv1.PageBaseDictItemsResponse, error) {
	page, err := s.baseDictItemCase.PageBaseDictItems(ctx, req)
	if err != nil {
		log.Errorf("PageBaseDictItems %v", err)
		return nil, errorsx.WrapInternal(err, "查询字典属性分页列表失败")
	}
	return page, nil
}

// GetBaseDictItem 查询字典属性
func (s *BaseDictService) GetBaseDictItem(ctx context.Context, req *adminv1.GetBaseDictItemRequest) (*adminv1.BaseDictItemForm, error) {
	baseDictItem, err := s.baseDictItemCase.GetBaseDictItem(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetBaseDictItem %v", err)
		return nil, errorsx.WrapInternal(err, "查询字典属性失败")
	}
	return baseDictItem, nil
}

// CreateBaseDictItem 创建字典属性
func (s *BaseDictService) CreateBaseDictItem(ctx context.Context, req *adminv1.CreateBaseDictItemRequest) (*emptypb.Empty, error) {
	err := s.baseDictItemCase.CreateBaseDictItem(ctx, req.GetBaseDictItem())
	if err != nil {
		log.Errorf("CreateBaseDictItem %v", err)
		return nil, errorsx.WrapInternal(err, "创建字典属性失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateBaseDictItem 更新字典属性
func (s *BaseDictService) UpdateBaseDictItem(ctx context.Context, req *adminv1.UpdateBaseDictItemRequest) (*emptypb.Empty, error) {
	err := s.baseDictItemCase.UpdateBaseDictItem(ctx, req.GetBaseDictItem())
	if err != nil {
		log.Errorf("UpdateBaseDictItem %v", err)
		return nil, errorsx.WrapInternal(err, "更新字典属性失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteBaseDictItem 删除字典属性
func (s *BaseDictService) DeleteBaseDictItem(ctx context.Context, req *adminv1.DeleteBaseDictItemRequest) (*emptypb.Empty, error) {
	err := s.baseDictItemCase.DeleteBaseDictItem(ctx, req.GetId())
	if err != nil {
		log.Errorf("DeleteBaseDictItem %v", err)
		return nil, errorsx.WrapInternal(err, "删除字典属性失败")
	}
	return new(emptypb.Empty), nil
}

// SetBaseDictItemStatus 设置状态
func (s *BaseDictService) SetBaseDictItemStatus(ctx context.Context, req *adminv1.SetBaseDictItemStatusRequest) (*emptypb.Empty, error) {
	err := s.baseDictItemCase.SetBaseDictItemStatus(ctx, req)
	if err != nil {
		log.Errorf("SetBaseDictItemStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}
