// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_menu.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	commonv1 "shop/api/gen/go/common/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseMenuService Admin菜单管理服务
type BaseMenuService struct {
	adminv1.UnimplementedBaseMenuServiceServer
	baseMenuCase *biz.BaseMenuCase
}

// NewBaseMenuService 创建Admin菜单管理服务
func NewBaseMenuService(
	menuCase *biz.BaseMenuCase,
) *BaseMenuService {
	return &BaseMenuService{
		baseMenuCase: menuCase,
	}
}

// TreeBaseMenus 查询菜单树形列表
func (s *BaseMenuService) TreeBaseMenus(ctx context.Context, req *adminv1.TreeBaseMenusRequest) (*adminv1.TreeBaseMenusResponse, error) {
	tree, err := s.baseMenuCase.TreeBaseMenus(ctx)
	if err != nil {
		log.Errorf("TreeBaseMenus %v", err)
		return nil, errorsx.WrapInternal(err, "查询菜单树形列表失败")
	}
	return tree, nil
}

// OptionBaseMenus 查询菜单树形选择
func (s *BaseMenuService) OptionBaseMenus(ctx context.Context, req *adminv1.OptionBaseMenusRequest) (*commonv1.TreeOptionResponse, error) {
	tree, err := s.baseMenuCase.OptionBaseMenus(ctx, req)
	if err != nil {
		log.Errorf("OptionBaseMenus %v", err)
		return nil, errorsx.WrapInternal(err, "查询菜单树形选择失败")
	}
	return tree, nil
}

// GetBaseMenu 查询菜单
func (s *BaseMenuService) GetBaseMenu(ctx context.Context, req *adminv1.GetBaseMenuRequest) (*adminv1.BaseMenuForm, error) {
	baseMenu, err := s.baseMenuCase.GetBaseMenu(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetBaseMenu %v", err)
		return nil, errorsx.WrapInternal(err, "查询菜单失败")
	}
	return baseMenu, nil
}

// CreateBaseMenu 创建菜单
func (s *BaseMenuService) CreateBaseMenu(ctx context.Context, req *adminv1.CreateBaseMenuRequest) (*emptypb.Empty, error) {
	err := s.baseMenuCase.CreateBaseMenu(ctx, req.GetBaseMenu())
	if err != nil {
		log.Errorf("CreateBaseMenu %v", err)
		return nil, errorsx.WrapInternal(err, "创建菜单失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateBaseMenu 更新菜单
func (s *BaseMenuService) UpdateBaseMenu(ctx context.Context, req *adminv1.UpdateBaseMenuRequest) (*emptypb.Empty, error) {
	err := s.baseMenuCase.UpdateBaseMenu(ctx, req.GetBaseMenu())
	if err != nil {
		log.Errorf("UpdateBaseMenu %v", err)
		return nil, errorsx.WrapInternal(err, "更新菜单失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteBaseMenu 删除菜单
func (s *BaseMenuService) DeleteBaseMenu(ctx context.Context, req *adminv1.DeleteBaseMenuRequest) (*emptypb.Empty, error) {
	err := s.baseMenuCase.DeleteBaseMenu(ctx, req.GetId())
	if err != nil {
		log.Errorf("DeleteBaseMenu %v", err)
		return nil, errorsx.WrapInternal(err, "删除菜单失败")
	}
	return new(emptypb.Empty), nil
}

// SetBaseMenuStatus 设置状态
func (s *BaseMenuService) SetBaseMenuStatus(ctx context.Context, req *adminv1.SetBaseMenuStatusRequest) (*emptypb.Empty, error) {
	err := s.baseMenuCase.SetBaseMenuStatus(ctx, req)
	if err != nil {
		log.Errorf("SetBaseMenuStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}
