// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_log.proto

package admin

import (
	"context"
	"errors"

	"shop/api/gen/go/admin"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseLogService Admin日志服务
type BaseLogService struct {
	admin.UnimplementedBaseLogServiceServer
	baseLogCase *biz.BaseLogCase
}

// NewBaseLogService 创建Admin日志服务
func NewBaseLogService(
	logCase *biz.BaseLogCase,
) *BaseLogService {
	return &BaseLogService{
		baseLogCase: logCase,
	}
}

// PageBaseLog 查询日志分页列表
func (s *BaseLogService) PageBaseLog(ctx context.Context, req *admin.PageBaseLogRequest) (*admin.PageBaseLogResponse, error) {
	page, err := s.baseLogCase.PageBaseLog(ctx, req)
	if err != nil {
		log.Error("PageBaseLog err:", err.Error())
		return nil, errors.New("查询日志分页列表失败")
	}

	return page, nil
}

// GetBaseLog 查询日志
func (s *BaseLogService) GetBaseLog(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseLog, error) {
	res, err := s.baseLogCase.GetBaseLog(ctx, req.GetValue())
	if err != nil {
		log.Error("GetBaseLog err:", err.Error())
		return nil, errors.New("查询日志失败")
	}
	return res, nil
}
