// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_dept.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	commonv1 "shop/api/gen/go/common/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseDeptService Admin部门服务
type BaseDeptService struct {
	adminv1.UnimplementedBaseDeptServiceServer
	baseDeptCase *biz.BaseDeptCase
}

// NewBaseDeptService 创建Admin部门服务
func NewBaseDeptService(
	deptCase *biz.BaseDeptCase,
) *BaseDeptService {
	return &BaseDeptService{
		baseDeptCase: deptCase,
	}
}

// TreeBaseDepts 查询部门树形列表
func (s *BaseDeptService) TreeBaseDepts(ctx context.Context, req *adminv1.TreeBaseDeptsRequest) (*adminv1.TreeBaseDeptsResponse, error) {
	tree, err := s.baseDeptCase.TreeBaseDepts(ctx)
	if err != nil {
		log.Errorf("TreeBaseDepts %v", err)
		return nil, errorsx.WrapInternal(err, "查询部门树形列表失败")
	}

	return tree, nil
}

// OptionBaseDepts 查询部门树形选择
func (s *BaseDeptService) OptionBaseDepts(ctx context.Context, req *adminv1.OptionBaseDeptsRequest) (*commonv1.TreeOptionResponse, error) {
	tree, err := s.baseDeptCase.OptionBaseDepts(ctx, req)
	if err != nil {
		log.Errorf("OptionBaseDepts %v", err)
		return nil, errorsx.WrapInternal(err, "查询部门树形选择失败")
	}
	return tree, nil
}

// GetBaseDept 查询部门
func (s *BaseDeptService) GetBaseDept(ctx context.Context, req *adminv1.GetBaseDeptRequest) (*adminv1.BaseDeptForm, error) {
	baseDept, err := s.baseDeptCase.GetBaseDept(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetBaseDept %v", err)
		return nil, errorsx.WrapInternal(err, "查询部门失败")
	}
	return baseDept, nil
}

// CreateBaseDept 创建部门
func (s *BaseDeptService) CreateBaseDept(ctx context.Context, req *adminv1.CreateBaseDeptRequest) (*emptypb.Empty, error) {
	err := s.baseDeptCase.CreateBaseDept(ctx, req.GetBaseDept())
	if err != nil {
		log.Errorf("CreateBaseDept %v", err)
		return nil, errorsx.WrapInternal(err, "创建部门失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateBaseDept 更新部门
func (s *BaseDeptService) UpdateBaseDept(ctx context.Context, req *adminv1.UpdateBaseDeptRequest) (*emptypb.Empty, error) {
	err := s.baseDeptCase.UpdateBaseDept(ctx, req.GetBaseDept())
	if err != nil {
		log.Errorf("UpdateBaseDept %v", err)
		return nil, errorsx.WrapInternal(err, "更新部门失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteBaseDept 删除部门
func (s *BaseDeptService) DeleteBaseDept(ctx context.Context, req *adminv1.DeleteBaseDeptRequest) (*emptypb.Empty, error) {
	err := s.baseDeptCase.DeleteBaseDept(ctx, req.GetId())
	if err != nil {
		log.Errorf("DeleteBaseDept %v", err)
		return nil, errorsx.WrapInternal(err, "删除部门失败")
	}
	return new(emptypb.Empty), nil
}

// SetBaseDeptStatus 设置状态
func (s *BaseDeptService) SetBaseDeptStatus(ctx context.Context, req *adminv1.SetBaseDeptStatusRequest) (*emptypb.Empty, error) {
	err := s.baseDeptCase.SetBaseDeptStatus(ctx, req)
	if err != nil {
		log.Errorf("SetBaseDeptStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}
