// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/goods_spec.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsSpecService Admin商品规格服务
type GoodsSpecService struct {
	adminv1.UnimplementedGoodsSpecServiceServer
	goodsSpecCase *biz.GoodsSpecCase
}

// NewGoodsSpecService 创建Admin商品规格服务
func NewGoodsSpecService(
	goodsSpecCase *biz.GoodsSpecCase,
) *GoodsSpecService {
	return &GoodsSpecService{
		goodsSpecCase: goodsSpecCase,
	}
}

// ListGoodsSpecs 查询商品规格列表
func (s *GoodsSpecService) ListGoodsSpecs(ctx context.Context, req *adminv1.ListGoodsSpecsRequest) (*adminv1.ListGoodsSpecsResponse, error) {
	list, err := s.goodsSpecCase.ListGoodsSpecs(ctx, req)
	if err != nil {
		log.Errorf("ListGoodsSpecs %v", err)
		return nil, errorsx.WrapInternal(err, "查询规格列表失败")
	}
	return list, nil
}
