// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/goods_sku.proto

package admin

import (
	"context"
	"fmt"

	adminv1 "shop/api/gen/go/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v3/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsSkuService Admin商品SKU服务
type GoodsSkuService struct {
	adminv1.UnimplementedGoodsSkuServiceServer
	goodsSKUCase *biz.GoodsSKUCase
}

// NewGoodsSkuService 创建Admin商品SKU服务
func NewGoodsSkuService(goodsSKUCase *biz.GoodsSKUCase) *GoodsSkuService {
	return &GoodsSkuService{
		goodsSKUCase: goodsSKUCase,
	}
}

// PageGoodsSku 查询商品SKU列表
func (s *GoodsSkuService) PageGoodsSku(ctx context.Context, req *adminv1.PageGoodsSkuRequest) (*adminv1.PageGoodsSkuResponse, error) {
	page, err := s.goodsSKUCase.ListGoodsSKUs(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("PageGoodsSku %v", err))
		return nil, errorsx.WrapInternal(err, "查询商品SKU列表失败")
	}
	return page, nil
}

// GetGoodsSku 查询商品SKU
func (s *GoodsSkuService) GetGoodsSku(ctx context.Context, req *adminv1.GetGoodsSkuRequest) (*adminv1.GoodsSku, error) {
	goodsSKU, err := s.goodsSKUCase.GetGoodsSKU(ctx, req.GetId())
	if err != nil {
		log.Error(fmt.Sprintf("GetGoodsSku %v", err))
		return nil, errorsx.WrapInternal(err, "查询商品SKU失败")
	}
	return goodsSKU, nil
}

// UpdateGoodsSku 更新商品SKU
func (s *GoodsSkuService) UpdateGoodsSku(ctx context.Context, req *adminv1.UpdateGoodsSkuRequest) (*emptypb.Empty, error) {
	err := s.goodsSKUCase.UpdateGoodsSKU(ctx, req.GetGoodsSku())
	if err != nil {
		log.Error(fmt.Sprintf("UpdateGoodsSku %v", err))
		return nil, errorsx.WrapInternal(err, "更新商品SKU失败")
	}
	return new(emptypb.Empty), nil
}
