// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/goods_info.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsInfoService Admin商品信息服务
type GoodsInfoService struct {
	adminv1.UnimplementedGoodsInfoServiceServer
	goodsInfoCase *biz.GoodsInfoCase
}

// NewGoodsInfoService 创建Admin商品信息服务
func NewGoodsInfoService(
	goodsInfoCase *biz.GoodsInfoCase,
) *GoodsInfoService {
	return &GoodsInfoService{
		goodsInfoCase: goodsInfoCase,
	}
}

// OptionGoodsInfos 查询商品信息下拉选择
func (s *GoodsInfoService) OptionGoodsInfos(ctx context.Context, req *adminv1.OptionGoodsInfosRequest) (*adminv1.OptionGoodsInfosResponse, error) {
	list, err := s.goodsInfoCase.OptionGoodsInfos(ctx, req)
	if err != nil {
		log.Errorf("OptionGoodsInfos %v", err)
		return nil, errorsx.WrapInternal(err, "查询商品列表失败")
	}
	return list, nil
}

// PageGoodsInfos 查询商品信息列表
func (s *GoodsInfoService) PageGoodsInfos(ctx context.Context, req *adminv1.PageGoodsInfosRequest) (*adminv1.PageGoodsInfosResponse, error) {
	page, err := s.goodsInfoCase.PageGoodsInfos(ctx, req)
	if err != nil {
		log.Errorf("PageGoodsInfos %v", err)
		return nil, errorsx.WrapInternal(err, "查询商品列表失败")
	}

	return page, nil
}

// GetGoodsInfo 查询商品信息
func (s *GoodsInfoService) GetGoodsInfo(ctx context.Context, req *adminv1.GetGoodsInfoRequest) (*adminv1.GoodsInfoForm, error) {
	goodsInfo, err := s.goodsInfoCase.GetGoodsInfo(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetGoodsInfo %v", err)
		return nil, errorsx.WrapInternal(err, "查询商品失败")
	}

	return goodsInfo, nil
}

// CreateGoodsInfo 创建商品信息
func (s *GoodsInfoService) CreateGoodsInfo(ctx context.Context, req *adminv1.CreateGoodsInfoRequest) (*emptypb.Empty, error) {
	err := s.goodsInfoCase.CreateGoodsInfo(ctx, req.GetGoodsInfo())
	if err != nil {
		log.Errorf("CreateGoodsInfo %v", err)
		return nil, errorsx.WrapInternal(err, "创建商品失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateGoodsInfo 更新商品信息
func (s *GoodsInfoService) UpdateGoodsInfo(ctx context.Context, req *adminv1.UpdateGoodsInfoRequest) (*emptypb.Empty, error) {
	err := s.goodsInfoCase.UpdateGoodsInfo(ctx, req.GetGoodsInfo())
	if err != nil {
		log.Errorf("UpdateGoodsInfo %v", err)
		return nil, errorsx.WrapInternal(err, "更新商品失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteGoodsInfo 删除商品信息
func (s *GoodsInfoService) DeleteGoodsInfo(ctx context.Context, req *adminv1.DeleteGoodsInfoRequest) (*emptypb.Empty, error) {
	err := s.goodsInfoCase.DeleteGoodsInfo(ctx, req.GetIds())
	if err != nil {
		log.Errorf("DeleteGoodsInfo %v", err)
		return nil, errorsx.WrapInternal(err, "删除商品失败")
	}
	return new(emptypb.Empty), nil
}

// SetGoodsInfoStatus 设置状态
func (s *GoodsInfoService) SetGoodsInfoStatus(ctx context.Context, req *adminv1.SetGoodsInfoStatusRequest) (*emptypb.Empty, error) {
	err := s.goodsInfoCase.SetGoodsInfoStatus(ctx, req)
	if err != nil {
		log.Errorf("SetGoodsInfoStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}
