// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/goods_sku.proto

package admin

import (
	"context"

	"shop/api/gen/go/admin"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsSkuService Admin商品SKU服务
type GoodsSkuService struct {
	admin.UnimplementedGoodsSkuServiceServer
	goodsSkuCase *biz.GoodsSkuCase
}

// NewGoodsSkuService 创建Admin商品SKU服务
func NewGoodsSkuService(goodsSkuCase *biz.GoodsSkuCase) *GoodsSkuService {
	return &GoodsSkuService{
		goodsSkuCase: goodsSkuCase,
	}
}

// PageGoodsSku 查询商品SKU分页列表
func (s *GoodsSkuService) PageGoodsSku(ctx context.Context, req *admin.PageGoodsSkuRequest) (*admin.PageGoodsSkuResponse, error) {
	page, err := s.goodsSkuCase.PageGoodsSku(ctx, req)
	if err != nil {
		log.Errorf("PageGoodsSku %v", err)
		return nil, errorsx.WrapInternal(err, "查询商品SKU分页列表失败")
	}
	return page, nil
}

// GetGoodsSku 查询商品SKU
func (s *GoodsSkuService) GetGoodsSku(ctx context.Context, req *wrapperspb.Int64Value) (*admin.GoodsSku, error) {
	goodsSku, err := s.goodsSkuCase.GetGoodsSku(ctx, req.GetValue())
	if err != nil {
		log.Errorf("GetGoodsSku %v", err)
		return nil, errorsx.WrapInternal(err, "查询商品SKU失败")
	}
	return goodsSku, nil
}

// UpdateGoodsSku 更新商品SKU
func (s *GoodsSkuService) UpdateGoodsSku(ctx context.Context, req *admin.GoodsSku) (*emptypb.Empty, error) {
	err := s.goodsSkuCase.UpdateGoodsSku(ctx, req)
	if err != nil {
		log.Errorf("UpdateGoodsSku %v", err)
		// 命中 SKU 编码唯一索引冲突时，返回更明确的业务错误。
		if errorsx.IsMySQLDuplicateKey(err) {
			return nil, errorsx.UniqueConflict("SKU编码重复", "goods_sku", "sku_code", "unique_goods_sku").WithCause(err)
		}
		return nil, errorsx.WrapInternal(err, "更新商品SKU失败")
	}
	return new(emptypb.Empty), nil
}
