// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/goods.proto

package admin

import (
	"context"
	"errors"
	"strings"

	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
	"shop/pkg/gen/models"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-sql-driver/mysql"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsService Admin商品服务
type GoodsService struct {
	admin.UnimplementedGoodsServiceServer
	goodsCase *biz.GoodsCase
}

// NewGoodsService 创建Admin商品服务
func NewGoodsService(
	goodsCase *biz.GoodsCase,
) *GoodsService {
	return &GoodsService{
		goodsCase: goodsCase,
	}
}

// ListGoods 查询商品列表
func (s *GoodsService) ListGoods(ctx context.Context, req *admin.ListGoodsRequest) (*admin.ListGoodsResponse, error) {
	list, err := s.goodsCase.ListGoods(ctx, req)
	if err != nil {
		log.Error("ListGoods err:", err.Error())
		return nil, errors.New("查询商品列表失败")
	}
	return list, nil
}

// PageGoods 查询商品分页列表
func (s *GoodsService) PageGoods(ctx context.Context, req *admin.PageGoodsRequest) (*admin.PageGoodsResponse, error) {
	page, err := s.goodsCase.PageGoods(ctx, req)
	if err != nil {
		log.Error("PageGoods err:", err.Error())
		return nil, errors.New("查询商品分页列表失败")
	}

	return page, nil
}

// GetGoods 查询商品
func (s *GoodsService) GetGoods(ctx context.Context, req *wrapperspb.Int64Value) (*admin.GoodsForm, error) {
	goods, err := s.goodsCase.GetGoods(ctx, req.GetValue())
	if err != nil {
		log.Error("GetGoods err:", err.Error())
		return nil, errors.New("查询商品失败")
	}

	return goods, nil
}

// CreateGoods 创建商品
func (s *GoodsService) CreateGoods(ctx context.Context, req *admin.GoodsForm) (*emptypb.Empty, error) {
	err := s.goodsCase.CreateGoods(ctx, req)
	if err != nil {
		log.Error("CreateGoods err:", err.Error())
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok && errMySQL.Number == 1062 {
			switch {
			case strings.Contains(errMySQL.Message, models.TableNameGoodsProp):
				return nil, errors.New("商品属性重复")
			case strings.Contains(errMySQL.Message, models.TableNameGoodsSku):
				return nil, errors.New("SKU编码重复")
			case strings.Contains(errMySQL.Message, models.TableNameGoodsSpec):
				return nil, errors.New("商品规格重复")
			}
		}
		return nil, errors.New("创建商品失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateGoods 更新商品
func (s *GoodsService) UpdateGoods(ctx context.Context, req *admin.GoodsForm) (*emptypb.Empty, error) {
	err := s.goodsCase.UpdateGoods(ctx, req)
	if err != nil {
		log.Error("UpdateGoods err:", err.Error())
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok && errMySQL.Number == 1062 {
			switch {
			case strings.Contains(errMySQL.Message, models.TableNameGoodsProp):
				return nil, errors.New("商品属性重复")
			case strings.Contains(errMySQL.Message, models.TableNameGoodsSku):
				return nil, errors.New("SKU编码重复")
			case strings.Contains(errMySQL.Message, models.TableNameGoodsSpec):
				return nil, errors.New("商品规格重复")
			}
		}
		return nil, errors.New("更新商品失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteGoods 删除商品
func (s *GoodsService) DeleteGoods(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	err := s.goodsCase.DeleteGoods(ctx, req.GetValue())
	if err != nil {
		log.Error("DeleteGoods err:", err.Error())
		return nil, errors.New("删除商品失败")
	}
	return new(emptypb.Empty), nil
}

// SetGoodsStatus 设置状态
func (s *GoodsService) SetGoodsStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.goodsCase.SetGoodsStatus(ctx, req)
	if err != nil {
		log.Error("SetGoodsStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return new(emptypb.Empty), nil
}
