// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/goods_category.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	commonv1 "shop/api/gen/go/common/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsCategoryService Admin商品分类服务
type GoodsCategoryService struct {
	adminv1.UnimplementedGoodsCategoryServiceServer
	goodsCategoryCase *biz.GoodsCategoryCase
}

// NewGoodsCategoryService 创建Admin商品分类服务
func NewGoodsCategoryService(
	categoryCase *biz.GoodsCategoryCase,
) *GoodsCategoryService {
	return &GoodsCategoryService{
		goodsCategoryCase: categoryCase,
	}
}

// TreeGoodsCategories 查询商品分类树形列表
func (s *GoodsCategoryService) TreeGoodsCategories(ctx context.Context, req *adminv1.TreeGoodsCategoriesRequest) (*adminv1.TreeGoodsCategoriesResponse, error) {
	tree, err := s.goodsCategoryCase.TreeGoodsCategories(ctx, req)
	if err != nil {
		log.Errorf("TreeGoodsCategories %v", err)
		return nil, errorsx.WrapInternal(err, "查询商品分类树形列表失败")
	}

	return tree, nil
}

// OptionGoodsCategories 查询商品分类树形选择
func (s *GoodsCategoryService) OptionGoodsCategories(ctx context.Context, req *adminv1.OptionGoodsCategoriesRequest) (*commonv1.TreeOptionResponse, error) {
	tree, err := s.goodsCategoryCase.OptionGoodsCategories(ctx, req)
	if err != nil {
		log.Errorf("OptionGoodsCategories %v", err)
		return nil, errorsx.WrapInternal(err, "查询商品分类树形选择失败")
	}
	return tree, nil
}

// GetGoodsCategory 查询商品分类
func (s *GoodsCategoryService) GetGoodsCategory(ctx context.Context, req *adminv1.GetGoodsCategoryRequest) (*adminv1.GoodsCategoryForm, error) {
	goodsCategory, err := s.goodsCategoryCase.GetGoodsCategory(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetGoodsCategory %v", err)
		return nil, errorsx.WrapInternal(err, "查询商品分类失败")
	}
	return goodsCategory, nil
}

// CreateGoodsCategory 创建商品分类
func (s *GoodsCategoryService) CreateGoodsCategory(ctx context.Context, req *adminv1.CreateGoodsCategoryRequest) (*emptypb.Empty, error) {
	err := s.goodsCategoryCase.CreateGoodsCategory(ctx, req.GetGoodsCategory())
	if err != nil {
		log.Errorf("CreateGoodsCategory %v", err)
		return nil, errorsx.WrapInternal(err, "创建商品分类失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateGoodsCategory 更新商品分类
func (s *GoodsCategoryService) UpdateGoodsCategory(ctx context.Context, req *adminv1.UpdateGoodsCategoryRequest) (*emptypb.Empty, error) {
	err := s.goodsCategoryCase.UpdateGoodsCategory(ctx, req.GetGoodsCategory())
	if err != nil {
		log.Errorf("UpdateGoodsCategory %v", err)
		return nil, errorsx.WrapInternal(err, "更新商品分类失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteGoodsCategory 删除商品分类
func (s *GoodsCategoryService) DeleteGoodsCategory(ctx context.Context, req *adminv1.DeleteGoodsCategoryRequest) (*emptypb.Empty, error) {
	err := s.goodsCategoryCase.DeleteGoodsCategory(ctx, req.GetIds())
	if err != nil {
		log.Errorf("DeleteGoodsCategory %v", err)
		return nil, errorsx.WrapInternal(err, "删除商品分类失败")
	}
	return new(emptypb.Empty), nil
}

// SetGoodsCategoryStatus 设置状态
func (s *GoodsCategoryService) SetGoodsCategoryStatus(ctx context.Context, req *adminv1.SetGoodsCategoryStatusRequest) (*emptypb.Empty, error) {
	err := s.goodsCategoryCase.SetGoodsCategoryStatus(ctx, req)
	if err != nil {
		log.Errorf("SetGoodsCategoryStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}
