// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/goods_prop.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsPropService Admin商品属性服务
type GoodsPropService struct {
	adminv1.UnimplementedGoodsPropServiceServer
	goodsPropCase *biz.GoodsPropCase
}

// NewGoodsPropService 创建Admin商品属性服务
func NewGoodsPropService(
	goodsPropCase *biz.GoodsPropCase,
) *GoodsPropService {
	return &GoodsPropService{
		goodsPropCase: goodsPropCase,
	}
}

// PageGoodsProps 查询商品属性列表
func (s *GoodsPropService) PageGoodsProps(ctx context.Context, req *adminv1.PageGoodsPropsRequest) (*adminv1.PageGoodsPropsResponse, error) {
	page, err := s.goodsPropCase.PageGoodsProps(ctx, req)
	if err != nil {
		log.Errorf("PageGoodsProps %v", err)
		return nil, errorsx.WrapInternal(err, "查询属性列表失败")
	}

	return page, nil
}

// GetGoodsProp 查询商品属性
func (s *GoodsPropService) GetGoodsProp(ctx context.Context, req *adminv1.GetGoodsPropRequest) (*adminv1.GoodsProp, error) {
	goodsProp, err := s.goodsPropCase.GetGoodsProp(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetGoodsProp %v", err)
		return nil, errorsx.WrapInternal(err, "查询商品属性失败")
	}
	return goodsProp, nil
}

// CreateGoodsProp 创建商品属性
func (s *GoodsPropService) CreateGoodsProp(ctx context.Context, req *adminv1.CreateGoodsPropRequest) (*emptypb.Empty, error) {
	err := s.goodsPropCase.CreateGoodsProp(ctx, req.GetGoodsProp())
	if err != nil {
		log.Errorf("CreateGoodsProp %v", err)
		return nil, errorsx.WrapInternal(err, "创建商品属性失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateGoodsProp 更新商品属性
func (s *GoodsPropService) UpdateGoodsProp(ctx context.Context, req *adminv1.UpdateGoodsPropRequest) (*emptypb.Empty, error) {
	err := s.goodsPropCase.UpdateGoodsProp(ctx, req.GetGoodsProp())
	if err != nil {
		log.Errorf("UpdateGoodsProp %v", err)
		return nil, errorsx.WrapInternal(err, "更新商品属性失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteGoodsProp 删除商品属性
func (s *GoodsPropService) DeleteGoodsProp(ctx context.Context, req *adminv1.DeleteGoodsPropRequest) (*emptypb.Empty, error) {
	err := s.goodsPropCase.DeleteGoodsProp(ctx, req.GetIds())
	if err != nil {
		log.Errorf("DeleteGoodsProp %v", err)
		return nil, errorsx.WrapInternal(err, "删除商品属性失败")
	}
	return new(emptypb.Empty), nil
}
