package admin

import (
	"shop/service/admin/biz"

	"github.com/google/wire"
)

// ProviderSet 汇总管理端服务依赖注入提供者。
var ProviderSet = wire.NewSet(

	biz.NewAuthCase,
	biz.NewBaseApiCase,
	biz.NewBaseConfigCase,
	biz.NewBaseDeptCase,
	biz.NewBaseDictCase,
	biz.NewBaseDictItemCase,
	biz.NewBaseJobCase,
	biz.NewBaseJobLogCase,
	biz.NewBaseLogCase,
	biz.NewBaseMenuCase,
	biz.NewBaseRoleCase,
	biz.NewBaseUserCase,
	biz.NewCasbinRuleCase,
	biz.NewGoodsInfoCase,
	biz.NewGoodsAnalyticsCase,
	biz.NewGoodsReportCase,
	biz.NewGoodsCategoryCase,
	biz.NewGoodsPropCase,
	biz.NewGoodsSkuCase,
	biz.NewGoodsSpecCase,
	biz.NewOrderInfoCase,
	biz.NewOrderAnalyticsCase,
	biz.NewOrderAddressCase,
	biz.NewOrderCancelCase,
	biz.NewOrderGoodsCase,
	biz.NewOrderLogisticsCase,
	biz.NewOrderPaymentCase,
	biz.NewOrderReportCase,
	biz.NewOrderRefundCase,
	biz.NewPayBillCase,
	biz.NewRecommendEventCase,
	biz.NewRecommendRequestItemCase,
	biz.NewRecommendRequestCase,
	biz.NewRecommendRemoteCase,
	biz.NewShopBannerCase,
	biz.NewShopHotCase,
	biz.NewShopHotItemCase,
	biz.NewShopServiceCase,
	biz.NewUserAnalyticsCase,
	biz.NewUserStoreCase,
	biz.NewWorkspaceCase,

	NewAuthService,
	NewBaseApiService,
	NewBaseConfigService,
	NewBaseDeptService,
	NewBaseDictService,
	NewBaseJobService,
	NewBaseLogService,
	NewBaseMenuService,
	NewBaseRoleService,
	NewBaseUserService,
	NewGoodsAnalyticsService,
	NewGoodsReportService,
	NewGoodsCategoryService,
	NewGoodsPropService,
	NewGoodsInfoService,
	NewGoodsSkuService,
	NewGoodsSpecService,
	NewOrderAnalyticsService,
	NewOrderReportService,
	NewOrderInfoService,
	NewPayBillService,
	NewRecommendRequestService,
	NewRecommendRemoteService,
	NewShopBannerService,
	NewShopHotService,
	NewShopServiceService,
	NewUserAnalyticsService,
	NewUserStoreService,
	NewWorkspaceService,
)
