// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/shop_banner.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// ShopBannerService Admin商城轮播图服务
type ShopBannerService struct {
	adminv1.UnimplementedShopBannerServiceServer
	bannerCase *biz.ShopBannerCase
}

// NewShopBannerService 创建Admin商城轮播图服务
func NewShopBannerService(
	bannerCase *biz.ShopBannerCase,
) *ShopBannerService {
	return &ShopBannerService{
		bannerCase: bannerCase,
	}
}

// PageShopBanners 查询商城轮播图列表
func (s *ShopBannerService) PageShopBanners(ctx context.Context, req *adminv1.PageShopBannersRequest) (*adminv1.PageShopBannersResponse, error) {
	page, err := s.bannerCase.PageShopBanners(ctx, req)
	if err != nil {
		log.Errorf("PageShopBanners %v", err)
		return nil, errorsx.WrapInternal(err, "查询商城轮播图列表失败")
	}

	return page, nil
}

// GetShopBanner 查询商城轮播图
func (s *ShopBannerService) GetShopBanner(ctx context.Context, req *adminv1.GetShopBannerRequest) (*adminv1.ShopBannerForm, error) {
	shopBanner, err := s.bannerCase.GetShopBanner(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetShopBanner %v", err)
		return nil, errorsx.WrapInternal(err, "查询商城轮播图失败")
	}
	return shopBanner, nil
}

// CreateShopBanner 创建商城轮播图
func (s *ShopBannerService) CreateShopBanner(ctx context.Context, req *adminv1.CreateShopBannerRequest) (*emptypb.Empty, error) {
	err := s.bannerCase.CreateShopBanner(ctx, req.GetShopBanner())
	if err != nil {
		log.Errorf("CreateShopBanner %v", err)
		return nil, errorsx.WrapInternal(err, "创建商城轮播图失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateShopBanner 更新商城轮播图
func (s *ShopBannerService) UpdateShopBanner(ctx context.Context, req *adminv1.UpdateShopBannerRequest) (*emptypb.Empty, error) {
	err := s.bannerCase.UpdateShopBanner(ctx, req.GetShopBanner())
	if err != nil {
		log.Errorf("UpdateShopBanner %v", err)
		return nil, errorsx.WrapInternal(err, "更新商城轮播图失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteShopBanner 删除商城轮播图
func (s *ShopBannerService) DeleteShopBanner(ctx context.Context, req *adminv1.DeleteShopBannerRequest) (*emptypb.Empty, error) {
	err := s.bannerCase.DeleteShopBanner(ctx, req.GetIds())
	if err != nil {
		log.Errorf("DeleteShopBanner %v", err)
		return nil, errorsx.WrapInternal(err, "删除商城轮播图失败")
	}
	return new(emptypb.Empty), nil
}

// SetShopBannerStatus 设置状态
func (s *ShopBannerService) SetShopBannerStatus(ctx context.Context, req *adminv1.SetShopBannerStatusRequest) (*emptypb.Empty, error) {
	err := s.bannerCase.SetShopBannerStatus(ctx, req)
	if err != nil {
		log.Errorf("SetShopBannerStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}
