// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/shop_banner.proto

package admin

import (
	"context"

	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// ShopBannerService Admin商城轮播图服务
type ShopBannerService struct {
	admin.UnimplementedShopBannerServiceServer
	bannerCase *biz.ShopBannerCase
}

// NewShopBannerService 创建Admin商城轮播图服务
func NewShopBannerService(
	bannerCase *biz.ShopBannerCase,
) *ShopBannerService {
	return &ShopBannerService{
		bannerCase: bannerCase,
	}
}

// PageShopBanner 查询商城轮播图分页列表
func (s *ShopBannerService) PageShopBanner(ctx context.Context, req *admin.PageShopBannerRequest) (*admin.PageShopBannerResponse, error) {
	page, err := s.bannerCase.PageShopBanner(ctx, req)
	if err != nil {
		log.Errorf("PageShopBanner %v", err)
		return nil, errorsx.WrapInternal(err, "查询商城轮播图分页列表失败")
	}

	return page, nil
}

// GetShopBanner 查询商城轮播图
func (s *ShopBannerService) GetShopBanner(ctx context.Context, req *wrapperspb.Int64Value) (*admin.ShopBannerForm, error) {
	shopBanner, err := s.bannerCase.GetShopBanner(ctx, req.GetValue())
	if err != nil {
		log.Errorf("GetShopBanner %v", err)
		return nil, errorsx.WrapInternal(err, "查询商城轮播图失败")
	}
	return shopBanner, nil
}

// CreateShopBanner 创建商城轮播图
func (s *ShopBannerService) CreateShopBanner(ctx context.Context, req *admin.ShopBannerForm) (*emptypb.Empty, error) {
	err := s.bannerCase.CreateShopBanner(ctx, req)
	if err != nil {
		log.Errorf("CreateShopBanner %v", err)
		return nil, errorsx.WrapInternal(err, "创建商城轮播图失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateShopBanner 更新商城轮播图
func (s *ShopBannerService) UpdateShopBanner(ctx context.Context, req *admin.ShopBannerForm) (*emptypb.Empty, error) {
	err := s.bannerCase.UpdateShopBanner(ctx, req)
	if err != nil {
		log.Errorf("UpdateShopBanner %v", err)
		return nil, errorsx.WrapInternal(err, "更新商城轮播图失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteShopBanner 删除商城轮播图
func (s *ShopBannerService) DeleteShopBanner(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	err := s.bannerCase.DeleteShopBanner(ctx, req.GetValue())
	if err != nil {
		log.Errorf("DeleteShopBanner %v", err)
		return nil, errorsx.WrapInternal(err, "删除商城轮播图失败")
	}
	return new(emptypb.Empty), nil
}

// SetShopBannerStatus 设置状态
func (s *ShopBannerService) SetShopBannerStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.bannerCase.SetShopBannerStatus(ctx, req)
	if err != nil {
		log.Errorf("SetShopBannerStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}
