// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/shop_hot.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// ShopHotService Admin商城热门推荐服务
type ShopHotService struct {
	adminv1.UnimplementedShopHotServiceServer
	hotCase     *biz.ShopHotCase
	hotItemCase *biz.ShopHotItemCase
}

// NewShopHotService 创建Admin商城热门推荐服务
func NewShopHotService(
	hotCase *biz.ShopHotCase,
	hotItemCase *biz.ShopHotItemCase,
) *ShopHotService {
	return &ShopHotService{
		hotCase:     hotCase,
		hotItemCase: hotItemCase,
	}
}

// PageShopHots 查询商城热门推荐列表
func (s *ShopHotService) PageShopHots(ctx context.Context, req *adminv1.PageShopHotsRequest) (*adminv1.PageShopHotsResponse, error) {
	page, err := s.hotCase.PageShopHots(ctx, req)
	if err != nil {
		log.Errorf("PageShopHots %v", err)
		return nil, errorsx.WrapInternal(err, "查询商城热门推荐列表失败")
	}

	return page, nil
}

// GetShopHot 查询商城热门推荐
func (s *ShopHotService) GetShopHot(ctx context.Context, req *adminv1.GetShopHotRequest) (*adminv1.ShopHotForm, error) {
	shopHot, err := s.hotCase.GetShopHot(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetShopHot %v", err)
		return nil, errorsx.WrapInternal(err, "查询商城热门推荐失败")
	}
	return shopHot, nil
}

// CreateShopHot 创建商城热门推荐
func (s *ShopHotService) CreateShopHot(ctx context.Context, req *adminv1.CreateShopHotRequest) (*emptypb.Empty, error) {
	err := s.hotCase.CreateShopHot(ctx, req.GetShopHot())
	if err != nil {
		log.Errorf("CreateShopHot %v", err)
		return nil, errorsx.WrapInternal(err, "创建商城热门推荐失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateShopHot 更新商城热门推荐
func (s *ShopHotService) UpdateShopHot(ctx context.Context, req *adminv1.UpdateShopHotRequest) (*emptypb.Empty, error) {
	err := s.hotCase.UpdateShopHot(ctx, req.GetShopHot())
	if err != nil {
		log.Errorf("UpdateShopHot %v", err)
		return nil, errorsx.WrapInternal(err, "更新商城热门推荐失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteShopHot 删除商城热门推荐
func (s *ShopHotService) DeleteShopHot(ctx context.Context, req *adminv1.DeleteShopHotRequest) (*emptypb.Empty, error) {
	err := s.hotCase.DeleteShopHot(ctx, req.GetIds())
	if err != nil {
		log.Errorf("DeleteShopHot %v", err)
		return nil, errorsx.WrapInternal(err, "删除商城热门推荐失败")
	}
	return new(emptypb.Empty), nil
}

// SetShopHotStatus 设置状态
func (s *ShopHotService) SetShopHotStatus(ctx context.Context, req *adminv1.SetShopHotStatusRequest) (*emptypb.Empty, error) {
	err := s.hotCase.SetShopHotStatus(ctx, req)
	if err != nil {
		log.Errorf("SetShopHotStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}

// PageShopHotItems 查询商城热门推荐属性列表
func (s *ShopHotService) PageShopHotItems(ctx context.Context, req *adminv1.PageShopHotItemsRequest) (*adminv1.PageShopHotItemsResponse, error) {
	page, err := s.hotItemCase.PageShopHotItems(ctx, req)
	if err != nil {
		log.Errorf("PageShopHotItems %v", err)
		return nil, errorsx.WrapInternal(err, "查询热门推荐选项列表失败")
	}
	return page, nil
}

// GetShopHotItem 查询商城热门推荐属性
func (s *ShopHotService) GetShopHotItem(ctx context.Context, req *adminv1.GetShopHotItemRequest) (*adminv1.ShopHotItemForm, error) {
	shopHotItem, err := s.hotItemCase.GetShopHotItem(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetShopHotItem %v", err)
		return nil, errorsx.WrapInternal(err, "查询热门推荐选项失败")
	}
	return shopHotItem, nil
}

// CreateShopHotItem 创建商城热门推荐属性
func (s *ShopHotService) CreateShopHotItem(ctx context.Context, req *adminv1.CreateShopHotItemRequest) (*emptypb.Empty, error) {
	err := s.hotItemCase.CreateShopHotItem(ctx, req.GetShopHotItem())
	if err != nil {
		log.Errorf("CreateShopHotItem %v", err)
		return nil, errorsx.WrapInternal(err, "创建热门推荐选项失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateShopHotItem 更新商城热门推荐属性
func (s *ShopHotService) UpdateShopHotItem(ctx context.Context, req *adminv1.UpdateShopHotItemRequest) (*emptypb.Empty, error) {
	err := s.hotItemCase.UpdateShopHotItem(ctx, req.GetShopHotItem())
	if err != nil {
		log.Errorf("UpdateShopHotItem %v", err)
		return nil, errorsx.WrapInternal(err, "更新热门推荐选项失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteShopHotItem 删除商城热门推荐属性
func (s *ShopHotService) DeleteShopHotItem(ctx context.Context, req *adminv1.DeleteShopHotItemRequest) (*emptypb.Empty, error) {
	err := s.hotItemCase.DeleteShopHotItem(ctx, req.GetIds())
	if err != nil {
		log.Errorf("DeleteShopHotItem %v", err)
		return nil, errorsx.WrapInternal(err, "删除热门推荐选项失败")
	}
	return new(emptypb.Empty), nil
}

// SetShopHotItemStatus 设置状态
func (s *ShopHotService) SetShopHotItemStatus(ctx context.Context, req *adminv1.SetShopHotItemStatusRequest) (*emptypb.Empty, error) {
	err := s.hotItemCase.SetShopHotItemStatus(ctx, req)
	if err != nil {
		log.Errorf("SetShopHotItemStatus %v", err)
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}
