// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/shop_hot.proto

package admin

import (
	"context"
	"errors"

	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// ShopHotService Admin商城热门推荐服务
type ShopHotService struct {
	admin.UnimplementedShopHotServiceServer
	hotCase     *biz.ShopHotCase
	hotItemCase *biz.ShopHotItemCase
}

// NewShopHotService 创建Admin商城热门推荐服务
func NewShopHotService(
	hotCase *biz.ShopHotCase,
	hotItemCase *biz.ShopHotItemCase,
) *ShopHotService {
	return &ShopHotService{
		hotCase:     hotCase,
		hotItemCase: hotItemCase,
	}
}

// PageShopHot 查询商城热门推荐分页列表
func (s *ShopHotService) PageShopHot(ctx context.Context, req *admin.PageShopHotRequest) (*admin.PageShopHotResponse, error) {
	page, err := s.hotCase.PageShopHot(ctx, req)
	if err != nil {
		log.Error("PageShopHot err:", err.Error())
		return nil, errors.New("查询商城热门推荐分页列表失败")
	}

	return page, nil
}

// GetShopHot 查询商城热门推荐
func (s *ShopHotService) GetShopHot(ctx context.Context, req *wrapperspb.Int64Value) (*admin.ShopHotForm, error) {
	shopHot, err := s.hotCase.GetShopHot(ctx, req.GetValue())
	if err != nil {
		log.Error("GetShopHot err:", err.Error())
		return nil, errors.New("查询商城热门推荐失败")
	}
	return shopHot, nil
}

// CreateShopHot 创建商城热门推荐
func (s *ShopHotService) CreateShopHot(ctx context.Context, req *admin.ShopHotForm) (*emptypb.Empty, error) {
	err := s.hotCase.CreateShopHot(ctx, req)
	if err != nil {
		log.Error("CreateShopHot err:", err.Error())
		return nil, errors.New("创建商城热门推荐失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateShopHot 更新商城热门推荐
func (s *ShopHotService) UpdateShopHot(ctx context.Context, req *admin.ShopHotForm) (*emptypb.Empty, error) {
	err := s.hotCase.UpdateShopHot(ctx, req)
	if err != nil {
		log.Error("UpdateShopHot err:", err.Error())
		return nil, errors.New("更新商城热门推荐失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteShopHot 删除商城热门推荐
func (s *ShopHotService) DeleteShopHot(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	err := s.hotCase.DeleteShopHot(ctx, req.GetValue())
	if err != nil {
		log.Error("DeleteShopHot err:", err.Error())
		return nil, errors.New("删除商城热门推荐失败")
	}
	return new(emptypb.Empty), nil
}

// SetShopHotStatus 设置状态
func (s *ShopHotService) SetShopHotStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.hotCase.SetShopHotStatus(ctx, req)
	if err != nil {
		log.Error("SetShopHotStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return new(emptypb.Empty), nil
}

// PageShopHotItem 查询商城热门推荐属性分页列表
func (s *ShopHotService) PageShopHotItem(ctx context.Context, req *admin.PageShopHotItemRequest) (*admin.PageShopHotItemResponse, error) {
	page, err := s.hotItemCase.PageShopHotItem(ctx, req)
	if err != nil {
		log.Error("PageShopHotItem err:", err.Error())
		return nil, errors.New("查询热门推荐选项分页列表失败")
	}
	return page, nil
}

// GetShopHotItem 查询商城热门推荐属性
func (s *ShopHotService) GetShopHotItem(ctx context.Context, req *wrapperspb.Int64Value) (*admin.ShopHotItemForm, error) {
	shopHotItem, err := s.hotItemCase.GetShopHotItem(ctx, req.GetValue())
	if err != nil {
		log.Error("GetShopHotItem err:", err.Error())
		return nil, errors.New("查询热门推荐选项失败")
	}
	return shopHotItem, nil
}

// CreateShopHotItem 创建商城热门推荐属性
func (s *ShopHotService) CreateShopHotItem(ctx context.Context, req *admin.ShopHotItemForm) (*emptypb.Empty, error) {
	err := s.hotItemCase.CreateShopHotItem(ctx, req)
	if err != nil {
		log.Error("CreateShopHotItem err:", err.Error())
		return nil, errors.New("创建热门推荐选项失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateShopHotItem 更新商城热门推荐属性
func (s *ShopHotService) UpdateShopHotItem(ctx context.Context, req *admin.ShopHotItemForm) (*emptypb.Empty, error) {
	err := s.hotItemCase.UpdateShopHotItem(ctx, req)
	if err != nil {
		log.Error("UpdateShopHotItem err:", err.Error())
		return nil, errors.New("更新热门推荐选项失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteShopHotItem 删除商城热门推荐属性
func (s *ShopHotService) DeleteShopHotItem(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	err := s.hotItemCase.DeleteShopHotItem(ctx, req.GetValue())
	if err != nil {
		log.Error("DeleteShopHotItem err:", err.Error())
		return nil, errors.New("删除热门推荐选项失败")
	}
	return new(emptypb.Empty), nil
}

// SetShopHotItemStatus 设置状态
func (s *ShopHotService) SetShopHotItemStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.hotItemCase.SetShopHotItemStatus(ctx, req)
	if err != nil {
		log.Error("SetShopHotItemStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return new(emptypb.Empty), nil
}
