// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/user_store.proto

package admin

import (
	"context"

	adminv1 "shop/api/gen/go/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/admin/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// UserStoreService Admin用户门店管理服务
type UserStoreService struct {
	adminv1.UnimplementedUserStoreServiceServer
	userStoreCase *biz.UserStoreCase
}

// NewUserStoreService 创建Admin用户门店管理服务
func NewUserStoreService(
	userStoreCase *biz.UserStoreCase,
) *UserStoreService {
	return &UserStoreService{
		userStoreCase: userStoreCase,
	}
}

// PageUserStores 查询用户门店列表
func (s *UserStoreService) PageUserStores(ctx context.Context, req *adminv1.PageUserStoresRequest) (*adminv1.PageUserStoresResponse, error) {
	page, err := s.userStoreCase.PageUserStores(ctx, req)
	if err != nil {
		log.Errorf("PageUserStores %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户门店列表失败")
	}

	return page, nil
}

// GetUserStore 查询用户门店
func (s *UserStoreService) GetUserStore(ctx context.Context, req *adminv1.GetUserStoreRequest) (*adminv1.UserStore, error) {
	userStore, err := s.userStoreCase.GetUserStore(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetUserStore %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户门店失败")
	}

	return userStore, nil
}

// AuditUserStore 门店认证
func (s *UserStoreService) AuditUserStore(ctx context.Context, req *adminv1.AuditUserStoreRequest) (*emptypb.Empty, error) {
	err := s.userStoreCase.AuditUserStore(ctx, req)
	if err != nil {
		log.Errorf("AuditUserStore %v", err)
		return nil, errorsx.WrapInternal(err, "门店认证失败")
	}
	return new(emptypb.Empty), nil
}
