// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/order_info.proto

package app

import (
	"context"
	"fmt"

	shopappv1 "shop/api/gen/go/shop/app/v1"
	"shop/pkg/errorsx"
	"shop/service/shop/app/biz"

	"github.com/go-kratos/kratos/v3/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// OrderInfoService 订单信息服务
type OrderInfoService struct {
	shopappv1.UnimplementedOrderInfoServiceServer
	orderInfoCase *biz.OrderInfoCase
}

// NewOrderInfoService 创建订单信息服务
func NewOrderInfoService(
	orderInfoCase *biz.OrderInfoCase,
) *OrderInfoService {
	var ss = OrderInfoService{
		orderInfoCase: orderInfoCase,
	}
	return &ss
}

// ConfirmOrderInfo 确认订单信息
func (s *OrderInfoService) ConfirmOrderInfo(ctx context.Context, req *shopappv1.ConfirmOrderInfoRequest) (*shopappv1.ConfirmOrderInfoResponse, error) {
	res, err := s.orderInfoCase.ConfirmOrderInfo(ctx)
	if err != nil {
		log.Error(fmt.Sprintf("ConfirmOrderInfo %v", err))
		return nil, errorsx.WrapInternal(err, "预付订单失败")
	}
	// 预付订单来自购物车结算，前端确认后需要清空购物车勾选项
	res.ClearCart = true
	return res, nil
}

// BuyNowOrderInfo 立即购买订单信息
func (s *OrderInfoService) BuyNowOrderInfo(ctx context.Context, req *shopappv1.BuyNowOrderInfoRequest) (*shopappv1.BuyNowOrderInfoResponse, error) {
	res, err := s.orderInfoCase.BuyNowOrderInfo(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("BuyNowOrderInfo %v", err))
		return nil, errorsx.WrapInternal(err, "立即购买失败")
	}
	return res, nil
}

// RepurchaseOrderInfo 再次购买订单信息
func (s *OrderInfoService) RepurchaseOrderInfo(ctx context.Context, req *shopappv1.RepurchaseOrderInfoRequest) (*shopappv1.RepurchaseOrderInfoResponse, error) {
	res, err := s.orderInfoCase.RepurchaseOrderInfo(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("RepurchaseOrderInfo %v", err))
		return nil, errorsx.WrapInternal(err, "再次购买订单失败")
	}
	return res, nil
}

// CountOrderInfo 查询订单信息数量汇总
func (s *OrderInfoService) CountOrderInfo(ctx context.Context, req *shopappv1.CountOrderInfoRequest) (*shopappv1.CountOrderInfoResponse, error) {
	res, err := s.orderInfoCase.CountOrderInfo(ctx)
	if err != nil {
		log.Error(fmt.Sprintf("CountOrderInfo %v", err))
		return nil, errorsx.WrapInternal(err, "查询订单数量汇总失败")
	}
	return res, nil
}

// PageOrderInfo 查询订单信息分页列表
func (s *OrderInfoService) PageOrderInfo(ctx context.Context, req *shopappv1.PageOrderInfoRequest) (*shopappv1.PageOrderInfoResponse, error) {
	page, err := s.orderInfoCase.PageOrderInfo(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("PageOrderInfo %v", err))
		return nil, errorsx.WrapInternal(err, "查询订单分页列表失败")
	}
	return page, nil
}

// GetOrderInfoIdByOrderNo 根据订单信息编号查询订单信息编号
func (s *OrderInfoService) GetOrderInfoIdByOrderNo(ctx context.Context, req *shopappv1.GetOrderInfoIdByOrderNoRequest) (*shopappv1.GetOrderInfoIdByOrderNoResponse, error) {
	res, err := s.orderInfoCase.GetOrderInfoIDByOrderNo(ctx, req.GetOrderNo())
	if err != nil {
		log.Error(fmt.Sprintf("GetOrderInfoIdByOrderNo %v", err))
		return nil, errorsx.WrapInternal(err, "查询订单失败")
	}

	return &shopappv1.GetOrderInfoIdByOrderNoResponse{
		OrderId: res,
	}, nil
}

// GetOrderInfoById 根据订单信息编号查询订单信息
func (s *OrderInfoService) GetOrderInfoById(ctx context.Context, req *shopappv1.GetOrderInfoByIdRequest) (*shopappv1.OrderInfoResponse, error) {
	res, err := s.orderInfoCase.GetOrderInfoByID(ctx, req.GetId())
	if err != nil {
		log.Error(fmt.Sprintf("GetOrderInfoById %v", err))
		return nil, errorsx.WrapInternal(err, "查询订单失败")
	}

	return res, nil
}

// GetOrderTradeById 根据交易单编号查询聚合订单详情。
func (s *OrderInfoService) GetOrderTradeById(ctx context.Context, req *shopappv1.GetOrderTradeByIdRequest) (*shopappv1.OrderInfoResponse, error) {
	res, err := s.orderInfoCase.GetOrderTradeByID(ctx, req.GetTradeId())
	if err != nil {
		log.Error(fmt.Sprintf("GetOrderTradeById %v", err))
		return nil, errorsx.WrapInternal(err, "查询交易单失败")
	}

	return res, nil
}

// CreateOrderInfo 创建订单信息
func (s *OrderInfoService) CreateOrderInfo(ctx context.Context, req *shopappv1.CreateOrderInfoRequest) (*shopappv1.CreateOrderInfoResponse, error) {
	res, err := s.orderInfoCase.CreateOrderInfo(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("CreateOrderInfo %v", err))
		return nil, errorsx.WrapInternal(err, "创建订单失败")
	}
	return res, nil
}

// DeleteOrderInfo 删除订单信息
func (s *OrderInfoService) DeleteOrderInfo(ctx context.Context, req *shopappv1.DeleteOrderInfoRequest) (*emptypb.Empty, error) {
	err := s.orderInfoCase.DeleteOrderInfo(ctx, req.GetId())
	if err != nil {
		log.Error(fmt.Sprintf("DeleteOrderInfo %v", err))
		return nil, errorsx.WrapInternal(err, "删除订单失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteOrderTrade 删除已关闭交易单。
func (s *OrderInfoService) DeleteOrderTrade(ctx context.Context, req *shopappv1.DeleteOrderTradeRequest) (*emptypb.Empty, error) {
	err := s.orderInfoCase.DeleteOrderTrade(ctx, req.GetTradeId())
	if err != nil {
		log.Error(fmt.Sprintf("DeleteOrderTrade %v", err))
		return nil, errorsx.WrapInternal(err, "删除交易单失败")
	}
	return new(emptypb.Empty), nil
}

// CancelOrderInfo 取消订单信息
func (s *OrderInfoService) CancelOrderInfo(ctx context.Context, req *shopappv1.CancelOrderInfoRequest) (*emptypb.Empty, error) {
	err := s.orderInfoCase.CancelOrderInfo(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("CancelOrderInfo %v", err))
		return nil, errorsx.WrapInternal(err, "取消订单失败")
	}
	return new(emptypb.Empty), nil
}

// RefundOrderInfo 订单信息退款
func (s *OrderInfoService) RefundOrderInfo(ctx context.Context, req *shopappv1.RefundOrderInfoRequest) (*emptypb.Empty, error) {
	err := s.orderInfoCase.RefundOrderInfo(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("RefundOrderInfo %v", err))
		return nil, errorsx.WrapInternal(err, "订单退款失败")
	}
	return new(emptypb.Empty), nil
}

// ReceiveOrderInfo 确认收货
func (s *OrderInfoService) ReceiveOrderInfo(ctx context.Context, req *shopappv1.ReceiveOrderInfoRequest) (*emptypb.Empty, error) {
	err := s.orderInfoCase.ReceiveOrderInfo(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("ReceiveOrderInfo %v", err))
		return nil, errorsx.WrapInternal(err, "确认收货失败")
	}
	return new(emptypb.Empty), nil
}
