// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/user_cart.proto

package app

import (
	"context"
	"fmt"

	shopappv1 "shop/api/gen/go/shop/app/v1"
	"shop/pkg/errorsx"
	"shop/service/shop/app/biz"

	"github.com/go-kratos/kratos/v3/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// UserCartService 用户购物车管理服务
type UserCartService struct {
	shopappv1.UnimplementedUserCartServiceServer
	userCartCase *biz.UserCartCase
}

// NewUserCartService 创建用户购物车管理服务
func NewUserCartService(
	userCartCase *biz.UserCartCase,
) *UserCartService {
	var ss = UserCartService{
		userCartCase: userCartCase,
	}
	return &ss
}

// ListUserCart 查询用户购物车列表
func (s *UserCartService) ListUserCart(ctx context.Context, req *shopappv1.ListUserCartRequest) (*shopappv1.ListUserCartResponse, error) {
	res, err := s.userCartCase.ListUserCart(ctx)
	if err != nil {
		log.Error(fmt.Sprintf("ListUserCart %v", err))
		return nil, errorsx.WrapInternal(err, "查询用户购物车列表失败")
	}
	return res, nil
}

// CreateUserCart 创建用户购物车
func (s *UserCartService) CreateUserCart(ctx context.Context, req *shopappv1.CreateUserCartRequest) (*emptypb.Empty, error) {
	err := s.userCartCase.CreateUserCart(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("CreateUserCart %v", err))
		return nil, errorsx.WrapInternal(err, "加入购物车失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateUserCart 更新用户购物车
func (s *UserCartService) UpdateUserCart(ctx context.Context, req *shopappv1.UpdateUserCartRequest) (*emptypb.Empty, error) {
	userCart := req.GetUserCart()
	// 请求体未携带购物车时，使用空表单交由业务层按原有校验处理。
	if userCart == nil {
		userCart = &shopappv1.UserCartForm{}
	}
	// 路径中的购物车编号优先作为本次更新目标，避免 body 漏传 ID。
	if userCart.GetId() == 0 {
		userCart.Id = req.GetId()
	}
	err := s.userCartCase.UpdateUserCart(ctx, userCart)
	if err != nil {
		log.Error(fmt.Sprintf("UpdateUserCart %v", err))
		return nil, errorsx.WrapInternal(err, "更新购物车失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteUserCart 删除用户购物车
func (s *UserCartService) DeleteUserCart(ctx context.Context, req *shopappv1.DeleteUserCartRequest) (*emptypb.Empty, error) {
	err := s.userCartCase.DeleteUserCart(ctx, req.GetId())
	if err != nil {
		log.Error(fmt.Sprintf("DeleteUserCart %v", err))
		return nil, errorsx.WrapInternal(err, "删除用户购物车失败")
	}
	return new(emptypb.Empty), nil
}

// SetUserCartSelection 设置购物车全选状态
func (s *UserCartService) SetUserCartSelection(ctx context.Context, req *shopappv1.SetUserCartSelectionRequest) (*emptypb.Empty, error) {
	err := s.userCartCase.SetUserCartSelection(ctx, req.GetIsChecked())
	if err != nil {
		log.Error(fmt.Sprintf("SetUserCartSelection %v", err))
		return nil, errorsx.WrapInternal(err, "设置全选失败")
	}
	return new(emptypb.Empty), nil
}

// SetUserCartStatus 设置购物车选中状态
func (s *UserCartService) SetUserCartStatus(ctx context.Context, req *shopappv1.SetUserCartStatusRequest) (*emptypb.Empty, error) {
	err := s.userCartCase.SetUserCartStatus(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("SetUserCartStatus %v", err))
		return nil, errorsx.WrapInternal(err, "更新购物车失败")
	}
	return new(emptypb.Empty), nil
}

// CountUserCart 查询用户购物车数量
func (s *UserCartService) CountUserCart(ctx context.Context, req *shopappv1.CountUserCartRequest) (*shopappv1.CountUserCartResponse, error) {
	count, err := s.userCartCase.CountUserCart(ctx)
	if err != nil {
		log.Error(fmt.Sprintf("CountUserCart %v", err))
		return nil, errorsx.WrapInternal(err, "查询用户购物车数量失败")
	}
	return &shopappv1.CountUserCartResponse{
		Count: int32(count),
	}, nil
}
