// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: shop/app/v1/user_collect.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";
import type { RecommendContext } from "./recommend";
import type { TenantStore } from "./tenant_store";

/** 用户收藏状态查询条件 */
export interface GetIsCollectRequest {
  /** 商品ID */
  goods_id: number;
}

/** 用户收藏状态响应 */
export interface GetIsCollectResponse {
  /** 是否已收藏 */
  is_collected: boolean;
}

/** 用户收藏列表查询条件 */
export interface PageUserCollectRequest {
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 用户收藏列表响应 */
export interface PageUserCollectResponse {
  /** 用户收藏列表 */
  user_collects: UserCollect[];
  /** 总数 */
  total: number;
}

/** 创建用户收藏请求参数 */
export interface CreateUserCollectRequest {
  /** 用户收藏 */
  user_collect: UserCollectForm | undefined;
}

/** 删除用户收藏请求参数 */
export interface DeleteUserCollectRequest {
  /** 用户收藏ID列表 */
  ids: string;
}

/** 用户收藏表单 */
export interface UserCollectForm {
  /** 商品ID */
  goods_id: number;
  /** 推荐上下文 */
  recommend_context: RecommendContext | undefined;
}

/** 用户收藏 */
export interface UserCollect {
  /** 用户收藏ID */
  id: number;
  /** 店铺ID */
  tenant_store_id: number;
  /** 商品ID */
  goods_id: number;
  /** 名称 */
  name: string;
  /** 描述 */
  desc: string;
  /** 商品图片 */
  picture: string;
  /** 销量 */
  sale_num: number;
  /** 价格 */
  price: number;
  /** 加入时价格 */
  join_price: number;
  /** 店铺信息 */
  tenant_store: TenantStore | undefined;
}

/** App用户收藏管理服务 */
export interface UserCollectService {
  /** 查询用户收藏列表 */
  PageUserCollect(request: PageUserCollectRequest): Promise<PageUserCollectResponse>;
  /** 查询用户是否收藏 */
  GetIsCollect(request: GetIsCollectRequest): Promise<GetIsCollectResponse>;
  /** 创建用户收藏 */
  CreateUserCollect(request: CreateUserCollectRequest): Promise<Empty>;
  /** 删除用户收藏 */
  DeleteUserCollect(request: DeleteUserCollectRequest): Promise<Empty>;
}
