// Package consts 定义商城模块专属的枚举常量。
package consts

import (
	commonv1 "shop/api/gen/go/common/v1"
	shopcommonv1 "shop/api/gen/go/shop/common/v1"
	baseconst "shop/pkg/const"
)

const (
	// STATUS_ENABLE 表示记录启用。
	STATUS_ENABLE = baseconst.STATUS_ENABLE
	// STATUS_DISABLE 表示记录禁用。
	STATUS_DISABLE = baseconst.STATUS_DISABLE
	// BASE_ROLE_CODE_SUPER 表示超级管理员角色。
	BASE_ROLE_CODE_SUPER = baseconst.BASE_ROLE_CODE_SUPER
	// BASE_ROLE_CODE_TENANT 表示租户角色。
	BASE_ROLE_CODE_TENANT = baseconst.BASE_ROLE_CODE_TENANT
	// BASE_ROLE_CODE_ADMIN 表示管理员角色。
	BASE_ROLE_CODE_ADMIN = baseconst.BASE_ROLE_CODE_ADMIN
	// BASE_ROLE_CODE_USER 表示商城用户角色。
	BASE_ROLE_CODE_USER = baseconst.BASE_ROLE_CODE_USER
	// BASE_ROLE_CODE_GUEST 表示游客角色。
	BASE_ROLE_CODE_GUEST = baseconst.BASE_ROLE_CODE_GUEST
)

const (
	// USER_STORE_STATUS_PENDING_REVIEW 表示用户门店待审核。
	USER_STORE_STATUS_PENDING_REVIEW = int32(shopcommonv1.UserStoreStatus_PENDING_REVIEW)
	// USER_STORE_STATUS_FAILED_REVIEW 表示用户门店审核失败。
	USER_STORE_STATUS_FAILED_REVIEW = int32(shopcommonv1.UserStoreStatus_FAILED_REVIEW)
	// USER_STORE_STATUS_APPROVED 表示用户门店审核通过。
	USER_STORE_STATUS_APPROVED = int32(shopcommonv1.UserStoreStatus_APPROVED)
	// TENANT_STORE_STATUS_PENDING_REVIEW 表示租户门店待审核。
	TENANT_STORE_STATUS_PENDING_REVIEW = int32(shopcommonv1.TenantStoreStatus_PENDING_REVIEW_TSS)
	// TENANT_STORE_STATUS_FAILED_REVIEW 表示租户门店审核失败。
	TENANT_STORE_STATUS_FAILED_REVIEW = int32(shopcommonv1.TenantStoreStatus_FAILED_REVIEW_TSS)
	// TENANT_STORE_STATUS_APPROVED 表示租户门店审核通过。
	TENANT_STORE_STATUS_APPROVED = int32(shopcommonv1.TenantStoreStatus_APPROVED_TSS)
)

const (
	// GOODS_STATUS_PUT_ON 表示商品已上架。
	GOODS_STATUS_PUT_ON = int32(shopcommonv1.GoodsStatus_PUT_ON)
	// GOODS_STATUS_PULL_OFF 表示商品已下架。
	GOODS_STATUS_PULL_OFF = int32(shopcommonv1.GoodsStatus_PULL_OFF)
	// GOODS_STATUS_DISABLED_BY_STORE 表示商品因门店状态下架。
	GOODS_STATUS_DISABLED_BY_STORE = int32(shopcommonv1.GoodsStatus_DISABLED_BY_STORE)
)

const (
	// ORDER_TRADE_STATUS_PENDING_PAYMENT 表示交易待支付。
	ORDER_TRADE_STATUS_PENDING_PAYMENT = int32(shopcommonv1.OrderTradeStatus_PENDING_PAYMENT_OTS)
	// ORDER_TRADE_STATUS_PAYING 表示交易支付中。
	ORDER_TRADE_STATUS_PAYING = int32(shopcommonv1.OrderTradeStatus_PAYING_OTS)
	// ORDER_TRADE_STATUS_PAID 表示交易已支付。
	ORDER_TRADE_STATUS_PAID = int32(shopcommonv1.OrderTradeStatus_PAID_OTS)
	// ORDER_TRADE_STATUS_CASH_ON_DELIVERY 表示交易货到付款。
	ORDER_TRADE_STATUS_CASH_ON_DELIVERY = int32(shopcommonv1.OrderTradeStatus_CASH_ON_DELIVERY_OTS)
	// ORDER_TRADE_STATUS_CLOSED 表示交易已关闭。
	ORDER_TRADE_STATUS_CLOSED = int32(shopcommonv1.OrderTradeStatus_CLOSED_OTS)
	// ORDER_TRADE_STATUS_PARTIAL_REFUND 表示交易部分退款。
	ORDER_TRADE_STATUS_PARTIAL_REFUND = int32(shopcommonv1.OrderTradeStatus_PARTIAL_REFUND_OTS)
	// ORDER_TRADE_STATUS_FULL_REFUND 表示交易全额退款。
	ORDER_TRADE_STATUS_FULL_REFUND = int32(shopcommonv1.OrderTradeStatus_FULL_REFUND_OTS)
	// ORDER_TRADE_STATUS_UNKNOWN 表示交易状态未指定。
	ORDER_TRADE_STATUS_UNKNOWN = int32(shopcommonv1.OrderTradeStatus_UNKNOWN_OTS)
)

const (
	// ORDER_INFO_STATUS_NOT_STARTED 表示订单尚未履约。
	ORDER_INFO_STATUS_NOT_STARTED = int32(shopcommonv1.OrderInfoStatus_NOT_STARTED_OIS)
	// ORDER_INFO_STATUS_WAIT_SHIPMENT 表示订单待发货。
	ORDER_INFO_STATUS_WAIT_SHIPMENT = int32(shopcommonv1.OrderInfoStatus_WAIT_SHIPMENT_OIS)
	// ORDER_INFO_STATUS_SHIPPED 表示订单已发货。
	ORDER_INFO_STATUS_SHIPPED = int32(shopcommonv1.OrderInfoStatus_SHIPPED_OIS)
	// ORDER_INFO_STATUS_WAIT_REVIEW 表示订单待评价。
	ORDER_INFO_STATUS_WAIT_REVIEW = int32(shopcommonv1.OrderInfoStatus_WAIT_REVIEW_OIS)
	// ORDER_INFO_STATUS_COMPLETED 表示订单已完成。
	ORDER_INFO_STATUS_COMPLETED = int32(shopcommonv1.OrderInfoStatus_COMPLETED_OIS)
	// ORDER_INFO_STATUS_CANCELED 表示订单已取消。
	ORDER_INFO_STATUS_CANCELED = int32(shopcommonv1.OrderInfoStatus_CANCELED_OIS)
	// ORDER_INFO_STATUS_UNKNOWN 表示订单状态未指定。
	ORDER_INFO_STATUS_UNKNOWN = int32(shopcommonv1.OrderInfoStatus_UNKNOWN_OIS)
)

const (
	// ORDER_REFUND_STATUS_NONE 表示订单无退款。
	ORDER_REFUND_STATUS_NONE = int32(shopcommonv1.OrderRefundStatus_NONE_ORS)
	// ORDER_REFUND_STATUS_PROCESSING 表示订单退款处理中。
	ORDER_REFUND_STATUS_PROCESSING = int32(shopcommonv1.OrderRefundStatus_PROCESSING_ORS)
	// ORDER_REFUND_STATUS_PARTIAL_REFUND 表示订单部分退款。
	ORDER_REFUND_STATUS_PARTIAL_REFUND = int32(shopcommonv1.OrderRefundStatus_PARTIAL_REFUND_ORS)
	// ORDER_REFUND_STATUS_REFUNDED 表示订单已退款。
	ORDER_REFUND_STATUS_REFUNDED = int32(shopcommonv1.OrderRefundStatus_REFUNDED_ORS)
	// ORDER_REFUND_STATUS_CLOSED_OR_FAILED 表示订单退款关闭或失败。
	ORDER_REFUND_STATUS_CLOSED_OR_FAILED = int32(shopcommonv1.OrderRefundStatus_CLOSED_OR_FAILED_ORS)
	// ORDER_REFUND_STATUS_UNKNOWN 表示订单退款状态未指定。
	ORDER_REFUND_STATUS_UNKNOWN = int32(shopcommonv1.OrderRefundStatus_UNKNOWN_ORS)
)

const (
	// ORDER_PAY_TYPE_ONLINE_PAY 表示在线支付。
	ORDER_PAY_TYPE_ONLINE_PAY = int32(shopcommonv1.OrderPayType_ONLINE_PAY)
	// ORDER_PAY_TYPE_CASH_ON_DELIVERY 表示货到付款。
	ORDER_PAY_TYPE_CASH_ON_DELIVERY = int32(shopcommonv1.OrderPayType_CASH_ON_DELIVERY)
	// ORDER_PAY_CHANNEL_WX_PAY 表示微信支付渠道。
	ORDER_PAY_CHANNEL_WX_PAY = int32(shopcommonv1.OrderPayChannel_WX_PAY)
	// ORDER_PAY_CHANNEL_UNION_PAY 表示银联支付渠道。
	ORDER_PAY_CHANNEL_UNION_PAY = int32(shopcommonv1.OrderPayChannel_UNION_PAY)
)

const (
	// ORDER_DELIVERY_TIME_ALL_TIME 表示任意时间配送。
	ORDER_DELIVERY_TIME_ALL_TIME = int32(shopcommonv1.OrderDeliveryTime_ALL_TIME)
	// ORDER_DELIVERY_TIME_WEEKDAY 表示工作日配送。
	ORDER_DELIVERY_TIME_WEEKDAY = int32(shopcommonv1.OrderDeliveryTime_WEEKDAY)
	// ORDER_DELIVERY_TIME_WEEKEND 表示周末配送。
	ORDER_DELIVERY_TIME_WEEKEND = int32(shopcommonv1.OrderDeliveryTime_WEEKEND)
	// ORDER_CANCEL_REASON_GOODS_NO_STOCK 表示商品无货取消订单。
	ORDER_CANCEL_REASON_GOODS_NO_STOCK = int32(shopcommonv1.OrderCancelReason_CANCEL_GOODS_NO_STOCK)
	// ORDER_CANCEL_REASON_SELF 表示用户取消订单。
	ORDER_CANCEL_REASON_SELF = int32(shopcommonv1.OrderCancelReason_CANCEL_SELF)
	// ORDER_CANCEL_REASON_GOODS_ERROR 表示商品信息错误取消订单。
	ORDER_CANCEL_REASON_GOODS_ERROR = int32(shopcommonv1.OrderCancelReason_CANCEL_GOODS_ERROR)
	// ORDER_CANCEL_REASON_ADDRESS_ERROR 表示地址错误取消订单。
	ORDER_CANCEL_REASON_ADDRESS_ERROR = int32(shopcommonv1.OrderCancelReason_CANCEL_ADDRESS_ERROR)
	// ORDER_CANCEL_REASON_GOODS_DISCOUNT 表示商品降价取消订单。
	ORDER_CANCEL_REASON_GOODS_DISCOUNT = int32(shopcommonv1.OrderCancelReason_CANCEL_GOODS_DISCOUNT)
	// ORDER_CANCEL_REASON_OTHER 表示其他订单取消原因。
	ORDER_CANCEL_REASON_OTHER = int32(shopcommonv1.OrderCancelReason_CANCEL_OTHER)
)

const (
	// ORDER_BILL_STATUS_NO_CHECK 表示订单未对账。
	ORDER_BILL_STATUS_NO_CHECK = int32(shopcommonv1.OrderBillStatus_NO_CHECK)
	// ORDER_BILL_STATUS_CHECK_SUCCESS 表示订单对账成功。
	ORDER_BILL_STATUS_CHECK_SUCCESS = int32(shopcommonv1.OrderBillStatus_CHECK_SUCCESS)
	// ORDER_BILL_STATUS_CHECK_FAIL 表示订单对账失败。
	ORDER_BILL_STATUS_CHECK_FAIL = int32(shopcommonv1.OrderBillStatus_CHECK_FAIL)
	// ORDER_REFUND_REASON_GOODS_NO_STOCK 表示商品无货退款。
	ORDER_REFUND_REASON_GOODS_NO_STOCK = int32(shopcommonv1.OrderRefundReason_REFUND_GOODS_NO_STOCK)
	// ORDER_REFUND_REASON_SELF 表示用户退款。
	ORDER_REFUND_REASON_SELF = int32(shopcommonv1.OrderRefundReason_REFUND_SELF)
	// ORDER_REFUND_REASON_GOODS_ERROR 表示商品信息错误退款。
	ORDER_REFUND_REASON_GOODS_ERROR = int32(shopcommonv1.OrderRefundReason_REFUND_GOODS_ERROR)
	// ORDER_REFUND_REASON_ADDRESS_ERROR 表示地址错误退款。
	ORDER_REFUND_REASON_ADDRESS_ERROR = int32(shopcommonv1.OrderRefundReason_REFUND_ADDRESS_ERROR)
	// ORDER_REFUND_REASON_GOODS_DISCOUNT 表示商品降价退款。
	ORDER_REFUND_REASON_GOODS_DISCOUNT = int32(shopcommonv1.OrderRefundReason_REFUND_GOODS_DISCOUNT)
	// ORDER_REFUND_REASON_OTHER 表示其他退款原因。
	ORDER_REFUND_REASON_OTHER = int32(shopcommonv1.OrderRefundReason_REFUND_OTHER)
)

const (
	// SHOP_BANNER_SITE_INDEX 表示首页轮播图。
	SHOP_BANNER_SITE_INDEX = int32(shopcommonv1.ShopBannerSite_INDEX)
	// SHOP_BANNER_SITE_CATEGORY 表示分类页轮播图。
	SHOP_BANNER_SITE_CATEGORY = int32(shopcommonv1.ShopBannerSite_CATEGORY)
	// SHOP_BANNER_TYPE_BANNER_GOODS_DETAIL 表示跳转商品详情。
	SHOP_BANNER_TYPE_BANNER_GOODS_DETAIL = int32(shopcommonv1.ShopBannerType_BANNER_GOODS_DETAIL)
	// SHOP_BANNER_TYPE_CATEGORY_DETAIL 表示跳转分类详情。
	SHOP_BANNER_TYPE_CATEGORY_DETAIL = int32(shopcommonv1.ShopBannerType_CATEGORY_DETAIL)
	// SHOP_BANNER_TYPE_WEB_VIEW 表示跳转 WebView。
	SHOP_BANNER_TYPE_WEB_VIEW = int32(shopcommonv1.ShopBannerType_WEB_VIEW)
	// SHOP_BANNER_TYPE_MINI 表示跳转其他小程序。
	SHOP_BANNER_TYPE_MINI = int32(shopcommonv1.ShopBannerType_MINI)
)

const (
	// PAY_BILL_STATUS_NO_COMPARE 表示账单未比对。
	PAY_BILL_STATUS_NO_COMPARE = int32(shopcommonv1.PayBillStatus_NO_COMPARE)
	// PAY_BILL_STATUS_NO_ERROR 表示账单比对无误差。
	PAY_BILL_STATUS_NO_ERROR = int32(shopcommonv1.PayBillStatus_NO_ERROR)
	// PAY_BILL_STATUS_HAS_ERROR 表示账单比对有误差。
	PAY_BILL_STATUS_HAS_ERROR = int32(shopcommonv1.PayBillStatus_HAS_ERROR)
)

const (
	// RECOMMEND_SCENE_HOME 表示首页推荐。
	RECOMMEND_SCENE_HOME = int32(shopcommonv1.RecommendScene_HOME)
	// RECOMMEND_SCENE_GOODS_DETAIL 表示商品详情推荐。
	RECOMMEND_SCENE_GOODS_DETAIL = int32(shopcommonv1.RecommendScene_GOODS_DETAIL)
	// RECOMMEND_SCENE_CART 表示购物车推荐。
	RECOMMEND_SCENE_CART = int32(shopcommonv1.RecommendScene_CART)
	// RECOMMEND_SCENE_PROFILE 表示个人中心推荐。
	RECOMMEND_SCENE_PROFILE = int32(shopcommonv1.RecommendScene_PROFILE)
	// RECOMMEND_SCENE_ORDER_DETAIL 表示订单详情推荐。
	RECOMMEND_SCENE_ORDER_DETAIL = int32(shopcommonv1.RecommendScene_ORDER_DETAIL)
	// RECOMMEND_SCENE_ORDER_PAID 表示支付完成推荐。
	RECOMMEND_SCENE_ORDER_PAID = int32(shopcommonv1.RecommendScene_ORDER_PAID)
	// RECOMMEND_SCENE_UNKNOWN 表示推荐场景未指定。
	RECOMMEND_SCENE_UNKNOWN = int32(shopcommonv1.RecommendScene_UNKNOWN_RS)
	// RECOMMEND_ACTOR_TYPE_ANONYMOUS 表示匿名推荐主体。
	RECOMMEND_ACTOR_TYPE_ANONYMOUS = int32(shopcommonv1.RecommendActorType_ANONYMOUS_ACTOR)
	// RECOMMEND_ACTOR_TYPE_USER 表示用户推荐主体。
	RECOMMEND_ACTOR_TYPE_USER = int32(shopcommonv1.RecommendActorType_USER_ACTOR)
	// RECOMMEND_ACTOR_TYPE_UNKNOWN 表示推荐主体类型未指定。
	RECOMMEND_ACTOR_TYPE_UNKNOWN = int32(shopcommonv1.RecommendActorType_UNKNOWN_RAT)
	// RECOMMEND_STRATEGY_REMOTE 表示远程推荐策略。
	RECOMMEND_STRATEGY_REMOTE = int32(shopcommonv1.RecommendStrategy_REMOTE_STRATEGY)
	// RECOMMEND_STRATEGY_LOCAL 表示本地推荐策略。
	RECOMMEND_STRATEGY_LOCAL = int32(shopcommonv1.RecommendStrategy_LOCAL_STRATEGY)
	// RECOMMEND_STRATEGY_UNKNOWN 表示推荐策略未指定。
	RECOMMEND_STRATEGY_UNKNOWN = int32(shopcommonv1.RecommendStrategy_UNKNOWN_RST)
)

const (
	// RECOMMEND_EVENT_TYPE_EXPOSURE 表示推荐曝光。
	RECOMMEND_EVENT_TYPE_EXPOSURE = int32(shopcommonv1.RecommendEventType_EXPOSURE)
	// RECOMMEND_EVENT_TYPE_CLICK 表示推荐点击。
	RECOMMEND_EVENT_TYPE_CLICK = int32(shopcommonv1.RecommendEventType_CLICK)
	// RECOMMEND_EVENT_TYPE_VIEW 表示商品浏览。
	RECOMMEND_EVENT_TYPE_VIEW = int32(shopcommonv1.RecommendEventType_VIEW)
	// RECOMMEND_EVENT_TYPE_COLLECT 表示商品收藏。
	RECOMMEND_EVENT_TYPE_COLLECT = int32(shopcommonv1.RecommendEventType_COLLECT)
	// RECOMMEND_EVENT_TYPE_ADD_CART 表示商品加购。
	RECOMMEND_EVENT_TYPE_ADD_CART = int32(shopcommonv1.RecommendEventType_ADD_CART)
	// RECOMMEND_EVENT_TYPE_ORDER_CREATE 表示创建订单。
	RECOMMEND_EVENT_TYPE_ORDER_CREATE = int32(shopcommonv1.RecommendEventType_ORDER_CREATE)
	// RECOMMEND_EVENT_TYPE_ORDER_PAY 表示订单支付。
	RECOMMEND_EVENT_TYPE_ORDER_PAY = int32(shopcommonv1.RecommendEventType_ORDER_PAY)
	// RECOMMEND_EVENT_TYPE_UNKNOWN 表示推荐事件未指定。
	RECOMMEND_EVENT_TYPE_UNKNOWN = int32(shopcommonv1.RecommendEventType_UNKNOWN_RET)
)

const (
	// ADVANCE_DATA_TYPE_USER 表示推荐调试用户数据。
	ADVANCE_DATA_TYPE_USER = int32(shopcommonv1.AdvanceDataType_USER_RRADT)
	// ADVANCE_DATA_TYPE_ITEM 表示推荐调试商品数据。
	ADVANCE_DATA_TYPE_ITEM = int32(shopcommonv1.AdvanceDataType_ITEM_RRADT)
	// ADVANCE_DATA_TYPE_FEEDBACK 表示推荐调试反馈数据。
	ADVANCE_DATA_TYPE_FEEDBACK = int32(shopcommonv1.AdvanceDataType_FEEDBACK_RRADT)
	// ADVANCE_DATA_TYPE_UNKNOWN 表示推荐调试数据未指定。
	ADVANCE_DATA_TYPE_UNKNOWN = int32(shopcommonv1.AdvanceDataType_UNKNOWN_RRADT)
)

const (
	// COMMENT_STATUS_PENDING_REVIEW 表示评价待审核。
	COMMENT_STATUS_PENDING_REVIEW = int32(shopcommonv1.CommentStatus_PENDING_REVIEW_CS)
	// COMMENT_STATUS_APPROVED 表示评价审核通过。
	COMMENT_STATUS_APPROVED = int32(shopcommonv1.CommentStatus_APPROVED_CS)
	// COMMENT_STATUS_REJECTED 表示评价审核拒绝。
	COMMENT_STATUS_REJECTED = int32(shopcommonv1.CommentStatus_REJECTED_CS)
	// COMMENT_REVIEW_TARGET_TYPE_COMMENT 表示审核评价。
	COMMENT_REVIEW_TARGET_TYPE_COMMENT = int32(shopcommonv1.CommentReviewTargetType_COMMENT_REVIEW_TARGET_TYPE_COMMENT)
	// COMMENT_REVIEW_TARGET_TYPE_DISCUSSION 表示审核讨论。
	COMMENT_REVIEW_TARGET_TYPE_DISCUSSION = int32(shopcommonv1.CommentReviewTargetType_COMMENT_REVIEW_TARGET_TYPE_DISCUSSION)
	// COMMENT_REVIEW_TYPE_AI 表示 AI 审核。
	COMMENT_REVIEW_TYPE_AI = int32(shopcommonv1.CommentReviewType_COMMENT_REVIEW_TYPE_AI)
	// COMMENT_REVIEW_TYPE_MANUAL 表示人工审核。
	COMMENT_REVIEW_TYPE_MANUAL = int32(shopcommonv1.CommentReviewType_COMMENT_REVIEW_TYPE_MANUAL)
	// COMMENT_REVIEW_STATUS_APPROVED 表示审核通过。
	COMMENT_REVIEW_STATUS_APPROVED = int32(shopcommonv1.CommentReviewStatus_COMMENT_REVIEW_STATUS_APPROVED)
	// COMMENT_REVIEW_STATUS_REJECTED 表示审核拒绝。
	COMMENT_REVIEW_STATUS_REJECTED = int32(shopcommonv1.CommentReviewStatus_COMMENT_REVIEW_STATUS_REJECTED)
	// COMMENT_REVIEW_STATUS_EXCEPTION 表示审核异常。
	COMMENT_REVIEW_STATUS_EXCEPTION = int32(shopcommonv1.CommentReviewStatus_COMMENT_REVIEW_STATUS_EXCEPTION)
)

const (
	// COMMENT_SUMMARY_SCENE_OVERVIEW 表示详情评价摘要。
	COMMENT_SUMMARY_SCENE_OVERVIEW = int32(shopcommonv1.CommentSummaryScene_OVERVIEW)
	// COMMENT_SUMMARY_SCENE_LIST 表示列表评价摘要。
	COMMENT_SUMMARY_SCENE_LIST = int32(shopcommonv1.CommentSummaryScene_LIST)
	// COMMENT_REACTION_TARGET_TYPE_COMMENT 表示评价互动目标。
	COMMENT_REACTION_TARGET_TYPE_COMMENT = int32(shopcommonv1.CommentReactionTargetType_COMMENT)
	// COMMENT_REACTION_TARGET_TYPE_DISCUSSION 表示讨论互动目标。
	COMMENT_REACTION_TARGET_TYPE_DISCUSSION = int32(shopcommonv1.CommentReactionTargetType_DISCUSSION)
	// COMMENT_REACTION_TARGET_TYPE_SUMMARY 表示摘要互动目标。
	COMMENT_REACTION_TARGET_TYPE_SUMMARY = int32(shopcommonv1.CommentReactionTargetType_SUMMARY)
	// COMMENT_REACTION_TYPE_LIKE 表示点赞互动。
	COMMENT_REACTION_TYPE_LIKE = int32(shopcommonv1.CommentReactionType_LIKE)
	// COMMENT_REACTION_TYPE_DISLIKE 表示点踩互动。
	COMMENT_REACTION_TYPE_DISLIKE = int32(shopcommonv1.CommentReactionType_DISLIKE)
)

const (
	// COMMENT_FILTER_TYPE_ALL 表示全部评价。
	COMMENT_FILTER_TYPE_ALL = int32(shopcommonv1.CommentFilterType_COMMENT_FILTER_ALL)
	// COMMENT_FILTER_TYPE_MEDIA 表示包含媒体的评价。
	COMMENT_FILTER_TYPE_MEDIA = int32(shopcommonv1.CommentFilterType_COMMENT_FILTER_MEDIA)
	// COMMENT_FILTER_TYPE_GOOD 表示好评。
	COMMENT_FILTER_TYPE_GOOD = int32(shopcommonv1.CommentFilterType_COMMENT_FILTER_GOOD)
	// COMMENT_FILTER_TYPE_MIDDLE 表示中评。
	COMMENT_FILTER_TYPE_MIDDLE = int32(shopcommonv1.CommentFilterType_COMMENT_FILTER_MIDDLE)
	// COMMENT_FILTER_TYPE_BAD 表示差评。
	COMMENT_FILTER_TYPE_BAD = int32(shopcommonv1.CommentFilterType_COMMENT_FILTER_BAD)
	// COMMENT_FILTER_TYPE_TAG 表示标签筛选。
	COMMENT_FILTER_TYPE_TAG = int32(shopcommonv1.CommentFilterType_COMMENT_FILTER_TAG)
	// COMMENT_SORT_TYPE_DEFAULT 表示默认排序。
	COMMENT_SORT_TYPE_DEFAULT = int32(shopcommonv1.CommentSortType_COMMENT_SORT_DEFAULT)
	// COMMENT_SORT_TYPE_LATEST 表示最新排序。
	COMMENT_SORT_TYPE_LATEST = int32(shopcommonv1.CommentSortType_COMMENT_SORT_LATEST)
)

const (
	// RESOURCE_TYPE_TRANSACTION 表示支付交易通知资源。
	RESOURCE_TYPE_TRANSACTION = int32(commonv1.ResourceType_TRANSACTION)
	// RESOURCE_TYPE_REFUND 表示退款通知资源。
	RESOURCE_TYPE_REFUND = int32(commonv1.ResourceType_REFUND)
	// ANALYTICS_TIME_TYPE_WEEK 表示按周统计。
	ANALYTICS_TIME_TYPE_WEEK = baseconst.ANALYTICS_TIME_TYPE_WEEK
	// ANALYTICS_TIME_TYPE_MONTH 表示按月统计。
	ANALYTICS_TIME_TYPE_MONTH = baseconst.ANALYTICS_TIME_TYPE_MONTH
	// ANALYTICS_TIME_TYPE_YEAR 表示按年统计。
	ANALYTICS_TIME_TYPE_YEAR = baseconst.ANALYTICS_TIME_TYPE_YEAR
	// ANALYTICS_SERIES_TYPE_BAR 表示柱状图系列。
	ANALYTICS_SERIES_TYPE_BAR = baseconst.ANALYTICS_SERIES_TYPE_BAR
	// ANALYTICS_SERIES_TYPE_LINE 表示折线图系列。
	ANALYTICS_SERIES_TYPE_LINE = baseconst.ANALYTICS_SERIES_TYPE_LINE
)
