package consts

import shopappv1 "shop/api/gen/go/shop/app/v1"

const (
	// PAYMENT_RESOURCE_TRADE_STATE_UNSPECIFIED 表示支付交易状态未指定。
	PAYMENT_RESOURCE_TRADE_STATE_UNSPECIFIED = int32(shopappv1.PaymentResource_TRADE_STATE_UNSPECIFIED)
	// PAYMENT_RESOURCE_TRADE_STATE_SUCCESS 表示支付成功。
	PAYMENT_RESOURCE_TRADE_STATE_SUCCESS = int32(shopappv1.PaymentResource_SUCCESS)
	// PAYMENT_RESOURCE_TRADE_STATE_REFUND 表示支付已退款。
	PAYMENT_RESOURCE_TRADE_STATE_REFUND = int32(shopappv1.PaymentResource_REFUND)
	// PAYMENT_RESOURCE_TRADE_STATE_NOT_PAY 表示支付未完成。
	PAYMENT_RESOURCE_TRADE_STATE_NOT_PAY = int32(shopappv1.PaymentResource_NOTPAY)
	// PAYMENT_RESOURCE_TRADE_STATE_CLOSED 表示支付已关闭。
	PAYMENT_RESOURCE_TRADE_STATE_CLOSED = int32(shopappv1.PaymentResource_CLOSED)
	// PAYMENT_RESOURCE_TRADE_STATE_REVOKED 表示支付已撤销。
	PAYMENT_RESOURCE_TRADE_STATE_REVOKED = int32(shopappv1.PaymentResource_REVOKED)
	// PAYMENT_RESOURCE_TRADE_STATE_USER_PAYING 表示用户支付中。
	PAYMENT_RESOURCE_TRADE_STATE_USER_PAYING = int32(shopappv1.PaymentResource_USERPAYING)
	// PAYMENT_RESOURCE_TRADE_STATE_PAY_ERROR 表示支付失败。
	PAYMENT_RESOURCE_TRADE_STATE_PAY_ERROR = int32(shopappv1.PaymentResource_PAYERROR)
)

const (
	// PAYMENT_RESOURCE_TRADE_TYPE_UNSPECIFIED 表示支付交易类型未指定。
	PAYMENT_RESOURCE_TRADE_TYPE_UNSPECIFIED = int32(shopappv1.PaymentResource_TRADE_TYPE_UNSPECIFIED)
	// PAYMENT_RESOURCE_TRADE_TYPE_JSAPI 表示 JSAPI 支付。
	PAYMENT_RESOURCE_TRADE_TYPE_JSAPI = int32(shopappv1.PaymentResource_JSAPI)
	// PAYMENT_RESOURCE_TRADE_TYPE_NATIVE 表示 Native 支付。
	PAYMENT_RESOURCE_TRADE_TYPE_NATIVE = int32(shopappv1.PaymentResource_NATIVE)
	// PAYMENT_RESOURCE_TRADE_TYPE_APP 表示应用支付。
	PAYMENT_RESOURCE_TRADE_TYPE_APP = int32(shopappv1.PaymentResource_APP)
	// PAYMENT_RESOURCE_TRADE_TYPE_MICROPAY 表示付款码支付。
	PAYMENT_RESOURCE_TRADE_TYPE_MICROPAY = int32(shopappv1.PaymentResource_MICROPAY)
	// PAYMENT_RESOURCE_TRADE_TYPE_MWEB 表示 H5 支付。
	PAYMENT_RESOURCE_TRADE_TYPE_MWEB = int32(shopappv1.PaymentResource_MWEB)
	// PAYMENT_RESOURCE_TRADE_TYPE_FACEPAY 表示刷脸支付。
	PAYMENT_RESOURCE_TRADE_TYPE_FACEPAY = int32(shopappv1.PaymentResource_FACEPAY)
)

const (
	// REFUND_RESOURCE_STATUS_UNSPECIFIED 表示退款状态未指定。
	REFUND_RESOURCE_STATUS_UNSPECIFIED = int32(shopappv1.RefundResource_REFUND_STATUS_UNSPECIFIED)
	// REFUND_RESOURCE_STATUS_SUCCESS 表示退款成功。
	REFUND_RESOURCE_STATUS_SUCCESS = int32(shopappv1.RefundResource_SUCCESS)
	// REFUND_RESOURCE_STATUS_CLOSED 表示退款关闭。
	REFUND_RESOURCE_STATUS_CLOSED = int32(shopappv1.RefundResource_CLOSED)
	// REFUND_RESOURCE_STATUS_PROCESSING 表示退款处理中。
	REFUND_RESOURCE_STATUS_PROCESSING = int32(shopappv1.RefundResource_PROCESSING)
	// REFUND_RESOURCE_STATUS_ABNORMAL 表示退款异常。
	REFUND_RESOURCE_STATUS_ABNORMAL = int32(shopappv1.RefundResource_ABNORMAL)
)
