// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_post.proto

package admin

import (
	"context"
	"fmt"

	commonv1 "shop/api/gen/go/common/v1"
	systemadminv1 "shop/api/gen/go/system/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/system/admin/biz"

	"github.com/go-kratos/kratos/v3/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// BasePostService Admin岗位管理服务。
type BasePostService struct {
	systemadminv1.UnimplementedBasePostServiceServer
	basePostCase *biz.BasePostCase
}

// NewBasePostService 创建Admin岗位管理服务。
func NewBasePostService(basePostCase *biz.BasePostCase) *BasePostService {
	return &BasePostService{basePostCase: basePostCase}
}

// OptionBasePost 查询岗位下拉选择。
func (s *BasePostService) OptionBasePost(ctx context.Context, req *systemadminv1.OptionBasePostRequest) (*commonv1.SelectOptionResponse, error) {
	list, err := s.basePostCase.OptionBasePost(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("OptionBasePost %v", err))
		return nil, errorsx.WrapInternal(err, "查询岗位下拉列表失败")
	}
	return list, nil
}

// PageBasePost 查询岗位分页列表。
func (s *BasePostService) PageBasePost(ctx context.Context, req *systemadminv1.PageBasePostRequest) (*systemadminv1.PageBasePostResponse, error) {
	page, err := s.basePostCase.PageBasePost(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("PageBasePost %v", err))
		return nil, errorsx.WrapInternal(err, "查询岗位分页列表失败")
	}
	return page, nil
}

// GetBasePost 查询岗位。
func (s *BasePostService) GetBasePost(ctx context.Context, req *systemadminv1.GetBasePostRequest) (*systemadminv1.BasePostForm, error) {
	basePost, err := s.basePostCase.GetBasePost(ctx, req.GetId())
	if err != nil {
		log.Error(fmt.Sprintf("GetBasePost %v", err))
		return nil, errorsx.WrapInternal(err, "查询岗位失败")
	}
	return basePost, nil
}

// CreateBasePost 创建岗位。
func (s *BasePostService) CreateBasePost(ctx context.Context, req *systemadminv1.CreateBasePostRequest) (*emptypb.Empty, error) {
	err := s.basePostCase.CreateBasePost(ctx, req.GetBasePost())
	if err != nil {
		log.Error(fmt.Sprintf("CreateBasePost %v", err))
		return nil, errorsx.WrapInternal(err, "创建岗位失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateBasePost 更新岗位。
func (s *BasePostService) UpdateBasePost(ctx context.Context, req *systemadminv1.UpdateBasePostRequest) (*emptypb.Empty, error) {
	err := s.basePostCase.UpdateBasePost(ctx, req.GetBasePost())
	if err != nil {
		log.Error(fmt.Sprintf("UpdateBasePost %v", err))
		return nil, errorsx.WrapInternal(err, "更新岗位失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteBasePost 删除岗位。
func (s *BasePostService) DeleteBasePost(ctx context.Context, req *systemadminv1.DeleteBasePostRequest) (*emptypb.Empty, error) {
	err := s.basePostCase.DeleteBasePost(ctx, req.GetId())
	if err != nil {
		log.Error(fmt.Sprintf("DeleteBasePost %v", err))
		return nil, errorsx.WrapInternal(err, "删除岗位失败")
	}
	return new(emptypb.Empty), nil
}

// SetBasePostStatus 设置岗位状态。
func (s *BasePostService) SetBasePostStatus(ctx context.Context, req *systemadminv1.SetBasePostStatusRequest) (*emptypb.Empty, error) {
	err := s.basePostCase.SetBasePostStatus(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("SetBasePostStatus %v", err))
		return nil, errorsx.WrapInternal(err, "设置岗位状态失败")
	}
	return new(emptypb.Empty), nil
}
