// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_api.proto

package admin

import (
	"context"
	"fmt"

	systemadminv1 "shop/api/gen/go/system/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/system/admin/biz"

	"github.com/go-kratos/kratos/v3/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseApiService AdminAPI列表
type BaseApiService struct {
	systemadminv1.UnimplementedBaseApiServiceServer
	baseAPICase *biz.BaseAPICase
}

// NewBaseApiService 创建AdminAPI列表
func NewBaseApiService(
	baseAPICase *biz.BaseAPICase,
) *BaseApiService {
	return &BaseApiService{
		baseAPICase: baseAPICase,
	}
}

// PageBaseApi 分页查询API列表
func (s *BaseApiService) PageBaseApi(ctx context.Context, req *systemadminv1.PageBaseApiRequest) (*systemadminv1.PageBaseApiResponse, error) {
	list, err := s.baseAPICase.PageBaseAPI(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("PageBaseApi %v", err))
		return nil, errorsx.WrapInternal(err, "分页查询API列表失败")
	}

	return list, nil
}

// ListBaseApi 查询菜单分配API选项列表
func (s *BaseApiService) ListBaseApi(ctx context.Context, req *systemadminv1.ListBaseApiRequest) (*systemadminv1.ListBaseApiResponse, error) {
	list, err := s.baseAPICase.ListBaseAPI(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("ListBaseApi %v", err))
		return nil, errorsx.WrapInternal(err, "查询API选项列表失败")
	}

	return list, nil
}

// GetBaseApi 查询API详情
func (s *BaseApiService) GetBaseApi(ctx context.Context, req *systemadminv1.GetBaseApiRequest) (*systemadminv1.BaseApi, error) {
	baseAPI, err := s.baseAPICase.GetBaseAPI(ctx, req.GetId())
	if err != nil {
		log.Error(fmt.Sprintf("GetBaseApi %v", err))
		return nil, errorsx.WrapInternal(err, "查询API详情失败")
	}

	return baseAPI, nil
}

// GetBaseApiDoc 查询API文档
func (s *BaseApiService) GetBaseApiDoc(ctx context.Context, req *systemadminv1.GetBaseApiDocRequest) (*systemadminv1.BaseApiDoc, error) {
	baseAPIDoc, err := s.baseAPICase.GetBaseAPIDoc(ctx, req.GetId())
	if err != nil {
		log.Error(fmt.Sprintf("GetBaseApiDoc %v", err))
		return nil, errorsx.WrapInternal(err, "查询API文档失败")
	}

	return baseAPIDoc, nil
}

// UpdateBaseApi 更新API配置
func (s *BaseApiService) UpdateBaseApi(ctx context.Context, req *systemadminv1.UpdateBaseApiRequest) (*emptypb.Empty, error) {
	err := s.baseAPICase.UpdateBaseAPI(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("UpdateBaseApi %v", err))
		return nil, errorsx.WrapInternal(err, "更新API配置失败")
	}

	return &emptypb.Empty{}, nil
}

// SetBaseApiAgentStatus 设置API Agent工具状态
func (s *BaseApiService) SetBaseApiAgentStatus(ctx context.Context, req *systemadminv1.SetBaseApiAgentStatusRequest) (*emptypb.Empty, error) {
	err := s.baseAPICase.SetBaseAPIAgentStatus(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("SetBaseApiAgentStatus %v", err))
		return nil, errorsx.WrapInternal(err, "设置API Agent工具状态失败")
	}

	return &emptypb.Empty{}, nil
}

// SetBaseApiMcpStatus 设置API MCP工具状态
func (s *BaseApiService) SetBaseApiMcpStatus(ctx context.Context, req *systemadminv1.SetBaseApiMcpStatusRequest) (*emptypb.Empty, error) {
	err := s.baseAPICase.SetBaseAPIMcpStatus(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("SetBaseApiMcpStatus %v", err))
		return nil, errorsx.WrapInternal(err, "设置API MCP工具状态失败")
	}

	return &emptypb.Empty{}, nil
}
