// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/auth.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"shop/api/gen/go/app"
)

const _ = grpc.SupportPackageIsVersion7

// AuthService App用户登录认证服务。
type AuthService struct {
	app.UnimplementedAuthServiceServer
	*core.ShopCore
}

// NewAuthService 创建App用户登录认证服务。
func NewAuthService(sc *core.ShopCore) *AuthService {
	var ss = AuthService{
		ShopCore: sc,
	}
	return &ss
}

// WxLogin 微信登录。
func (s *AuthService) WxLogin(ctx context.Context, req *app.WxLoginRequest) (*app.WxLoginResponse, error) {
	var reply = &app.WxLoginResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method WxLogin not implemented")
	return reply, err
}

// GetUserInfo 获取已经登录的用户的数据。
func (s *AuthService) GetUserInfo(ctx context.Context, req *emptypb.Empty) (*app.UserInfo, error) {
	var reply = &app.UserInfo{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
	return reply, err
}

// UpdateUserInfo 修改个人中心用户信息。
func (s *AuthService) UpdateUserInfo(ctx context.Context, req *app.UpdateUserInfoRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method UpdateUserInfo not implemented")
	return reply, err
}

// PhoneAuth 手机号授权。
func (s *AuthService) PhoneAuth(ctx context.Context, req *app.PhoneAuthRequest) (*app.PhoneAuthResponse, error) {
	var reply = &app.PhoneAuthResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PhoneAuth not implemented")
	return reply, err
}
