// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/base_dict.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/wrapperspb"
	"shop/api/gen/go/app"
)

const _ = grpc.SupportPackageIsVersion7

// BaseDictService App字典服务。
type BaseDictService struct {
	app.UnimplementedBaseDictServiceServer
	*core.ShopCore
}

// NewBaseDictService 创建App字典服务。
func NewBaseDictService(sc *core.ShopCore) *BaseDictService {
	var ss = BaseDictService{
		ShopCore: sc,
	}
	return &ss
}

// ListBaseDict 查询字典列表。
func (s *BaseDictService) ListBaseDict(ctx context.Context, req *wrapperspb.StringValue) (*app.ListBaseDictResponse, error) {
	var reply = &app.ListBaseDictResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method ListBaseDict not implemented")
	return reply, err
}
