// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/base_area.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"shop/api/gen/go/app"
	"shop/api/gen/go/common"
)

const _ = grpc.SupportPackageIsVersion7

// BaseAreaService App行政区域服务。
type BaseAreaService struct {
	app.UnimplementedBaseAreaServiceServer
	*core.ShopCore
}

// NewBaseAreaService 创建App行政区域服务。
func NewBaseAreaService(sc *core.ShopCore) *BaseAreaService {
	var ss = BaseAreaService{
		ShopCore: sc,
	}
	return &ss
}

// TreeBaseArea 查询行政区域树形列表。
func (s *BaseAreaService) TreeBaseArea(ctx context.Context, req *emptypb.Empty) (*common.AppTreeOptionResponse, error) {
	var reply = &common.AppTreeOptionResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method TreeBaseArea not implemented")
	return reply, err
}
