// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/goods_category.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"shop/api/gen/go/app"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsCategoryService App商品分类服务。
type GoodsCategoryService struct {
	app.UnimplementedGoodsCategoryServiceServer
	*core.ShopCore
}

// NewGoodsCategoryService 创建App商品分类服务。
func NewGoodsCategoryService(sc *core.ShopCore) *GoodsCategoryService {
	var ss = GoodsCategoryService{
		ShopCore: sc,
	}
	return &ss
}

// ListGoodsCategory 查询分类列表。
func (s *GoodsCategoryService) ListGoodsCategory(ctx context.Context, req *app.ListGoodsCategoryRequest) (*app.ListGoodsCategoryResponse, error) {
	var reply = &app.ListGoodsCategoryResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method ListGoodsCategory not implemented")
	return reply, err
}
