// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/order.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
	"shop/api/gen/go/app"
)

const _ = grpc.SupportPackageIsVersion7

// OrderService App订单服务。
type OrderService struct {
	app.UnimplementedOrderServiceServer
	*core.ShopCore
}

// NewOrderService 创建App订单服务。
func NewOrderService(sc *core.ShopCore) *OrderService {
	var ss = OrderService{
		ShopCore: sc,
	}
	return &ss
}

// OrderPre 预付订单。
func (s *OrderService) OrderPre(ctx context.Context, req *emptypb.Empty) (*app.ConfirmOrderResponse, error) {
	var reply = &app.ConfirmOrderResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method OrderPre not implemented")
	return reply, err
}

// OrderBuy 立即购买订单。
func (s *OrderService) OrderBuy(ctx context.Context, req *app.CreateOrderGoods) (*app.ConfirmOrderResponse, error) {
	var reply = &app.ConfirmOrderResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method OrderBuy not implemented")
	return reply, err
}

// OrderRepurchase 再次购买订单。
func (s *OrderService) OrderRepurchase(ctx context.Context, req *app.OrderRepurchaseRequest) (*app.ConfirmOrderResponse, error) {
	var reply = &app.ConfirmOrderResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method OrderRepurchase not implemented")
	return reply, err
}

// CountOrder 查询订单数量汇总。
func (s *OrderService) CountOrder(ctx context.Context, req *emptypb.Empty) (*app.CountOrderResponse, error) {
	var reply = &app.CountOrderResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CountOrder not implemented")
	return reply, err
}

// PageOrder 查询订单分页列表。
func (s *OrderService) PageOrder(ctx context.Context, req *app.PageOrderRequest) (*app.PageOrderResponse, error) {
	var reply = &app.PageOrderResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PageOrder not implemented")
	return reply, err
}

// GetOrderIdByOrderNo 根据订单编号查询订单id。
func (s *OrderService) GetOrderIdByOrderNo(ctx context.Context, req *wrapperspb.StringValue) (*wrapperspb.Int64Value, error) {
	var reply = &wrapperspb.Int64Value{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetOrderIdByOrderNo not implemented")
	return reply, err
}

// GetOrderById 根据订单id查询订单。
func (s *OrderService) GetOrderById(ctx context.Context, req *wrapperspb.Int64Value) (*app.OrderResponse, error) {
	var reply = &app.OrderResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetOrderById not implemented")
	return reply, err
}

// CreateOrder 创建订单。
func (s *OrderService) CreateOrder(ctx context.Context, req *app.CreateOrderRequest) (*app.CreateOrderResponse, error) {
	var reply = &app.CreateOrderResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
	return reply, err
}

// DeleteOrder 删除订单。
func (s *OrderService) DeleteOrder(ctx context.Context, req *wrapperspb.Int64Value) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method DeleteOrder not implemented")
	return reply, err
}

// CancelOrder 取消订单。
func (s *OrderService) CancelOrder(ctx context.Context, req *app.CancelOrderRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
	return reply, err
}

// RefundOrder 订单退款。
func (s *OrderService) RefundOrder(ctx context.Context, req *app.RefundOrderRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method RefundOrder not implemented")
	return reply, err
}

// ReceiveOrder 确认收货。
func (s *OrderService) ReceiveOrder(ctx context.Context, req *app.ReceiveOrderRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method ReceiveOrder not implemented")
	return reply, err
}
