// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/shop_service.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"shop/api/gen/go/app"
)

const _ = grpc.SupportPackageIsVersion7

// ShopServiceService App商城服务。
type ShopServiceService struct {
	app.UnimplementedShopServiceServiceServer
	*core.ShopCore
}

// NewShopServiceService 创建App商城服务。
func NewShopServiceService(sc *core.ShopCore) *ShopServiceService {
	var ss = ShopServiceService{
		ShopCore: sc,
	}
	return &ss
}

// ListShopService 查询商城服务列表。
func (s *ShopServiceService) ListShopService(ctx context.Context, req *emptypb.Empty) (*app.ListShopServiceResponse, error) {
	var reply = &app.ListShopServiceResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method ListShopService not implemented")
	return reply, err
}
