// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/shop_banner.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"shop/api/gen/go/app"
)

const _ = grpc.SupportPackageIsVersion7

// ShopBannerService App轮播图服务。
type ShopBannerService struct {
	app.UnimplementedShopBannerServiceServer
	*core.ShopCore
}

// NewShopBannerService 创建App轮播图服务。
func NewShopBannerService(sc *core.ShopCore) *ShopBannerService {
	var ss = ShopBannerService{
		ShopCore: sc,
	}
	return &ss
}

// ListShopBanner 查询轮播图列表。
func (s *ShopBannerService) ListShopBanner(ctx context.Context, req *app.ListShopBannerRequest) (*app.ListShopBannerResponse, error) {
	var reply = &app.ListShopBannerResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method ListShopBanner not implemented")
	return reply, err
}
