// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: shop/admin/v1/tenant_store.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty";
import type { TenantStoreStatus } from "../../common/v1/enum";

/** 租户门店下拉选项查询条件 */
export interface OptionTenantStoreRequest {
  /** 门店名称关键字 */
  keyword: string;
}

/** 租户门店下拉选项响应 */
export interface OptionTenantStoreResponse {
  /** 门店选项列表 */
  list: OptionTenantStoreResponse_Option[];
}

/** 租户门店选项 */
export interface OptionTenantStoreResponse_Option {
  /** 门店ID */
  value: number;
  /** 门店名称 */
  label: string;
}

/** 租户门店列表查询条件 */
export interface PageTenantStoreRequest {
  /** 门店名称 */
  name: string;
  /** 租户ID */
  tenant_id?:
    | number
    | undefined;
  /** 审核状态：枚举【TenantStoreStatus】 */
  status?:
    | TenantStoreStatus
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 租户门店列表响应 */
export interface PageTenantStoreResponse {
  /** 租户门店列表 */
  tenant_stores: TenantStore[];
  /** 总数 */
  total: number;
}

/** 租户门店树形选项查询条件 */
export interface TreeTenantStoreRequest {
  /** 门店名称关键字 */
  keyword: string;
}

/** 租户门店树形选项响应 */
export interface TreeTenantStoreResponse {
  /** 租户门店树形选项列表 */
  list: TreeTenantStoreResponse_Option[];
}

/** 租户门店树形选项 */
export interface TreeTenantStoreResponse_Option {
  /** 选项值，tenant:{id} 或 store:{id} */
  value: string;
  /** 选项名称 */
  label: string;
  /** 节点类型：tenant 或 store */
  type: string;
  /** 节点业务ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 子节点树 */
  children: TreeTenantStoreResponse_Option[];
}

/** 租户门店详情查询条件 */
export interface GetTenantStoreRequest {
  /** 门店ID */
  id: number;
}

/** 租户门店表单 */
export interface TenantStoreForm {
  /** 门店ID */
  id: number;
  /** 门店名称 */
  name: string;
  /** 门店LOGO */
  logo: string;
  /** 门店封面 */
  cover: string;
  /** 门店简介 */
  intro: string;
  /** 门店公告 */
  notice: string;
  /** 营业执照 */
  business_license: string[];
  /** 备注 */
  remark: string;
  /** 审核状态：枚举【TenantStoreStatus】 */
  status: TenantStoreStatus;
}

/** 租户门店创建条件 */
export interface CreateTenantStoreRequest {
  /** 租户门店表单 */
  tenant_store: TenantStoreForm | undefined;
}

/** 租户门店更新条件 */
export interface UpdateTenantStoreRequest {
  /** 门店ID */
  id: number;
  /** 租户门店表单 */
  tenant_store: TenantStoreForm | undefined;
}

/** 租户门店删除条件 */
export interface DeleteTenantStoreRequest {
  /** 门店ID列表，多个用逗号分隔 */
  ids: string;
}

/** 租户门店审核条件 */
export interface AuditTenantStoreRequest {
  /** 门店ID */
  id: number;
  /** 审核状态：枚举【TenantStoreStatus】 */
  status: TenantStoreStatus;
  /** 审核备注 */
  remark: string;
}

/** 租户门店 */
export interface TenantStore {
  /** 门店ID */
  id: number;
  /** 租户ID */
  tenant_id: number;
  /** 门店名称 */
  name: string;
  /** 门店LOGO */
  logo: string;
  /** 门店封面 */
  cover: string;
  /** 门店简介 */
  intro: string;
  /** 门店公告 */
  notice: string;
  /** 营业执照 */
  business_license: string[];
  /** 审核状态：枚举【TenantStoreStatus】 */
  status: TenantStoreStatus;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** Admin租户门店服务 */
export interface TenantStoreService {
  /** 查询租户门店下拉选项 */
  OptionTenantStore(request: OptionTenantStoreRequest): Promise<OptionTenantStoreResponse>;
  /** 查询租户门店列表 */
  PageTenantStore(request: PageTenantStoreRequest): Promise<PageTenantStoreResponse>;
  /** 查询租户门店树形选项 */
  TreeTenantStore(request: TreeTenantStoreRequest): Promise<TreeTenantStoreResponse>;
  /** 查询租户门店 */
  GetTenantStore(request: GetTenantStoreRequest): Promise<TenantStoreForm>;
  /** 创建租户门店 */
  CreateTenantStore(request: CreateTenantStoreRequest): Promise<Empty>;
  /** 更新租户门店 */
  UpdateTenantStore(request: UpdateTenantStoreRequest): Promise<Empty>;
  /** 删除租户门店 */
  DeleteTenantStore(request: DeleteTenantStoreRequest): Promise<Empty>;
  /** 审核租户门店 */
  AuditTenantStore(request: AuditTenantStoreRequest): Promise<Empty>;
}
