// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: file/base.proto

package base

import (
	"context"
	"shop/api/gen/go/base"
	"shop/pkg/errorsx"

	"shop/service/base/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// FileService 文件服务
type FileService struct {
	base.UnimplementedFileServiceServer
	fileCase *biz.FileCase
}

// NewFileService 创建文件服务
func NewFileService(
	fileCase *biz.FileCase,
) *FileService {
	var ss = FileService{
		fileCase: fileCase}
	return &ss
}

// MultiUploadFile 多个文件上传
func (s *FileService) MultiUploadFile(ctx context.Context, req *base.MultiUploadFileRequest) (*base.MultiUploadFileResponse, error) {
	res, err := s.fileCase.MultiUploadFile(req)
	if err != nil {
		log.Errorf("MultiUploadFile %v", err)
		return nil, errorsx.WrapInternal(err, "多个文件上传失败")
	}
	return res, nil
}

// UploadFile 单个文件上传
func (s *FileService) UploadFile(ctx context.Context, req *base.UploadFileInfo) (*base.FileInfo, error) {
	res, err := s.fileCase.UploadFile(req)
	if err != nil {
		log.Errorf("UploadFile %v", err)
		return nil, errorsx.WrapInternal(err, "单个文件上传失败")
	}
	return res, nil
}

// DownloadFile 下载文件
func (s *FileService) DownloadFile(ctx context.Context, req *base.DownloadFileRequest) (*wrapperspb.BytesValue, error) {
	res, err := s.fileCase.DownloadFile(req)
	if err != nil {
		log.Errorf("DownloadFile %v", err)
		return nil, errorsx.WrapInternal(err, "下载文件失败")
	}
	return res, nil
}
