// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: login/base.proto

package base

import (
	"context"
	"errors"
	"shop/api/gen/go/base"
	"shop/service/base/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// LoginService 登录公共服务
type LoginService struct {
	base.UnimplementedLoginServiceServer
	loginCase *biz.LoginCase
}

// NewLoginService 创建登录公共服务
func NewLoginService(
	loginCase *biz.LoginCase,
) *LoginService {
	var ss = LoginService{
		loginCase: loginCase,
	}

	return &ss
}

// Captcha 验证码
func (s *LoginService) Captcha(ctx context.Context, req *emptypb.Empty) (*base.CaptchaResponse, error) {
	res, err := s.loginCase.Captcha(ctx)
	if err != nil {
		log.Error("Captcha err:", err.Error())
		return nil, errors.New("获取验证码失败")
	}
	return res, nil
}

// Logout 登出
func (s *LoginService) Logout(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	err := s.loginCase.Logout(ctx)
	if err != nil {
		log.Error("Logout err:", err.Error())
		return nil, errors.New("退出登录失败")
	}
	return &emptypb.Empty{}, nil
}

// RefreshToken 刷新认证令牌
func (s *LoginService) RefreshToken(ctx context.Context, req *base.RefreshTokenRequest) (*base.RefreshTokenResponse, error) {
	res, err := s.loginCase.RefreshToken(ctx, req)
	if err != nil {
		log.Error("RefreshToken err:", err.Error())
		return nil, errors.New("刷新认证令牌失败")
	}
	return res, nil
}

// Login 登录
func (s *LoginService) Login(ctx context.Context, req *base.LoginRequest) (*base.LoginResponse, error) {
	res, err := s.loginCase.Login(ctx, req)
	if err != nil {
		log.Error("Login err:", err.Error())
		return nil, errors.New("登录失败")
	}
	return res, nil
}
