// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: base/v1/mcp.proto

package base

import (
	"context"
	"fmt"

	basev1 "shop/api/gen/go/base/v1"
	"shop/pkg/errorsx"
	"shop/service/base/biz"

	"github.com/go-kratos/kratos/v3/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// McpService Base MCP 服务。
type McpService struct {
	basev1.UnimplementedMcpServiceServer
	mcpCase *biz.McpCase
}

// NewMcpService 创建 Base MCP 服务。
func NewMcpService(
	mcpCase *biz.McpCase,
) *McpService {
	var ss = McpService{
		mcpCase: mcpCase,
	}
	return &ss
}

// HandleMcp 处理 MCP Streamable HTTP 请求。
func (s *McpService) HandleMcp(ctx context.Context, req *basev1.HandleMcpRequest) (*emptypb.Empty, error) {
	res, err := s.mcpCase.HandleMcp(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("HandleMcp %v", err))
		return nil, errorsx.WrapInternal(err, "处理MCP请求失败")
	}
	return res, nil
}
