// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: base/v1/ai_assistant.proto

/* eslint-disable */
import type { Terminal } from "../../common/v1/enum";
import type { Empty } from "../../google/protobuf/empty";
import type { Timestamp } from "../../google/protobuf/timestamp";

/** AI 助手会话列表查询条件 */
export interface ListAiAssistantSessionsRequest {
  /** 终端类型：枚举【Terminal】 */
  terminal: Terminal;
}

/** AI 助手会话列表响应 */
export interface ListAiAssistantSessionsResponse {
  /** 会话列表 */
  sessions: AiAssistantSession[];
}

/** AI 助手会话创建请求 */
export interface CreateAiAssistantSessionRequest {
  /** 会话标题 */
  title: string;
  /** 会话场景 */
  scene: string;
  /** 终端类型：枚举【Terminal】 */
  terminal: Terminal;
}

/** AI 助手会话更新请求 */
export interface UpdateAiAssistantSessionRequest {
  /** 会话ID */
  id: string;
  /** 会话标题 */
  title: string;
}

/** AI 助手会话删除请求 */
export interface DeleteAiAssistantSessionRequest {
  /** 会话ID */
  id: string;
}

/** AI 助手消息列表查询条件 */
export interface ListAiAssistantMessagesRequest {
  /** 会话ID */
  session_id: string;
}

/** AI 助手消息列表响应 */
export interface ListAiAssistantMessagesResponse {
  /** 消息列表 */
  messages: AiAssistantMessage[];
}

/** AI 助手消息发送请求 */
export interface SendAiAssistantMessageRequest {
  /** 会话ID */
  session_id: string;
  /** 消息内容 */
  content: string;
  /** 附件列表 */
  attachments: AiAssistantAttachment[];
  /** 前端本地消息ID，用于流式回复关联 */
  client_message_id: string;
}

/** AI 助手消息发送响应 */
export interface SendAiAssistantMessageResponse {
  /** 新增消息列表 */
  messages: AiAssistantMessage[];
  /** 最新会话信息 */
  session: AiAssistantSession | undefined;
}

/** AI 助手会话 */
export interface AiAssistantSession {
  /** 会话ID */
  id: string;
  /** 会话标题 */
  title: string;
  /** 会话场景 */
  scene: string;
  /** 会话摘要 */
  summary: string;
  /** 工具数量 */
  tool_count: number;
  /** 更新时间 */
  updated_at:
    | Timestamp
    | undefined;
  /** 终端类型：枚举【Terminal】 */
  terminal: Terminal;
}

/** AI 助手消息 */
export interface AiAssistantMessage {
  /** 消息ID */
  id: string;
  /** 消息角色 */
  role: string;
  /** 消息类型 */
  kind: string;
  /** 消息内容 */
  content: string;
  /** 附件列表 */
  attachments: AiAssistantAttachment[];
  /** 创建时间 */
  created_at:
    | Timestamp
    | undefined;
  /** 回复来源：llm/fallback */
  reply_source: string;
  /** 回复使用的模型名称 */
  model: string;
  /** 是否为降级回复 */
  fallback: boolean;
  /** 降级原因 */
  fallback_reason: string;
}

/** AI 助手附件 */
export interface AiAssistantAttachment {
  /** 附件ID */
  id: string;
  /** 附件名称 */
  name: string;
  /** 附件大小 */
  size: number;
  /** 附件地址 */
  url: string;
  /** 附件 MIME 类型 */
  mime_type: string;
}

/** Base AI 助手服务 */
export interface AiAssistantService {
  /** 查询 AI 助手会话列表 */
  ListAiAssistantSessions(request: ListAiAssistantSessionsRequest): Promise<ListAiAssistantSessionsResponse>;
  /** 创建 AI 助手会话 */
  CreateAiAssistantSession(request: CreateAiAssistantSessionRequest): Promise<AiAssistantSession>;
  /** 更新 AI 助手会话 */
  UpdateAiAssistantSession(request: UpdateAiAssistantSessionRequest): Promise<AiAssistantSession>;
  /** 删除 AI 助手会话 */
  DeleteAiAssistantSession(request: DeleteAiAssistantSessionRequest): Promise<Empty>;
  /** 查询 AI 助手消息列表 */
  ListAiAssistantMessages(request: ListAiAssistantMessagesRequest): Promise<ListAiAssistantMessagesResponse>;
  /** 发送 AI 助手消息 */
  SendAiAssistantMessage(request: SendAiAssistantMessageRequest): Promise<SendAiAssistantMessageResponse>;
}
