// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: base/v1/ai_image.proto

/* eslint-disable */

/** AI 图片生成请求 */
export interface GenerateAiImageRequest {
  /** 图片生成提示词 */
  prompt: string;
  /** 图片模型名称 */
  model: string;
  /** 图片尺寸 */
  size: string;
  /** 图片质量 */
  quality: string;
  /** 图片风格 */
  style: string;
  /** 背景模式 */
  background: string;
  /** 输出格式 */
  output_format: string;
  /** 响应格式 */
  response_format: string;
  /** 生成数量 */
  n: number;
  /** 是否保存生成图片到对象存储 */
  save_output: boolean;
  /** 是否先润色提示词再生成 */
  polish_prompt: boolean;
}

/** AI 图片提示词润色请求 */
export interface PolishAiImagePromptRequest {
  /** 原始图片提示词 */
  prompt: string;
  /** 图片使用场景 */
  scene: string;
}

/** AI 图片提示词润色响应 */
export interface PolishAiImagePromptResponse {
  /** 润色后的图片提示词 */
  prompt: string;
  /** 原始图片提示词 */
  original_prompt: string;
  /** 润色模型名称 */
  model: string;
}

/** AI 图片生成响应 */
export interface GenerateAiImageResponse {
  /** 图片列表 */
  images: AiImage[];
  /** 图片模型名称 */
  model: string;
  /** 图片生成提示词 */
  prompt: string;
  /** 模型生成时间戳 */
  created: number;
  /** 生成批次编号 */
  request_id: string;
  /** 原始图片提示词 */
  original_prompt: string;
}

/** AI 图片结果 */
export interface AiImage {
  /** 图片名称 */
  name: string;
  /** 图片地址 */
  url: string;
  /** 图片 MIME 类型 */
  mime_type: string;
  /** 图片字节大小 */
  size: number;
  /** 模型修订后的提示词 */
  revised_prompt: string;
  /** 是否已保存到对象存储 */
  saved: boolean;
  /** 对象存储目录 */
  storage_path: string;
  /** 生成批次编号 */
  request_id: string;
}

/** Base AI 图片服务 */
export interface AiImageService {
  /** 生成 AI 图片 */
  GenerateAiImage(request: GenerateAiImageRequest): Promise<GenerateAiImageResponse>;
  /** 润色 AI 图片提示词 */
  PolishAiImagePrompt(request: PolishAiImagePromptRequest): Promise<PolishAiImagePromptResponse>;
}
