// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: base/v1/login.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";

/** 验证码获取条件 */
export interface CaptchaRequest {
}

/** 登出请求条件 */
export interface LogoutRequest {
}

/** 验证码响应 */
export interface CaptchaResponse {
  /** 验证码ID。 */
  captcha_id: string;
  /** 验证码base64 */
  captcha_base64: string;
}

/** 刷新令牌请求参数 */
export interface RefreshTokenRequest {
  /** 更新令牌，用来获取下一次的访问令牌，必选项。 */
  refresh_token: string;
}

/** 刷新令牌响应 */
export interface RefreshTokenResponse {
  /** 访问令牌，必选项。 */
  access_token: string;
  /** 更新令牌，用来获取下一次的访问令牌，可选项。 */
  refresh_token: string;
  /** 令牌类型，该值大小写不敏感，必选项，可以是bearer类型或mac类型。 */
  token_type: string;
  /** 令牌有效时间，单位为秒。如果访问令牌过期，服务器应回复授予访问令牌的持续时间。如果省略该参数，必须其他方式设置过期时间。 */
  expires_in: number;
}

/** 登录请求参数 */
export interface LoginRequest {
  /** 用户名，必选项。 */
  user_name: string;
  /** 用户的密码，必选项。 */
  password: string;
  /** 验证码 */
  captcha_code: string;
  /** 验证码Id */
  captcha_id: string;
}

/** 登录响应 */
export interface LoginResponse {
  /** 访问令牌，必选项。 */
  access_token: string;
  /** 更新令牌，用来获取下一次的访问令牌，可选项。 */
  refresh_token: string;
  /** 令牌类型，该值大小写不敏感，必选项，可以是bearer类型或mac类型。 */
  token_type: string;
  /** 令牌有效时间，单位为秒。如果访问令牌过期，服务器应回复授予访问令牌的持续时间。如果省略该参数，必须其他方式设置过期时间。 */
  expires_in: number;
}

/** Base登录公共服务 */
export interface LoginService {
  /** 验证码 */
  Captcha(request: CaptchaRequest): Promise<CaptchaResponse>;
  /** 登出 */
  Logout(request: LogoutRequest): Promise<Empty>;
  /** 刷新认证令牌 */
  RefreshToken(request: RefreshTokenRequest): Promise<RefreshTokenResponse>;
  /** 登录 */
  Login(request: LoginRequest): Promise<LoginResponse>;
}
