// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/analytics.proto

/* eslint-disable */

/** 时间类型 */
export enum AnalyticsTimeType {
  /** WEEK - 周 */
  WEEK = 0,
  /** MONTH - 月 */
  MONTH = 1,
  /** YEAR - 年 */
  YEAR = 2,
}

/** 汇总数据请求参数 */
export interface AnalyticsCountRequest {
  /** 时间类型 */
  timeType: AnalyticsTimeType;
}

/** 汇总数据返回结果 */
export interface AnalyticsCountResponse {
  /** 新增数量 */
  newNum: number;
  /** 总数量 */
  totalNum: number;
}

/** 订单销量（柱状图）请求参数 */
export interface AnalyticsBarOrderRequest {
  /** 时间类型 */
  timeType: AnalyticsTimeType;
}

/** 订单销售额（柱状图）请求参数 */
export interface AnalyticsBarSaleRequest {
  /** 时间类型 */
  timeType: AnalyticsTimeType;
}

/** 商品分类（饼状图）请求参数 */
export interface AnalyticsPieGoodsRequest {
  /** 时间类型 */
  timeType: AnalyticsTimeType;
}

/** 商品订单销量状态（雷达图）请求参数 */
export interface AnalyticsPieOrderRequest {
  /** 时间类型 */
  timeType: AnalyticsTimeType;
}

/** （柱状图）请求参数 */
export interface AnalyticsBarResponse {
  /** 图例的数据数组 */
  axisData: string[];
  /** 数据内容数组 */
  seriesData: AnalyticsBarResponse_SeriesData[];
}

export interface AnalyticsBarResponse_SeriesData {
  /** 数量 */
  value: number[];
}

/** （饼状图）返回结果 */
export interface AnalyticsPieResponse {
  /** 数据内容数组 */
  seriesData: AnalyticsPieResponse_SeriesData[];
}

export interface AnalyticsPieResponse_SeriesData {
  /** 数值 */
  value: number;
  /** 系列名称 */
  name: string;
}

/** Admin数据分析服务 */
export interface AnalyticsService {
  /** 查询汇总数据（用户） */
  AnalyticsCountUser(request: AnalyticsCountRequest): Promise<AnalyticsCountResponse>;
  /** 查询汇总数据（商品） */
  AnalyticsCountGoods(request: AnalyticsCountRequest): Promise<AnalyticsCountResponse>;
  /** 查询汇总数据（订单） */
  AnalyticsCountOrder(request: AnalyticsCountRequest): Promise<AnalyticsCountResponse>;
  /** 查询汇总数据（销量） */
  AnalyticsCountSale(request: AnalyticsCountRequest): Promise<AnalyticsCountResponse>;
  /** 查询订单销量（柱状图） */
  AnalyticsBarOrder(request: AnalyticsBarOrderRequest): Promise<AnalyticsBarResponse>;
  /** 查询订单销售额（柱状图） */
  AnalyticsBarSale(request: AnalyticsBarSaleRequest): Promise<AnalyticsBarResponse>;
  /** 查询订单商品分类（饼状图） */
  AnalyticsPieGoods(request: AnalyticsPieGoodsRequest): Promise<AnalyticsPieResponse>;
  /** 查询订单状态（饼状图） */
  AnalyticsPieOrder(request: AnalyticsPieOrderRequest): Promise<AnalyticsPieResponse>;
}
