// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/auth.proto

/* eslint-disable */
import type { StringValues } from "../common/types";
import type { Empty } from "../google/protobuf/empty";

/** 用户信息表单 */
export interface UserInfoForm {
  /** 用户账号 */
  userName: string;
  /** 用户昵称 */
  nickName: string;
  /** 手机号 */
  phone: string;
  /** 头像 */
  avatar: string;
  /** 角色编号 */
  roleCode: string;
  /** 角色名称 */
  roleName: string;
  /** 部门名称 */
  deptName: string;
}

/** Route树响应 */
export interface TreeRouteResponse {
  /** 路由列表 */
  list: RouteItem[];
}

/** Route项 */
export interface RouteItem {
  /** 路由路径 */
  path?:
    | string
    | undefined;
  /** 重定向地址 */
  redirect?:
    | string
    | undefined;
  /** 路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。 */
  name?:
    | string
    | undefined;
  /** 指向的组件 */
  component?:
    | string
    | undefined;
  /** 路由元信息 */
  meta?:
    | RouteMeta
    | undefined;
  /** 子节点树 */
  children: RouteItem[];
}

/** Route元信息 */
export interface RouteMeta {
  /** 菜单标题 */
  title?:
    | string
    | undefined;
  /** 菜单图标 */
  icon?:
    | string
    | undefined;
  /** 【目录】只有一个子路由是否始终显示 */
  alwaysShow?:
    | boolean
    | undefined;
  /** 是否隐藏(true-是 false-否) */
  hidden?:
    | boolean
    | undefined;
  /** 【菜单】是否开启页面缓存 */
  keepAlive?:
    | boolean
    | undefined;
  /** 【菜单】是否全屏(示例：数据大屏页面) */
  full?:
    | boolean
    | undefined;
  /** 【菜单】是否固定在标签页中(首页通常是固定项) */
  affix?:
    | boolean
    | undefined;
  /** 参数 */
  params: RouteParams[];
}

/** Route参数 */
export interface RouteParams {
  /** key */
  key?:
    | string
    | undefined;
  /** value */
  value?: string | undefined;
}

/** 用户资料表单 */
export interface UserProfileForm {
  /** 用户名 */
  userName: string;
  /** 昵称 */
  nickName: string;
  /** 头像URL */
  avatar: string;
  /** 性别 */
  gender: number;
  /** 手机号 */
  phone: string;
  /** 角色名 */
  roleName: string;
  /** 部门名 */
  deptName: string;
  /** 创建时间 */
  createdAt: string;
}

/** 用户密码表单 */
export interface UserPasswordForm {
  /** 原密码 */
  oldPwd: string;
  /** 新密码 */
  newPwd: string;
  /** 确认密码 */
  confirmPwd: string;
}

/** 发送手机号验证码请求参数 */
export interface SendPhoneCodeRequest {
  /** 手机号 */
  phone: string;
}

/** 用户手机号表单 */
export interface UserPhoneForm {
  /** 手机号 */
  phone: string;
  /** 验证码 */
  code: string;
}

/** Admin用户登录认证服务 */
export interface AuthService {
  /** 获取已经登录的用户的数据 */
  GetUserInfo(request: Empty): Promise<UserInfoForm>;
  /** 获取已经登录的用户菜单 */
  GetUserMenu(request: Empty): Promise<TreeRouteResponse>;
  /** 获取已经登录的用户按钮 */
  GetUserButton(request: Empty): Promise<StringValues>;
  /** 获取个人中心用户信息 */
  GetUserProfile(request: Empty): Promise<UserProfileForm>;
  /** 修改个人中心用户信息 */
  UpdateUserProfile(request: UserProfileForm): Promise<Empty>;
  /** 发送手机号验证码 */
  SendPhoneCode(request: SendPhoneCodeRequest): Promise<Empty>;
  /** 修改个人中心手机号 */
  UpdateUserPhone(request: UserPhoneForm): Promise<Empty>;
  /** 修改个人中心密码 */
  UpdateUserPassword(request: UserPasswordForm): Promise<Empty>;
}
