// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/goods_analytics.proto

/* eslint-disable */
import type { AnalyticsPieResponse, AnalyticsTimeRequest, AnalyticsTrendResponse } from "../common/analytics";

export interface GoodsAnalyticsSummaryResponse {
  newGoodsCount: number;
  putOnGoodsRate: number;
  activeGoodsCount: number;
  activeGoodsRate: number;
  saleCount: number;
  saleGrowthRate: number;
}

/** Admin商品分析服务 */
export interface GoodsAnalyticsService {
  /** 查询商品摘要指标 */
  GetGoodsAnalyticsSummary(request: AnalyticsTimeRequest): Promise<GoodsAnalyticsSummaryResponse>;
  /** 查询商品趋势 */
  GetGoodsAnalyticsTrend(request: AnalyticsTimeRequest): Promise<AnalyticsTrendResponse>;
  /** 查询商品分类分布 */
  GetGoodsAnalyticsPie(request: AnalyticsTimeRequest): Promise<AnalyticsPieResponse>;
}
