// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/order_analytics.proto

/* eslint-disable */
import type { AnalyticsPieResponse, AnalyticsTimeRequest, AnalyticsTrendResponse } from "../common/analytics";

export interface OrderAnalyticsSummaryResponse {
  newOrderCount: number;
  newOrderGrowthRate: number;
  saleAmount: number;
  averageOrderAmount: number;
  orderUserCount: number;
  repurchaseRate: number;
}

/** Admin订单分析服务 */
export interface OrderAnalyticsService {
  /** 查询订单摘要指标 */
  GetOrderAnalyticsSummary(request: AnalyticsTimeRequest): Promise<OrderAnalyticsSummaryResponse>;
  /** 查询订单趋势 */
  GetOrderAnalyticsTrend(request: AnalyticsTimeRequest): Promise<AnalyticsTrendResponse>;
  /** 查询订单状态分布 */
  GetOrderAnalyticsPie(request: AnalyticsTimeRequest): Promise<AnalyticsPieResponse>;
}
