// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/order_report.proto

/* eslint-disable */

/** 订单月报汇总查询条件 */
export interface OrderMonthReportSummaryRequest {
  /** 开始月份，格式：YYYY-MM */
  startMonth: string;
  /** 结束月份，格式：YYYY-MM */
  endMonth: string;
  /** 支付方式：枚举【OrderPayType】，0 表示全部 */
  payType: number;
  /** 支付渠道：枚举【OrderPayChannel】，0 表示全部 */
  payChannel: number;
}

/** 订单月报名细查询条件 */
export interface OrderMonthReportListRequest {
  /** 开始月份，格式：YYYY-MM */
  startMonth: string;
  /** 结束月份，格式：YYYY-MM */
  endMonth: string;
  /** 支付方式：枚举【OrderPayType】，0 表示全部 */
  payType: number;
  /** 支付渠道：枚举【OrderPayChannel】，0 表示全部 */
  payChannel: number;
}

/** 订单月报汇总响应 */
export interface OrderMonthReportSummaryResponse {
  /** 支付成功订单数 */
  paidOrderCount: number;
  /** 支付成功金额，单位分 */
  paidOrderAmount: number;
  /** 退款成功订单数 */
  refundOrderCount: number;
  /** 退款成功金额，单位分 */
  refundOrderAmount: number;
  /** 净销售额，单位分 */
  netOrderAmount: number;
  /** 支付用户数 */
  paidUserCount: number;
  /** 商品件数 */
  goodsCount: number;
  /** 客单价，单位分 */
  customerUnitPrice: number;
}

/** 订单月报明细 */
export interface OrderMonthReportItem {
  /** 月份，格式：YYYY-MM */
  month: string;
  /** 支付成功订单数 */
  paidOrderCount: number;
  /** 支付成功金额，单位分 */
  paidOrderAmount: number;
  /** 退款成功订单数 */
  refundOrderCount: number;
  /** 退款成功金额，单位分 */
  refundOrderAmount: number;
  /** 净销售额，单位分 */
  netOrderAmount: number;
  /** 支付用户数 */
  paidUserCount: number;
  /** 商品件数 */
  goodsCount: number;
  /** 客单价，单位分 */
  customerUnitPrice: number;
}

/** 订单月报名细列表响应 */
export interface OrderMonthReportListResponse {
  /** 月报明细 */
  items: OrderMonthReportItem[];
}

/** Admin订单报表服务 */
export interface OrderReportService {
  /** 查询订单月报汇总 */
  OrderMonthReportSummary(request: OrderMonthReportSummaryRequest): Promise<OrderMonthReportSummaryResponse>;
  /** 查询订单月报明细 */
  OrderMonthReportList(request: OrderMonthReportListRequest): Promise<OrderMonthReportListResponse>;
}
