// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/recommend_request.proto

/* eslint-disable */
import type { GoodsStatus, RecommendEventType, RecommendScene } from "../common/enum";
import type { Int64Value } from "../google/protobuf/wrappers";

/** 推荐请求分页查询条件 */
export interface PageRecommendRequestRequest {
  /** 推荐请求ID */
  requestId?:
    | string
    | undefined;
  /** 主体类型：字典【recommend_actor_type】 */
  actorType?:
    | number
    | undefined;
  /** 主体编号（仅内部定位使用） */
  actorId?:
    | number
    | undefined;
  /** 推荐场景：字典【recommend_scene】 */
  scene?:
    | RecommendScene
    | undefined;
  /** 请求时间 */
  requestAt: string[];
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

/** 推荐请求分页响应 */
export interface PageRecommendRequestResponse {
  /** 分页数据 */
  list: RecommendRequest[];
  /** 总数 */
  total: number;
}

/** 推荐请求 */
export interface RecommendRequest {
  /** 主键ID */
  id: number;
  /** 推荐请求ID */
  requestId: string;
  /** 主体类型：字典【recommend_actor_type】 */
  actorType: number;
  /** 主体编号（仅内部定位使用） */
  actorId: number;
  /** 推荐场景：字典【recommend_scene】 */
  scene: RecommendScene;
  /** 页码 */
  pageNum: number;
  /** 分页大小 */
  pageSize: number;
  /** 本次返回总数 */
  total: number;
  /** 命中的推荐策略 */
  strategy: string;
  /** 最终命中的推荐器 */
  providerName: string;
  /** 请求时间 */
  requestAt: string;
  /** 主体信息 */
  actorInfo: string;
}

/** 推荐请求详情响应 */
export interface RecommendRequestDetailResponse {
  /** 请求基础信息 */
  request:
    | RecommendRequest
    | undefined;
  /** 推荐上下文信息 */
  context:
    | RecommendRequestContext
    | undefined;
  /** 当前请求页的推荐商品列表 */
  itemList: RecommendRequestItem[];
}

/** 推荐请求上下文信息 */
export interface RecommendRequestContext {
  /** 锚点商品ID */
  goodsId: number;
  /** 关联订单ID */
  orderId: number;
  /** 上下文商品ID列表 */
  contextGoodsIds: number[];
  /** 命中的推荐策略 */
  strategy: string;
  /** 上下文记录的推荐器 */
  providerName: string;
  /** 最终命中的推荐器 */
  finalProviderName: string;
  /** 推荐请求链路轨迹 */
  trace: RecommendRequestTrace[];
  /** 原始上下文JSON */
  rawJson: string;
}

/** 推荐请求链路轨迹 */
export interface RecommendRequestTrace {
  /** 推荐器名称 */
  providerName: string;
  /** 当前推荐器返回的商品数量 */
  resultCount: number;
  /** 当前推荐器是否命中 */
  hit: boolean;
  /** 当前推荐器错误信息 */
  errorMsg: string;
  /** 当前推荐器是否为最终命中的推荐器 */
  isFinal: boolean;
}

/** 推荐请求商品信息 */
export interface RecommendRequestItem {
  /** 商品ID */
  goodsId: number;
  /** 结果位置 */
  position: number;
  /** 商品名称 */
  goodsName: string;
  /** 商品图片 */
  picture: string;
  /** 当前价格（分） */
  price: number;
  /** 折扣价格（分） */
  discountPrice: number;
  /** 商品状态：枚举【GoodsStatus】 */
  goodsStatus: GoodsStatus;
  /** 关联事件条数 */
  eventCount: number;
}

/** 推荐请求事件查询条件 */
export interface GetRecommendRequestEventRequest {
  /** 推荐请求记录ID */
  requestRecordId: number;
  /** 商品ID */
  goodsId: number;
  /** 结果位置 */
  position: number;
}

/** 推荐请求事件响应 */
export interface GetRecommendRequestEventResponse {
  /** 事件数据 */
  list: RecommendEvent[];
  /** 总数 */
  total: number;
}

/** 推荐事件 */
export interface RecommendEvent {
  /** 主键ID */
  id: number;
  /** 主体类型：字典【recommend_actor_type】 */
  actorType: number;
  /** 主体编号（仅内部定位使用） */
  actorId: number;
  /** 推荐场景：字典【recommend_scene】 */
  scene: RecommendScene;
  /** 事件类型：枚举【RecommendEventType】 */
  eventType: RecommendEventType;
  /** 商品ID */
  goodsId: number;
  /** 商品数量 */
  goodsNum: number;
  /** 推荐请求ID */
  requestId: string;
  /** 结果位置 */
  position: number;
  /** 事件时间 */
  eventAt: string;
}

/** Admin推荐请求服务 */
export interface RecommendRequestService {
  /** 查询推荐请求分页列表 */
  PageRecommendRequest(request: PageRecommendRequestRequest): Promise<PageRecommendRequestResponse>;
  /** 查询推荐请求详情 */
  GetRecommendRequest(request: Int64Value): Promise<RecommendRequestDetailResponse>;
  /** 查询推荐请求商品关联事件 */
  GetRecommendRequestEvent(request: GetRecommendRequestEventRequest): Promise<GetRecommendRequestEventResponse>;
}
