// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/recommend_remote.proto

/* eslint-disable */
import type { Empty } from "../google/protobuf/empty";

/** 远程推荐游标查询条件 */
export interface RecommendRemoteCursorRequest {
  /** 游标 */
  cursor: string;
  /** 返回数量 */
  n: number;
  /** 编号关键字 */
  id: string;
}

/** 远程推荐编号查询条件 */
export interface RecommendRemoteIdRequest {
  /** 编号 */
  id: string;
}

/** 远程推荐名称查询条件 */
export interface RecommendRemoteNameRequest {
  /** 名称 */
  name: string;
}

/** 远程推荐数据查询条件 */
export interface RecommendRemoteDataRequest {
  /** 数据类型 */
  type: string;
  /** 游标 */
  cursor: string;
  /** 返回数量 */
  n: number;
}

/** 远程推荐导入内容 */
export interface RecommendRemoteImportRequest {
  /** 数据类型 */
  type: string;
  /** JSON内容 */
  json: string;
}

/** 远程推荐JSON请求 */
export interface RecommendRemoteJsonRequest {
  /** JSON内容 */
  json: string;
}

/** 远程推荐JSON响应 */
export interface RecommendRemoteJsonResponse {
  /** JSON内容 */
  json: string;
}

/** Admin远程推荐服务 */
export interface RecommendRemoteService {
  /** 查询远程推荐概览 */
  GetRecommendRemoteOverview(request: Empty): Promise<RecommendRemoteJsonResponse>;
  /** 查询远程推荐任务状态 */
  GetRecommendRemoteTasks(request: Empty): Promise<RecommendRemoteJsonResponse>;
  /** 查询远程推荐分类 */
  GetRecommendRemoteCategories(request: Empty): Promise<RecommendRemoteJsonResponse>;
  /** 查询远程推荐时间序列 */
  GetRecommendRemoteTimeseries(request: RecommendRemoteNameRequest): Promise<RecommendRemoteJsonResponse>;
  /** 查询远程推荐用户列表 */
  PageRecommendRemoteUsers(request: RecommendRemoteCursorRequest): Promise<RecommendRemoteJsonResponse>;
  /** 查询远程推荐用户 */
  GetRecommendRemoteUser(request: RecommendRemoteIdRequest): Promise<RecommendRemoteJsonResponse>;
  /** 删除远程推荐用户 */
  DeleteRecommendRemoteUser(request: RecommendRemoteIdRequest): Promise<Empty>;
  /** 查询远程推荐商品列表 */
  PageRecommendRemoteItems(request: RecommendRemoteCursorRequest): Promise<RecommendRemoteJsonResponse>;
  /** 查询远程推荐商品 */
  GetRecommendRemoteItem(request: RecommendRemoteIdRequest): Promise<RecommendRemoteJsonResponse>;
  /** 删除远程推荐商品 */
  DeleteRecommendRemoteItem(request: RecommendRemoteIdRequest): Promise<Empty>;
  /** 导出远程推荐数据 */
  ExportRecommendRemoteData(request: RecommendRemoteDataRequest): Promise<RecommendRemoteJsonResponse>;
  /** 导入远程推荐数据 */
  ImportRecommendRemoteData(request: RecommendRemoteImportRequest): Promise<Empty>;
  /** 查询推荐编排配置 */
  GetRecommendRemoteFlowConfig(request: Empty): Promise<RecommendRemoteJsonResponse>;
  /** 保存推荐编排配置 */
  SaveRecommendRemoteFlowConfig(request: RecommendRemoteJsonRequest): Promise<Empty>;
  /** 重置推荐编排配置 */
  ResetRecommendRemoteFlowConfig(request: Empty): Promise<Empty>;
  /** 查询推荐编排配置结构 */
  GetRecommendRemoteFlowSchema(request: Empty): Promise<RecommendRemoteJsonResponse>;
  /** 查询远程推荐配置 */
  GetRecommendRemoteConfig(request: Empty): Promise<RecommendRemoteJsonResponse>;
}
