// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/user_analytics.proto

/* eslint-disable */
import type { AnalyticsRankResponse, AnalyticsTimeRequest, AnalyticsTrendResponse } from "../common/analytics";

/** 用户分析汇总响应 */
export interface UserAnalyticsSummaryResponse {
  /** 新增用户数 */
  newUserCount: number;
  /** 新增用户增长率 */
  newUserGrowthRate: number;
  /** 下单用户数 */
  orderUserCount: number;
  /** 下单转化率 */
  orderUserConversionRate: number;
  /** 活跃用户数 */
  activeUserCount: number;
  /** 活跃覆盖率 */
  activeUserCoverageRate: number;
}

/** Admin用户分析服务 */
export interface UserAnalyticsService {
  /** 查询用户摘要指标 */
  GetUserAnalyticsSummary(request: AnalyticsTimeRequest): Promise<UserAnalyticsSummaryResponse>;
  /** 查询用户趋势 */
  GetUserAnalyticsTrend(request: AnalyticsTimeRequest): Promise<AnalyticsTrendResponse>;
  /** 查询用户行为覆盖排行 */
  GetUserAnalyticsRank(request: AnalyticsTimeRequest): Promise<AnalyticsRankResponse>;
}
