// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/workspace.proto

/* eslint-disable */

export interface WorkspaceMetricsRequest {
}

export interface WorkspaceMetricsResponse {
  todayOrderCount: number;
  todayOrderGrowthRate: number;
  todaySaleAmount: number;
  averageOrderAmount: number;
  payConversionRate: number;
  todayOrderUserCount: number;
  repurchaseRate: number;
  todayNewUserCount: number;
  todaySaleCount: number;
  activeGoodsCount: number;
  todayNewGoodsCount: number;
  todaySaleGrowthRate: number;
}

export interface WorkspaceTodoListRequest {
}

export interface WorkspaceTodoListResponse {
  pendingPayOrderCount: number;
  pendingShippedOrderCount: number;
  lowInventorySkuCount: number;
  pendingPutOnGoodsCount: number;
}

export interface WorkspaceRiskListRequest {
}

export interface WorkspaceRiskListResponse {
  abnormalPayBillCount: number;
  zeroInventoryPutOnSkuCount: number;
  abnormalPriceSkuCount: number;
  pendingOperationCount: number;
}

/** Admin工作台服务 */
export interface WorkspaceService {
  /** 查询工作台顶部指标 */
  GetWorkspaceMetrics(request: WorkspaceMetricsRequest): Promise<WorkspaceMetricsResponse>;
  /** 查询工作台待处理事项 */
  GetWorkspaceTodoList(request: WorkspaceTodoListRequest): Promise<WorkspaceTodoListResponse>;
  /** 查询工作台风险提醒 */
  GetWorkspaceRiskList(request: WorkspaceRiskListRequest): Promise<WorkspaceRiskListResponse>;
}
