// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: app/v1/comment.proto

/* eslint-disable */
import type { CommentAiContentItem } from "../../common/v1/common";
import type {
  CommentFilterType,
  CommentReactionTargetType,
  CommentReactionType,
  CommentSortType,
  CommentStatus,
} from "../../common/v1/enum";
import type { Empty } from "../../google/protobuf/empty";

/** 删除商品评价条件 */
export interface DeleteCommentRequest {
  /** 评价ID */
  id: number;
}

/** 文本片段 */
export interface CommentTextSegment {
  /** 文本内容 */
  text: string;
  /** 是否高亮 */
  highlight: boolean;
}

/** 评价用户展示信息 */
export interface CommentUserView {
  /** 展示昵称，匿名时返回匿名用户 */
  user_name: string;
  /** 展示头像，匿名时返回默认头像 */
  avatar: string;
  /** 用户展示标签，匿名时为空 */
  user_tag_text: string;
  /** 是否匿名展示 */
  anonymous: boolean;
}

/** 评价筛选项 */
export interface CommentFilterItem {
  /** 筛选类型 */
  filter_type: CommentFilterType;
  /** 内容标签ID，系统筛选项固定为0 */
  tag_id: number;
  /** 展示名称 */
  label: string;
  /** 展示值，可为空 */
  value: string;
}

/** 评价展示项 */
export interface CommentItem {
  /** 评价ID */
  id: number;
  /** 商品ID */
  goods_id: number;
  /** 商品名称快照 */
  goods_name: string;
  /** 商品主图快照 */
  goods_picture: string;
  /** SKU编码 */
  sku_code: string;
  /** 规格展示文案 */
  sku_desc: string;
  /** 评价用户展示信息 */
  user:
    | CommentUserView
    | undefined;
  /** 前端展示日期 */
  date_text: string;
  /** 评价正文片段 */
  content_segments: CommentTextSegment[];
  /** 评价图片数组 */
  img: string[];
  /** 图片数量 */
  image_count: number;
  /** 讨论数 */
  discussion_count: number;
  /** 仅本人列表展示是否已匿名 */
  anonymous_for_owner: boolean;
  /** 商品评分 */
  goods_score: number;
  /** 评价审核状态：枚举【CommentStatus】 */
  status: CommentStatus;
  /** 点赞数 */
  like_count: number;
  /** 点踩数 */
  dislike_count: number;
  /** 当前用户互动类型：枚举【CommentReactionType】 */
  reaction_type: CommentReactionType;
}

/** AI摘要 */
export interface CommentAi {
  /** AI摘要ID */
  id: number;
  /** AI摘要内容列表 */
  content: CommentAiContentItem[];
  /** 点赞数 */
  like_count: number;
  /** 点踩数 */
  dislike_count: number;
  /** 当前用户互动类型：枚举【CommentReactionType】 */
  reaction_type: CommentReactionType;
}

/** 评价讨论展示项 */
export interface CommentDiscussionItem {
  /** 讨论ID */
  id: number;
  /** 评价ID */
  comment_id: number;
  /** 讨论用户展示信息 */
  user:
    | CommentUserView
    | undefined;
  /** 讨论内容 */
  content: string;
  /** 被回复人的展示名称 */
  reply_to_display_name: string;
  /** 前端展示日期 */
  date_text: string;
  /** 点赞数 */
  like_count: number;
  /** 当前用户互动类型：枚举【CommentReactionType】 */
  reaction_type: CommentReactionType;
}

/** 待评价商品展示项 */
export interface PendingCommentGoodsItem {
  /** 订单ID */
  order_id: number;
  /** 商品ID */
  goods_id: number;
  /** 商品名称 */
  goods_name: string;
  /** 商品主图 */
  goods_picture: string;
  /** SKU编码 */
  sku_code: string;
  /** 规格展示文案 */
  sku_desc: string;
  /** 待评价卡片提示文案 */
  desc: string;
}

/** 商品评价摘要查询条件 */
export interface GoodsCommentOverviewRequest {
  /** 商品ID */
  goods_id: number;
  /** 评价预览数量 */
  preview_limit: number;
}

/** 商品评价摘要响应 */
export interface GoodsCommentOverviewResponse {
  /** 评价总数 */
  total_count: number;
  /** 好评率统计天数 */
  recent_days: number;
  /** 近N天好评率百分比整数 */
  recent_good_rate: number;
  /** 商品详情AI摘要 */
  ai_summary:
    | CommentAi
    | undefined;
  /** 高频标签列表 */
  comment_filters: CommentFilterItem[];
  /** 评价预览列表 */
  preview_comments: CommentItem[];
}

/** 商品评价分页查询条件 */
export interface PageGoodsCommentRequest {
  /** 商品ID */
  goods_id: number;
  /** SKU编码，仅当前商品筛选时使用 */
  sku_code: string;
  /** 筛选类型 */
  filter_type: CommentFilterType;
  /** 内容标签ID，筛选标签时使用 */
  tag_id: number;
  /** 是否只看当前SKU商品 */
  current_goods_only: boolean;
  /** 排序类型 */
  sort_type: CommentSortType;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 商品评价分页响应 */
export interface PageGoodsCommentResponse {
  /** 顶部筛选项列表 */
  comment_filters: CommentFilterItem[];
  /** 评价列表AI摘要 */
  ai_summary:
    | CommentAi
    | undefined;
  /** 评价分页数据 */
  comments: CommentItem[];
  /** 总数 */
  total: number;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
  /** 是否还有下一页 */
  has_more: boolean;
}

/** 评价讨论分页查询条件 */
export interface PageCommentDiscussionRequest {
  /** 评价ID */
  comment_id: number;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 评价讨论分页响应 */
export interface PageCommentDiscussionResponse {
  /** 评价ID */
  comment_id: number;
  /** 讨论分页数据 */
  comment_discussions: CommentDiscussionItem[];
  /** 总数 */
  total: number;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
  /** 是否还有下一页 */
  has_more: boolean;
}

/** 发布评价讨论请求参数 */
export interface CreateCommentDiscussionRequest {
  /** 所属评价ID */
  comment_id: number;
  /** 讨论内容 */
  content: string;
  /** 父级讨论ID，可为空 */
  parent_id: number;
  /** 被回复讨论ID，可为空 */
  reply_to_discussion_id: number;
  /** 是否匿名讨论 */
  is_anonymous: boolean;
}

/** 发布评价讨论响应 */
export interface CreateCommentDiscussionResponse {
  /** 新创建的讨论 */
  item:
    | CommentDiscussionItem
    | undefined;
  /** 发布后的讨论总数 */
  discussion_count: number;
}

/** 保存评价互动状态请求参数 */
export interface SaveCommentReactionRequest {
  /** 互动目标类型：枚举【CommentReactionTargetType】 */
  target_type: CommentReactionTargetType;
  /** 互动目标ID */
  target_id: number;
  /** 互动类型：枚举【CommentReactionType】 */
  reaction_type: CommentReactionType;
  /** 是否设置当前互动状态 */
  active: boolean;
}

/** 保存评价互动状态响应 */
export interface SaveCommentReactionResponse {
  /** 互动目标类型：枚举【CommentReactionTargetType】 */
  target_type: CommentReactionTargetType;
  /** 互动目标ID */
  target_id: number;
  /** 当前用户互动类型：枚举【CommentReactionType】 */
  reaction_type: CommentReactionType;
  /** 点赞数 */
  like_count: number;
  /** 点踩数 */
  dislike_count: number;
}

/** 待评价商品分页查询条件 */
export interface PagePendingCommentGoodsRequest {
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 待评价商品分页响应 */
export interface PagePendingCommentGoodsResponse {
  /** 待评价商品列表 */
  pending_comment_goods: PendingCommentGoodsItem[];
  /** 总数 */
  total: number;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
  /** 是否还有下一页 */
  has_more: boolean;
}

/** 发布商品评价请求参数 */
export interface CreateCommentRequest {
  /** 订单ID */
  order_id: number;
  /** 商品ID */
  goods_id: number;
  /** SKU编码 */
  sku_code: string;
  /** 评价正文 */
  content: string;
  /** 评价图片数组 */
  img: string[];
  /** 是否匿名展示 */
  is_anonymous: boolean;
  /** 商品评价评分，范围1到5 */
  goods_score: number;
  /** 包装评价评分，范围1到5 */
  package_score: number;
  /** 送货评价评分，范围1到5 */
  delivery_score: number;
}

/** 发布商品评价响应 */
export interface CreateCommentResponse {
  /** 新建评价ID */
  comment_id: number;
  /** 订单ID */
  order_id: number;
  /** 订单是否已因全部评价完成而流转为已完成 */
  order_completed: boolean;
}

/** 我的评价分页查询条件 */
export interface PageMyCommentRequest {
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** 我的评价分页响应 */
export interface PageMyCommentResponse {
  /** 我的评价列表 */
  comments: CommentItem[];
  /** 总数 */
  total: number;
  /** 当前页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
  /** 是否还有下一页 */
  has_more: boolean;
}

/** App评价服务 */
export interface CommentService {
  /** 查询商品评价摘要 */
  GoodsCommentOverview(request: GoodsCommentOverviewRequest): Promise<GoodsCommentOverviewResponse>;
  /** 查询商品评价分页列表 */
  PageGoodsComment(request: PageGoodsCommentRequest): Promise<PageGoodsCommentResponse>;
  /** 查询评价讨论分页列表 */
  PageCommentDiscussion(request: PageCommentDiscussionRequest): Promise<PageCommentDiscussionResponse>;
  /** 发布评价讨论 */
  CreateCommentDiscussion(request: CreateCommentDiscussionRequest): Promise<CreateCommentDiscussionResponse>;
  /** 保存评价互动状态 */
  SaveCommentReaction(request: SaveCommentReactionRequest): Promise<SaveCommentReactionResponse>;
  /** 查询待评价商品分页列表 */
  PagePendingCommentGoods(request: PagePendingCommentGoodsRequest): Promise<PagePendingCommentGoodsResponse>;
  /** 发布商品评价 */
  CreateComment(request: CreateCommentRequest): Promise<CreateCommentResponse>;
  /** 删除商品评价 */
  DeleteComment(request: DeleteCommentRequest): Promise<Empty>;
  /** 查询我的评价分页列表 */
  PageMyComment(request: PageMyCommentRequest): Promise<PageMyCommentResponse>;
}
