// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: app/v1/order_info.proto

/* eslint-disable */
import type {
  OrderCancelReason,
  OrderDeliveryTime,
  OrderInfoStatus,
  OrderPayChannel,
  OrderPayType,
  OrderRefundReason,
  OrderRefundStatus,
  OrderTradeStatus,
} from "../../common/v1/enum";
import type { Empty } from "../../google/protobuf/empty";
import type { RecommendContext } from "./recommend";
import type { TenantStore } from "./tenant_store";

/** 确认订单查询条件 */
export interface ConfirmOrderInfoRequest {
}

/** 订单数量汇总查询条件 */
export interface CountOrderInfoRequest {
}

/** 订单编号查询订单ID条件 */
export interface GetOrderInfoIdByOrderNoRequest {
  /** 订单编号 */
  order_no: string;
}

/** 订单编号查询订单ID响应 */
export interface GetOrderInfoIdByOrderNoResponse {
  /** 订单ID */
  order_id: number;
}

/** 订单详情查询条件 */
export interface GetOrderInfoByIdRequest {
  /** 订单ID */
  id: number;
}

/** 交易单详情查询条件 */
export interface GetOrderTradeByIdRequest {
  /** 交易单ID */
  trade_id: number;
}

/** 删除订单条件 */
export interface DeleteOrderInfoRequest {
  /** 订单ID */
  id: number;
}

/** 删除交易单条件 */
export interface DeleteOrderTradeRequest {
  /** 交易单ID */
  trade_id: number;
}

/** 立即购买订单请求参数 */
export interface BuyNowOrderInfoRequest {
  /** 商品id */
  goods_id: number;
  /** 规格编号 */
  sku_code: string;
  /** 数量 */
  num: number;
  /** 推荐上下文 */
  recommend_context: RecommendContext | undefined;
}

/** 下单商品 */
export interface CreateOrderInfoGoods {
  /** 商品id */
  goods_id: number;
  /** 规格编号 */
  sku_code: string;
  /** 数量 */
  num: number;
  /** 推荐上下文 */
  recommend_context: RecommendContext | undefined;
}

/** 确认订单响应 */
export interface ConfirmOrderInfoResponse {
  /** 按门店分组的商品信息 */
  order_goods_stores: OrderGoodsStore[];
  /** 汇总信息 */
  summary:
    | OrderSummary
    | undefined;
  /** 是否清空购物车 */
  clear_cart: boolean;
}

/** 立即购买订单响应 */
export interface BuyNowOrderInfoResponse {
  /** 按门店分组的商品信息 */
  order_goods_stores: OrderGoodsStore[];
  /** 汇总信息 */
  summary:
    | OrderSummary
    | undefined;
  /** 是否清空购物车 */
  clear_cart: boolean;
}

/** 再次购买订单请求参数 */
export interface RepurchaseOrderInfoRequest {
  /** 订单id */
  order_id: number;
}

/** 再次购买订单响应 */
export interface RepurchaseOrderInfoResponse {
  /** 按门店分组的商品信息 */
  order_goods_stores: OrderGoodsStore[];
  /** 汇总信息 */
  summary:
    | OrderSummary
    | undefined;
  /** 是否清空购物车 */
  clear_cart: boolean;
}

/** 订单数量汇总响应 */
export interface CountOrderInfoResponse {
  /** 总数 */
  counts: CountOrderInfoResponse_Count[];
}

/** 订单数量统计项 */
export interface CountOrderInfoResponse_Count {
  /** 订单履约状态 */
  status: OrderInfoStatus;
  /** 订单数量 */
  num: number;
  /** 交易支付状态 */
  trade_status: OrderTradeStatus;
  /** 订单退款状态 */
  refund_status: OrderRefundStatus;
  /** 是否为可申请售后订单统计 */
  refundable: boolean;
}

/** 订单分页查询条件 */
export interface PageOrderInfoRequest {
  /** 订单履约状态 */
  status?:
    | OrderInfoStatus
    | undefined;
  /** 交易支付状态 */
  trade_status?:
    | OrderTradeStatus
    | undefined;
  /** 订单退款状态 */
  refund_status?:
    | OrderRefundStatus
    | undefined;
  /** 是否存在退款 */
  has_refund?:
    | boolean
    | undefined;
  /** 是否仅查询可申请退款订单 */
  refundable?:
    | boolean
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 订单分页响应 */
export interface PageOrderInfoResponse {
  /** 分页数据 */
  order_infos: OrderInfo[];
  /** 总数 */
  total: number;
}

/** 订单详情响应 */
export interface OrderInfoResponse {
  /** 订单信息 */
  order:
    | OrderInfo
    | undefined;
  /** 地址信息 */
  address:
    | OrderInfoResponse_Address
    | undefined;
  /** 物流信息 */
  logistics:
    | OrderInfoResponse_Logistics
    | undefined;
  /** 支付倒计时 */
  countdown: number;
  /** 关联门店订单 */
  related_orders: OrderInfoResponse_RelatedOrder[];
}

/** 收货地址 */
export interface OrderInfoResponse_Address {
  /** 联系人 */
  receiver: string;
  /** 联系方式 */
  contact: string;
  /** 省市区全部 */
  address: string[];
  /** 详细地址 */
  detail: string;
}

/** 物流信息 */
export interface OrderInfoResponse_Logistics {
  /** 物流公司名 */
  name: string;
  /** 单号 */
  no: string;
  /** 联系方式 */
  contact: string;
  /** 物流详情 */
  detail: OrderInfoResponse_Logistics_Detail[];
}

/** Detail */
export interface OrderInfoResponse_Logistics_Detail {
  /** 时间 */
  time: string;
  /** 动态 */
  text: string;
}

/** 关联订单 */
export interface OrderInfoResponse_RelatedOrder {
  /** 订单ID */
  order_id: number;
  /** 订单编号 */
  order_no: string;
}

/** 创建订单请求参数 */
export interface CreateOrderInfoRequest {
  /** 地址id */
  address_id: number;
  /** 是否清空购物车 */
  clear_cart: boolean;
  /** 支付方式：枚举【OrderPayType】 */
  pay_type: OrderPayType;
  /** 支付渠道：枚举【OrderPayChannel】 */
  pay_channel: OrderPayChannel;
  /** 门店订单选项 */
  order_store_options: OrderStoreOption[];
  /** 商品信息 */
  goods: CreateOrderInfoGoods[];
}

/** 创建订单响应 */
export interface CreateOrderInfoResponse {
  /** 交易单ID */
  trade_id: number;
  /** 交易单编号 */
  trade_no: string;
  /** 门店订单ID */
  order_ids: number[];
}

/** 取消订单请求参数 */
export interface CancelOrderInfoRequest {
  /** 交易单ID */
  trade_id: number;
  /** 取消原因 */
  reason: OrderCancelReason;
}

/** 门店订单选项 */
export interface OrderStoreOption {
  /** 租户门店ID */
  tenant_store_id: number;
  /** 配送时间：枚举【OrderDeliveryTime】 */
  delivery_time: OrderDeliveryTime;
  /** 订单备注 */
  remark: string;
}

/** 订单退款请求参数 */
export interface RefundOrderInfoRequest {
  /** 订单id */
  order_id: number;
  /** 退款原因 */
  reason: OrderRefundReason;
}

/** 确认收货请求参数 */
export interface ReceiveOrderInfoRequest {
  /** 订单id */
  order_id: number;
}

/** 订单商品 */
export interface OrderGoods {
  /** 商品ID */
  goods_id: number;
  /** 规格编号 */
  sku_code: string;
  /** 规格描述 */
  spec_item: string[];
  /** 商品图片 */
  picture: string;
  /** 名称 */
  name: string;
  /** 数量 */
  num: number;
  /** 价格 */
  price: number;
  /** 支付价格 */
  pay_price: number;
  /** 当前金额汇总 */
  total_price: number;
  /** 支付金额汇总 */
  total_pay_price: number;
  /** 推荐上下文 */
  recommend_context: RecommendContext | undefined;
}

/** 订单商品门店分组 */
export interface OrderGoodsStore {
  /** 店铺信息 */
  store:
    | TenantStore
    | undefined;
  /** 商品信息 */
  goods: OrderGoods[];
  /** 门店订单汇总 */
  summary:
    | OrderSummary
    | undefined;
  /** 配送时间：枚举【OrderDeliveryTime】 */
  delivery_time: OrderDeliveryTime;
  /** 订单备注 */
  remark: string;
  /** 门店订单ID */
  order_id: number;
  /** 门店订单编号 */
  order_no: string;
}

/** Order信息 */
export interface OrderInfo {
  /** 订单id */
  id: number;
  /** 交易单ID */
  trade_id: number;
  /** 订单编号 */
  order_no: string;
  /** 实际支付金额 */
  pay_money: number;
  /** 总价 */
  total_money: number;
  /** 优惠金额 */
  post_fee: number;
  /** 商品总数 */
  goods_num: number;
  /** 配送时间：枚举【OrderDeliveryTime】 */
  delivery_time: OrderDeliveryTime;
  /** 订单履约状态：枚举【OrderInfoStatus】 */
  status: OrderInfoStatus;
  /** 订单退款状态：枚举【OrderRefundStatus】 */
  refund_status: OrderRefundStatus;
  /** 订单备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 支付方式：枚举【OrderPayType】 */
  pay_type: OrderPayType;
  /** 支付渠道：枚举【OrderPayChannel】 */
  pay_channel: OrderPayChannel;
  /** 交易单编号 */
  trade_no: string;
  /** 交易支付状态：枚举【OrderTradeStatus】 */
  trade_status: OrderTradeStatus;
  /** 是否为交易聚合记录 */
  is_trade: boolean;
  /** 支付时间 */
  payment_time: string;
  /** 取消时间 */
  cancel_time: string;
  /** 退款时间 */
  refund_time: string;
  /** 按门店分组的商品信息 */
  order_goods_stores: OrderGoodsStore[];
}

/** Order汇总 */
export interface OrderSummary {
  /** 实际支付金额 */
  pay_money: number;
  /** 总价 */
  total_money: number;
  /** 优惠金额 */
  post_fee: number;
  /** 商品总数 */
  goods_num: number;
}

/** App订单信息服务 */
export interface OrderInfoService {
  /** 确认订单信息 */
  ConfirmOrderInfo(request: ConfirmOrderInfoRequest): Promise<ConfirmOrderInfoResponse>;
  /** 立即购买订单信息 */
  BuyNowOrderInfo(request: BuyNowOrderInfoRequest): Promise<BuyNowOrderInfoResponse>;
  /** 再次购买订单信息 */
  RepurchaseOrderInfo(request: RepurchaseOrderInfoRequest): Promise<RepurchaseOrderInfoResponse>;
  /** 查询订单信息数量汇总 */
  CountOrderInfo(request: CountOrderInfoRequest): Promise<CountOrderInfoResponse>;
  /** 查询订单信息分页列表 */
  PageOrderInfo(request: PageOrderInfoRequest): Promise<PageOrderInfoResponse>;
  /** 根据订单信息编号查询订单信息id */
  GetOrderInfoIdByOrderNo(request: GetOrderInfoIdByOrderNoRequest): Promise<GetOrderInfoIdByOrderNoResponse>;
  /** 根据订单信息id查询订单信息 */
  GetOrderInfoById(request: GetOrderInfoByIdRequest): Promise<OrderInfoResponse>;
  /** 根据交易单ID查询聚合订单详情 */
  GetOrderTradeById(request: GetOrderTradeByIdRequest): Promise<OrderInfoResponse>;
  /** 创建订单信息 */
  CreateOrderInfo(request: CreateOrderInfoRequest): Promise<CreateOrderInfoResponse>;
  /** 删除订单信息 */
  DeleteOrderInfo(request: DeleteOrderInfoRequest): Promise<Empty>;
  /** 删除交易单 */
  DeleteOrderTrade(request: DeleteOrderTradeRequest): Promise<Empty>;
  /** 取消订单信息 */
  CancelOrderInfo(request: CancelOrderInfoRequest): Promise<Empty>;
  /** 订单信息退款 */
  RefundOrderInfo(request: RefundOrderInfoRequest): Promise<Empty>;
  /** 确认收货 */
  ReceiveOrderInfo(request: ReceiveOrderInfoRequest): Promise<Empty>;
}
