// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: app/v1/shop_banner.proto

/* eslint-disable */
import type { ShopBannerSite, ShopBannerType } from "../../common/v1/enum";

/** 轮播图列表查询条件 */
export interface ListShopBannersRequest {
  /** 位置：枚举【ShopBannerSite】 */
  site: ShopBannerSite;
}

/** 轮播图列表响应 */
export interface ListShopBannersResponse {
  /** 商城轮播图列表 */
  shop_banners: ShopBanner[];
}

/** 轮播图 */
export interface ShopBanner {
  /** 主键ID */
  id: number;
  /** 位置：枚举【ShopBannerSite】 */
  site: ShopBannerSite;
  /** 图片链接 */
  picture: string;
  /** 跳转类型：枚举【ShopBannerType】 */
  type: ShopBannerType;
  /** 跳转地址 */
  href: string;
}

/** App商城轮播图服务 */
export interface ShopBannerService {
  /** 查询商城轮播图列表 */
  ListShopBanners(request: ListShopBannersRequest): Promise<ListShopBannersResponse>;
}
