// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: app/v1/user_store.proto

/* eslint-disable */
import type { UserStoreStatus } from "../../common/v1/enum";
import type { Empty } from "../../google/protobuf/empty";

/** 查询用户门店请求参数 */
export interface GetUserStoreRequest {
}

/** 创建用户门店请求参数 */
export interface CreateUserStoreRequest {
  /** 用户门店 */
  user_store: UserStoreForm | undefined;
}

/** 更新用户门店请求参数 */
export interface UpdateUserStoreRequest {
  /** 用户门店ID */
  id: number;
  /** 用户门店 */
  user_store: UserStoreForm | undefined;
}

/** 用户门店 */
export interface UserStore {
  /** 用户门店ID */
  id: number;
  /** 门店名称 */
  name: string;
  /** 省市区 */
  address: string[];
  /** 详细地址 */
  detail: string;
  /** 门店照片 */
  picture: string[];
  /** 营业执照 */
  business_license: string[];
  /** 省市区 */
  address_name: string[];
  /** 状态 */
  status: UserStoreStatus;
  /** 备注名 */
  remark: string;
}

/** 用户门店表单 */
export interface UserStoreForm {
  /** 用户门店ID */
  id: number;
  /** 门店名称 */
  name: string;
  /** 省市区 */
  address: string[];
  /** 详细地址 */
  detail: string;
  /** 门店照片 */
  picture: string[];
  /** 营业执照 */
  business_license: string[];
  /** 省市区 */
  address_name: string[];
}

/** App用户门店管理服务 */
export interface UserStoreService {
  /** 查询用户门店 */
  GetUserStore(request: GetUserStoreRequest): Promise<UserStore>;
  /** 创建用户门店 */
  CreateUserStore(request: CreateUserStoreRequest): Promise<Empty>;
  /** 更新用户门店 */
  UpdateUserStore(request: UpdateUserStoreRequest): Promise<Empty>;
}
