// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: app/v1/user_address.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";

/** 用户地址列表查询条件 */
export interface ListUserAddressesRequest {
}

/** 查询用户地址请求参数 */
export interface GetUserAddressRequest {
  /** 用户地址ID */
  id: number;
}

/** 创建用户地址请求参数 */
export interface CreateUserAddressRequest {
  /** 用户地址 */
  user_address: UserAddressForm | undefined;
}

/** 更新用户地址请求参数 */
export interface UpdateUserAddressRequest {
  /** 用户地址ID */
  id: number;
  /** 用户地址 */
  user_address: UserAddressForm | undefined;
}

/** 删除用户地址请求参数 */
export interface DeleteUserAddressRequest {
  /** 用户地址ID */
  id: number;
}

/** 用户地址列表响应 */
export interface ListUserAddressesResponse {
  /** 用户地址列表 */
  user_addresses: UserAddress[];
}

/** 用户地址 */
export interface UserAddress {
  /** 用户地址ID */
  id: number;
  /** 联系人 */
  receiver: string;
  /** 联系方式 */
  contact: string;
  /** 省市区名称 */
  address: string[];
  /** 详细地址 */
  detail: string;
  /** 是否默认 */
  is_default: boolean;
}

/** 用户地址表单 */
export interface UserAddressForm {
  /** 用户地址ID */
  id: number;
  /** 联系人 */
  receiver: string;
  /** 联系方式 */
  contact: string;
  /** 省市区 */
  address: string[];
  /** 详细地址 */
  detail: string;
  /** 省市区 */
  address_name: string[];
  /** 是否默认 */
  is_default: boolean;
}

/** App用户地址管理服务 */
export interface UserAddressService {
  /** 查询用户地址列表 */
  ListUserAddresses(request: ListUserAddressesRequest): Promise<ListUserAddressesResponse>;
  /** 查询用户地址 */
  GetUserAddress(request: GetUserAddressRequest): Promise<UserAddressForm>;
  /** 创建用户地址 */
  CreateUserAddress(request: CreateUserAddressRequest): Promise<Empty>;
  /** 更新用户地址 */
  UpdateUserAddress(request: UpdateUserAddressRequest): Promise<Empty>;
  /** 删除用户地址 */
  DeleteUserAddress(request: DeleteUserAddressRequest): Promise<Empty>;
}
