// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: app/v1/user_cart.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";
import type { RecommendContext } from "./recommend";

/** 用户购物车数量查询条件 */
export interface CountUserCartRequest {
}

/** 用户购物车数量响应 */
export interface CountUserCartResponse {
  /** 购物车数量 */
  count: number;
}

/** 用户购物车列表查询条件 */
export interface ListUserCartsRequest {
}

/** 用户购物车列表响应 */
export interface ListUserCartsResponse {
  /** 用户购物车列表 */
  user_carts: UserCart[];
}

/** 用户购物车 */
export interface UserCart {
  /** 用户购物车ID */
  id: number;
  /** 商品ID */
  goods_id: number;
  /** 规格编号 */
  sku_code: string;
  /** 商品图片 */
  picture: string;
  /** 名称 */
  name: string;
  /** 数量 */
  num: number;
  /** 规格描述 */
  spec_item: string[];
  /** 库存数量 */
  inventory: number;
  /** 价格 */
  price: number;
  /** 加入时价格 */
  join_price: number;
  /** 是否选中 */
  is_checked: boolean;
  /** 推荐上下文 */
  recommend_context: RecommendContext | undefined;
}

/** 创建购物车请求参数 */
export interface CreateUserCartRequest {
  /** 商品ID */
  goods_id: number;
  /** 规格编号 */
  sku_code: string;
  /** 数量 */
  num: number;
  /** 推荐上下文 */
  recommend_context: RecommendContext | undefined;
}

/** 用户购物车表单 */
export interface UserCartForm {
  /** 购物车ID */
  id: number;
  /** 数量 */
  num: number;
}

/** 更新用户购物车请求参数 */
export interface UpdateUserCartRequest {
  /** 购物车ID */
  id: number;
  /** 用户购物车 */
  user_cart: UserCartForm | undefined;
}

/** 删除用户购物车请求参数 */
export interface DeleteUserCartRequest {
  /** 购物车ID */
  id: number;
}

/** 设置用户购物车选中状态请求参数 */
export interface SetUserCartStatusRequest {
  /** 购物车ID */
  id: number;
  /** 是否选中 */
  is_checked: boolean;
}

/** 设置购物车选中状态请求参数 */
export interface SetUserCartSelectionRequest {
  /** 是否选中 */
  is_checked: boolean;
}

/** App用户购物车管理服务 */
export interface UserCartService {
  /** 查询用户购物车数量 */
  CountUserCart(request: CountUserCartRequest): Promise<CountUserCartResponse>;
  /** 查询用户购物车列表 */
  ListUserCarts(request: ListUserCartsRequest): Promise<ListUserCartsResponse>;
  /** 创建用户购物车 */
  CreateUserCart(request: CreateUserCartRequest): Promise<Empty>;
  /** 设置全选 */
  SetUserCartSelection(request: SetUserCartSelectionRequest): Promise<Empty>;
  /** 更新用户购物车 */
  UpdateUserCart(request: UpdateUserCartRequest): Promise<Empty>;
  /** 删除用户购物车 */
  DeleteUserCart(request: DeleteUserCartRequest): Promise<Empty>;
  /** 设置状态 */
  SetUserCartStatus(request: SetUserCartStatusRequest): Promise<Empty>;
}
