// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: common/error.proto

export enum ErrorReason {
  /** INVALID_ARGUMENT - 请求参数错误 */
  INVALID_ARGUMENT = 0,
  /** UNAUTHENTICATED - 用户未通过认证 */
  UNAUTHENTICATED = 1,
  /** PERMISSION_DENIED - 用户没有权限 */
  PERMISSION_DENIED = 2,
  /** RESOURCE_NOT_FOUND - 资源不存在 */
  RESOURCE_NOT_FOUND = 3,
  /** CONFLICT - 当前状态冲突 */
  CONFLICT = 4,
  /** INTERNAL_ERROR - 服务内部异常 */
  INTERNAL_ERROR = 5,
}
