// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: shop/config/v1/shop_config.proto

/* eslint-disable */

/** 商城配置 */
export interface ShopConfigWrapper {
  /** 商城配置 */
  shop: ShopConfig | undefined;
}

/** 商城业务配置。 */
export interface ShopConfig {
  /** 微信支付参数 */
  wx_pay:
    | WxPay
    | undefined;
  /** 推荐配置 */
  recommend: Recommend | undefined;
}

/** 微信支付配置。 */
export interface WxPay {
  /** 微信支付 AppID */
  appid: string;
  /** 商户id */
  mch_id: string;
  /** 通知地址 */
  notify_url: string;
  /** 商户证书序列号 */
  mch_cert_sn: string;
  /** 商户证书路径 */
  mch_cert_path: string;
  /** api 密钥 */
  mch_api_v3_key: string;
}

/** 推荐服务配置。 */
export interface Recommend {
  /** 请求地址 */
  entry_point: string;
  /** api 密钥 */
  api_key: string;
}
