// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/v1/base_dept.proto

/* eslint-disable */
import type { TreeOptionResponse } from "../../common/v1/common";
import type { Status } from "../../common/v1/enum";
import type { Empty } from "../../google/protobuf/empty";

/** 部门树查询条件 */
export interface TreeBaseDeptsRequest {
}

/** 部门树响应 */
export interface TreeBaseDeptsResponse {
  /** 部门树 */
  base_depts: BaseDept[];
}

/** 部门选项查询条件 */
export interface OptionBaseDeptsRequest {
  /** 父级部门ID */
  parent_id?: number | undefined;
}

/** 查询部门请求参数 */
export interface GetBaseDeptRequest {
  /** 部门ID */
  id: number;
}

/** 创建部门请求参数 */
export interface CreateBaseDeptRequest {
  /** 部门表单 */
  base_dept: BaseDeptForm | undefined;
}

/** 更新部门请求参数 */
export interface UpdateBaseDeptRequest {
  /** 部门表单 */
  base_dept: BaseDeptForm | undefined;
}

/** 删除部门请求参数 */
export interface DeleteBaseDeptRequest {
  /** 部门ID列表 */
  id: string;
}

/** 设置部门状态请求参数 */
export interface SetBaseDeptStatusRequest {
  /** 部门ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 部门 */
export interface BaseDept {
  /** 部门ID */
  id: number;
  /** 父级部门ID */
  parent_id: number;
  /** 部门名称 */
  name: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status: Status;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 子部门 */
  children: BaseDept[];
}

/** 部门表单 */
export interface BaseDeptForm {
  /** 部门ID */
  id: number;
  /** 父级部门ID */
  parent_id?:
    | number
    | undefined;
  /** 部门名称 */
  name: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 备注 */
  remark: string;
}

/** Admin部门服务 */
export interface BaseDeptService {
  /** 查询部门树形列表 */
  TreeBaseDepts(request: TreeBaseDeptsRequest): Promise<TreeBaseDeptsResponse>;
  /** 查询部门树形选择 */
  OptionBaseDepts(request: OptionBaseDeptsRequest): Promise<TreeOptionResponse>;
  /** 查询部门 */
  GetBaseDept(request: GetBaseDeptRequest): Promise<BaseDeptForm>;
  /** 创建部门 */
  CreateBaseDept(request: CreateBaseDeptRequest): Promise<Empty>;
  /** 更新部门 */
  UpdateBaseDept(request: UpdateBaseDeptRequest): Promise<Empty>;
  /** 删除部门 */
  DeleteBaseDept(request: DeleteBaseDeptRequest): Promise<Empty>;
  /** 设置状态 */
  SetBaseDeptStatus(request: SetBaseDeptStatusRequest): Promise<Empty>;
}
