// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/v1/base_user.proto

/* eslint-disable */
import type { SelectOptionResponse } from "../../common/v1/common";
import type { BaseUserGender, Status } from "../../common/v1/enum";
import type { Empty } from "../../google/protobuf/empty";

/** 用户选项查询条件 */
export interface OptionBaseUsersRequest {
  /** 关键字 */
  keyword: string;
}

/** 用户分页查询条件 */
export interface PageBaseUsersRequest {
  /** 用户账号 */
  user_name: string;
  /** 用户昵称 */
  nick_name: string;
  /** 部门ID */
  dept_id?:
    | number
    | undefined;
  /** 手机号 */
  phone: string;
  /** 状态 */
  status?:
    | Status
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 用户分页响应 */
export interface PageBaseUsersResponse {
  /** 分页数据 */
  base_users: BaseUser[];
  /** 总数 */
  total: number;
}

/** 查询用户请求参数 */
export interface GetBaseUserRequest {
  /** 用户ID */
  id: number;
}

/** 创建用户请求参数 */
export interface CreateBaseUserRequest {
  /** 用户表单 */
  base_user: BaseUserForm | undefined;
}

/** 更新用户请求参数 */
export interface UpdateBaseUserRequest {
  /** 用户表单 */
  base_user: BaseUserForm | undefined;
}

/** 删除用户请求参数 */
export interface DeleteBaseUserRequest {
  /** 用户ID列表 */
  id: string;
}

/** 设置用户状态请求参数 */
export interface SetBaseUserStatusRequest {
  /** 用户ID */
  id: number;
  /** 状态 */
  status: number;
}

/** 用户 */
export interface BaseUser {
  /** 用户ID */
  id: number;
  /** 用户账号 */
  user_name: string;
  /** 用户昵称 */
  nick_name: string;
  /** 角色ID */
  role_id: number;
  /** 部门ID */
  dept_id: number;
  /** 手机号 */
  phone: string;
  /** 性别 */
  gender: BaseUserGender;
  /** 头像 */
  avatar: string;
  /** 用户状态 */
  status: Status;
  /** 备注名 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** 用户表单 */
export interface BaseUserForm {
  /** 用户ID */
  id: number;
  /** 用户账号 */
  user_name: string;
  /** 用户昵称 */
  nick_name: string;
  /** 角色ID */
  role_id?:
    | number
    | undefined;
  /** 部门ID */
  dept_id?:
    | number
    | undefined;
  /** 手机号 */
  phone: string;
  /** 密码 */
  pwd: string;
  /** 性别 */
  gender?:
    | BaseUserGender
    | undefined;
  /** 头像 */
  avatar: string;
  /** 用户状态 */
  status?:
    | Status
    | undefined;
  /** 备注名 */
  remark: string;
}

/** 重置用户密码请求参数 */
export interface ResetBaseUserPasswordRequest {
  /** 用户ID */
  id: number;
  /** 密码 */
  pwd: string;
}

/** Admin用户管理服务 */
export interface BaseUserService {
  /** 查询用户下拉选择 */
  OptionBaseUsers(request: OptionBaseUsersRequest): Promise<SelectOptionResponse>;
  /** 查询用户分页列表 */
  PageBaseUsers(request: PageBaseUsersRequest): Promise<PageBaseUsersResponse>;
  /** 查询用户 */
  GetBaseUser(request: GetBaseUserRequest): Promise<BaseUserForm>;
  /** 创建用户 */
  CreateBaseUser(request: CreateBaseUserRequest): Promise<Empty>;
  /** 更新用户 */
  UpdateBaseUser(request: UpdateBaseUserRequest): Promise<Empty>;
  /** 删除用户 */
  DeleteBaseUser(request: DeleteBaseUserRequest): Promise<Empty>;
  /** 设置状态 */
  SetBaseUserStatus(request: SetBaseUserStatusRequest): Promise<Empty>;
  /** 重置密码 */
  ResetBaseUserPassword(request: ResetBaseUserPasswordRequest): Promise<Empty>;
}
