// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: admin/v1/base_api.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";

/** API分页查询条件 */
export interface PageBaseApisRequest {
  /** 服务名 */
  service_name?:
    | string
    | undefined;
  /** 服务描述 */
  service_desc?:
    | string
    | undefined;
  /** 描述 */
  desc?:
    | string
    | undefined;
  /** 操作方法 */
  operation?:
    | string
    | undefined;
  /** 请求方式 */
  method?:
    | string
    | undefined;
  /** 请求地址 */
  path?:
    | string
    | undefined;
  /** 是否暴露为MCP工具 */
  mcp_enabled?:
    | boolean
    | undefined;
  /** 是否暴露为Agent工具 */
  agent_enabled?:
    | boolean
    | undefined;
  /** 工具名 */
  tool_name?:
    | string
    | undefined;
  /** Agent/MCP工具提示词搜索关键字 */
  tool_prompt?:
    | string
    | undefined;
  /** 页码 */
  page_num: number;
  /** 每页数量 */
  page_size: number;
}

/** API分页查询响应 */
export interface PageBaseApisResponse {
  /** API列表 */
  base_apis: BaseApi[];
  /** 总数 */
  total: number;
}

/** API详情查询条件 */
export interface GetBaseApiRequest {
  /** API ID */
  id: number;
}

/** API文档查询条件 */
export interface GetBaseApiDocRequest {
  /** API ID */
  id: number;
}

/** API MCP启用状态设置条件 */
export interface SetBaseApiMcpEnabledRequest {
  /** API ID */
  id: number;
  /** 是否暴露为MCP工具 */
  mcp_enabled: boolean;
}

/** API Agent启用状态设置条件 */
export interface SetBaseApiAgentEnabledRequest {
  /** API ID */
  id: number;
  /** 是否暴露为Agent工具 */
  agent_enabled: boolean;
}

/** API更新条件 */
export interface UpdateBaseApiRequest {
  /** API ID */
  id: number;
  /** 是否暴露为MCP工具 */
  mcp_enabled: boolean;
  /** 是否暴露为Agent工具 */
  agent_enabled: boolean;
  /** Agent/MCP工具提示词 */
  tool_prompts: string[];
}

/** API列表查询条件 */
export interface ListBaseApisRequest {
}

/** API列表响应 */
export interface ListBaseApisResponse {
  /** API列表 */
  base_apis: BaseApi[];
}

/** API */
export interface BaseApi {
  /** API ID */
  id: number;
  /** 服务名 */
  service_name: string;
  /** 服务描述 */
  service_desc: string;
  /** 描述 */
  desc: string;
  /** 操作方法 */
  operation: string;
  /** 请求方法 */
  method: string;
  /** 请求地址 */
  path: string;
  /** 是否暴露为MCP工具 */
  mcp_enabled: boolean;
  /** 是否暴露为Agent工具 */
  agent_enabled: boolean;
  /** 工具名 */
  tool_name: string;
  /** Agent/MCP工具提示词 */
  tool_prompts: string[];
}

/** API文档 */
export interface BaseApiDoc {
  /** API ID */
  id: number;
  /** 摘要 */
  summary: string;
  /** 描述 */
  description: string;
  /** 请求参数 */
  parameters: BaseApiDocSchema[];
  /** 请求体 */
  request_body:
    | BaseApiDocSchema
    | undefined;
  /** 返回值 */
  responses: BaseApiDocResponse[];
}

/** API文档Schema */
export interface BaseApiDocSchema {
  /** 字段名 */
  name: string;
  /** 字段路径 */
  path: string;
  /** 参数位置 */
  in: string;
  /** 字段类型 */
  type: string;
  /** 字段格式 */
  format: string;
  /** 是否必填 */
  required: boolean;
  /** 字段描述 */
  description: string;
  /** 引用类型 */
  ref: string;
  /** 枚举值 */
  enum: string[];
  /** 子字段 */
  children: BaseApiDocSchema[];
}

/** API文档响应 */
export interface BaseApiDocResponse {
  /** 状态码 */
  status: string;
  /** 响应描述 */
  description: string;
  /** 响应体 */
  body: BaseApiDocSchema | undefined;
}

/** AdminAPI服务 */
export interface BaseApiService {
  /** 分页查询API列表 */
  PageBaseApis(request: PageBaseApisRequest): Promise<PageBaseApisResponse>;
  /** 查询菜单分配API选项列表 */
  ListBaseApis(request: ListBaseApisRequest): Promise<ListBaseApisResponse>;
  /** 查询API详情 */
  GetBaseApi(request: GetBaseApiRequest): Promise<BaseApi>;
  /** 查询API文档 */
  GetBaseApiDoc(request: GetBaseApiDocRequest): Promise<BaseApiDoc>;
  /** 设置API MCP启用状态 */
  SetBaseApiMcpEnabled(request: SetBaseApiMcpEnabledRequest): Promise<Empty>;
  /** 设置API Agent启用状态 */
  SetBaseApiAgentEnabled(request: SetBaseApiAgentEnabledRequest): Promise<Empty>;
  /** 更新API配置 */
  UpdateBaseApi(request: UpdateBaseApiRequest): Promise<Empty>;
}
