// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: admin/v1/code_gen_table.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";

/** 数据库表列表查询条件 */
export interface ListCodeGenDatabaseTablesRequest {
}

/** 数据库表列表响应 */
export interface ListCodeGenDatabaseTablesResponse {
  /** 数据库表列表 */
  tables: CodeGenDatabaseTable[];
}

/** 代码生成表配置分页查询条件 */
export interface PageCodeGenTablesRequest {
  /** 业务表名 */
  name?:
    | string
    | undefined;
  /** 业务名 */
  business_name?:
    | string
    | undefined;
  /** 模块路径 */
  module_path?:
    | string
    | undefined;
  /** 页面类型 */
  page_type?:
    | string
    | undefined;
  /** 状态 */
  status?:
    | number
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 代码生成表配置分页响应 */
export interface PageCodeGenTablesResponse {
  /** 代码生成表配置列表 */
  code_gen_tables: CodeGenTable[];
  /** 总数 */
  total: number;
}

/** 代码生成表配置详情查询条件 */
export interface GetCodeGenTableRequest {
  /** 主键ID */
  id: number;
}

/** 代码生成表配置创建条件 */
export interface CreateCodeGenTableRequest {
  /** 代码生成表配置表单 */
  code_gen_table: CodeGenTableForm | undefined;
}

/** 代码生成表配置更新条件 */
export interface UpdateCodeGenTableRequest {
  /** 主键ID */
  id: number;
  /** 代码生成表配置表单 */
  code_gen_table: CodeGenTableForm | undefined;
}

/** 代码生成表配置删除条件 */
export interface DeleteCodeGenTableRequest {
  /** 代码生成表配置ID列表，多个用逗号分隔 */
  ids: string;
}

/** 数据库表元数据 */
export interface CodeGenDatabaseTable {
  /** 数据库表名 */
  name: string;
  /** 业务表描述 */
  comment: string;
  /** 是否已被选择 */
  disabled: boolean;
  /** 默认业务名 */
  business_name: string;
  /** 默认实体名 */
  entity_name: string;
  /** 默认模块路径 */
  module_path: string;
  /** 默认权限前缀 */
  permission_prefix: string;
}

/** 代码生成表配置 */
export interface CodeGenTable {
  /** 主键ID */
  id: number;
  /** 业务表名 */
  name: string;
  /** 业务表描述 */
  comment: string;
  /** 业务名 */
  business_name: string;
  /** 实体名 */
  entity_name: string;
  /** 模块路径 */
  module_path: string;
  /** 页面类型 */
  page_type: string;
  /** 状态 */
  status: number;
  /** 备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

/** 代码生成表配置表单 */
export interface CodeGenTableForm {
  /** 主键ID */
  id: number;
  /** 业务表名 */
  name: string;
  /** 业务表描述 */
  comment: string;
  /** 业务名 */
  business_name: string;
  /** 实体名 */
  entity_name: string;
  /** 模块路径 */
  module_path: string;
  /** 权限标识前缀 */
  permission_prefix: string;
  /** 页面类型：normal普通表格 tree树形表格 left_tree左树右表 */
  page_type: string;
  /** 树形表格父节点字段 */
  parent_column: string;
  /** 树节点显示字段 */
  tree_label_column: string;
  /** 左树配置 */
  left_tree_config:
    | CodeGenLeftTreeConfig
    | undefined;
  /** 是否生成后端 */
  gen_backend: boolean;
  /** 是否生成前端 */
  gen_frontend: boolean;
  /** 是否生成建表SQL */
  gen_sql: boolean;
  /** 父级菜单ID */
  parent_menu_id: number;
  /** 状态 */
  status: number;
  /** 备注 */
  remark: string;
}

/** 左树右表页面配置 */
export interface CodeGenLeftTreeConfig {
  /** 左树数据表名 */
  table_name: string;
  /** 左树筛选当前表字段 */
  filter_column: string;
  /** 左树父节点字段 */
  parent_column: string;
  /** 左树显示字段 */
  label_column: string;
  /** 左树值字段 */
  value_column: string;
  /** 左树描述 */
  comment: string;
}

/** Admin代码生成表配置服务 */
export interface CodeGenTableService {
  /** 查询数据库表列表 */
  ListCodeGenDatabaseTables(request: ListCodeGenDatabaseTablesRequest): Promise<ListCodeGenDatabaseTablesResponse>;
  /** 分页查询代码生成表配置 */
  PageCodeGenTables(request: PageCodeGenTablesRequest): Promise<PageCodeGenTablesResponse>;
  /** 查询代码生成表配置 */
  GetCodeGenTable(request: GetCodeGenTableRequest): Promise<CodeGenTableForm>;
  /** 创建代码生成表配置 */
  CreateCodeGenTable(request: CreateCodeGenTableRequest): Promise<Empty>;
  /** 更新代码生成表配置 */
  UpdateCodeGenTable(request: UpdateCodeGenTableRequest): Promise<Empty>;
  /** 删除代码生成表配置 */
  DeleteCodeGenTable(request: DeleteCodeGenTableRequest): Promise<Empty>;
}
