// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/v1/comment_info.proto

/* eslint-disable */
import type { CommentAiContentItem } from "../../common/v1/common";
import type {
  CommentAiScene,
  CommentReviewStatus,
  CommentReviewTargetType,
  CommentReviewType,
  CommentStatus,
} from "../../common/v1/enum";
import type { Empty } from "../../google/protobuf/empty";

/** 评论分页查询条件 */
export interface PageCommentInfosRequest {
  /** 商品ID */
  goods_id?:
    | number
    | undefined;
  /** 商品名称 */
  goods_name?:
    | string
    | undefined;
  /** 评价用户昵称 */
  user_name?:
    | string
    | undefined;
  /** 商品评分 */
  goods_score?:
    | number
    | undefined;
  /** 最低商品评分 */
  min_goods_score?:
    | number
    | undefined;
  /** 最高商品评分 */
  max_goods_score?:
    | number
    | undefined;
  /** 是否存在待审核讨论 */
  has_pending_discussion?:
    | boolean
    | undefined;
  /** 审核状态：枚举【CommentStatus】 */
  status?:
    | CommentStatus
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 评论分页响应 */
export interface PageCommentInfosResponse {
  /** 分页数据 */
  comment_infos: CommentInfo[];
  /** 总数 */
  total: number;
}

/** 商品评论聚合查询条件 */
export interface GetGoodsCommentInfoRequest {
  /** 商品ID */
  goods_id: number;
}

/** 评论详情查询条件 */
export interface GetCommentInfoRequest {
  /** 评论ID */
  id: number;
}

/** 评论状态设置条件 */
export interface SetCommentInfoStatusRequest {
  /** 评论ID */
  id: number;
  /** 审核状态：枚举【CommentStatus】 */
  status: CommentStatus;
  /** 人工审核备注或不通过原因 */
  reason: string;
}

/** 评论讨论状态设置条件 */
export interface SetCommentDiscussionStatusRequest {
  /** 讨论ID */
  id: number;
  /** 审核状态：枚举【CommentStatus】 */
  status: CommentStatus;
  /** 人工审核备注或不通过原因 */
  reason: string;
}

/** 评论审核记录查询条件 */
export interface ListCommentReviewsRequest {
  /** 审核目标类型：枚举【CommentReviewTargetType】 */
  target_type: CommentReviewTargetType;
  /** 审核目标ID */
  target_id: number;
}

/** 评论审核记录列表响应 */
export interface ListCommentReviewsResponse {
  /** 审核记录列表 */
  comment_reviews: CommentReview[];
}

/** 评论详情 */
export interface CommentInfoDetail {
  /** 评论内容 */
  comment:
    | CommentInfo
    | undefined;
  /** 商品评论标签 */
  comment_tags: CommentTag[];
  /** 评论讨论列表 */
  comment_discussions: CommentDiscussion[];
  /** 商品评论AI摘要 */
  comment_ais: CommentAi[];
  /** 评论审核记录 */
  comment_reviews: CommentReview[];
}

/** 商品评论聚合响应 */
export interface GoodsCommentInfoResponse {
  /** 评论列表 */
  comment_infos: CommentInfo[];
  /** 商品评论标签 */
  comment_tags: CommentTag[];
  /** 评论讨论列表 */
  comment_discussions: CommentDiscussion[];
  /** 商品评论AI摘要 */
  comment_ais: CommentAi[];
}

/** 评论信息 */
export interface CommentInfo {
  /** 评价主键 */
  id: number;
  /** 订单ID */
  order_id: number;
  /** 商品ID */
  goods_id: number;
  /** 商品名称快照 */
  goods_name_snapshot: string;
  /** 商品主图快照 */
  goods_picture_snapshot: string;
  /** SKU编码 */
  sku_code: string;
  /** 规格描述快照 */
  sku_desc_snapshot: string;
  /** 评价用户ID */
  user_id: number;
  /** 评价用户昵称快照 */
  user_name_snapshot: string;
  /** 评价用户头像快照 */
  user_avatar_snapshot: string;
  /** 用户展示标签 */
  user_tag_text: string;
  /** 是否匿名展示 */
  is_anonymous: boolean;
  /** 商品评分 */
  goods_score: number;
  /** 包装评分 */
  package_score: number;
  /** 配送评分 */
  delivery_score: number;
  /** 评价正文 */
  content: string;
  /** 命中的标签ID数组 */
  tag_id: number[];
  /** 评价图片数组 */
  img: string[];
  /** 点赞数 */
  like_count: number;
  /** 点踩数 */
  dislike_count: number;
  /** 已审核通过讨论数 */
  discussion_count: number;
  /** 待审核讨论数 */
  pending_discussion_count: number;
  /** 审核状态：枚举【CommentStatus】 */
  status: CommentStatus;
  /** 评价时间 */
  created_at: string;
  /** 最后更新时间 */
  updated_at: string;
}

/** 评论标签 */
export interface CommentTag {
  /** 标签主键 */
  id: number;
  /** 商品ID */
  goods_id: number;
  /** 标签名称 */
  name: string;
  /** 提及次数 */
  mention_count: number;
  /** 展示排序 */
  sort: number;
}

/** 评论讨论分页查询条件 */
export interface PageCommentDiscussionsRequest {
  /** 所属评价ID */
  comment_id: number;
  /** 讨论用户昵称 */
  user_name?:
    | string
    | undefined;
  /** 讨论内容 */
  content?:
    | string
    | undefined;
  /** 审核状态：枚举【CommentStatus】 */
  status?:
    | CommentStatus
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 评论讨论分页响应 */
export interface PageCommentDiscussionsResponse {
  /** 分页数据 */
  comment_discussions: CommentDiscussion[];
  /** 总数 */
  total: number;
}

/** 评论讨论 */
export interface CommentDiscussion {
  /** 讨论主键 */
  id: number;
  /** 所属评价ID */
  comment_id: number;
  /** 讨论用户ID */
  user_id: number;
  /** 讨论用户昵称快照 */
  user_name_snapshot: string;
  /** 讨论用户头像快照 */
  user_avatar_snapshot: string;
  /** 用户展示标签 */
  user_tag_text: string;
  /** 是否匿名展示 */
  is_anonymous: boolean;
  /** 父级讨论ID */
  parent_id: number;
  /** 回复目标讨论ID */
  reply_to_discussion_id: number;
  /** 被回复用户ID */
  reply_to_user_id: number;
  /** 被回复人的展示名称 */
  reply_to_display_name: string;
  /** 讨论内容 */
  content: string;
  /** 点赞数 */
  like_count: number;
  /** 审核状态：枚举【CommentStatus】 */
  status: CommentStatus;
  /** 发布时间 */
  created_at: string;
  /** 最后更新时间 */
  updated_at: string;
}

/** 评论AI摘要 */
export interface CommentAi {
  /** AI摘要主键 */
  id: number;
  /** 商品ID */
  goods_id: number;
  /** 展示场景：枚举【CommentAiScene】 */
  scene: CommentAiScene;
  /** AI摘要内容列表 */
  content: CommentAiContentItem[];
  /** 点赞数 */
  like_count: number;
  /** 点踩数 */
  dislike_count: number;
  /** 创建时间 */
  created_at: string;
  /** 最后更新时间 */
  updated_at: string;
}

/** 评论审核记录 */
export interface CommentReview {
  /** 审核记录ID */
  id: number;
  /** 审核目标类型：枚举【CommentReviewTargetType】 */
  target_type: CommentReviewTargetType;
  /** 审核目标ID */
  target_id: number;
  /** 审核类型：枚举【CommentReviewType】 */
  type: CommentReviewType;
  /** 审核结果：枚举【CommentReviewStatus】 */
  status: CommentReviewStatus;
  /** 本次审核提取出的标签名称 */
  tags: string[];
  /** 操作人ID，AI审核为0 */
  operator_id: number;
  /** 操作人名称或AI模型名 */
  operator_name: string;
  /** 原因说明、异常信息或人工备注 */
  reason: string;
  /** 创建时间 */
  created_at: string;
  /** 最后更新时间 */
  updated_at: string;
}

/** Admin评论管理服务 */
export interface CommentInfoService {
  /** 查询评论分页列表 */
  PageCommentInfos(request: PageCommentInfosRequest): Promise<PageCommentInfosResponse>;
  /** 按商品查询评论聚合信息 */
  GetGoodsCommentInfo(request: GetGoodsCommentInfoRequest): Promise<GoodsCommentInfoResponse>;
  /** 查询评论详情 */
  GetCommentInfo(request: GetCommentInfoRequest): Promise<CommentInfoDetail>;
  /** 设置评论审核状态 */
  SetCommentInfoStatus(request: SetCommentInfoStatusRequest): Promise<Empty>;
  /** 查询评论讨论分页列表 */
  PageCommentDiscussions(request: PageCommentDiscussionsRequest): Promise<PageCommentDiscussionsResponse>;
  /** 设置评论讨论审核状态 */
  SetCommentDiscussionStatus(request: SetCommentDiscussionStatusRequest): Promise<Empty>;
  /** 查询评论审核记录列表 */
  ListCommentReviews(request: ListCommentReviewsRequest): Promise<ListCommentReviewsResponse>;
}
