// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/v1/goods_info.proto

/* eslint-disable */
import type { GoodsStatus } from "../../common/v1/enum";
import type { Empty } from "../../google/protobuf/empty";
import type { GoodsProp } from "./goods_prop";
import type { GoodsSku } from "./goods_sku";
import type { GoodsSpec } from "./goods_spec";

/** 商品选项查询条件 */
export interface OptionGoodsInfosRequest {
  /** 商品名称 */
  name: string;
}

/** 商品选项响应 */
export interface OptionGoodsInfosResponse {
  /** 商品选项列表 */
  goods_infos: OptionGoodsInfosResponse_GoodsInfo[];
}

/** 商品选项 */
export interface OptionGoodsInfosResponse_GoodsInfo {
  /** 商品ID */
  id: number;
  /** 名称 */
  name: string;
  /** 当前价格(分) */
  price: number;
  /** 分类名称 */
  category_name: string;
}

/** 商品列表查询条件 */
export interface PageGoodsInfosRequest {
  /** 分类id */
  category_id?:
    | number
    | undefined;
  /** 商品名称 */
  name: string;
  /** 状态 */
  status?:
    | GoodsStatus
    | undefined;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
  /** 库存预警类型：1 低库存，2 零库存 */
  inventory_alert?:
    | number
    | undefined;
  /** 价格异常类型：1 价格配置异常 */
  price_alert?: number | undefined;
}

/** 商品列表响应 */
export interface PageGoodsInfosResponse {
  /** 商品列表 */
  goods_infos: GoodsInfo[];
  /** 总数 */
  total: number;
}

/** 商品详情查询条件 */
export interface GetGoodsInfoRequest {
  /** 商品ID */
  id: number;
}

/** 商品创建条件 */
export interface CreateGoodsInfoRequest {
  /** 商品表单 */
  goods_info: GoodsInfoForm | undefined;
}

/** 商品更新条件 */
export interface UpdateGoodsInfoRequest {
  /** 商品ID */
  id: number;
  /** 商品表单 */
  goods_info: GoodsInfoForm | undefined;
}

/** 商品删除条件 */
export interface DeleteGoodsInfoRequest {
  /** 商品ID列表，多个用逗号分隔 */
  ids: string;
}

/** 商品状态设置条件 */
export interface SetGoodsInfoStatusRequest {
  /** 商品ID */
  id: number;
  /** 状态：枚举【GoodsStatus】 */
  status: GoodsStatus;
}

/** 商品信息 */
export interface GoodsInfo {
  /** 商品ID */
  id: number;
  /** 分类ID列表 */
  category_id: number[];
  /** 名称 */
  name: string;
  /** 描述 */
  desc: string;
  /** 商品图片 */
  picture: string;
  /** 当前价格(分) */
  price: number;
  /** 折扣价格（分） */
  discount_price: number;
  /** 初始销量 */
  init_sale_num: number;
  /** 真实销售数量 */
  real_sale_num: number;
  /** 库存数量 */
  inventory: number;
  /** 状态 */
  status: GoodsStatus;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 分类名称 */
  category_name: string;
}

/** 商品表单 */
export interface GoodsInfoForm {
  /** 商品ID */
  id: number;
  /** 分类ID列表 */
  category_id: number[];
  /** 名称 */
  name: string;
  /** 描述 */
  desc: string;
  /** 商品图片 */
  picture: string;
  /** 轮播图 */
  banner: string[];
  /** 商品详情 */
  detail: string[];
  /** 状态 */
  status?:
    | GoodsStatus
    | undefined;
  /** 商品属性 */
  prop_list: GoodsProp[];
  /** 商品SKU */
  sku_list: GoodsSku[];
  /** 商品规格 */
  spec_list: GoodsSpec[];
  /** 分类名称 */
  category_name: string;
}

/** Admin商品信息服务 */
export interface GoodsInfoService {
  /** 查询商品信息下拉选择 */
  OptionGoodsInfos(request: OptionGoodsInfosRequest): Promise<OptionGoodsInfosResponse>;
  /** 查询商品信息列表 */
  PageGoodsInfos(request: PageGoodsInfosRequest): Promise<PageGoodsInfosResponse>;
  /** 查询商品信息 */
  GetGoodsInfo(request: GetGoodsInfoRequest): Promise<GoodsInfoForm>;
  /** 创建商品信息 */
  CreateGoodsInfo(request: CreateGoodsInfoRequest): Promise<Empty>;
  /** 更新商品信息 */
  UpdateGoodsInfo(request: UpdateGoodsInfoRequest): Promise<Empty>;
  /** 删除商品信息 */
  DeleteGoodsInfo(request: DeleteGoodsInfoRequest): Promise<Empty>;
  /** 设置状态 */
  SetGoodsInfoStatus(request: SetGoodsInfoStatusRequest): Promise<Empty>;
}
