// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/v1/goods_sku.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";

/** 商品SKU列表查询条件 */
export interface PageGoodsSkusRequest {
  /** 商品id */
  goods_id: number;
  /** 商品SKU编号 */
  sku_code: string;
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 商品SKU列表响应 */
export interface PageGoodsSkusResponse {
  /** 商品SKU列表 */
  goods_skus: GoodsSku[];
  /** 总数 */
  total: number;
}

/** 商品SKU详情查询条件 */
export interface GetGoodsSkuRequest {
  /** 商品SKUID */
  id: number;
}

/** 商品SKU更新条件 */
export interface UpdateGoodsSkuRequest {
  /** 商品SKUID */
  id: number;
  /** 商品SKU */
  goods_sku: GoodsSku | undefined;
}

/** 商品SKU */
export interface GoodsSku {
  /** 商品SKUID */
  id: number;
  /** 商品id */
  goods_id: number;
  /** 商品图片 */
  picture: string;
  /** SKU组成，需要与商品规格数组顺序对应 */
  spec_item: string[];
  /** SKU编码 */
  sku_code: string;
  /** 当前价格(分) */
  price: number;
  /** 折扣价格（分） */
  discount_price: number;
  /** 初始销量 */
  init_sale_num: number;
  /** 真实销售数量 */
  real_sale_num: number;
  /** 库存数量 */
  inventory: number;
}

/** Admin商品SKU服务 */
export interface GoodsSkuService {
  /** 查询商品SKU列表 */
  PageGoodsSkus(request: PageGoodsSkusRequest): Promise<PageGoodsSkusResponse>;
  /** 查询商品SKU */
  GetGoodsSku(request: GetGoodsSkuRequest): Promise<GoodsSku>;
  /** 更新商品SKU */
  UpdateGoodsSku(request: UpdateGoodsSkuRequest): Promise<Empty>;
}
