// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/v1/goods_analytics.proto

/* eslint-disable */
import type {
  AnalyticsPieResponse,
  AnalyticsRankResponse,
  AnalyticsTimeType,
  AnalyticsTrendResponse,
} from "../../common/v1/analytics";

/** 商品摘要指标查询条件 */
export interface SummaryGoodsAnalyticsRequest {
  /** 时间类型 */
  time_type: AnalyticsTimeType;
}

/** 商品趋势查询条件 */
export interface TrendGoodsAnalyticsRequest {
  /** 时间类型 */
  time_type: AnalyticsTimeType;
}

/** 商品分类分布查询条件 */
export interface PieGoodsAnalyticsRequest {
  /** 时间类型 */
  time_type: AnalyticsTimeType;
}

/** 商品支付排行查询条件 */
export interface RankGoodsAnalyticsRequest {
  /** 时间类型 */
  time_type: AnalyticsTimeType;
}

/** 商品分析汇总响应 */
export interface SummaryGoodsAnalyticsResponse {
  /** 新增商品数 */
  new_goods_count: number;
  /** 上架商品占比 */
  put_on_goods_rate: number;
  /** 活跃商品数 */
  active_goods_count: number;
  /** 活跃商品占比 */
  active_goods_rate: number;
  /** 销售件数 */
  sale_count: number;
  /** 销售增长率 */
  sale_growth_rate: number;
  /** 浏览次数 */
  view_count: number;
  /** 收藏次数 */
  collect_count: number;
  /** 加购件数 */
  cart_count: number;
  /** 下单次数 */
  order_count: number;
  /** 支付次数 */
  pay_count: number;
  /** 支付金额，单位分 */
  pay_amount: number;
  /** 浏览加购转化率 */
  cart_conversion_rate: number;
  /** 加购下单转化率 */
  order_conversion_rate: number;
  /** 浏览支付转化率 */
  pay_conversion_rate: number;
  /** 件均成交价，单位分 */
  pay_unit_price: number;
}

/** Admin商品分析服务 */
export interface GoodsAnalyticsService {
  /** 查询商品摘要指标 */
  SummaryGoodsAnalytics(request: SummaryGoodsAnalyticsRequest): Promise<SummaryGoodsAnalyticsResponse>;
  /** 查询商品趋势 */
  TrendGoodsAnalytics(request: TrendGoodsAnalyticsRequest): Promise<AnalyticsTrendResponse>;
  /** 查询商品分类分布 */
  PieGoodsAnalytics(request: PieGoodsAnalyticsRequest): Promise<AnalyticsPieResponse>;
  /** 查询商品支付排行 */
  RankGoodsAnalytics(request: RankGoodsAnalyticsRequest): Promise<AnalyticsRankResponse>;
}
