// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/v1/order_report.proto

/* eslint-disable */

/** 订单月报汇总查询条件 */
export interface SummaryOrderMonthReportRequest {
  /** 开始月份，格式：YYYY-MM */
  start_month: string;
  /** 结束月份，格式：YYYY-MM */
  end_month: string;
  /** 支付方式：枚举【OrderPayType】，0 表示全部 */
  pay_type: number;
  /** 支付渠道：枚举【OrderPayChannel】，0 表示全部 */
  pay_channel: number;
}

/** 订单月报列表请求参数 */
export interface ListOrderMonthReportsRequest {
  /** 开始月份，格式：YYYY-MM */
  start_month: string;
  /** 结束月份，格式：YYYY-MM */
  end_month: string;
  /** 支付方式：枚举【OrderPayType】，0 表示全部 */
  pay_type: number;
  /** 支付渠道：枚举【OrderPayChannel】，0 表示全部 */
  pay_channel: number;
}

/** 订单月报汇总响应 */
export interface SummaryOrderMonthReportResponse {
  /** 支付成功订单数 */
  paid_order_count: number;
  /** 支付成功金额，单位分 */
  paid_order_amount: number;
  /** 退款成功订单数 */
  refund_order_count: number;
  /** 退款成功金额，单位分 */
  refund_order_amount: number;
  /** 净销售额，单位分 */
  net_order_amount: number;
  /** 支付用户数 */
  paid_user_count: number;
  /** 商品件数 */
  goods_count: number;
  /** 客单价，单位分 */
  customer_unit_price: number;
}

/** 订单月报项 */
export interface OrderMonthReportItem {
  /** 月份，格式：YYYY-MM */
  month: string;
  /** 支付成功订单数 */
  paid_order_count: number;
  /** 支付成功金额，单位分 */
  paid_order_amount: number;
  /** 退款成功订单数 */
  refund_order_count: number;
  /** 退款成功金额，单位分 */
  refund_order_amount: number;
  /** 净销售额，单位分 */
  net_order_amount: number;
  /** 支付用户数 */
  paid_user_count: number;
  /** 商品件数 */
  goods_count: number;
  /** 客单价，单位分 */
  customer_unit_price: number;
}

/** 订单月报列表响应 */
export interface ListOrderMonthReportsResponse {
  /** 月报明细 */
  order_month_reports: OrderMonthReportItem[];
}

/** 订单日报汇总查询条件 */
export interface SummaryOrderDayReportRequest {
  /** 开始日期，格式：YYYY-MM-DD */
  start_date: string;
  /** 结束日期，格式：YYYY-MM-DD */
  end_date: string;
  /** 支付方式：枚举【OrderPayType】，0 表示全部 */
  pay_type: number;
  /** 支付渠道：枚举【OrderPayChannel】，0 表示全部 */
  pay_channel: number;
}

/** 订单日报列表请求参数 */
export interface ListOrderDayReportsRequest {
  /** 开始日期，格式：YYYY-MM-DD */
  start_date: string;
  /** 结束日期，格式：YYYY-MM-DD */
  end_date: string;
  /** 支付方式：枚举【OrderPayType】，0 表示全部 */
  pay_type: number;
  /** 支付渠道：枚举【OrderPayChannel】，0 表示全部 */
  pay_channel: number;
}

/** 订单日报汇总响应 */
export interface SummaryOrderDayReportResponse {
  /** 支付成功订单数 */
  paid_order_count: number;
  /** 支付成功金额，单位分 */
  paid_order_amount: number;
  /** 退款成功订单数 */
  refund_order_count: number;
  /** 退款成功金额，单位分 */
  refund_order_amount: number;
  /** 净销售额，单位分 */
  net_order_amount: number;
  /** 支付用户数 */
  paid_user_count: number;
  /** 商品件数 */
  goods_count: number;
  /** 客单价，单位分 */
  customer_unit_price: number;
}

/** 订单日报项 */
export interface OrderDayReportItem {
  /** 日期，格式：YYYY-MM-DD */
  day: string;
  /** 支付成功订单数 */
  paid_order_count: number;
  /** 支付成功金额，单位分 */
  paid_order_amount: number;
  /** 退款成功订单数 */
  refund_order_count: number;
  /** 退款成功金额，单位分 */
  refund_order_amount: number;
  /** 净销售额，单位分 */
  net_order_amount: number;
  /** 支付用户数 */
  paid_user_count: number;
  /** 商品件数 */
  goods_count: number;
  /** 客单价，单位分 */
  customer_unit_price: number;
}

/** 订单日报列表响应 */
export interface ListOrderDayReportsResponse {
  /** 日报明细 */
  order_day_reports: OrderDayReportItem[];
}

/** Admin订单报表服务 */
export interface OrderReportService {
  /** 查询订单月报汇总 */
  SummaryOrderMonthReport(request: SummaryOrderMonthReportRequest): Promise<SummaryOrderMonthReportResponse>;
  /** 查询订单月报明细 */
  ListOrderMonthReports(request: ListOrderMonthReportsRequest): Promise<ListOrderMonthReportsResponse>;
  /** 查询订单日报汇总 */
  SummaryOrderDayReport(request: SummaryOrderDayReportRequest): Promise<SummaryOrderDayReportResponse>;
  /** 查询订单日报明细 */
  ListOrderDayReports(request: ListOrderDayReportsRequest): Promise<ListOrderDayReportsResponse>;
}
