// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/v1/order_info.proto

/* eslint-disable */
import type {
  OrderBillStatus,
  OrderCancelReason,
  OrderDeliveryTime,
  OrderPayChannel,
  OrderPayType,
  OrderRefundReason,
  OrderStatus,
} from "../../common/v1/enum";
import type { Empty } from "../../google/protobuf/empty";

/** 订单分页查询条件 */
export interface PageOrderInfosRequest {
  /** 订单编号 */
  order_no: string;
  /** 用户id */
  user_id: number;
  /** 订单状态 */
  status?:
    | OrderStatus
    | undefined;
  /** 支付方式：枚举【OrderPayType】 */
  pay_type?:
    | OrderPayType
    | undefined;
  /** 支付渠道：枚举【OrderPayChannel】 */
  pay_channel?:
    | OrderPayChannel
    | undefined;
  /** 创建时间 */
  created_at: string[];
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 订单分页响应 */
export interface PageOrderInfosResponse {
  /** 订单分页数据 */
  order_infos: OrderInfo[];
  /** 总数 */
  total: number;
}

/** 订单详情查询条件 */
export interface GetOrderInfoRequest {
  /** 订单ID */
  id: number;
}

/** 订单退款信息查询条件 */
export interface GetOrderInfoRefundRequest {
  /** 订单ID */
  id: number;
}

/** 订单发货信息查询条件 */
export interface GetOrderInfoShipmentRequest {
  /** 订单ID */
  id: number;
}

/** 订单详情响应 */
export interface OrderInfoResponse {
  /** 订单信息 */
  order:
    | OrderInfo
    | undefined;
  /** 支付倒计时 */
  countdown: number;
  /** 地址信息 */
  address:
    | OrderAddress
    | undefined;
  /** 取消信息 */
  cancel:
    | OrderCancel
    | undefined;
  /** 商品信息 */
  goods: OrderGoods[];
  /** 物流信息 */
  logistics:
    | OrderLogistics
    | undefined;
  /** 支付信息 */
  payment:
    | OrderPayment
    | undefined;
  /** 退款信息 */
  refund: OrderRefund[];
}

/** 订单Refund响应 */
export interface OrderInfoRefundResponse {
  /** 支付信息 */
  payment:
    | OrderPayment
    | undefined;
  /** 退款信息 */
  refund: OrderRefund[];
}

/** 订单退款请求参数 */
export interface RefundOrderInfoRequest {
  /** 订单id */
  order_id: number;
  /** 退款原因：枚举【OrderRefundReason】 */
  reason?:
    | OrderRefundReason
    | undefined;
  /** 退款金额 */
  refund_money: number;
}

/** 订单发货表单 */
export interface OrderInfoShipmentForm {
  /** 地址信息 */
  address:
    | OrderAddress
    | undefined;
  /** 商品信息 */
  goods: OrderGoods[];
  /** 物流信息 */
  logistics: OrderLogistics | undefined;
}

/** 订单发货请求参数 */
export interface ShipOrderInfoRequest {
  /** 订单id */
  order_id: number;
  /** 物流公司名 */
  name: string;
  /** 物流单号 */
  no: string;
  /** 联系方式 */
  contact: string;
}

/** Order信息 */
export interface OrderInfo {
  /** 订单ID */
  id: number;
  /** 订单编号 */
  order_no: string;
  /** 用户ID */
  user_id: number;
  /** 实际支付金额（单位：分） */
  pay_money: number;
  /** 总价（单位：分） */
  total_money: number;
  /** 优惠金额（单位：分） */
  post_fee: number;
  /** 商品总数 */
  goods_num: number;
  /** 支付方式：枚举【OrderPayType】 */
  pay_type: OrderPayType;
  /** 支付渠道：枚举【OrderPayChannel】 */
  pay_channel: OrderPayChannel;
  /** 配送时间：枚举【OrderDeliveryTime】 */
  delivery_time: OrderDeliveryTime;
  /** 状态：枚举【OrderStatus】 */
  status: OrderStatus;
  /** 订单备注 */
  remark: string;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 用户名 */
  nick_name: string;
}

/** 订单地址 */
export interface OrderAddress {
  /** 联系人 */
  receiver: string;
  /** 联系方式 */
  contact: string;
  /** 省市区（JSON存储） */
  address: string[];
  /** 详细地址 */
  detail: string;
}

/** 订单取消记录 */
export interface OrderCancel {
  /** 取消原因：枚举【OrderCancelReason】 */
  reason: OrderCancelReason;
  /** 创建时间 */
  created_at: string;
}

/** 订单商品 */
export interface OrderGoods {
  /** 商品ID */
  goods_id: number;
  /** 规格编号 */
  sku_code: string;
  /** SKU规格组成（需与goods_spec顺序对应，JSON存储） */
  spec_item: string[];
  /** 商品图片 */
  picture: string;
  /** 商品名称 */
  name: string;
  /** 数量 */
  num: number;
  /** 当前价格（单位：分） */
  price: number;
  /** 支付价格（单位：分） */
  pay_price: number;
  /** 当前金额汇总 */
  total_price: number;
  /** 支付金额汇总 */
  total_pay_price: number;
}

/** 订单物流 */
export interface OrderLogistics {
  /** 物流公司名 */
  name: string;
  /** 物流单号 */
  no: string;
  /** 联系方式 */
  contact: string;
  /** 物流详情（JSON存储） */
  detail: OrderLogistics_Detail[];
  /** 创建时间 */
  created_at: string;
}

/** Detail */
export interface OrderLogistics_Detail {
  /** 时间 */
  time: string;
  /** 动态 */
  text: string;
}

/** 订单支付 */
export interface OrderPayment {
  /** 订单编号 */
  order_no: string;
  /** 三方订单编号 */
  third_order_no: string;
  /** 交易类型 */
  trade_type: string;
  /** 交易状态 */
  trade_state: string;
  /** 交易状态描述 */
  trade_state_desc: string;
  /** 银行类型 */
  bank_type: string;
  /** 支付完成时间 */
  success_time: string;
  /** 支付者信息 */
  payer:
    | OrderPayment_Payer
    | undefined;
  /** 订单金额 */
  amount:
    | OrderPayment_Amount
    | undefined;
  /** 场景信息 */
  scene_info:
    | OrderPayment_SceneInfo
    | undefined;
  /** 对账状态：枚举【OrderBillStatus】 */
  status: OrderBillStatus;
}

/** 支付者信息 */
export interface OrderPayment_Payer {
  /** 【用户标识】用户在商户appid下的唯一标识 */
  openid: string;
}

/** 支付金额信息 */
export interface OrderPayment_Amount {
  /** 【用户支付金额】用户支付金额，整型，单位为分。（指使用优惠券的情况下，这里等于总金额-优惠券金额） */
  payer_total: number;
  /** 【总金额】订单总金额，单位为分，整型 */
  total: number;
  /** 【货币类型】固定返回：CNY，代表人民币 */
  currency: string;
  /** 【用户支付币种】 固定返回：CNY，代表人民币。 */
  payer_currency: string;
}

/** 支付场景信息 */
export interface OrderPayment_SceneInfo {
  /** 【商户端设备号】门店号/收银设备ID */
  device_id: string;
}

/** 订单退款 */
export interface OrderRefund {
  /** 支付订单编号 */
  order_no: string;
  /** 三方支付订单编号 */
  third_order_no: string;
  /** 退款编号 */
  refund_no: string;
  /** 退款原因：枚举【OrderRefundReason】 */
  reason: OrderRefundReason;
  /** 三方退款编号 */
  third_refund_no: string;
  /** 退款渠道 */
  channel: string;
  /** 退款入账账户 */
  user_received_account: string;
  /** 退款创建时间 */
  create_time: string;
  /** 退款成功时间 */
  success_time: string;
  /** 退款状态 */
  refund_state: string;
  /** 资金账户类型 */
  funds_account: string;
  /** 金额信息 */
  amount:
    | OrderRefund_Amount
    | undefined;
  /** 对账状态：枚举【OrderBillStatus】 */
  status: OrderBillStatus;
}

/** 退款金额信息 */
export interface OrderRefund_Amount {
  /** 【原订单金额】单位：分 */
  total: number;
  /** 【退款金额】单位：分 */
  refund: number;
  /** 【用户实际支付金额】单位：分 */
  payer_total: number;
  /** 【用户退款金额】单位：分 */
  payer_refund: number;
}

/** Admin订单信息服务 */
export interface OrderInfoService {
  /** 查询订单信息分页列表 */
  PageOrderInfos(request: PageOrderInfosRequest): Promise<PageOrderInfosResponse>;
  /** 查询订单信息 */
  GetOrderInfo(request: GetOrderInfoRequest): Promise<OrderInfoResponse>;
  /** 查询订单信息退款信息 */
  GetOrderInfoRefund(request: GetOrderInfoRefundRequest): Promise<OrderInfoRefundResponse>;
  /** 订单信息退款 */
  RefundOrderInfo(request: RefundOrderInfoRequest): Promise<Empty>;
  /** 查询订单信息发货信息 */
  GetOrderInfoShipment(request: GetOrderInfoShipmentRequest): Promise<OrderInfoShipmentForm>;
  /** 订单信息发货 */
  ShipOrderInfo(request: ShipOrderInfoRequest): Promise<Empty>;
}
