// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/v1/recommend_request.proto

/* eslint-disable */
import type {
  GoodsStatus,
  RecommendActorType,
  RecommendEventType,
  RecommendScene,
  RecommendStrategy,
} from "../../common/v1/enum";

/** 推荐请求分页查询条件 */
export interface PageRecommendRequestsRequest {
  /** 推荐请求ID */
  request_id?:
    | string
    | undefined;
  /** 主体类型：字典【recommend_actor_type】 */
  actor_type?:
    | RecommendActorType
    | undefined;
  /** 主体编号（仅内部定位使用） */
  actor_id?:
    | number
    | undefined;
  /** 推荐场景：字典【recommend_scene】 */
  scene?:
    | RecommendScene
    | undefined;
  /** 请求时间 */
  request_at: string[];
  /** 当前页码 */
  page_num: number;
  /** 每一页的行数 */
  page_size: number;
}

/** 推荐请求分页响应 */
export interface PageRecommendRequestsResponse {
  /** 分页数据 */
  recommend_requests: RecommendRequest[];
  /** 总数 */
  total: number;
}

/** 推荐请求 */
export interface RecommendRequest {
  /** 主键ID */
  id: number;
  /** 推荐请求ID */
  request_id: string;
  /** 主体类型：字典【recommend_actor_type】 */
  actor_type: RecommendActorType;
  /** 主体编号（仅内部定位使用） */
  actor_id: number;
  /** 推荐场景：字典【recommend_scene】 */
  scene: RecommendScene;
  /** 页码 */
  page_num: number;
  /** 分页大小 */
  page_size: number;
  /** 本次返回总数 */
  total: number;
  /** 命中的推荐策略：字典【recommend_strategy】 */
  strategy: RecommendStrategy;
  /** 最终命中的推荐器 */
  provider_name: string;
  /** 请求时间 */
  request_at: string;
  /** 主体名称 */
  actor_name: string;
}

/** 推荐请求详情查询条件 */
export interface GetRecommendRequestRequest {
  /** 推荐请求记录ID */
  id: number;
}

/** 推荐请求详情响应 */
export interface RecommendRequestDetailResponse {
  /** 请求基础信息 */
  request:
    | RecommendRequest
    | undefined;
  /** 推荐上下文信息 */
  context:
    | RecommendRequestContext
    | undefined;
  /** 当前请求页的推荐商品列表 */
  item_list: RecommendRequestItem[];
}

/** 推荐请求上下文信息 */
export interface RecommendRequestContext {
  /** 锚点商品ID */
  goods_id: number;
  /** 关联订单ID */
  order_id: number;
  /** 上下文商品ID列表 */
  context_goods_ids: number[];
  /** 命中的推荐策略：字典【recommend_strategy】 */
  strategy: RecommendStrategy;
  /** 上下文记录的推荐器 */
  provider_name: string;
  /** 最终命中的推荐器 */
  final_provider_name: string;
  /** 推荐请求链路轨迹 */
  trace: RecommendRequestTrace[];
  /** 原始上下文JSON */
  raw_json: string;
}

/** 推荐请求链路轨迹 */
export interface RecommendRequestTrace {
  /** 推荐器名称 */
  provider_name: string;
  /** 当前推荐器返回的商品数量 */
  result_count: number;
  /** 当前推荐器是否命中 */
  hit: boolean;
  /** 当前推荐器错误信息 */
  error_msg: string;
  /** 当前推荐器是否为最终命中的推荐器 */
  is_final: boolean;
}

/** 推荐请求商品信息 */
export interface RecommendRequestItem {
  /** 商品ID */
  goods_id: number;
  /** 结果位置 */
  position: number;
  /** 商品名称 */
  goods_name: string;
  /** 商品图片 */
  picture: string;
  /** 当前价格（分） */
  price: number;
  /** 折扣价格（分） */
  discount_price: number;
  /** 商品状态：枚举【GoodsStatus】 */
  goods_status: GoodsStatus;
  /** 关联事件条数 */
  event_count: number;
}

/** 推荐请求事件查询条件 */
export interface ListRecommendRequestEventsRequest {
  /** 推荐请求记录ID */
  request_record_id: number;
  /** 商品ID */
  goods_id: number;
  /** 结果位置 */
  position: number;
}

/** 推荐请求事件响应 */
export interface ListRecommendRequestEventsResponse {
  /** 事件数据 */
  recommend_events: RecommendEvent[];
  /** 总数 */
  total: number;
}

/** 推荐事件 */
export interface RecommendEvent {
  /** 主键ID */
  id: number;
  /** 主体类型：字典【recommend_actor_type】 */
  actor_type: RecommendActorType;
  /** 主体编号（仅内部定位使用） */
  actor_id: number;
  /** 推荐场景：字典【recommend_scene】 */
  scene: RecommendScene;
  /** 事件类型：枚举【RecommendEventType】 */
  event_type: RecommendEventType;
  /** 商品ID */
  goods_id: number;
  /** 商品数量 */
  goods_num: number;
  /** 推荐请求ID */
  request_id: string;
  /** 结果位置 */
  position: number;
  /** 事件时间 */
  event_at: string;
}

/** Admin推荐请求服务 */
export interface RecommendRequestService {
  /** 查询推荐请求分页列表 */
  PageRecommendRequests(request: PageRecommendRequestsRequest): Promise<PageRecommendRequestsResponse>;
  /** 查询推荐请求详情 */
  GetRecommendRequest(request: GetRecommendRequestRequest): Promise<RecommendRequestDetailResponse>;
  /** 查询推荐请求商品关联事件 */
  ListRecommendRequestEvents(request: ListRecommendRequestEventsRequest): Promise<ListRecommendRequestEventsResponse>;
}
