// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/v1/recommend_gorse.proto

/* eslint-disable */
import type { AdvanceDataType } from "../../common/v1/enum";
import type { Empty } from "../../google/protobuf/empty";

/** 外部推荐脚本预览请求 */
export interface PreviewExternalRequest {
  /** 用户编号 */
  user_id: string;
  /** 外部推荐脚本 */
  script: string;
}

/** 外部推荐脚本预览响应 */
export interface PreviewExternalResponse {
  /** 推荐商品编号列表 */
  items: string[];
}

/** 排序提示词预览请求 */
export interface PreviewRankerPromptRequest {
  /** 用户编号 */
  user_id: string;
  /** 查询模板 */
  query_template: string;
  /** 文档模板 */
  document_template: string;
}

/** 排序提示词预览响应 */
export interface PreviewRankerPromptResponse {
  /** 查询提示词 */
  query: string;
  /** 文档提示词列表 */
  documents: string[];
}

/** Gorse 推荐导出数据查询条件 */
export interface ExportDataRequest {
  /** 数据类型：枚举【AdvanceDataType】 */
  data_type: AdvanceDataType;
}

/** Gorse 推荐导出数据响应 */
export interface ExportDataResponse {
  /** 文件名 */
  file_name: string;
  /** JSONL文件内容 */
  content: string;
}

/** Gorse 推荐导入数据请求 */
export interface ImportDataRequest {
  /** 数据类型：枚举【AdvanceDataType】 */
  data_type: AdvanceDataType;
  /** 文件名 */
  file_name: string;
  /** JSONL文件内容 */
  content: string;
}

/** Gorse 推荐导入数据响应 */
export interface ImportDataResponse {
  /** 成功导入数量 */
  success_count: number;
}

/** Gorse 推荐名称查询条件 */
export interface GetTimeSeriesRequest {
  /** 名称 */
  name: string;
  /** 开始时间 */
  begin: string;
  /** 结束时间 */
  end: string;
}

/** Gorse 推荐仪表盘推荐商品查询条件 */
export interface ListDashboardItemsRequest {
  /** 推荐器名称 */
  recommender: string;
  /** 分类 */
  category: string;
  /** 结束位置 */
  end: number;
}

/** Gorse 推荐分类查询条件 */
export interface OptionCategoriesRequest {
}

/** Gorse 推荐分类响应 */
export interface OptionCategoriesResponse {
  /** 分类列表 */
  categories: string[];
}

/** Gorse 推荐仪表盘推荐商品响应 */
export interface ListDashboardItemsResponse {
  /** 商品列表 */
  items: Item[];
  /** 最后更新时间 */
  last_modified: string;
}

/** Gorse 推荐时间序列响应 */
export interface TimeSeriesResponse {
  /** 时间序列点列表 */
  points: TimeSeriesPoint[];
}

/** Gorse 推荐时间序列点 */
export interface TimeSeriesPoint {
  /** 名称 */
  name: string;
  /** 时间 */
  timestamp: string;
  /** 数值 */
  value: number;
}

/** Gorse 推荐相似用户查询条件 */
export interface GetUserSimilarRequest {
  /** 用户编号 */
  id: string;
  /** 推荐器名称 */
  recommender: string;
  /** 分类 */
  category: string;
}

/** Gorse 推荐相似商品查询条件 */
export interface GetItemSimilarRequest {
  /** 商品编号 */
  id: string;
  /** 推荐器名称 */
  recommender: string;
  /** 分类 */
  category: string;
}

/** Gorse 推荐用户反馈查询条件 */
export interface GetUserFeedbackRequest {
  /** 用户编号 */
  id: string;
  /** 反馈类型 */
  feedback_type: string;
  /** 偏移量 */
  offset: number;
  /** 查询数量 */
  n: number;
}

/** Gorse 推荐用户推荐查询条件 */
export interface GetUserRecommendRequest {
  /** 用户编号 */
  id: string;
  /** 推荐器名称 */
  recommender: string;
  /** 分类 */
  category: string;
  /** 查询数量 */
  n: number;
}

/** Gorse 推荐任务状态查询条件 */
export interface ListTasksRequest {
}

/** Gorse 推荐任务状态响应 */
export interface ListTasksResponse {
  /** 任务状态列表 */
  tasks: Task[];
}

/** Gorse 推荐任务状态 */
export interface Task {
  /** 执行节点 */
  tracer: string;
  /** 任务名称 */
  name: string;
  /** 任务状态 */
  status: string;
  /** 错误信息 */
  error: string;
  /** 当前进度 */
  count: number;
  /** 总进度 */
  total: number;
  /** 开始时间 */
  start_time: string;
  /** 结束时间 */
  finish_time: string;
}

/** Gorse 推荐用户列表查询条件 */
export interface PageUsersRequest {
  /** 分页游标 */
  cursor: string;
  /** 查询数量 */
  n: number;
}

/** Gorse 推荐用户查询条件 */
export interface GetUserRequest {
  /** 用户编号 */
  id: string;
}

/** Gorse 推荐用户删除条件 */
export interface DeleteUserRequest {
  /** 用户编号 */
  id: string;
}

/** Gorse 推荐用户分页响应 */
export interface PageUsersResponse {
  /** 下一页游标 */
  cursor: string;
  /** 用户列表 */
  users: UserResponse[];
}

/** Gorse 推荐相似用户响应 */
export interface UserSimilarResponse {
  /** 相似用户列表 */
  users: UserResponse[];
}

/** Gorse 推荐用户 */
export interface UserResponse {
  /** 用户编号 */
  user_id: string;
  /** 标签信息 */
  labels:
    | UserLabel
    | undefined;
  /** 备注 */
  comment: string;
  /** 最后活跃时间 */
  last_active_time: string;
  /** 最后更新时间 */
  last_update_time: string;
  /** 分数 */
  score: number;
}

/** Gorse 推荐用户标签信息 */
export interface UserLabel {
  /** 部门编号 */
  dept_id: number;
  /** 性别 */
  gender: number;
  /** 角色编号 */
  role_id: number;
  /** 状态 */
  status: number;
}

/** Gorse 推荐商品列表查询条件 */
export interface PageItemsRequest {
  /** 分页游标 */
  cursor: string;
  /** 查询数量 */
  n: number;
}

/** Gorse 推荐商品查询条件 */
export interface GetItemRequest {
  /** 商品编号 */
  id: string;
}

/** Gorse 推荐商品删除条件 */
export interface DeleteItemRequest {
  /** 商品编号 */
  id: string;
}

/** Gorse 推荐商品分页响应 */
export interface PageItemsResponse {
  /** 下一页游标 */
  cursor: string;
  /** 商品列表 */
  items: Item[];
}

/** Gorse 推荐商品列表响应 */
export interface ItemListResponse {
  /** 商品列表 */
  items: Item[];
}

/** Gorse 推荐商品 */
export interface Item {
  /** 商品编号 */
  item_id: string;
  /** 是否隐藏 */
  is_hidden: boolean;
  /** 分类列表 */
  categories: string[];
  /** 时间 */
  timestamp: string;
  /** 标签信息 */
  labels:
    | ItemLabel
    | undefined;
  /** 备注 */
  comment: string;
  /** 分数 */
  score: number;
}

/** Gorse 推荐商品标签信息 */
export interface ItemLabel {
  /** 商品描述 */
  desc: string;
  /** 折扣价 */
  discount_price: number;
  /** 库存 */
  inventory: number;
  /** 原价 */
  price: number;
  /** 状态 */
  status: number;
}

/** Gorse 推荐反馈响应 */
export interface FeedbackResponse {
  /** 反馈列表 */
  feedback: Feedback[];
}

/** Gorse 推荐反馈 */
export interface Feedback {
  /** 反馈类型 */
  feedback_type: string;
  /** 用户编号 */
  user_id: string;
  /** 反馈商品 */
  item:
    | Item
    | undefined;
  /** 反馈值 */
  value: number;
  /** 时间 */
  timestamp: string;
  /** 备注 */
  comment: string;
}

/** Gorse 推荐配置查询条件 */
export interface GetConfigRequest {
}

/** Gorse 推荐配置保存条件 */
export interface SaveConfigRequest {
  /** Gorse 推荐配置 */
  config: ConfigResponse | undefined;
}

/** Gorse 推荐配置重置条件 */
export interface ResetConfigRequest {
}

/** Gorse 推荐配置响应 */
export interface ConfigResponse {
  /** 数据库配置 */
  database:
    | ConfigResponse_Database
    | undefined;
  /** 主节点配置 */
  master:
    | ConfigResponse_Master
    | undefined;
  /** 服务配置 */
  server:
    | ConfigResponse_Server
    | undefined;
  /** 推荐配置 */
  recommend:
    | ConfigResponse_Recommend
    | undefined;
  /** Blob存储配置 */
  blob:
    | ConfigResponse_Blob
    | undefined;
  /** 链路追踪配置 */
  tracing:
    | ConfigResponse_Tracing
    | undefined;
  /** OIDC认证配置 */
  oidc:
    | ConfigResponse_Oidc
    | undefined;
  /** OpenAI配置 */
  openai: ConfigResponse_Openai | undefined;
}

/** Gorse 推荐数据库配置 */
export interface ConfigResponse_Database {
  /** 数据存储数据库 */
  data_store: string;
  /** 缓存存储数据库 */
  cache_store: string;
  /** 数据库表名前缀 */
  table_prefix: string;
  /** 缓存表名前缀 */
  cache_table_prefix: string;
  /** 数据表名前缀 */
  data_table_prefix: string;
  /** MySQL配置 */
  mysql:
    | ConfigResponse_Database_Mysql
    | undefined;
  /** PostgreSQL配置 */
  postgres:
    | ConfigResponse_Database_Postgres
    | undefined;
  /** Redis配置 */
  redis: ConfigResponse_Database_Redis | undefined;
}

/** MySQL配置 */
export interface ConfigResponse_Database_Mysql {
  /** 事务隔离级别 */
  isolation_level: string;
  /** 最大打开连接数 */
  max_open_conns: number;
  /** 最大空闲连接数 */
  max_idle_conns: number;
  /** 连接最长复用时间 */
  conn_max_lifetime: string;
}

/** PostgreSQL配置 */
export interface ConfigResponse_Database_Postgres {
  /** 最大打开连接数 */
  max_open_conns: number;
  /** 最大空闲连接数 */
  max_idle_conns: number;
  /** 连接最长复用时间 */
  conn_max_lifetime: string;
}

/** Redis配置 */
export interface ConfigResponse_Database_Redis {
  /** 最大搜索结果数 */
  max_search_results: number;
}

/** Gorse 推荐主节点配置 */
export interface ConfigResponse_Master {
  /** gRPC监听地址 */
  host: string;
  /** gRPC监听端口 */
  port: number;
  /** 是否启用gRPC SSL */
  ssl_mode: boolean;
  /** gRPC SSL证书颁发机构 */
  ssl_ca: string;
  /** gRPC SSL证书 */
  ssl_cert: string;
  /** gRPC SSL证书密钥 */
  ssl_key: string;
  /** HTTP监听地址 */
  http_host: string;
  /** HTTP监听端口 */
  http_port: number;
  /** HTTP CORS允许域名 */
  http_cors_domains: string[];
  /** HTTP CORS允许方法 */
  http_cors_methods: string[];
  /** 工作线程数 */
  n_jobs: number;
  /** 元数据超时时间 */
  meta_timeout: string;
  /** 仪表盘登录用户名 */
  dashboard_user_name: string;
  /** 仪表盘登录密码 */
  dashboard_password: string;
  /** 是否隐藏仪表盘敏感信息 */
  dashboard_redacted: boolean;
  /** 管理员API密钥 */
  admin_api_key: string;
}

/** Gorse 推荐服务配置 */
export interface ConfigResponse_Server {
  /** 默认返回物品数量 */
  default_n: number;
  /** RESTful API密钥 */
  api_key: string;
  /** 集群时钟误差 */
  clock_error: string;
  /** 插入反馈时自动插入新用户 */
  auto_insert_user: boolean;
  /** 插入反馈时自动插入新物品 */
  auto_insert_item: boolean;
  /** 服务端缓存过期时间 */
  cache_expire: string;
}

/** Gorse 推荐算法配置 */
export interface ConfigResponse_Recommend {
  /** 缓存元素数量 */
  cache_size: number;
  /** 推荐缓存过期时间 */
  cache_expire: string;
  /** 在线推荐上下文大小 */
  context_size: number;
  /** 活跃用户生存时间 */
  active_user_ttl: number;
  /** 数据源配置 */
  data_source:
    | ConfigResponse_Recommend_DataSource
    | undefined;
  /** 非个性化推荐器 */
  non_personalized: ConfigResponse_Recommend_NonPersonalized[];
  /** 物品相似推荐器 */
  item_to_item: ConfigResponse_Recommend_ItemToItem[];
  /** 用户相似推荐器 */
  user_to_user: ConfigResponse_Recommend_UserToUser[];
  /** 外部推荐器 */
  external: ConfigResponse_Recommend_External[];
  /** 协同过滤配置 */
  collaborative:
    | ConfigResponse_Recommend_Collaborative
    | undefined;
  /** 替换配置 */
  replacement:
    | ConfigResponse_Recommend_Replacement
    | undefined;
  /** 排序器配置 */
  ranker:
    | ConfigResponse_Recommend_Ranker
    | undefined;
  /** 回退推荐配置 */
  fallback: ConfigResponse_Recommend_Fallback | undefined;
}

/** 推荐数据源配置 */
export interface ConfigResponse_Recommend_DataSource {
  /** 正向反馈类型 */
  positive_feedback_types: string[];
  /** 已读反馈类型 */
  read_feedback_types: string[];
  /** 负反馈类型 */
  negative_feedback_types: string[];
  /** 正向反馈生存时间 */
  positive_feedback_ttl: number;
  /** 物品生存时间 */
  item_ttl: number;
}

/** 非个性化推荐器配置 */
export interface ConfigResponse_Recommend_NonPersonalized {
  /** 名称 */
  name: string;
  /** 评分函数 */
  score: string;
  /** 筛选函数 */
  filter: string;
}

/** 物品相似推荐器配置 */
export interface ConfigResponse_Recommend_ItemToItem {
  /** 名称 */
  name: string;
  /** 相似度类型 */
  type: string;
  /** 相似度字段 */
  column: string;
  /** 提示词 */
  prompt: string;
}

/** 用户相似推荐器配置 */
export interface ConfigResponse_Recommend_UserToUser {
  /** 名称 */
  name: string;
  /** 相似度类型 */
  type: string;
  /** 相似度字段 */
  column: string;
}

/** 外部推荐器配置 */
export interface ConfigResponse_Recommend_External {
  /** 名称 */
  name: string;
  /** 外部推荐脚本 */
  script: string;
}

/** 协同过滤配置 */
export interface ConfigResponse_Recommend_Collaborative {
  /** 协同过滤类型 */
  type: string;
  /** 模型训练周期 */
  fit_period: string;
  /** 模型训练轮数 */
  fit_epoch: number;
  /** 模型搜索周期 */
  optimize_period: string;
  /** 模型搜索试验次数 */
  optimize_trials: number;
  /** 早停配置 */
  early_stopping: ConfigResponse_Recommend_EarlyStopping | undefined;
}

/** 早停配置 */
export interface ConfigResponse_Recommend_EarlyStopping {
  /** 停止前等待轮数 */
  patience: number;
}

/** 推荐替换配置 */
export interface ConfigResponse_Recommend_Replacement {
  /** 是否启用已读物品替换 */
  enable_replacement: boolean;
  /** 正向反馈替换衰减 */
  positive_replacement_decay: number;
  /** 已读反馈替换衰减 */
  read_replacement_decay: number;
}

/** 排序器配置 */
export interface ConfigResponse_Recommend_Ranker {
  /** 排序器类型 */
  type: string;
  /** 不活跃用户推荐刷新周期 */
  cache_expire: string;
  /** 排序前候选推荐器 */
  recommenders: string[];
  /** 模型拟合周期 */
  fit_period: string;
  /** 模型拟合轮数 */
  fit_epoch: number;
  /** 超参数优化周期 */
  optimize_period: string;
  /** 超参数优化次数 */
  optimize_trials: number;
  /** 大语言模型重排查询模板 */
  query_template: string;
  /** 大语言模型重排文档模板 */
  document_template: string;
  /** 早停配置 */
  early_stopping:
    | ConfigResponse_Recommend_EarlyStopping
    | undefined;
  /** 重排API配置 */
  reranker_api: ConfigResponse_Recommend_Ranker_RerankerApi | undefined;
}

/** 重排 API 配置 */
export interface ConfigResponse_Recommend_Ranker_RerankerApi {
  /** 重排API密钥 */
  auth_token: string;
  /** 重排模型 */
  model: string;
  /** 重排API地址 */
  url: string;
}

/** 回退推荐配置 */
export interface ConfigResponse_Recommend_Fallback {
  /** 个性化推荐用尽时的推荐来源 */
  recommenders: string[];
}

/** Blob存储配置 */
export interface ConfigResponse_Blob {
  /** Blob URI */
  uri: string;
  /** S3配置 */
  s3:
    | ConfigResponse_Blob_S3
    | undefined;
  /** GCS配置 */
  gcs:
    | ConfigResponse_Blob_Gcs
    | undefined;
  /** Azure Blob配置 */
  azure: ConfigResponse_Blob_Azure | undefined;
}

/** S3配置 */
export interface ConfigResponse_Blob_S3 {
  /** AWS S3端点 */
  endpoint: string;
  /** 访问密钥ID */
  access_key_id: string;
  /** 秘密访问密钥 */
  secret_access_key: string;
}

/** GCS配置 */
export interface ConfigResponse_Blob_Gcs {
  /** 凭据文件路径 */
  credentials_file: string;
}

/** Azure Blob配置 */
export interface ConfigResponse_Blob_Azure {
  /** 端点 */
  endpoint: string;
  /** 账户名称 */
  account_name: string;
  /** 账户密钥 */
  account_key: string;
  /** 连接字符串 */
  connection_string: string;
}

/** 链路追踪配置 */
export interface ConfigResponse_Tracing {
  /** 是否启用REST API追踪 */
  enable_tracing: boolean;
  /** 追踪导出器类型 */
  exporter: string;
  /** 追踪收集器端点 */
  collector_endpoint: string;
  /** 追踪采样器类型 */
  sampler: string;
  /** 采样比率 */
  ratio: number;
}

/** OIDC认证配置 */
export interface ConfigResponse_Oidc {
  /** 是否启用OIDC认证 */
  enable: boolean;
  /** OAuth提供商颁发者 */
  issuer: string;
  /** OAuth应用公共标识符 */
  client_id: string;
  /** OAuth令牌访问权限 */
  client_secret: string;
  /** 认证后重定向地址 */
  redirect_url: string;
}

/** OpenAI配置 */
export interface ConfigResponse_Openai {
  /** 基础地址 */
  base_url: string;
  /** 认证令牌 */
  auth_token: string;
  /** 对话模型 */
  chat_completion_model: string;
  /** 对话每分钟请求数 */
  chat_completion_rpm: number;
  /** 对话每分钟Token数 */
  chat_completion_tpm: number;
  /** Embedding模型 */
  embedding_model: string;
  /** Embedding维度 */
  embedding_dimensions: number;
  /** Embedding每分钟请求数 */
  embedding_rpm: number;
  /** Embedding每分钟Token数 */
  embedding_tpm: number;
  /** 日志文件 */
  log_file: string;
}

/** Admin Gorse 推荐服务 */
export interface RecommendGorseService {
  /** 查询 Gorse 推荐时间序列 */
  GetTimeSeries(request: GetTimeSeriesRequest): Promise<TimeSeriesResponse>;
  /** 查询 Gorse 推荐分类 */
  OptionCategories(request: OptionCategoriesRequest): Promise<OptionCategoriesResponse>;
  /** 查询 Gorse 推荐仪表盘推荐商品 */
  ListDashboardItems(request: ListDashboardItemsRequest): Promise<ListDashboardItemsResponse>;
  /** 查询 Gorse 推荐任务状态 */
  ListTasks(request: ListTasksRequest): Promise<ListTasksResponse>;
  /** 查询 Gorse 推荐用户列表 */
  PageUsers(request: PageUsersRequest): Promise<PageUsersResponse>;
  /** 查询 Gorse 推荐用户 */
  GetUser(request: GetUserRequest): Promise<UserResponse>;
  /** 删除 Gorse 推荐用户 */
  DeleteUser(request: DeleteUserRequest): Promise<Empty>;
  /** 查询 Gorse 推荐相似用户 */
  GetUserSimilar(request: GetUserSimilarRequest): Promise<UserSimilarResponse>;
  /** 查询 Gorse 推荐用户反馈 */
  GetUserFeedback(request: GetUserFeedbackRequest): Promise<FeedbackResponse>;
  /** 查询 Gorse 推荐用户推荐结果 */
  GetUserRecommend(request: GetUserRecommendRequest): Promise<ItemListResponse>;
  /** 查询 Gorse 推荐商品列表 */
  PageItems(request: PageItemsRequest): Promise<PageItemsResponse>;
  /** 查询 Gorse 推荐商品 */
  GetItem(request: GetItemRequest): Promise<Item>;
  /** 删除 Gorse 推荐商品 */
  DeleteItem(request: DeleteItemRequest): Promise<Empty>;
  /** 查询 Gorse 推荐相似商品 */
  GetItemSimilar(request: GetItemSimilarRequest): Promise<ItemListResponse>;
  /** 导出 Gorse 推荐数据 */
  ExportData(request: ExportDataRequest): Promise<ExportDataResponse>;
  /** 导入 Gorse 推荐数据 */
  ImportData(request: ImportDataRequest): Promise<ImportDataResponse>;
  /** 查询 Gorse 推荐配置 */
  GetConfig(request: GetConfigRequest): Promise<ConfigResponse>;
  /** 保存 Gorse 推荐配置 */
  SaveConfig(request: SaveConfigRequest): Promise<ConfigResponse>;
  /** 重置 Gorse 推荐配置 */
  ResetConfig(request: ResetConfigRequest): Promise<Empty>;
  /** 预览 Gorse 推荐外部推荐脚本 */
  PreviewExternal(request: PreviewExternalRequest): Promise<PreviewExternalResponse>;
  /** 预览 Gorse 推荐排序提示词 */
  PreviewRankerPrompt(request: PreviewRankerPromptRequest): Promise<PreviewRankerPromptResponse>;
}
