// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/v1/user_analytics.proto

/* eslint-disable */
import type { AnalyticsRankResponse, AnalyticsTimeType, AnalyticsTrendResponse } from "../../common/v1/analytics";

/** 用户摘要指标查询条件 */
export interface SummaryUserAnalyticsRequest {
  /** 时间类型 */
  time_type: AnalyticsTimeType;
}

/** 用户趋势查询条件 */
export interface TrendUserAnalyticsRequest {
  /** 时间类型 */
  time_type: AnalyticsTimeType;
}

/** 用户行为覆盖排行查询条件 */
export interface RankUserAnalyticsRequest {
  /** 时间类型 */
  time_type: AnalyticsTimeType;
}

/** 用户分析汇总响应 */
export interface SummaryUserAnalyticsResponse {
  /** 新增用户数 */
  new_user_count: number;
  /** 新增用户增长率 */
  new_user_growth_rate: number;
  /** 下单用户数 */
  order_user_count: number;
  /** 下单转化率 */
  order_user_conversion_rate: number;
  /** 活跃用户数 */
  active_user_count: number;
  /** 活跃覆盖率 */
  active_user_coverage_rate: number;
}

/** Admin用户分析服务 */
export interface UserAnalyticsService {
  /** 查询用户摘要指标 */
  SummaryUserAnalytics(request: SummaryUserAnalyticsRequest): Promise<SummaryUserAnalyticsResponse>;
  /** 查询用户趋势 */
  TrendUserAnalytics(request: TrendUserAnalyticsRequest): Promise<AnalyticsTrendResponse>;
  /** 查询用户行为覆盖排行 */
  RankUserAnalytics(request: RankUserAnalyticsRequest): Promise<AnalyticsRankResponse>;
}
