// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: base/login.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"shop/api/gen/go/base"
)

const _ = grpc.SupportPackageIsVersion7

// LoginService Base登录公共服务。
type LoginService struct {
	base.UnimplementedLoginServiceServer
	*core.ShopCore
}

// NewLoginService 创建Base登录公共服务。
func NewLoginService(sc *core.ShopCore) *LoginService {
	var ss = LoginService{
		ShopCore: sc,
	}
	return &ss
}

// Captcha 验证码。
func (s *LoginService) Captcha(ctx context.Context, req *emptypb.Empty) (*base.CaptchaResponse, error) {
	var reply = &base.CaptchaResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method Captcha not implemented")
	return reply, err
}

// Logout 登出。
func (s *LoginService) Logout(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method Logout not implemented")
	return reply, err
}

// RefreshToken 刷新认证令牌。
func (s *LoginService) RefreshToken(ctx context.Context, req *base.RefreshTokenRequest) (*base.RefreshTokenResponse, error) {
	var reply = &base.RefreshTokenResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
	return reply, err
}

// Login 登录。
func (s *LoginService) Login(ctx context.Context, req *base.LoginRequest) (*base.LoginResponse, error) {
	var reply = &base.LoginResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method Login not implemented")
	return reply, err
}
