// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_user.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
)

const _ = grpc.SupportPackageIsVersion7

// BaseUserService Admin用户管理服务。
type BaseUserService struct {
	admin.UnimplementedBaseUserServiceServer
	*core.ShopCore
}

// NewBaseUserService 创建Admin用户管理服务。
func NewBaseUserService(sc *core.ShopCore) *BaseUserService {
	var ss = BaseUserService{
		ShopCore: sc,
	}
	return &ss
}

// OptionBaseUser 查询用户下拉选择。
func (s *BaseUserService) OptionBaseUser(ctx context.Context, req *admin.OptionBaseUserRequest) (*common.SelectOptionResponse, error) {
	var reply = &common.SelectOptionResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method OptionBaseUser not implemented")
	return reply, err
}

// PageBaseUser 查询用户分页列表。
func (s *BaseUserService) PageBaseUser(ctx context.Context, req *admin.PageBaseUserRequest) (*admin.PageBaseUserResponse, error) {
	var reply = &admin.PageBaseUserResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PageBaseUser not implemented")
	return reply, err
}

// GetBaseUser 查询用户。
func (s *BaseUserService) GetBaseUser(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseUserForm, error) {
	var reply = &admin.BaseUserForm{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetBaseUser not implemented")
	return reply, err
}

// CreateBaseUser 创建用户。
func (s *BaseUserService) CreateBaseUser(ctx context.Context, req *admin.BaseUserForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CreateBaseUser not implemented")
	return reply, err
}

// UpdateBaseUser 更新用户。
func (s *BaseUserService) UpdateBaseUser(ctx context.Context, req *admin.BaseUserForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method UpdateBaseUser not implemented")
	return reply, err
}

// DeleteBaseUser 删除用户。
func (s *BaseUserService) DeleteBaseUser(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method DeleteBaseUser not implemented")
	return reply, err
}

// SetBaseUserStatus 设置状态。
func (s *BaseUserService) SetBaseUserStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method SetBaseUserStatus not implemented")
	return reply, err
}

// ResetBaseUserPwd 重置密码。
func (s *BaseUserService) ResetBaseUserPwd(ctx context.Context, req *admin.ResetBaseUserPwdRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method ResetBaseUserPwd not implemented")
	return reply, err
}
