// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_log.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/wrapperspb"
	"shop/api/gen/go/admin"
)

const _ = grpc.SupportPackageIsVersion7

// BaseLogService Admin日志服务。
type BaseLogService struct {
	admin.UnimplementedBaseLogServiceServer
	*core.ShopCore
}

// NewBaseLogService 创建Admin日志服务。
func NewBaseLogService(sc *core.ShopCore) *BaseLogService {
	var ss = BaseLogService{
		ShopCore: sc,
	}
	return &ss
}

// PageBaseLog 查询日志分页列表。
func (s *BaseLogService) PageBaseLog(ctx context.Context, req *admin.PageBaseLogRequest) (*admin.PageBaseLogResponse, error) {
	var reply = &admin.PageBaseLogResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PageBaseLog not implemented")
	return reply, err
}

// GetBaseLog 查询日志。
func (s *BaseLogService) GetBaseLog(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseLog, error) {
	var reply = &admin.BaseLog{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetBaseLog not implemented")
	return reply, err
}
