// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_config.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
)

const _ = grpc.SupportPackageIsVersion7

// BaseConfigService Admin系统配置服务。
type BaseConfigService struct {
	admin.UnimplementedBaseConfigServiceServer
	*core.ShopCore
}

// NewBaseConfigService 创建Admin系统配置服务。
func NewBaseConfigService(sc *core.ShopCore) *BaseConfigService {
	var ss = BaseConfigService{
		ShopCore: sc,
	}
	return &ss
}

// RefreshBaseConfig 刷新缓存。
func (s *BaseConfigService) RefreshBaseConfig(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method RefreshBaseConfig not implemented")
	return reply, err
}

// PageBaseConfig 查询系统配置分页列表。
func (s *BaseConfigService) PageBaseConfig(ctx context.Context, req *admin.PageBaseConfigRequest) (*admin.PageBaseConfigResponse, error) {
	var reply = &admin.PageBaseConfigResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PageBaseConfig not implemented")
	return reply, err
}

// GetBaseConfig 查询系统配置。
func (s *BaseConfigService) GetBaseConfig(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseConfigForm, error) {
	var reply = &admin.BaseConfigForm{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetBaseConfig not implemented")
	return reply, err
}

// CreateBaseConfig 创建系统配置。
func (s *BaseConfigService) CreateBaseConfig(ctx context.Context, req *admin.BaseConfigForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CreateBaseConfig not implemented")
	return reply, err
}

// UpdateBaseConfig 更新系统配置。
func (s *BaseConfigService) UpdateBaseConfig(ctx context.Context, req *admin.BaseConfigForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method UpdateBaseConfig not implemented")
	return reply, err
}

// DeleteBaseConfig 删除系统配置。
func (s *BaseConfigService) DeleteBaseConfig(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method DeleteBaseConfig not implemented")
	return reply, err
}

// SetBaseConfigStatus 设置状态。
func (s *BaseConfigService) SetBaseConfigStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method SetBaseConfigStatus not implemented")
	return reply, err
}
