// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_dict.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
)

const _ = grpc.SupportPackageIsVersion7

// BaseDictService Admin字典服务。
type BaseDictService struct {
	admin.UnimplementedBaseDictServiceServer
	*core.ShopCore
}

// NewBaseDictService 创建Admin字典服务。
func NewBaseDictService(sc *core.ShopCore) *BaseDictService {
	var ss = BaseDictService{
		ShopCore: sc,
	}
	return &ss
}

// ListBaseDict 查询字典列表。
func (s *BaseDictService) ListBaseDict(ctx context.Context, req *emptypb.Empty) (*admin.ListBaseDictResponse, error) {
	var reply = &admin.ListBaseDictResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method ListBaseDict not implemented")
	return reply, err
}

// PageBaseDict 查询字典分页列表。
func (s *BaseDictService) PageBaseDict(ctx context.Context, req *admin.PageBaseDictRequest) (*admin.PageBaseDictResponse, error) {
	var reply = &admin.PageBaseDictResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PageBaseDict not implemented")
	return reply, err
}

// GetBaseDict 查询字典。
func (s *BaseDictService) GetBaseDict(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseDictForm, error) {
	var reply = &admin.BaseDictForm{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetBaseDict not implemented")
	return reply, err
}

// CreateBaseDict 创建字典。
func (s *BaseDictService) CreateBaseDict(ctx context.Context, req *admin.BaseDictForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CreateBaseDict not implemented")
	return reply, err
}

// UpdateBaseDict 更新字典。
func (s *BaseDictService) UpdateBaseDict(ctx context.Context, req *admin.BaseDictForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method UpdateBaseDict not implemented")
	return reply, err
}

// DeleteBaseDict 删除字典。
func (s *BaseDictService) DeleteBaseDict(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method DeleteBaseDict not implemented")
	return reply, err
}

// SetBaseDictStatus 设置状态。
func (s *BaseDictService) SetBaseDictStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method SetBaseDictStatus not implemented")
	return reply, err
}

// PageBaseDictItem 查询字典属性分页列表。
func (s *BaseDictService) PageBaseDictItem(ctx context.Context, req *admin.PageBaseDictItemRequest) (*admin.PageBaseDictItemResponse, error) {
	var reply = &admin.PageBaseDictItemResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PageBaseDictItem not implemented")
	return reply, err
}

// GetBaseDictItem 查询字典属性。
func (s *BaseDictService) GetBaseDictItem(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseDictItemForm, error) {
	var reply = &admin.BaseDictItemForm{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetBaseDictItem not implemented")
	return reply, err
}

// CreateBaseDictItem 创建字典属性。
func (s *BaseDictService) CreateBaseDictItem(ctx context.Context, req *admin.BaseDictItemForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CreateBaseDictItem not implemented")
	return reply, err
}

// UpdateBaseDictItem 更新字典属性。
func (s *BaseDictService) UpdateBaseDictItem(ctx context.Context, req *admin.BaseDictItemForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method UpdateBaseDictItem not implemented")
	return reply, err
}

// DeleteBaseDictItem 删除字典属性。
func (s *BaseDictService) DeleteBaseDictItem(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method DeleteBaseDictItem not implemented")
	return reply, err
}

// SetBaseDictItemStatus 设置状态。
func (s *BaseDictService) SetBaseDictItemStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method SetBaseDictItemStatus not implemented")
	return reply, err
}
