// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_role.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
)

const _ = grpc.SupportPackageIsVersion7

// BaseRoleService Admin角色管理服务。
type BaseRoleService struct {
	admin.UnimplementedBaseRoleServiceServer
	*core.ShopCore
}

// NewBaseRoleService 创建Admin角色管理服务。
func NewBaseRoleService(sc *core.ShopCore) *BaseRoleService {
	var ss = BaseRoleService{
		ShopCore: sc,
	}
	return &ss
}

// OptionBaseRole 查询角色下拉选择。
func (s *BaseRoleService) OptionBaseRole(ctx context.Context, req *emptypb.Empty) (*common.SelectOptionResponse, error) {
	var reply = &common.SelectOptionResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method OptionBaseRole not implemented")
	return reply, err
}

// PageBaseRole 查询角色分页列表。
func (s *BaseRoleService) PageBaseRole(ctx context.Context, req *admin.PageBaseRoleRequest) (*admin.PageBaseRoleResponse, error) {
	var reply = &admin.PageBaseRoleResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PageBaseRole not implemented")
	return reply, err
}

// GetBaseRole 查询角色。
func (s *BaseRoleService) GetBaseRole(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseRoleForm, error) {
	var reply = &admin.BaseRoleForm{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetBaseRole not implemented")
	return reply, err
}

// CreateBaseRole 创建角色。
func (s *BaseRoleService) CreateBaseRole(ctx context.Context, req *admin.BaseRoleForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CreateBaseRole not implemented")
	return reply, err
}

// UpdateBaseRole 更新角色。
func (s *BaseRoleService) UpdateBaseRole(ctx context.Context, req *admin.BaseRoleForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method UpdateBaseRole not implemented")
	return reply, err
}

// DeleteBaseRole 删除角色。
func (s *BaseRoleService) DeleteBaseRole(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method DeleteBaseRole not implemented")
	return reply, err
}

// SetBaseRoleStatus 设置状态。
func (s *BaseRoleService) SetBaseRoleStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method SetBaseRoleStatus not implemented")
	return reply, err
}

// SetBaseRoleMenus 设置角色菜单权限。
func (s *BaseRoleService) SetBaseRoleMenus(ctx context.Context, req *admin.SetMenusRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method SetBaseRoleMenus not implemented")
	return reply, err
}
