// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/base_dept.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
)

const _ = grpc.SupportPackageIsVersion7

// BaseDeptService Admin部门服务。
type BaseDeptService struct {
	admin.UnimplementedBaseDeptServiceServer
	*core.ShopCore
}

// NewBaseDeptService 创建Admin部门服务。
func NewBaseDeptService(sc *core.ShopCore) *BaseDeptService {
	var ss = BaseDeptService{
		ShopCore: sc,
	}
	return &ss
}

// TreeBaseDept 查询部门树形列表。
func (s *BaseDeptService) TreeBaseDept(ctx context.Context, req *emptypb.Empty) (*admin.TreeBaseDeptResponse, error) {
	var reply = &admin.TreeBaseDeptResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method TreeBaseDept not implemented")
	return reply, err
}

// OptionBaseDept 查询部门树形选择。
func (s *BaseDeptService) OptionBaseDept(ctx context.Context, req *admin.OptionBaseDeptRequest) (*common.TreeOptionResponse, error) {
	var reply = &common.TreeOptionResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method OptionBaseDept not implemented")
	return reply, err
}

// GetBaseDept 查询部门。
func (s *BaseDeptService) GetBaseDept(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseDeptForm, error) {
	var reply = &admin.BaseDeptForm{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetBaseDept not implemented")
	return reply, err
}

// CreateBaseDept 创建部门。
func (s *BaseDeptService) CreateBaseDept(ctx context.Context, req *admin.BaseDeptForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CreateBaseDept not implemented")
	return reply, err
}

// UpdateBaseDept 更新部门。
func (s *BaseDeptService) UpdateBaseDept(ctx context.Context, req *admin.BaseDeptForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method UpdateBaseDept not implemented")
	return reply, err
}

// DeleteBaseDept 删除部门。
func (s *BaseDeptService) DeleteBaseDept(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method DeleteBaseDept not implemented")
	return reply, err
}

// SetBaseDeptStatus 设置状态。
func (s *BaseDeptService) SetBaseDeptStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method SetBaseDeptStatus not implemented")
	return reply, err
}
