// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/goods_spec.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"shop/api/gen/go/admin"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsSpecService Admin商品规格服务。
type GoodsSpecService struct {
	admin.UnimplementedGoodsSpecServiceServer
	*core.ShopCore
}

// NewGoodsSpecService 创建Admin商品规格服务。
func NewGoodsSpecService(sc *core.ShopCore) *GoodsSpecService {
	var ss = GoodsSpecService{
		ShopCore: sc,
	}
	return &ss
}

// ListGoodsSpec 查询商品规格列表。
func (s *GoodsSpecService) ListGoodsSpec(ctx context.Context, req *admin.ListGoodsSpecRequest) (*admin.ListGoodsSpecResponse, error) {
	var reply = &admin.ListGoodsSpecResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method ListGoodsSpec not implemented")
	return reply, err
}
