// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/goods.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsService Admin商品服务。
type GoodsService struct {
	admin.UnimplementedGoodsServiceServer
	*core.ShopCore
}

// NewGoodsService 创建Admin商品服务。
func NewGoodsService(sc *core.ShopCore) *GoodsService {
	var ss = GoodsService{
		ShopCore: sc,
	}
	return &ss
}

// ListGoods 查询商品列表。
func (s *GoodsService) ListGoods(ctx context.Context, req *admin.ListGoodsRequest) (*admin.ListGoodsResponse, error) {
	var reply = &admin.ListGoodsResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method ListGoods not implemented")
	return reply, err
}

// PageGoods 查询商品分页列表。
func (s *GoodsService) PageGoods(ctx context.Context, req *admin.PageGoodsRequest) (*admin.PageGoodsResponse, error) {
	var reply = &admin.PageGoodsResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PageGoods not implemented")
	return reply, err
}

// GetGoods 查询商品。
func (s *GoodsService) GetGoods(ctx context.Context, req *wrapperspb.Int64Value) (*admin.GoodsForm, error) {
	var reply = &admin.GoodsForm{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetGoods not implemented")
	return reply, err
}

// CreateGoods 创建商品。
func (s *GoodsService) CreateGoods(ctx context.Context, req *admin.GoodsForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CreateGoods not implemented")
	return reply, err
}

// UpdateGoods 更新商品。
func (s *GoodsService) UpdateGoods(ctx context.Context, req *admin.GoodsForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method UpdateGoods not implemented")
	return reply, err
}

// DeleteGoods 删除商品。
func (s *GoodsService) DeleteGoods(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method DeleteGoods not implemented")
	return reply, err
}

// SetGoodsStatus 设置状态。
func (s *GoodsService) SetGoodsStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method SetGoodsStatus not implemented")
	return reply, err
}
