// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/goods_prop.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
	"shop/api/gen/go/admin"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsPropService Admin商品属性服务。
type GoodsPropService struct {
	admin.UnimplementedGoodsPropServiceServer
	*core.ShopCore
}

// NewGoodsPropService 创建Admin商品属性服务。
func NewGoodsPropService(sc *core.ShopCore) *GoodsPropService {
	var ss = GoodsPropService{
		ShopCore: sc,
	}
	return &ss
}

// PageGoodsProp 查询商品属性分页列表。
func (s *GoodsPropService) PageGoodsProp(ctx context.Context, req *admin.PageGoodsPropRequest) (*admin.PageGoodsPropResponse, error) {
	var reply = &admin.PageGoodsPropResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PageGoodsProp not implemented")
	return reply, err
}

// GetGoodsProp 查询商品属性。
func (s *GoodsPropService) GetGoodsProp(ctx context.Context, req *wrapperspb.Int64Value) (*admin.GoodsProp, error) {
	var reply = &admin.GoodsProp{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetGoodsProp not implemented")
	return reply, err
}

// CreateGoodsProp 创建商品属性。
func (s *GoodsPropService) CreateGoodsProp(ctx context.Context, req *admin.GoodsProp) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CreateGoodsProp not implemented")
	return reply, err
}

// UpdateGoodsProp 更新商品属性。
func (s *GoodsPropService) UpdateGoodsProp(ctx context.Context, req *admin.GoodsProp) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method UpdateGoodsProp not implemented")
	return reply, err
}

// DeleteGoodsProp 删除商品属性。
func (s *GoodsPropService) DeleteGoodsProp(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method DeleteGoodsProp not implemented")
	return reply, err
}
