// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/pay_bill.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"shop/api/gen/go/admin"
)

const _ = grpc.SupportPackageIsVersion7

// PayBillService Admin支付账单服务。
type PayBillService struct {
	admin.UnimplementedPayBillServiceServer
	*core.ShopCore
}

// NewPayBillService 创建Admin支付账单服务。
func NewPayBillService(sc *core.ShopCore) *PayBillService {
	var ss = PayBillService{
		ShopCore: sc,
	}
	return &ss
}

// PagePayBill 查询支付账单分页列表。
func (s *PayBillService) PagePayBill(ctx context.Context, req *admin.PagePayBillRequest) (*admin.PagePayBillResponse, error) {
	var reply = &admin.PagePayBillResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PagePayBill not implemented")
	return reply, err
}
