// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/shop_hot.proto

package service

import (
	"context"
	"github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
	"shop/api/gen/go/admin"
	"shop/api/gen/go/common"
)

const _ = grpc.SupportPackageIsVersion7

// ShopHotService Admin商城热门推荐服务。
type ShopHotService struct {
	admin.UnimplementedShopHotServiceServer
	*core.ShopCore
}

// NewShopHotService 创建Admin商城热门推荐服务。
func NewShopHotService(sc *core.ShopCore) *ShopHotService {
	var ss = ShopHotService{
		ShopCore: sc,
	}
	return &ss
}

// PageShopHot 查询商城热门推荐分页列表。
func (s *ShopHotService) PageShopHot(ctx context.Context, req *admin.PageShopHotRequest) (*admin.PageShopHotResponse, error) {
	var reply = &admin.PageShopHotResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PageShopHot not implemented")
	return reply, err
}

// GetShopHot 查询商城热门推荐。
func (s *ShopHotService) GetShopHot(ctx context.Context, req *wrapperspb.Int64Value) (*admin.ShopHotForm, error) {
	var reply = &admin.ShopHotForm{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetShopHot not implemented")
	return reply, err
}

// CreateShopHot 创建商城热门推荐。
func (s *ShopHotService) CreateShopHot(ctx context.Context, req *admin.ShopHotForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CreateShopHot not implemented")
	return reply, err
}

// UpdateShopHot 更新商城热门推荐。
func (s *ShopHotService) UpdateShopHot(ctx context.Context, req *admin.ShopHotForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method UpdateShopHot not implemented")
	return reply, err
}

// DeleteShopHot 删除商城热门推荐。
func (s *ShopHotService) DeleteShopHot(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method DeleteShopHot not implemented")
	return reply, err
}

// SetShopHotStatus 设置状态。
func (s *ShopHotService) SetShopHotStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method SetShopHotStatus not implemented")
	return reply, err
}

// PageShopHotItem 查询商城热门推荐属性分页列表。
func (s *ShopHotService) PageShopHotItem(ctx context.Context, req *admin.PageShopHotItemRequest) (*admin.PageShopHotItemResponse, error) {
	var reply = &admin.PageShopHotItemResponse{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method PageShopHotItem not implemented")
	return reply, err
}

// GetShopHotItem 查询商城热门推荐属性。
func (s *ShopHotService) GetShopHotItem(ctx context.Context, req *wrapperspb.Int64Value) (*admin.ShopHotItemForm, error) {
	var reply = &admin.ShopHotItemForm{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method GetShopHotItem not implemented")
	return reply, err
}

// CreateShopHotItem 创建商城热门推荐属性。
func (s *ShopHotService) CreateShopHotItem(ctx context.Context, req *admin.ShopHotItemForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method CreateShopHotItem not implemented")
	return reply, err
}

// UpdateShopHotItem 更新商城热门推荐属性。
func (s *ShopHotService) UpdateShopHotItem(ctx context.Context, req *admin.ShopHotItemForm) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method UpdateShopHotItem not implemented")
	return reply, err
}

// DeleteShopHotItem 删除商城热门推荐属性。
func (s *ShopHotService) DeleteShopHotItem(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method DeleteShopHotItem not implemented")
	return reply, err
}

// SetShopHotItemStatus 设置状态。
func (s *ShopHotService) SetShopHotItemStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	var reply = &emptypb.Empty{}
	var err error
	// TODO: 在此补充具体业务逻辑。
	err = status.Errorf(codes.Unimplemented, "method SetShopHotItemStatus not implemented")
	return reply, err
}
