// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: config/v1/shop_config.proto

/* eslint-disable */

/** 商城配置 */
export interface ShopConfigWrapper {
  /** 商城配置 */
  shop: ShopConfig | undefined;
}

/** 商城业务配置。 */
export interface ShopConfig {
  /** 小程序登录参数 */
  wx_mini_app:
    | WxMiniApp
    | undefined;
  /** 微信支付参数 */
  wx_pay:
    | WxPay
    | undefined;
  /** 推荐配置 */
  recommend:
    | Recommend
    | undefined;
  /** 提示词配置 */
  prompt: Prompt | undefined;
}

/** 微信小程序配置。 */
export interface WxMiniApp {
  /** 小程序 AppID */
  appid: string;
  /** 小程序密钥 */
  secret: string;
}

/** 微信支付配置。 */
export interface WxPay {
  /** 微信支付 AppID */
  appid: string;
  /** 商户id */
  mch_id: string;
  /** 通知地址 */
  notify_url: string;
  /** 商户证书序列号 */
  mch_cert_sn: string;
  /** 商户证书路径 */
  mch_cert_path: string;
  /** api 密钥 */
  mch_api_v3_key: string;
}

/** 推荐服务配置。 */
export interface Recommend {
  /** 请求地址 */
  entry_point: string;
  /** api 密钥 */
  api_key: string;
}

/** Prompt 提示词 */
export interface Prompt {
  /** AI评论提示词 */
  comment_review: string;
  /** AI汇总提示词 */
  comment_ai: string;
}
