// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: admin/analytics.proto

/* eslint-disable */

/** 时间类型 */
export enum AnalyticsTimeType {
  /** DAY - 日 */
  DAY = 0,
  /** WEEK - 周 */
  WEEK = 1,
  /** MONTH - 月 */
  MONTH = 2,
}

/** 汇总数据请求参数 */
export interface AnalyticsCountRequest {
  /** 时间类型 */
  timeType: AnalyticsTimeType;
}

/** 汇总数据返回结果 */
export interface AnalyticsCountResponse {
  /** 新增数量 */
  newNum: number;
  /** 总数量 */
  totalNum: number;
}

/** 订单销量（柱状图）请求参数 */
export interface AnalyticsBarOrderRequest {
  /** 时间类型 */
  timeType: AnalyticsTimeType;
}

/** 商品销量（柱状图）请求参数 */
export interface AnalyticsBarGoodsRequest {
  /** 时间类型 */
  timeType: AnalyticsTimeType;
  /** top */
  top: number;
}

/** 商品分类（饼状图）请求参数 */
export interface AnalyticsPieGoodsRequest {
  /** 时间类型 */
  timeType: AnalyticsTimeType;
}

/** 商品订单销量状态（雷达图）请求参数 */
export interface AnalyticsRadarOrderRequest {
  /** 时间类型 */
  timeType: AnalyticsTimeType;
}

/** （柱状图）请求参数 */
export interface AnalyticsBarResponse {
  /** 图例的数据数组 */
  axisData: string[];
  /** 数据内容数组 */
  seriesData: AnalyticsBarResponse_SeriesData[];
}

export interface AnalyticsBarResponse_SeriesData {
  /** 数量 */
  value: number[];
}

/** （饼状图）返回结果 */
export interface AnalyticsPieResponse {
  /** 数据内容数组 */
  seriesData: AnalyticsPieResponse_SeriesData[];
}

export interface AnalyticsPieResponse_SeriesData {
  /** 数值 */
  value: number;
  /** 系列名称 */
  name: string;
}

/** （雷达图）返回结果 */
export interface AnalyticsRadarResponse {
  /** 图例的数据数组 */
  legendData: string[];
  /** 指示器 */
  radarIndicator: AnalyticsRadarResponse_RadarIndicator[];
  /** 数据 */
  seriesData: AnalyticsRadarResponse_SeriesData[];
}

export interface AnalyticsRadarResponse_RadarIndicator {
  /** 指示器名称 */
  name: string;
}

export interface AnalyticsRadarResponse_SeriesData {
  /** 数据项名称 */
  name: string;
  /** 单个数据项的数值 */
  value: number[];
}

/** Admin 数据分析服务 */
export interface AnalyticsService {
  /** 查询汇总数据（用户） */
  AnalyticsCountUser(request: AnalyticsCountRequest): Promise<AnalyticsCountResponse>;
  /** 查询汇总数据（商品） */
  AnalyticsCountGoods(request: AnalyticsCountRequest): Promise<AnalyticsCountResponse>;
  /** 查询汇总数据（订单） */
  AnalyticsCountOrder(request: AnalyticsCountRequest): Promise<AnalyticsCountResponse>;
  /** 查询汇总数据（销量） */
  AnalyticsCountSale(request: AnalyticsCountRequest): Promise<AnalyticsCountResponse>;
  /** 查询订单销量（柱状图） */
  AnalyticsBarOrder(request: AnalyticsBarOrderRequest): Promise<AnalyticsBarResponse>;
  /** 查询商品销量（柱状图） */
  AnalyticsBarGoods(request: AnalyticsBarGoodsRequest): Promise<AnalyticsBarResponse>;
  /** 查询商品分类（饼状图） */
  AnalyticsPieGoods(request: AnalyticsPieGoodsRequest): Promise<AnalyticsPieResponse>;
  /** 查询商品订单销量状态（雷达图） */
  AnalyticsRadarOrder(request: AnalyticsRadarOrderRequest): Promise<AnalyticsRadarResponse>;
}
