// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: app/auth.proto

/* eslint-disable */
import type { Empty } from "../google/protobuf/empty";

export interface UserInfo {
  /** 用户账号 */
  userName: string;
  /** 用户昵称 */
  nickName: string;
  /** 性别 */
  gender: number;
  /** 手机号 */
  phone: string;
  /** 头像 */
  avatar: string;
}

/** 微信后台登录 - 请求 */
export interface WxLoginRequest {
  /** 用户登录凭据 */
  code: string;
}

/** 微信后台登录 - 回应 */
export interface WxLoginResponse {
  /** 访问令牌，必选项。 */
  accessToken: string;
  /** 更新令牌，用来获取下一次的访问令牌，可选项。 */
  refreshToken: string;
  /** 令牌类型，该值大小写不敏感，必选项，可以是bearer类型或mac类型。 */
  tokenType: string;
  /** 令牌有效时间，单位为秒。如果访问令牌过期，服务器应回复授予访问令牌的持续时间。如果省略该参数，必须其他方式设置过期时间。 */
  expiresIn: number;
}

export interface UpdateUserInfoRequest {
  /** 昵称 */
  nickName: string;
  /** 头像URL */
  avatar: string;
  /** 性别 */
  gender: number;
}

export interface PhoneAuthRequest {
  /** 授权信息 */
  code: string;
}

export interface PhoneAuthResponse {
  /** 手机号 */
  phone: string;
}

/** App用户登录认证服务 */
export interface AuthService {
  /** 微信登录 */
  WxLogin(request: WxLoginRequest): Promise<WxLoginResponse>;
  /** 获取已经登录的用户的数据 */
  GetUserInfo(request: Empty): Promise<UserInfo>;
  /** 修改个人中心用户信息 */
  UpdateUserInfo(request: UpdateUserInfoRequest): Promise<Empty>;
  /** 手机号授权 */
  PhoneAuth(request: PhoneAuthRequest): Promise<PhoneAuthResponse>;
}
