// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: app/base_dict.proto

/* eslint-disable */
import type { StringValue } from "../google/protobuf/wrappers";

/** 字典表单 */
export interface BaseDictForm {
  /** 字典编号 */
  code: string;
  /** 字典名称 */
  name: string;
  /** 字典属性 */
  items: BaseDictForm_DictItem[];
}

/** 字典项 */
export interface BaseDictForm_DictItem {
  /** 字典值 */
  value: string;
  /** 字典项标签 */
  label: string;
}

/** App字典服务 */
export interface BaseDictService {
  /** 查询字典 */
  GetBaseDict(request: StringValue): Promise<BaseDictForm>;
}
