// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: app/recommend.proto

/* eslint-disable */
import type { Empty } from "../google/protobuf/empty";
import type { GoodsInfo } from "./goods_info";

export enum RecommendScene {
  RECOMMEND_SCENE_UNKNOWN = 0,
  HOME = 1,
  CART = 2,
  PROFILE = 3,
  ORDER_DETAIL = 4,
  ORDER_PAID = 5,
}

export interface RecommendGoodsRequest {
  scene: RecommendScene;
  orderId: number;
  cartGoodsIds: number[];
  pageNum: number;
  pageSize: number;
}

export interface RecommendGoodsResponse {
  list: GoodsInfo[];
  total: number;
  requestId: string;
}

export interface RecommendExposureRequest {
  requestId: string;
  scene: RecommendScene;
  goodsIds: number[];
}

/** App推荐服务 */
export interface RecommendService {
  /** 查询推荐商品列表 */
  RecommendGoods(request: RecommendGoodsRequest): Promise<RecommendGoodsResponse>;
  /** 记录推荐曝光 */
  RecommendExposure(request: RecommendExposureRequest): Promise<Empty>;
}
