// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/liujitcn/kratos-kit/bootstrap"
	"github.com/liujitcn/kratos-kit/cache"
	"github.com/liujitcn/kratos-kit/database/gorm"
	"github.com/liujitcn/kratos-kit/oss"
	"github.com/liujitcn/kratos-kit/pprof"
	"github.com/liujitcn/kratos-kit/queue"
	"shop/pkg/biz"
	"shop/pkg/configs"
	"shop/pkg/gen/data"
	"shop/pkg/job"
	"shop/pkg/job/task"
	"shop/pkg/middleware"
	cache2 "shop/pkg/recommend/cache"
	"shop/pkg/recommend/offline/materialize"
	"shop/pkg/wx"
	"shop/server"
	"shop/service/admin"
	biz3 "shop/service/admin/biz"
	"shop/service/app"
	biz2 "shop/service/app/biz"
	"shop/service/base"
	biz4 "shop/service/base/biz"
)

import (
	_ "github.com/liujitcn/kratos-kit/database/gorm/driver/mysql"
	_ "github.com/liujitcn/kratos-kit/logger/zap"
)

// Injectors from wire.go:

// initApp 初始化 Kratos 应用实例。
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	confData, err := configs.ParseData(context)
	if err != nil {
		return nil, nil, err
	}
	data_Database := configs.ParseDatabase(confData)
	client, cleanup, err := gorm.NewGormClient(data_Database)
	if err != nil {
		return nil, nil, err
	}
	dataData := data.NewData(client)
	baseJobRepo := data.NewBaseJobRepo(dataData)
	confOSS, err := configs.ParseOss(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	ossOSS := oss.NewOSS(confOSS)
	transaction := data.NewTransaction(dataData)
	data_Redis := configs.ParseRedis(confData)
	cacheCache, cleanup2, err := cache.NewCache(data_Redis)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	data_Queue := configs.ParseQueue(confData)
	queueQueue, cleanup3, err := queue.NewQueue(data_Redis, data_Queue)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	confPprof, err := configs.ParsePprof(context)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofPprof, err := pprof.NewPprof(confPprof)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	casbinRuleRepo := data.NewCasbinRuleRepo(dataData)
	baseApiRepo := data.NewBaseApiRepo(dataData)
	baseApiCase := biz.NewBaseApiCase(baseApiRepo)
	engine, err := middleware.NewAuthzEngine()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	casbinRuleCase, err := biz.NewCasbinRuleCase(casbinRuleRepo, baseApiCase, engine)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseCase, cleanup4, err := biz.NewBaseCase(context, cacheCache, queueQueue, client, pprofPprof, casbinRuleCase, baseApiCase)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	shopConfig := configs.NewShopConfig(context)
	wxPay, err := configs.ParseWxPay(shopConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	wxPayCase, err := wx.NewWxPayCase(baseCase, wxPay)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	payBillRepo := data.NewPayBillRepo(dataData)
	orderPaymentRepo := data.NewOrderPaymentRepo(dataData)
	orderRefundRepo := data.NewOrderRefundRepo(dataData)
	tradeBill := task.NewTradeBill(dataData, ossOSS, transaction, wxPayCase, payBillRepo, orderPaymentRepo, orderRefundRepo)
	orderStatDayRepo := data.NewOrderStatDayRepo(dataData)
	orderInfoRepo := data.NewOrderInfoRepo(dataData)
	orderStatDay := task.NewOrderStatDay(transaction, orderStatDayRepo, orderInfoRepo)
	goodsStatDayRepo := data.NewGoodsStatDayRepo(dataData)
	recommendGoodsActionRepo := data.NewRecommendGoodsActionRepo(dataData)
	userCollectRepo := data.NewUserCollectRepo(dataData)
	userCartRepo := data.NewUserCartRepo(dataData)
	orderGoodsRepo := data.NewOrderGoodsRepo(dataData)
	goodsStatDay := task.NewGoodsStatDay(transaction, shopConfig, goodsStatDayRepo, recommendGoodsActionRepo, userCollectRepo, userCartRepo, orderInfoRepo, orderGoodsRepo)
	recommendGoodsStatDayRepo := data.NewRecommendGoodsStatDayRepo(dataData)
	recommendRequestRepo := data.NewRecommendRequestRepo(dataData)
	recommendRequestItemRepo := data.NewRecommendRequestItemRepo(dataData)
	recommendExposureRepo := data.NewRecommendExposureRepo(dataData)
	recommendExposureItemRepo := data.NewRecommendExposureItemRepo(dataData)
	recommendGoodsStatDay := task.NewRecommendGoodsStatDay(transaction, recommendGoodsStatDayRepo, recommendRequestRepo, recommendRequestItemRepo, recommendExposureRepo, recommendExposureItemRepo, recommendGoodsActionRepo, orderGoodsRepo)
	recommendActorBindLogRepo := data.NewRecommendActorBindLogRepo(dataData)
	recommendUserPreferenceRepo := data.NewRecommendUserPreferenceRepo(dataData)
	goodsInfoRepo := data.NewGoodsInfoRepo(dataData)
	goodsCategoryRepo := data.NewGoodsCategoryRepo(dataData)
	goodsPropRepo := data.NewGoodsPropRepo(dataData)
	goodsPropCase := biz2.NewGoodsPropCase(baseCase, goodsPropRepo)
	goodsSpecRepo := data.NewGoodsSpecRepo(dataData)
	goodsSpecCase := biz2.NewGoodsSpecCase(baseCase, goodsSpecRepo)
	goodsSkuRepo := data.NewGoodsSkuRepo(dataData)
	goodsSkuCase := biz2.NewGoodsSkuCase(baseCase, goodsSkuRepo)
	goodsInfoCase := biz2.NewGoodsInfoCase(baseCase, goodsInfoRepo, goodsCategoryRepo, goodsPropCase, goodsSpecCase, goodsSkuCase)
	recommendUserPreferenceCase := biz2.NewRecommendUserPreferenceCase(baseCase, recommendUserPreferenceRepo, recommendGoodsActionRepo, goodsInfoCase)
	recommendUserGoodsPreferenceRepo := data.NewRecommendUserGoodsPreferenceRepo(dataData)
	recommendUserGoodsPreferenceCase := biz2.NewRecommendUserGoodsPreferenceCase(baseCase, recommendUserGoodsPreferenceRepo, recommendGoodsActionRepo)
	recommendGoodsRelationRepo := data.NewRecommendGoodsRelationRepo(dataData)
	recommendRequestItemCase := biz2.NewRecommendRequestItemCase(baseCase, recommendRequestItemRepo, recommendRequestRepo)
	recommendGoodsRelationCase := biz2.NewRecommendGoodsRelationCase(baseCase, recommendGoodsRelationRepo, recommendGoodsActionRepo, recommendRequestItemCase)
	recommendActorBindLogCase := biz2.NewRecommendActorBindLogCase(baseCase, dataData, transaction, recommendActorBindLogRepo, recommendUserPreferenceCase, recommendUserGoodsPreferenceCase, recommendGoodsRelationCase)
	recommendUserPreferenceRebuild := task.NewRecommendUserPreferenceRebuild(recommendActorBindLogCase)
	recommendGoodsRelationRebuild := task.NewRecommendGoodsRelationRebuild(recommendActorBindLogCase)
	recommendModelVersionRepo := data.NewRecommendModelVersionRepo(dataData)
	store, cleanup5, err := cache2.NewStore(data_Redis)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	materializer := materialize.NewMaterializer(store)
	recommendHotMaterialize := task.NewRecommendHotMaterialize(recommendGoodsStatDayRepo, recommendModelVersionRepo, goodsInfoRepo, materializer)
	recommendLatestMaterialize := task.NewRecommendLatestMaterialize(recommendModelVersionRepo, goodsInfoRepo, materializer)
	recommendSimilarItemMaterialize := task.NewRecommendSimilarItemMaterialize(recommendGoodsRelationRepo, recommendModelVersionRepo, goodsInfoRepo, store, materializer)
	recommendSimilarUserMaterialize := task.NewRecommendSimilarUserMaterialize(recommendUserPreferenceRepo, recommendUserGoodsPreferenceRepo, recommendModelVersionRepo, store, materializer)
	recommendCollaborativeFilteringMaterialize := task.NewRecommendCollaborativeFilteringMaterialize(recommendGoodsActionRepo, recommendModelVersionRepo, goodsInfoRepo, store, materializer)
	recommendContentBasedMaterialize := task.NewRecommendContentBasedMaterialize(recommendModelVersionRepo, goodsInfoRepo, store, materializer)
	recommendRankerMaterialize := task.NewRecommendRankerMaterialize(recommendModelVersionRepo, recommendRequestRepo, recommendRequestItemRepo, recommendGoodsActionRepo, goodsInfoRepo, store, materializer)
	orderGoodsCase := biz2.NewOrderGoodsCase(baseCase, orderGoodsRepo, goodsInfoCase, goodsSkuCase)
	userCartCase := biz2.NewUserCartCase(baseCase, userCartRepo, goodsInfoCase, goodsSkuCase)
	recommendExposureItemCase := biz2.NewRecommendExposureItemCase(baseCase, recommendExposureItemRepo, recommendExposureRepo, recommendRequestItemCase)
	recommendExposureCase := biz2.NewRecommendExposureCase(baseCase, recommendExposureRepo, recommendExposureItemCase, recommendGoodsActionRepo)
	recommendGoodsStatDayCase := biz2.NewRecommendGoodsStatDayCase(baseCase, recommendGoodsStatDayRepo)
	goodsStatDayCase := biz2.NewGoodsStatDayCase(baseCase, goodsStatDayRepo)
	recommendModelVersionCase := biz2.NewRecommendModelVersionCase(baseCase, recommendModelVersionRepo)
	recommendRequestCase := biz2.NewRecommendRequestCase(baseCase, shopConfig, recommendRequestRepo, recommendRequestItemCase, goodsInfoCase, orderGoodsCase, userCartCase, recommendExposureCase, recommendUserGoodsPreferenceCase, recommendUserPreferenceCase, recommendGoodsRelationCase, recommendGoodsStatDayCase, goodsStatDayCase, recommendModelVersionCase, store)
	recommendResultMaterialize := task.NewRecommendResultMaterialize(recommendRequestCase, recommendRequestRepo, recommendGoodsActionRepo, store, materializer)
	recommendLlmRerankMaterialize := task.NewRecommendLlmRerankMaterialize(store, materializer)
	recommendEvalReportRepo := data.NewRecommendEvalReportRepo(dataData)
	recommendEvalReport := task.NewRecommendEvalReport(transaction, recommendEvalReportRepo, recommendModelVersionRepo, recommendRequestRepo, recommendRequestItemRepo, recommendExposureRepo, recommendExposureItemRepo, recommendGoodsActionRepo)
	recommendVersionPublish := task.NewRecommendVersionPublish(transaction, recommendModelVersionRepo)
	v := task.NewTaskList(tradeBill, orderStatDay, goodsStatDay, recommendGoodsStatDay, recommendUserPreferenceRebuild, recommendGoodsRelationRebuild, recommendHotMaterialize, recommendLatestMaterialize, recommendSimilarItemMaterialize, recommendSimilarUserMaterialize, recommendCollaborativeFilteringMaterialize, recommendContentBasedMaterialize, recommendRankerMaterialize, recommendResultMaterialize, recommendLlmRerankMaterialize, recommendEvalReport, recommendVersionPublish)
	cronServer := job.NewCronServer(baseJobRepo, v)
	authentication_Jwt := configs.ParseAuthnJwt(context)
	authenticator := middleware.NewAuthenticator(authentication_Jwt)
	baseUserRepo := data.NewBaseUserRepo(dataData)
	userToken := middleware.NewUserToken(authentication_Jwt, cacheCache, authenticator)
	grpcMiddlewares := server.NewGrpcMiddleware(context, authenticator, baseUserRepo, engine, userToken, authentication_Jwt)
	baseDeptRepo := data.NewBaseDeptRepo(dataData)
	baseRoleRepo := data.NewBaseRoleRepo(dataData)
	baseMenuRepo := data.NewBaseMenuRepo(dataData)
	bizBaseApiCase := biz3.NewBaseApiCase(baseCase, baseApiRepo, authentication_Jwt)
	bizCasbinRuleCase, err := biz3.NewCasbinRuleCase(baseCase, casbinRuleRepo, baseMenuRepo, baseRoleRepo, bizBaseApiCase, engine)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseRoleCase := biz3.NewBaseRoleCase(baseCase, transaction, baseRoleRepo, bizCasbinRuleCase)
	baseDeptCase := biz3.NewBaseDeptCase(baseCase, baseDeptRepo)
	baseMenuCase := biz3.NewBaseMenuCase(baseCase, transaction, baseMenuRepo, bizCasbinRuleCase)
	baseUserCase := biz3.NewBaseUserCase(baseCase, baseUserRepo, baseDeptRepo, baseRoleCase, baseDeptCase, baseMenuCase)
	fileCase := biz4.NewFileCase(ossOSS)
	authCase := biz3.NewAuthCase(baseCase, baseUserCase, baseRoleCase, baseDeptCase, baseMenuCase, fileCase)
	authService := admin.NewAuthService(authCase)
	baseApiService := admin.NewBaseApiService(bizBaseApiCase)
	baseConfigRepo := data.NewBaseConfigRepo(dataData)
	baseConfigCase := biz3.NewBaseConfigCase(baseCase, baseConfigRepo)
	baseConfigService, err := admin.NewBaseConfigService(baseConfigCase)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseDeptService := admin.NewBaseDeptService(baseDeptCase)
	baseDictRepo := data.NewBaseDictRepo(dataData)
	baseDictItemRepo := data.NewBaseDictItemRepo(dataData)
	baseDictItemCase := biz3.NewBaseDictItemCase(baseCase, baseDictRepo, baseDictItemRepo)
	baseDictCase := biz3.NewBaseDictCase(baseCase, baseDictRepo, baseDictItemCase)
	baseDictService := admin.NewBaseDictService(baseDictCase, baseDictItemCase)
	baseJobLogRepo := data.NewBaseJobLogRepo(dataData)
	baseJobLogCase := biz3.NewBaseJobLogCase(baseCase, baseJobLogRepo)
	baseJobCase := biz3.NewBaseJobCase(baseCase, baseJobRepo, baseJobLogCase, cronServer)
	baseJobService := admin.NewBaseJobService(baseJobCase, baseJobLogCase)
	baseLogRepo := data.NewBaseLogRepo(dataData)
	baseLogCase := biz3.NewBaseLogCase(baseCase, baseLogRepo)
	baseLogService := admin.NewBaseLogService(baseLogCase)
	baseMenuService := admin.NewBaseMenuService(baseMenuCase)
	baseRoleService := admin.NewBaseRoleService(baseRoleCase)
	baseUserService := admin.NewBaseUserService(baseUserCase)
	goodsCategoryCase := biz3.NewGoodsCategoryCase(baseCase, goodsCategoryRepo)
	bizGoodsPropCase := biz3.NewGoodsPropCase(baseCase, goodsPropRepo)
	bizGoodsSpecCase := biz3.NewGoodsSpecCase(baseCase, goodsSpecRepo)
	bizGoodsSkuCase := biz3.NewGoodsSkuCase(baseCase, goodsSkuRepo)
	bizGoodsInfoCase := biz3.NewGoodsInfoCase(baseCase, transaction, goodsInfoRepo, goodsCategoryCase, bizGoodsPropCase, bizGoodsSpecCase, bizGoodsSkuCase)
	goodsAnalyticsCase := biz3.NewGoodsAnalyticsCase(bizGoodsInfoCase, goodsCategoryCase, goodsStatDayRepo)
	goodsAnalyticsService := admin.NewGoodsAnalyticsService(goodsAnalyticsCase)
	goodsReportCase := biz3.NewGoodsReportCase(baseCase, goodsStatDayRepo)
	goodsReportService := admin.NewGoodsReportService(goodsReportCase)
	goodsCategoryService := admin.NewGoodsCategoryService(goodsCategoryCase)
	goodsPropService := admin.NewGoodsPropService(bizGoodsPropCase)
	goodsInfoService := admin.NewGoodsInfoService(bizGoodsInfoCase)
	goodsSkuService := admin.NewGoodsSkuService(bizGoodsSkuCase)
	goodsSpecService := admin.NewGoodsSpecService(bizGoodsSpecCase)
	orderAddressRepo := data.NewOrderAddressRepo(dataData)
	orderAddressCase := biz3.NewOrderAddressCase(baseCase, orderAddressRepo)
	orderCancelRepo := data.NewOrderCancelRepo(dataData)
	orderCancelCase := biz3.NewOrderCancelCase(baseCase, orderCancelRepo)
	bizOrderGoodsCase := biz3.NewOrderGoodsCase(baseCase, orderGoodsRepo)
	orderLogisticsRepo := data.NewOrderLogisticsRepo(dataData)
	orderLogisticsCase := biz3.NewOrderLogisticsCase(baseCase, orderLogisticsRepo)
	orderPaymentCase := biz3.NewOrderPaymentCase(baseCase, orderPaymentRepo)
	orderRefundCase := biz3.NewOrderRefundCase(baseCase, orderRefundRepo)
	orderInfoCase := biz3.NewOrderInfoCase(baseCase, transaction, orderAddressCase, orderInfoRepo, orderCancelCase, bizOrderGoodsCase, orderLogisticsCase, orderPaymentCase, orderRefundCase, baseUserCase, baseDictItemCase, wxPayCase)
	orderAnalyticsCase := biz3.NewOrderAnalyticsCase(orderInfoCase, baseDictCase, baseDictItemCase)
	orderAnalyticsService := admin.NewOrderAnalyticsService(orderAnalyticsCase)
	orderReportCase := biz3.NewOrderReportCase(baseCase, orderStatDayRepo)
	orderReportService := admin.NewOrderReportService(orderReportCase)
	orderInfoService := admin.NewOrderInfoService(orderInfoCase)
	payBillCase := biz3.NewPayBillCase(baseCase, payBillRepo)
	payBillService := admin.NewPayBillService(payBillCase)
	bizRecommendModelVersionCase := biz3.NewRecommendModelVersionCase(baseCase, recommendModelVersionRepo, recommendVersionPublish)
	recommendModelVersionService := admin.NewRecommendModelVersionService(bizRecommendModelVersionCase)
	shopBannerRepo := data.NewShopBannerRepo(dataData)
	shopBannerCase := biz3.NewShopBannerCase(baseCase, shopBannerRepo)
	shopBannerService := admin.NewShopBannerService(shopBannerCase)
	shopHotRepo := data.NewShopHotRepo(dataData)
	shopHotItemRepo := data.NewShopHotItemRepo(dataData)
	shopHotGoodsRepo := data.NewShopHotGoodsRepo(dataData)
	shopHotItemCase := biz3.NewShopHotItemCase(baseCase, transaction, shopHotRepo, shopHotItemRepo, shopHotGoodsRepo)
	shopHotCase := biz3.NewShopHotCase(baseCase, transaction, shopHotRepo, shopHotItemCase)
	shopHotService := admin.NewShopHotService(shopHotCase, shopHotItemCase)
	shopServiceRepo := data.NewShopServiceRepo(dataData)
	shopServiceCase := biz3.NewShopServiceCase(baseCase, shopServiceRepo)
	shopServiceService := admin.NewShopServiceService(shopServiceCase)
	userAnalyticsCase := biz3.NewUserAnalyticsCase(baseUserCase, orderInfoCase)
	userAnalyticsService := admin.NewUserAnalyticsService(userAnalyticsCase)
	userStoreRepo := data.NewUserStoreRepo(dataData)
	baseAreaRepo := data.NewBaseAreaRepo(dataData)
	userStoreCase := biz3.NewUserStoreCase(baseCase, transaction, userStoreRepo, baseAreaRepo, baseUserCase, baseRoleCase)
	userStoreService := admin.NewUserStoreService(userStoreCase)
	workspaceCase := biz3.NewWorkspaceCase(orderInfoCase, baseUserCase, bizOrderGoodsCase, bizGoodsInfoCase, bizGoodsSkuCase, payBillCase)
	workspaceService := admin.NewWorkspaceService(workspaceCase)
	bizBaseUserCase := biz2.NewBaseUserCase(baseCase, baseUserRepo)
	bizBaseRoleCase := biz2.NewBaseRoleCase(baseCase, baseRoleRepo)
	bizBaseDeptCase := biz2.NewBaseDeptCase(baseCase, baseDeptRepo)
	wxMiniApp, err := configs.ParseWxMiniApp(shopConfig)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bizAuthCase := biz2.NewAuthCase(baseCase, userToken, bizBaseUserCase, bizBaseRoleCase, bizBaseDeptCase, wxMiniApp)
	appAuthService := app.NewAuthService(bizAuthCase)
	baseAreaCase := biz2.NewBaseAreaCase(baseCase, baseAreaRepo)
	baseAreaService := app.NewBaseAreaService(baseAreaCase)
	bizBaseDictItemCase := biz2.NewBaseDictItemCase(baseCase, baseDictRepo, baseDictItemRepo)
	bizBaseDictCase := biz2.NewBaseDictCase(baseCase, baseDictRepo, bizBaseDictItemCase)
	appBaseDictService := app.NewBaseDictService(bizBaseDictCase)
	bizGoodsCategoryCase := biz2.NewGoodsCategoryCase(baseCase, goodsCategoryRepo, goodsInfoRepo)
	appGoodsCategoryService := app.NewGoodsCategoryService(bizGoodsCategoryCase)
	appGoodsInfoService := app.NewGoodsInfoService(goodsInfoCase)
	bizOrderCancelCase := biz2.NewOrderCancelCase(baseCase, orderCancelRepo)
	userAddressRepo := data.NewUserAddressRepo(dataData)
	bizOrderAddressCase := biz2.NewOrderAddressCase(baseCase, orderAddressRepo, userAddressRepo, baseAreaCase)
	bizOrderLogisticsCase := biz2.NewOrderLogisticsCase(baseCase, orderLogisticsRepo)
	bizOrderPaymentCase := biz2.NewOrderPaymentCase(baseCase, orderPaymentRepo)
	bizOrderRefundCase := biz2.NewOrderRefundCase(baseCase, orderRefundRepo)
	userAddressCase := biz2.NewUserAddressCase(baseCase, transaction, userAddressRepo, baseAreaCase)
	orderSchedulerCase := biz2.NewOrderSchedulerCase(baseCase)
	payCase := biz2.NewPayCase(baseCase, transaction, orderInfoRepo, orderGoodsRepo, orderPaymentRepo, orderRefundRepo, orderSchedulerCase, wxPayCase)
	bizOrderInfoCase, err := biz2.NewOrderInfoCase(baseCase, transaction, orderInfoRepo, bizOrderCancelCase, orderGoodsCase, bizOrderAddressCase, bizOrderLogisticsCase, bizOrderPaymentCase, bizOrderRefundCase, goodsInfoCase, goodsSkuCase, userAddressCase, userCartCase, bizBaseDictItemCase, orderSchedulerCase, payCase, wxPayCase)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appOrderInfoService := app.NewOrderInfoService(bizOrderInfoCase)
	payService := app.NewPayService(payCase)
	recommendGoodsActionCase := biz2.NewRecommendGoodsActionCase(baseCase, transaction, recommendGoodsActionRepo, recommendUserGoodsPreferenceCase, recommendUserPreferenceCase, recommendGoodsRelationCase)
	recommendCase := biz2.NewRecommendCase(baseCase, transaction, recommendActorBindLogCase, recommendRequestCase, recommendExposureCase, recommendGoodsActionCase)
	recommendService := app.NewRecommendService(recommendCase)
	bizShopBannerCase := biz2.NewShopBannerCase(baseCase, shopBannerRepo, bizGoodsCategoryCase)
	appShopBannerService := app.NewShopBannerService(bizShopBannerCase)
	bizShopHotCase := biz2.NewShopHotCase(baseCase, shopHotRepo)
	bizShopHotItemCase := biz2.NewShopHotItemCase(baseCase, shopHotRepo, shopHotItemRepo, shopHotGoodsRepo, goodsInfoRepo)
	appShopHotService := app.NewShopHotService(bizShopHotCase, bizShopHotItemCase)
	bizShopServiceCase := biz2.NewShopServiceCase(baseCase, shopServiceRepo)
	appShopServiceService := app.NewShopServiceService(bizShopServiceCase)
	userAddressService := app.NewUserAddressService(userAddressCase)
	userCartService := app.NewUserCartService(userCartCase)
	userCollectCase := biz2.NewUserCollectCase(baseCase, userCollectRepo, goodsInfoCase, goodsSkuCase)
	userCollectService := app.NewUserCollectService(userCollectCase)
	bizUserStoreCase := biz2.NewUserStoreCase(baseCase, transaction, userStoreRepo, baseAreaCase)
	appUserStoreService := app.NewUserStoreService(bizUserStoreCase)
	configCase := biz4.NewConfigCase(baseConfigRepo)
	configService := base.NewConfigService(configCase)
	fileService := base.NewFileService(fileCase)
	baseDeptCase2 := biz4.NewBaseDeptCase(baseDeptRepo)
	baseRoleCase2 := biz4.NewBaseRoleCase(baseRoleRepo)
	baseUserCase2 := biz4.NewBaseUserCase(baseUserRepo)
	loginCase := biz4.NewLoginCase(baseCase, userToken, baseDeptCase2, baseRoleCase2, baseUserCase2)
	loginService := base.NewLoginService(loginCase)
	grpcServer, err := server.NewGRPCServer(context, grpcMiddlewares, authService, baseApiService, baseConfigService, baseDeptService, baseDictService, baseJobService, baseLogService, baseMenuService, baseRoleService, baseUserService, goodsAnalyticsService, goodsReportService, goodsCategoryService, goodsPropService, goodsInfoService, goodsSkuService, goodsSpecService, orderAnalyticsService, orderReportService, orderInfoService, payBillService, recommendModelVersionService, shopBannerService, shopHotService, shopServiceService, userAnalyticsService, userStoreService, workspaceService, appAuthService, baseAreaService, appBaseDictService, appGoodsCategoryService, appGoodsInfoService, appOrderInfoService, payService, recommendService, appShopBannerService, appShopHotService, appShopServiceService, userAddressService, userCartService, userCollectService, appUserStoreService, configService, fileService, loginService)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpMiddlewares := server.NewHttpMiddleware(context, authenticator, baseUserRepo, engine, userToken, authentication_Jwt)
	httpServer, err := server.NewHttpServer(context, httpMiddlewares, authService, baseApiService, baseConfigService, baseDeptService, baseDictService, baseJobService, baseLogService, baseMenuService, baseRoleService, baseUserService, goodsAnalyticsService, goodsReportService, goodsCategoryService, goodsPropService, goodsInfoService, goodsSkuService, goodsSpecService, orderAnalyticsService, orderReportService, orderInfoService, payBillService, recommendModelVersionService, shopBannerService, shopHotService, shopServiceService, userAnalyticsService, userStoreService, workspaceService, appAuthService, baseAreaService, appBaseDictService, appGoodsCategoryService, appGoodsInfoService, appOrderInfoService, payService, recommendService, appShopBannerService, appShopHotService, appShopServiceService, userAddressService, userCartService, userCollectService, appUserStoreService, configService, fileService, loginService)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kratosApp := newApp(context, cronServer, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
