// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"shop/pkg/biz"
	"shop/pkg/config"
	"shop/pkg/gen/data"
	"shop/pkg/job"
	"shop/pkg/job/task"
	"shop/pkg/llm"
	"shop/pkg/middleware"
	"shop/pkg/recommend"
	"shop/pkg/recommend/gorse"
	"shop/pkg/recommend/local"
	"shop/pkg/wx"
	"shop/server"
	"shop/service/admin"
	biz2 "shop/service/admin/biz"
	"shop/service/app"
	biz4 "shop/service/app/biz"
	"shop/service/base"
	biz3 "shop/service/base/biz"

	"github.com/go-kratos/kratos/v2"
	"github.com/liujitcn/kratos-kit/bootstrap"
	"github.com/liujitcn/kratos-kit/cache"
	"github.com/liujitcn/kratos-kit/database/gorm"
	"github.com/liujitcn/kratos-kit/oss"
	"github.com/liujitcn/kratos-kit/pprof"
	"github.com/liujitcn/kratos-kit/queue"

	_ "github.com/liujitcn/kratos-kit/database/gorm/driver/mysql"

	_ "github.com/liujitcn/kratos-kit/logger/zap"
)

// Injectors from wire.go:

// initApp 初始化 Kratos 应用实例。
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	configv1Data, err := config.ParseData(context)
	if err != nil {
		return nil, nil, err
	}
	data_Database := config.ParseDatabase(configv1Data)
	client, cleanup, err := gorm.NewGormClient(data_Database)
	if err != nil {
		return nil, nil, err
	}
	dataData := data.NewData(client)
	baseJobRepository := data.NewBaseJobRepository(dataData)
	configv1Oss, err := config.ParseOSS(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	ossOSS := oss.NewOSS(configv1Oss)
	transaction := data.NewTransaction(dataData)
	data_Redis := config.ParseRedis(configv1Data)
	cacheCache, cleanup2, err := cache.NewCache(data_Redis)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	data_Queue := config.ParseQueue(configv1Data)
	queueQueue, cleanup3, err := queue.NewQueue(data_Redis, data_Queue)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configv1Pprof, err := config.ParsePprof(context)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofPprof, err := pprof.NewPprof(configv1Pprof)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	casbinRuleRepository := data.NewCasbinRuleRepository(dataData)
	baseAPIRepository := data.NewBaseAPIRepository(dataData)
	baseAPICase := biz.NewBaseAPICase(baseAPIRepository)
	engine, err := middleware.NewAuthzEngine()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	casbinRuleCase, err := biz.NewCasbinRuleCase(casbinRuleRepository, baseAPICase, engine)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseCase, cleanup4, err := biz.NewBaseCase(context, cacheCache, queueQueue, client, pprofPprof, casbinRuleCase, baseAPICase)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	shopConfig := config.NewShopConfig(context)
	wxPay, err := config.ParseWxPay(shopConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	wxPayCase, err := wx.NewWxPayCase(baseCase, wxPay)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	payBillRepository := data.NewPayBillRepository(dataData)
	orderPaymentRepository := data.NewOrderPaymentRepository(dataData)
	orderRefundRepository := data.NewOrderRefundRepository(dataData)
	tradeBill := task.NewTradeBill(dataData, ossOSS, transaction, wxPayCase, payBillRepository, orderPaymentRepository, orderRefundRepository)
	orderStatDayRepository := data.NewOrderStatDayRepository(dataData)
	orderInfoRepository := data.NewOrderInfoRepository(dataData)
	orderStatDay := task.NewOrderStatDay(transaction, orderStatDayRepository, orderInfoRepository)
	goodsStatDayRepository := data.NewGoodsStatDayRepository(dataData)
	recommendEventRepository := data.NewRecommendEventRepository(dataData)
	userCollectRepository := data.NewUserCollectRepository(dataData)
	userCartRepository := data.NewUserCartRepository(dataData)
	orderGoodsRepository := data.NewOrderGoodsRepository(dataData)
	goodsStatDay := task.NewGoodsStatDay(transaction, goodsStatDayRepository, recommendEventRepository, userCollectRepository, userCartRepository, orderInfoRepository, orderGoodsRepository)
	baseUserRepository := data.NewBaseUserRepository(dataData)
	goodsInfoRepository := data.NewGoodsInfoRepository(dataData)
	configv1Recommend, err := config.ParseRecommend(shopConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	gorseRecommend := gorse.NewRecommend(configv1Recommend)
	userSyncReceiver := gorse.NewUserSyncReceiver(gorseRecommend)
	goodsSyncReceiver := gorse.NewGoodsSyncReceiver(gorseRecommend)
	queueReceiver := gorse.NewQueueReceiver(gorseRecommend, baseUserRepository, goodsInfoRepository, userSyncReceiver, goodsSyncReceiver)
	recommendSync := task.NewRecommendSync(baseUserRepository, goodsInfoRepository, userSyncReceiver, goodsSyncReceiver, queueReceiver)
	v := task.NewTaskList(tradeBill, orderStatDay, goodsStatDay, recommendSync)
	cronServer := job.NewCronServer(baseJobRepository, v)
	authentication_Jwt := config.ParseAuthnJWT(context)
	authenticator := middleware.NewAuthenticator(authentication_Jwt)
	userToken := middleware.NewUserToken(authentication_Jwt, cacheCache, authenticator)
	grpcMiddlewares := server.NewGRPCMiddleware(context, authenticator, baseUserRepository, engine, userToken, authentication_Jwt)
	baseDeptRepository := data.NewBaseDeptRepository(dataData)
	baseRoleRepository := data.NewBaseRoleRepository(dataData)
	baseMenuRepository := data.NewBaseMenuRepository(dataData)
	bizBaseAPICase := biz2.NewBaseAPICase(baseCase, baseAPIRepository, authentication_Jwt)
	bizCasbinRuleCase, err := biz2.NewCasbinRuleCase(baseCase, casbinRuleRepository, baseMenuRepository, baseRoleRepository, bizBaseAPICase, engine)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseRoleCase := biz2.NewBaseRoleCase(baseCase, transaction, baseRoleRepository, bizCasbinRuleCase)
	baseDeptCase := biz2.NewBaseDeptCase(baseCase, baseDeptRepository)
	baseMenuCase := biz2.NewBaseMenuCase(baseCase, transaction, baseMenuRepository, bizCasbinRuleCase)
	baseUserCase := biz2.NewBaseUserCase(baseCase, baseUserRepository, baseDeptRepository, baseRoleCase, baseDeptCase, baseMenuCase)
	fileCase := biz3.NewFileCase(ossOSS)
	authCase := biz2.NewAuthCase(baseCase, baseUserCase, baseRoleCase, baseDeptCase, baseMenuCase, fileCase)
	authService := admin.NewAuthService(authCase)
	baseApiService := admin.NewBaseApiService(bizBaseAPICase)
	baseConfigRepository := data.NewBaseConfigRepository(dataData)
	baseConfigCase := biz2.NewBaseConfigCase(baseCase, baseConfigRepository)
	baseConfigService, err := admin.NewBaseConfigService(baseConfigCase)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseDeptService := admin.NewBaseDeptService(baseDeptCase)
	baseDictRepository := data.NewBaseDictRepository(dataData)
	baseDictItemRepository := data.NewBaseDictItemRepository(dataData)
	baseDictItemCase := biz2.NewBaseDictItemCase(baseCase, baseDictRepository, baseDictItemRepository)
	baseDictCase := biz2.NewBaseDictCase(baseCase, baseDictRepository, baseDictItemCase)
	baseDictService := admin.NewBaseDictService(baseDictCase, baseDictItemCase)
	baseJobLogRepository := data.NewBaseJobLogRepository(dataData)
	baseJobLogCase := biz2.NewBaseJobLogCase(baseCase, baseJobLogRepository)
	baseJobCase := biz2.NewBaseJobCase(baseCase, baseJobRepository, baseJobLogCase, cronServer)
	baseJobService := admin.NewBaseJobService(baseJobCase, baseJobLogCase)
	baseLogRepository := data.NewBaseLogRepository(dataData)
	baseLogCase := biz2.NewBaseLogCase(baseCase, baseLogRepository)
	baseLogService := admin.NewBaseLogService(baseLogCase)
	baseMenuService := admin.NewBaseMenuService(baseMenuCase)
	baseRoleService := admin.NewBaseRoleService(baseRoleCase)
	baseUserService := admin.NewBaseUserService(baseUserCase)
	commentInfoRepository := data.NewCommentInfoRepository(dataData)
	commentTagRepository := data.NewCommentTagRepository(dataData)
	commentTagCase := biz2.NewCommentTagCase(baseCase, commentTagRepository)
	commentDiscussionRepository := data.NewCommentDiscussionRepository(dataData)
	commentReviewRepository := data.NewCommentReviewRepository(dataData)
	commentReviewCase := biz2.NewCommentReviewCase(baseCase, commentReviewRepository)
	commentDiscussionCase := biz2.NewCommentDiscussionCase(baseCase, commentDiscussionRepository, transaction, commentInfoRepository, commentReviewCase, baseUserCase)
	commentAiRepository := data.NewCommentAiRepository(dataData)
	commentAiCase := biz2.NewCommentAiCase(baseCase, commentAiRepository)
	commentInfoCase := biz2.NewCommentInfoCase(baseCase, commentInfoRepository, transaction, commentTagCase, commentDiscussionCase, commentAiCase, commentReviewCase, baseUserCase)
	commentInfoService := admin.NewCommentInfoService(commentInfoCase, commentDiscussionCase, commentReviewCase)
	goodsCategoryRepository := data.NewGoodsCategoryRepository(dataData)
	goodsCategoryCase := biz2.NewGoodsCategoryCase(baseCase, goodsCategoryRepository)
	goodsPropRepository := data.NewGoodsPropRepository(dataData)
	goodsPropCase := biz2.NewGoodsPropCase(baseCase, goodsPropRepository)
	goodsSpecRepository := data.NewGoodsSpecRepository(dataData)
	goodsSpecCase := biz2.NewGoodsSpecCase(baseCase, goodsSpecRepository)
	goodsSKURepository := data.NewGoodsSKURepository(dataData)
	goodsSKUCase := biz2.NewGoodsSKUCase(baseCase, goodsSKURepository)
	goodsInfoCase := biz2.NewGoodsInfoCase(baseCase, transaction, goodsInfoRepository, goodsCategoryCase, goodsPropCase, goodsSpecCase, goodsSKUCase)
	goodsAnalyticsCase := biz2.NewGoodsAnalyticsCase(goodsInfoCase, goodsCategoryCase, goodsStatDayRepository)
	goodsAnalyticsService := admin.NewGoodsAnalyticsService(goodsAnalyticsCase)
	goodsReportCase := biz2.NewGoodsReportCase(baseCase, goodsStatDayRepository)
	goodsReportService := admin.NewGoodsReportService(goodsReportCase)
	goodsCategoryService := admin.NewGoodsCategoryService(goodsCategoryCase)
	goodsPropService := admin.NewGoodsPropService(goodsPropCase)
	goodsInfoService := admin.NewGoodsInfoService(goodsInfoCase)
	goodsSkuService := admin.NewGoodsSkuService(goodsSKUCase)
	goodsSpecService := admin.NewGoodsSpecService(goodsSpecCase)
	orderAddressRepository := data.NewOrderAddressRepository(dataData)
	orderAddressCase := biz2.NewOrderAddressCase(baseCase, orderAddressRepository)
	orderCancelRepository := data.NewOrderCancelRepository(dataData)
	orderCancelCase := biz2.NewOrderCancelCase(baseCase, orderCancelRepository)
	orderGoodsCase := biz2.NewOrderGoodsCase(baseCase, orderGoodsRepository)
	orderLogisticsRepository := data.NewOrderLogisticsRepository(dataData)
	orderLogisticsCase := biz2.NewOrderLogisticsCase(baseCase, orderLogisticsRepository)
	orderPaymentCase := biz2.NewOrderPaymentCase(baseCase, orderPaymentRepository)
	orderRefundCase := biz2.NewOrderRefundCase(baseCase, orderRefundRepository)
	orderInfoCase := biz2.NewOrderInfoCase(baseCase, transaction, orderAddressCase, orderInfoRepository, orderCancelCase, orderGoodsCase, orderLogisticsCase, orderPaymentCase, orderRefundCase, baseUserCase, baseDictItemCase, wxPayCase)
	orderAnalyticsCase := biz2.NewOrderAnalyticsCase(orderInfoCase)
	orderAnalyticsService := admin.NewOrderAnalyticsService(orderAnalyticsCase)
	orderReportCase := biz2.NewOrderReportCase(baseCase, orderStatDayRepository)
	orderReportService := admin.NewOrderReportService(orderReportCase)
	orderInfoService := admin.NewOrderInfoService(orderInfoCase)
	payBillCase := biz2.NewPayBillCase(baseCase, payBillRepository)
	payBillService := admin.NewPayBillService(payBillCase)
	recommendRequestRepository := data.NewRecommendRequestRepository(dataData)
	recommendRequestItemRepository := data.NewRecommendRequestItemRepository(dataData)
	recommendEventCase := biz2.NewRecommendEventCase(baseCase, recommendEventRepository)
	recommendRequestItemCase := biz2.NewRecommendRequestItemCase(baseCase, recommendRequestItemRepository, goodsInfoRepository, recommendEventCase)
	recommendRequestCase := biz2.NewRecommendRequestCase(baseCase, recommendRequestRepository, baseUserRepository, recommendRequestItemCase, recommendEventCase)
	recommendRequestService := admin.NewRecommendRequestService(recommendRequestCase)
	dashboard := gorse.NewDashboard(gorseRecommend)
	recommendGorseCase := biz2.NewRecommendGorseCase(dashboard)
	recommendGorseService := admin.NewRecommendGorseService(recommendGorseCase)
	shopBannerRepository := data.NewShopBannerRepository(dataData)
	shopBannerCase := biz2.NewShopBannerCase(baseCase, shopBannerRepository)
	shopBannerService := admin.NewShopBannerService(shopBannerCase)
	shopHotRepository := data.NewShopHotRepository(dataData)
	shopHotItemRepository := data.NewShopHotItemRepository(dataData)
	shopHotGoodsRepository := data.NewShopHotGoodsRepository(dataData)
	shopHotItemCase := biz2.NewShopHotItemCase(baseCase, transaction, shopHotRepository, shopHotItemRepository, shopHotGoodsRepository)
	shopHotCase := biz2.NewShopHotCase(baseCase, transaction, shopHotRepository, shopHotItemCase)
	shopHotService := admin.NewShopHotService(shopHotCase, shopHotItemCase)
	shopServiceRepository := data.NewShopServiceRepository(dataData)
	shopServiceCase := biz2.NewShopServiceCase(baseCase, shopServiceRepository)
	shopServiceService := admin.NewShopServiceService(shopServiceCase)
	userAnalyticsCase := biz2.NewUserAnalyticsCase(baseUserCase, orderInfoCase)
	userAnalyticsService := admin.NewUserAnalyticsService(userAnalyticsCase)
	userStoreRepository := data.NewUserStoreRepository(dataData)
	baseAreaRepository := data.NewBaseAreaRepository(dataData)
	userStoreCase := biz2.NewUserStoreCase(baseCase, transaction, userStoreRepository, baseAreaRepository, baseUserCase, baseRoleCase)
	userStoreService := admin.NewUserStoreService(userStoreCase)
	workspaceCase := biz2.NewWorkspaceCase(orderInfoCase, baseUserCase, orderGoodsCase, goodsInfoCase, goodsSKUCase, payBillCase, commentInfoCase, commentDiscussionCase, commentTagCase, commentAiCase)
	workspaceService := admin.NewWorkspaceService(workspaceCase)
	bizBaseUserCase := biz4.NewBaseUserCase(baseCase, baseUserRepository)
	bizBaseRoleCase := biz4.NewBaseRoleCase(baseCase, baseRoleRepository)
	bizBaseDeptCase := biz4.NewBaseDeptCase(baseCase, baseDeptRepository)
	wxMiniApp, err := config.ParseWxMiniApp(shopConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bizAuthCase := biz4.NewAuthCase(baseCase, userToken, bizBaseUserCase, bizBaseRoleCase, bizBaseDeptCase, wxMiniApp)
	appAuthService := app.NewAuthService(bizAuthCase)
	baseAreaCase := biz4.NewBaseAreaCase(baseCase, baseAreaRepository)
	baseAreaService := app.NewBaseAreaService(baseAreaCase)
	bizBaseDictItemCase := biz4.NewBaseDictItemCase(baseCase, baseDictRepository, baseDictItemRepository)
	bizBaseDictCase := biz4.NewBaseDictCase(baseCase, baseDictRepository, bizBaseDictItemCase)
	appBaseDictService := app.NewBaseDictService(bizBaseDictCase)
	bizCommentInfoCase := biz4.NewCommentInfoCase(baseCase, commentInfoRepository)
	commentReactionRepository := data.NewCommentReactionRepository(dataData)
	bizCommentAiCase := biz4.NewCommentAiCase(baseCase, commentAiRepository, commentReactionRepository)
	bizCommentTagCase := biz4.NewCommentTagCase(baseCase, commentTagRepository)
	bizCommentReviewCase := biz4.NewCommentReviewCase(baseCase, commentReviewRepository)
	bizCommentDiscussionCase := biz4.NewCommentDiscussionCase(baseCase, commentDiscussionRepository, commentReactionRepository)
	commentReactionCase := biz4.NewCommentReactionCase(baseCase, commentReactionRepository, commentInfoRepository, commentAiRepository, commentDiscussionRepository)
	bizOrderCancelCase := biz4.NewOrderCancelCase(baseCase, orderCancelRepository)
	bizGoodsPropCase := biz4.NewGoodsPropCase(baseCase, goodsPropRepository)
	bizGoodsSpecCase := biz4.NewGoodsSpecCase(baseCase, goodsSpecRepository)
	bizGoodsSKUCase := biz4.NewGoodsSKUCase(baseCase, goodsSKURepository)
	bizGoodsInfoCase := biz4.NewGoodsInfoCase(baseCase, goodsInfoRepository, goodsCategoryRepository, bizGoodsPropCase, bizGoodsSpecCase, bizGoodsSKUCase)
	bizOrderGoodsCase := biz4.NewOrderGoodsCase(baseCase, orderGoodsRepository, bizGoodsInfoCase, bizGoodsSKUCase)
	userAddressRepository := data.NewUserAddressRepository(dataData)
	bizOrderAddressCase := biz4.NewOrderAddressCase(baseCase, orderAddressRepository, userAddressRepository, baseAreaCase)
	bizOrderLogisticsCase := biz4.NewOrderLogisticsCase(baseCase, orderLogisticsRepository)
	bizOrderPaymentCase := biz4.NewOrderPaymentCase(baseCase, orderPaymentRepository)
	bizOrderRefundCase := biz4.NewOrderRefundCase(baseCase, orderRefundRepository)
	userAddressCase := biz4.NewUserAddressCase(baseCase, transaction, userAddressRepository, baseAreaCase)
	userCartCase := biz4.NewUserCartCase(baseCase, userCartRepository, bizGoodsInfoCase, bizGoodsSKUCase)
	orderSchedulerCase := biz4.NewOrderSchedulerCase(baseCase)
	payCase := biz4.NewPayCase(baseCase, transaction, orderInfoRepository, orderGoodsRepository, orderPaymentRepository, orderRefundRepository, orderSchedulerCase, wxPayCase)
	bizOrderInfoCase, err := biz4.NewOrderInfoCase(baseCase, transaction, orderInfoRepository, bizOrderCancelCase, bizOrderGoodsCase, bizOrderAddressCase, bizOrderLogisticsCase, bizOrderPaymentCase, bizOrderRefundCase, bizGoodsInfoCase, bizGoodsSKUCase, userAddressCase, userCartCase, bizBaseDictItemCase, orderSchedulerCase, payCase, wxPayCase)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client_Llm := config.ParseLLM(context)
	prompt := config.ParsePrompt(shopConfig)
	llmClient := llm.NewClient(client_Llm, prompt)
	commentCase := biz4.NewCommentCase(baseCase, transaction, bizCommentInfoCase, bizCommentAiCase, bizCommentTagCase, bizCommentReviewCase, bizCommentDiscussionCase, commentReactionCase, bizOrderInfoCase, bizOrderGoodsCase, bizBaseUserCase, llmClient)
	commentService := app.NewCommentService(commentCase)
	bizGoodsCategoryCase := biz4.NewGoodsCategoryCase(baseCase, goodsCategoryRepository, goodsInfoRepository)
	appGoodsCategoryService := app.NewGoodsCategoryService(bizGoodsCategoryCase)
	appGoodsInfoService := app.NewGoodsInfoService(bizGoodsInfoCase)
	appOrderInfoService := app.NewOrderInfoService(bizOrderInfoCase)
	payService := app.NewPayService(payCase)
	recommendAnonymousActorRepository := data.NewRecommendAnonymousActorRepository(dataData)
	recommendAnonymousActorCase := biz4.NewRecommendAnonymousActorCase(baseCase, transaction, recommendAnonymousActorRepository, recommendRequestRepository, recommendEventRepository)
	bizRecommendRequestCase := biz4.NewRecommendRequestCase(baseCase, transaction, recommendRequestRepository, recommendRequestItemRepository)
	bizRecommendEventCase := biz4.NewRecommendEventCase(baseCase, recommendEventRepository, bizRecommendRequestCase)
	userCollectCase := biz4.NewUserCollectCase(baseCase, userCollectRepository, bizGoodsInfoCase, bizGoodsSKUCase)
	userReceiver := gorse.NewUserReceiver(gorseRecommend)
	sessionReceiver := gorse.NewSessionReceiver(gorseRecommend)
	namedReceiver := gorse.NewNamedReceiver(gorseRecommend)
	chainReceiver := gorse.NewChainReceiver(gorseRecommend, userReceiver, sessionReceiver, namedReceiver)
	localRecommend := local.NewRecommend(goodsInfoRepository, goodsStatDayRepository)
	contextReceiver := local.NewContextReceiver(localRecommend)
	hotReceiver := local.NewHotReceiver(localRecommend)
	exploreReceiver := local.NewExploreReceiver(localRecommend)
	localChainReceiver := local.NewChainReceiver(localRecommend, contextReceiver, hotReceiver, exploreReceiver)
	goodsReceiver := recommend.NewGoodsReceiver(chainReceiver, localChainReceiver)
	recommendCase := biz4.NewRecommendCase(baseCase, recommendAnonymousActorCase, bizRecommendRequestCase, bizRecommendEventCase, bizOrderGoodsCase, userCartCase, userCollectCase, bizGoodsInfoCase, goodsReceiver)
	recommendService := app.NewRecommendService(recommendCase)
	bizShopBannerCase := biz4.NewShopBannerCase(baseCase, shopBannerRepository, bizGoodsCategoryCase)
	appShopBannerService := app.NewShopBannerService(bizShopBannerCase)
	bizShopHotCase := biz4.NewShopHotCase(baseCase, shopHotRepository)
	bizShopHotItemCase := biz4.NewShopHotItemCase(baseCase, shopHotRepository, shopHotItemRepository, shopHotGoodsRepository, goodsInfoRepository)
	appShopHotService := app.NewShopHotService(bizShopHotCase, bizShopHotItemCase)
	bizShopServiceCase := biz4.NewShopServiceCase(baseCase, shopServiceRepository)
	appShopServiceService := app.NewShopServiceService(bizShopServiceCase)
	userAddressService := app.NewUserAddressService(userAddressCase)
	userCartService := app.NewUserCartService(userCartCase)
	userCollectService := app.NewUserCollectService(userCollectCase)
	bizUserStoreCase := biz4.NewUserStoreCase(baseCase, transaction, userStoreRepository, baseAreaCase)
	appUserStoreService := app.NewUserStoreService(bizUserStoreCase)
	configCase := biz3.NewConfigCase(baseConfigRepository)
	configService := base.NewConfigService(configCase)
	fileService := base.NewFileService(fileCase)
	baseDeptCase2 := biz3.NewBaseDeptCase(baseDeptRepository)
	baseRoleCase2 := biz3.NewBaseRoleCase(baseRoleRepository)
	baseUserCase2 := biz3.NewBaseUserCase(baseUserRepository)
	loginCase := biz3.NewLoginCase(baseCase, userToken, baseDeptCase2, baseRoleCase2, baseUserCase2)
	loginService := base.NewLoginService(loginCase)
	grpcServer, err := server.NewGRPCServer(context, grpcMiddlewares, authService, baseApiService, baseConfigService, baseDeptService, baseDictService, baseJobService, baseLogService, baseMenuService, baseRoleService, baseUserService, commentInfoService, goodsAnalyticsService, goodsReportService, goodsCategoryService, goodsPropService, goodsInfoService, goodsSkuService, goodsSpecService, orderAnalyticsService, orderReportService, orderInfoService, payBillService, recommendRequestService, recommendGorseService, shopBannerService, shopHotService, shopServiceService, userAnalyticsService, userStoreService, workspaceService, appAuthService, baseAreaService, appBaseDictService, commentService, appGoodsCategoryService, appGoodsInfoService, appOrderInfoService, payService, recommendService, appShopBannerService, appShopHotService, appShopServiceService, userAddressService, userCartService, userCollectService, appUserStoreService, configService, fileService, loginService)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpMiddlewares := server.NewHTTPMiddleware(context, authenticator, baseUserRepository, engine, userToken, authentication_Jwt)
	mcpServer, err := server.NewMcpServer(context, baseAPIRepository)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpServer, err := server.NewHTTPServer(context, httpMiddlewares, mcpServer, authService, baseApiService, baseConfigService, baseDeptService, baseDictService, baseJobService, baseLogService, baseMenuService, baseRoleService, baseUserService, commentInfoService, goodsAnalyticsService, goodsReportService, goodsCategoryService, goodsPropService, goodsInfoService, goodsSkuService, goodsSpecService, orderAnalyticsService, orderReportService, orderInfoService, payBillService, recommendRequestService, recommendGorseService, shopBannerService, shopHotService, shopServiceService, userAnalyticsService, userStoreService, workspaceService, appAuthService, baseAreaService, appBaseDictService, commentService, appGoodsCategoryService, appGoodsInfoService, appOrderInfoService, payService, recommendService, appShopBannerService, appShopHotService, appShopServiceService, userAddressService, userCartService, userCollectService, appUserStoreService, configService, fileService, loginService)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kratosApp := newApp(context, cronServer, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
