// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"shop/pkg/agent/eino/model"
	"shop/pkg/biz"
	"shop/pkg/config"
	"shop/pkg/event"
	"shop/pkg/gen/data"
	"shop/pkg/job"
	"shop/pkg/middleware"
	"shop/pkg/sse"
	"shop/server"
	base2 "shop/server/base"
	admin2 "shop/server/system/admin"
	app2 "shop/server/system/app"
	"shop/service/base"
	"shop/service/base/agent/ai"
	biz2 "shop/service/base/biz"
	"shop/service/system/admin"
	biz3 "shop/service/system/admin/biz"
	"shop/service/system/admin/codegen"
	"shop/service/system/app"
	biz4 "shop/service/system/app/biz"

	"github.com/go-kratos/kratos/v3"
	"github.com/liujitcn/kratos-kit/bootstrap"
	"github.com/liujitcn/kratos-kit/cache"
	"github.com/liujitcn/kratos-kit/database/gorm"
	"github.com/liujitcn/kratos-kit/oauth"
	"github.com/liujitcn/kratos-kit/oss"
	"github.com/liujitcn/kratos-kit/pprof"
	"github.com/liujitcn/kratos-kit/queue"

	_ "github.com/liujitcn/kratos-kit/database/gorm/driver/mysql"

	_ "github.com/liujitcn/kratos-kit/logger/zap"
)

// Injectors from wire.go:

// initApp 初始化 Kratos 应用实例。
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	configv1Data, err := config.ParseData(context)
	if err != nil {
		return nil, nil, err
	}
	data_Database := config.ParseDatabase(configv1Data)
	client, cleanup, err := gorm.NewGormClient(data_Database)
	if err != nil {
		return nil, nil, err
	}
	dataData := data.NewData(client)
	baseJobRepository := data.NewBaseJobRepository(dataData)
	registry := job.NewRegistry()
	cronServer := job.NewCronServer(baseJobRepository, registry)
	authentication_Jwt := config.ParseAuthnJWT(context)
	authenticator := middleware.NewAuthenticator(authentication_Jwt)
	baseUserRepository := data.NewBaseUserRepository(dataData)
	engine, err := middleware.NewAuthzEngine()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	data_Redis := config.ParseRedis(configv1Data)
	cacheCache, cleanup2, err := cache.NewCache(data_Redis)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userToken := middleware.NewUserToken(authentication_Jwt, cacheCache, authenticator)
	grpcMiddlewares := server.NewGRPCMiddleware(context, authenticator, baseUserRepository, engine, userToken, authentication_Jwt)
	data_Queue := config.ParseQueue(configv1Data)
	queueQueue, cleanup3, err := queue.NewQueue(data_Redis, data_Queue)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configv1Pprof, err := config.ParsePprof(context)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofPprof, err := pprof.NewPprof(configv1Pprof)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	casbinRuleRepository := data.NewCasbinRuleRepository(dataData)
	transaction := data.NewTransaction(dataData)
	baseMenuRepository := data.NewBaseMenuRepository(dataData)
	baseRoleRepository := data.NewBaseRoleRepository(dataData)
	baseTenantRepository := data.NewBaseTenantRepository(dataData)
	baseAPIRepository := data.NewBaseAPIRepository(dataData)
	baseAPICase := biz.NewBaseAPICase(baseAPIRepository)
	casbinRuleCase, err := biz.NewCasbinRuleCase(casbinRuleRepository, transaction, baseMenuRepository, baseRoleRepository, baseTenantRepository, baseAPICase, engine)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseTenantCase := biz.NewBaseTenantCase(transaction, baseRoleRepository, baseTenantRepository)
	baseCase, cleanup4, err := biz.NewBaseCase(context, cacheCache, queueQueue, client, pprofPprof, casbinRuleCase, baseAPICase, baseTenantCase)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	aiSessionRepository := data.NewAiSessionRepository(dataData)
	aiMessageRepository := data.NewAiMessageRepository(dataData)
	aiSessionCase := biz2.NewAiSessionCase(baseCase, transaction, aiSessionRepository, aiMessageRepository)
	baseUserCase := biz2.NewBaseUserCase(baseUserRepository)
	ai_Model := config.ParseAIModel(context)
	responsesClient := model.NewResponsesClient(ai_Model)
	runtime := ai.NewRuntime(responsesClient)
	aiMessageCase := biz2.NewAiMessageCase(baseCase, transaction, aiMessageRepository, aiSessionCase, baseAPIRepository, baseUserCase, runtime)
	aiSessionService := base.NewAiSessionService(aiSessionCase, aiMessageCase)
	aiToolCase := biz2.NewAiToolCase(runtime)
	aiToolService := base.NewAiToolService(aiToolCase)
	aiMessageService := base.NewAiMessageService(aiMessageCase)
	baseConfigRepository := data.NewBaseConfigRepository(dataData)
	configCase := biz2.NewConfigCase(baseConfigRepository)
	configService := base.NewConfigService(configCase)
	configv1Oss, err := config.ParseOSS(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ossOSS := oss.NewOSS(configv1Oss)
	fileCase := biz2.NewFileCase(ossOSS)
	fileService := base.NewFileService(fileCase)
	baseDeptRepository := data.NewBaseDeptRepository(dataData)
	baseDeptCase := biz2.NewBaseDeptCase(baseDeptRepository)
	baseRoleCase := biz2.NewBaseRoleCase(baseRoleRepository)
	baseDictRepository := data.NewBaseDictRepository(dataData)
	baseDictItemRepository := data.NewBaseDictItemRepository(dataData)
	loginCase := biz2.NewLoginCase(baseCase, userToken, baseDeptCase, baseRoleCase, baseUserCase, baseTenantRepository, baseDictRepository, baseDictItemRepository)
	loginService := base.NewLoginService(loginCase)
	oAuth := config.ParseOAuth(context)
	manager, err := oauth.NewManager(oAuth)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseThirdAccountRepository := data.NewBaseThirdAccountRepository(dataData)
	baseThirdAccountCase := biz2.NewBaseThirdAccountCase(baseThirdAccountRepository)
	userEvents := event.NewUserEvents()
	oauthCase := biz2.NewOauthCase(baseCase, transaction, manager, baseThirdAccountCase, baseUserCase, loginCase, userEvents)
	oauthService := base.NewOauthService(oauthCase)
	mcpServer, err := server.NewMCPHandler(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mcpCase, err := biz2.NewMcpCase(context, baseAPIRepository, mcpServer)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mcpService := base.NewMcpService(mcpCase)
	sseServer, err := base2.NewSSEHandler(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseRegistry := sse.NewRegistry()
	publisher := sse.NewPublisher(sseServer)
	codegenManager := codegen.NewManager()
	sseCase, err := biz2.NewSseCase(context, authenticator, sseServer, sseRegistry, publisher, codegenManager)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sseService := base.NewSseService(sseCase)
	services := base2.Services{
		AiSession: aiSessionService,
		AiTool:    aiToolService,
		AiMessage: aiMessageService,
		Config:    configService,
		File:      fileService,
		Login:     loginService,
		Oauth:     oauthService,
		Mcp:       mcpService,
		Sse:       sseService,
	}
	basePostRepository := data.NewBasePostRepository(dataData)
	bizBaseAPICase := biz3.NewBaseAPICase(baseCase, baseAPIRepository, authentication_Jwt)
	bizCasbinRuleCase, err := biz3.NewCasbinRuleCase(baseCase, transaction, casbinRuleRepository, baseMenuRepository, baseRoleRepository, baseTenantRepository, bizBaseAPICase)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bizBaseRoleCase := biz3.NewBaseRoleCase(baseCase, transaction, baseRoleRepository, baseTenantRepository, bizCasbinRuleCase)
	bizBaseDeptCase := biz3.NewBaseDeptCase(baseCase, baseDeptRepository)
	baseMenuCase := biz3.NewBaseMenuCase(baseCase, transaction, baseMenuRepository, baseRoleRepository, bizCasbinRuleCase)
	bizBaseUserCase := biz3.NewBaseUserCase(baseCase, transaction, baseUserRepository, baseDeptRepository, basePostRepository, bizBaseRoleCase, bizBaseDeptCase, baseMenuCase, userEvents)
	bizBaseTenantCase := biz3.NewBaseTenantCase(baseCase, transaction, baseTenantRepository, baseDeptRepository, baseRoleRepository, baseUserRepository, casbinRuleRepository, bizCasbinRuleCase, userEvents)
	authCase := biz3.NewAuthCase(baseCase, bizBaseUserCase, bizBaseRoleCase, bizBaseDeptCase, bizBaseTenantCase, baseMenuCase, fileCase)
	authService := admin.NewAuthService(authCase)
	baseApiService := admin.NewBaseApiService(bizBaseAPICase)
	baseAreaRepository := data.NewBaseAreaRepository(dataData)
	baseAreaCase := biz3.NewBaseAreaCase(baseCase, baseAreaRepository)
	baseAreaService := admin.NewBaseAreaService(baseAreaCase)
	baseConfigCase := biz3.NewBaseConfigCase(baseCase, baseConfigRepository)
	baseConfigService, err := admin.NewBaseConfigService(baseConfigCase)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseDeptService := admin.NewBaseDeptService(bizBaseDeptCase)
	baseDictItemCase := biz3.NewBaseDictItemCase(baseCase, baseDictRepository, baseDictItemRepository)
	baseDictCase := biz3.NewBaseDictCase(baseCase, baseDictRepository, baseDictItemCase)
	baseDictService := admin.NewBaseDictService(baseDictCase, baseDictItemCase)
	baseJobLogRepository := data.NewBaseJobLogRepository(dataData)
	baseJobLogCase := biz3.NewBaseJobLogCase(baseCase, baseJobLogRepository)
	baseJobCase := biz3.NewBaseJobCase(baseCase, baseJobRepository, baseJobLogCase, cronServer)
	baseJobService := admin.NewBaseJobService(baseJobCase, baseJobLogCase)
	baseLogRepository := data.NewBaseLogRepository(dataData)
	baseLogCase := biz3.NewBaseLogCase(baseCase, baseLogRepository)
	baseLogService := admin.NewBaseLogService(baseLogCase)
	baseMenuService := admin.NewBaseMenuService(baseMenuCase)
	basePostCase := biz3.NewBasePostCase(baseCase, transaction, basePostRepository, baseUserRepository)
	basePostService := admin.NewBasePostService(basePostCase)
	baseRoleService := admin.NewBaseRoleService(bizBaseRoleCase)
	baseTenantService := admin.NewBaseTenantService(bizBaseTenantCase)
	baseUserService := admin.NewBaseUserService(bizBaseUserCase)
	codeGenTableRepository := data.NewCodeGenTableRepository(dataData)
	codeGenColumnRepository := data.NewCodeGenColumnRepository(dataData)
	codeGenColumnCase := biz3.NewCodeGenColumnCase(codeGenColumnRepository, client, transaction, baseDictRepository, codeGenTableRepository)
	codeGenProtoRepository := data.NewCodeGenProtoRepository(dataData)
	codeGenProtoCase := biz3.NewCodeGenProtoCase(codeGenProtoRepository, transaction, baseAPIRepository, codeGenTableRepository, codeGenColumnCase)
	codeGenTableCase := biz3.NewCodeGenTableCase(codeGenTableRepository, client, transaction, baseDictRepository, baseDictItemRepository, baseMenuCase, codeGenColumnCase, codeGenProtoCase)
	codeGenCase := biz3.NewCodeGenCase(baseCase, transaction, bizBaseAPICase, codeGenTableCase, codeGenColumnCase, codeGenProtoCase, baseMenuCase, codegenManager)
	codeGenService := admin.NewCodeGenService(codeGenCase)
	codeGenColumnService := admin.NewCodeGenColumnService(codeGenColumnCase)
	codeGenProtoService := admin.NewCodeGenProtoService(codeGenProtoCase)
	codeGenTableService := admin.NewCodeGenTableService(codeGenTableCase)
	adminServices := admin2.Services{
		Auth:          authService,
		BaseAPI:       baseApiService,
		BaseArea:      baseAreaService,
		BaseConfig:    baseConfigService,
		BaseDept:      baseDeptService,
		BaseDict:      baseDictService,
		BaseJob:       baseJobService,
		BaseLog:       baseLogService,
		BaseMenu:      baseMenuService,
		BasePost:      basePostService,
		BaseRole:      baseRoleService,
		BaseTenant:    baseTenantService,
		BaseUser:      baseUserService,
		CodeGen:       codeGenService,
		CodeGenColumn: codeGenColumnService,
		CodeGenProto:  codeGenProtoService,
		CodeGenTable:  codeGenTableService,
	}
	baseUserCase2 := biz4.NewBaseUserCase(baseCase, baseUserRepository)
	bizAuthCase := biz4.NewAuthCase(baseCase, baseUserCase2, manager, userEvents)
	appAuthService := app.NewAuthService(bizAuthCase)
	bizBaseAreaCase := biz4.NewBaseAreaCase(baseCase, baseAreaRepository)
	appBaseAreaService := app.NewBaseAreaService(bizBaseAreaCase)
	bizBaseDictItemCase := biz4.NewBaseDictItemCase(baseCase, baseDictRepository, baseDictItemRepository)
	bizBaseDictCase := biz4.NewBaseDictCase(baseCase, baseDictRepository, bizBaseDictItemCase)
	appBaseDictService := app.NewBaseDictService(bizBaseDictCase)
	appServices := app2.Services{
		Auth:     appAuthService,
		BaseArea: appBaseAreaService,
		BaseDict: appBaseDictService,
	}
	modules, err := newModules(services, adminServices, appServices)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mcpToolsReady := server.NewMCPToolsReady(mcpServer, modules)
	agentToolsReady, err := server.NewAgentToolsReady(runtime, modules)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcServer, err := server.NewGRPCServer(context, grpcMiddlewares, modules, mcpToolsReady, agentToolsReady)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appInfo := config.GetAppInfo(context)
	httpMiddlewares := server.NewHTTPMiddleware(context, authenticator, baseUserRepository, engine, userToken, authentication_Jwt)
	httpServer, err := server.NewHTTPServer(context, appInfo, httpMiddlewares, modules, authenticator, userToken, mcpToolsReady, agentToolsReady)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kratosApp := newApp(context, cronServer, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
