// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: base/v1/config.proto

/* eslint-disable */
import type { BaseConfigSite } from "../../common/v1/enum";

/** 获取系统配置条件 */
export interface GetConfigRequest {
  /** 位置：枚举【BaseConfigSite】 */
  site: BaseConfigSite;
}

/** 系统配置项 */
export interface ConfigItem {
  /** 配置key */
  key: string;
  /** 配置value */
  value: string;
}

/** 系统配置查询结果 */
export interface GetConfigResponse {
  /** 系统配置列表 */
  configs: ConfigItem[];
}

/** Base系统配置公共服务 */
export interface ConfigService {
  /** 获取系统配置 */
  GetConfig(request: GetConfigRequest): Promise<GetConfigResponse>;
}
