// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: base/v1/mcp.proto

/* eslint-disable */
import type { McpTerminal } from "../../common/v1/enum";
import type { Empty } from "../../google/protobuf/empty";

/** MCP请求参数 */
export interface HandleMcpRequest {
  /** 终端类型 */
  terminal: McpTerminal;
}

/** Base MCP服务 */
export interface McpService {
  /** 处理MCP Streamable HTTP请求 */
  HandleMcp(request: HandleMcpRequest): Promise<Empty>;
}
