// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/auth.proto

package app

import (
	"context"

	"shop/api/gen/go/app"
	"shop/pkg/errorsx"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// AuthService 用户登录认证服务
type AuthService struct {
	app.UnimplementedAuthServiceServer
	authCase *biz.AuthCase
}

// NewAuthService 创建用户登录认证服务
func NewAuthService(
	authCase *biz.AuthCase,
) *AuthService {
	var ss = AuthService{
		authCase: authCase,
	}
	return &ss
}

// WechatLogin 微信登录
func (s *AuthService) WechatLogin(ctx context.Context, req *app.WechatLoginRequest) (*app.WechatLoginResponse, error) {
	res, err := s.authCase.WechatLogin(ctx, req)
	if err != nil {
		log.Errorf("WechatLogin %v", err)
		return nil, errorsx.WrapInternal(err, "登录失败")
	}
	return res, nil
}

// GetUserProfile 获取已经登录的用户数据
func (s *AuthService) GetUserProfile(ctx context.Context, req *emptypb.Empty) (*app.UserProfileForm, error) {
	res, err := s.authCase.GetUserProfile(ctx)
	if err != nil {
		log.Errorf("GetUserProfile %v", err)
		return nil, errorsx.WrapInternal(err, "获取用户信息失败")
	}
	return res, nil
}

// UpdateUserProfile 修改个人中心用户信息
func (s *AuthService) UpdateUserProfile(ctx context.Context, req *app.UserProfileForm) (*emptypb.Empty, error) {
	err := s.authCase.UpdateUserProfile(ctx, req)
	if err != nil {
		log.Errorf("UpdateUserProfile %v", err)
		return nil, errorsx.WrapInternal(err, "修改个人中心用户信息失败")
	}
	return new(emptypb.Empty), nil
}

// BindUserPhone 手机号授权
func (s *AuthService) BindUserPhone(ctx context.Context, req *app.BindUserPhoneRequest) (*app.BindUserPhoneResponse, error) {
	res, err := s.authCase.BindUserPhone(ctx, req)
	if err != nil {
		log.Errorf("BindUserPhone %v", err)
		return nil, errorsx.WrapInternal(err, "手机号授权失败")
	}
	return res, nil
}
