// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/auth.proto

package app

import (
	"context"
	"errors"

	"shop/api/gen/go/app"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// AuthService 用户登录认证服务
type AuthService struct {
	app.UnimplementedAuthServiceServer
	authCase *biz.AuthCase
}

// NewAuthService 创建用户登录认证服务
func NewAuthService(
	authCase *biz.AuthCase,
) *AuthService {
	var ss = AuthService{
		authCase: authCase,
	}
	return &ss
}

// WxLogin 微信登录
func (s *AuthService) WxLogin(ctx context.Context, req *app.WxLoginRequest) (*app.WxLoginResponse, error) {
	res, err := s.authCase.WxLogin(ctx, req)
	if err != nil {
		log.Error("WxLogin err:", err.Error())
		return nil, errors.New("登录失败")
	}
	return res, nil
}

// GetUserInfo 获取已经登录的用户数据
func (s *AuthService) GetUserInfo(ctx context.Context, req *emptypb.Empty) (*app.UserInfo, error) {
	res, err := s.authCase.GetUserInfo(ctx)
	if err != nil {
		log.Error("GetUserInfo err:", err.Error())
		return nil, err
	}
	return res, nil
}

// UpdateUserInfo 修改个人中心用户信息
func (s *AuthService) UpdateUserInfo(ctx context.Context, req *app.UpdateUserInfoRequest) (*emptypb.Empty, error) {
	err := s.authCase.UpdateUserInfo(ctx, req)
	if err != nil {
		log.Error("UpdateUserInfo err:", err.Error())
		return nil, errors.New("修改个人中心用户信息失败")
	}
	return new(emptypb.Empty), nil
}

// PhoneAuth 手机号授权
func (s *AuthService) PhoneAuth(ctx context.Context, req *app.PhoneAuthRequest) (*app.PhoneAuthResponse, error) {
	res, err := s.authCase.PhoneAuth(ctx, req)
	if err != nil {
		log.Error("PhoneAuth err:", err.Error())
		return nil, err
	}
	return res, nil
}
