// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/base_area.proto

package app

import (
	"context"
	"errors"

	"shop/api/gen/go/app"
	"shop/api/gen/go/common"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseAreaService 行政区域服务
type BaseAreaService struct {
	app.UnimplementedBaseAreaServiceServer
	baseAreaCase *biz.BaseAreaCase
}

// NewBaseAreaService 创建行政区域服务
func NewBaseAreaService(
	baseAreaCase *biz.BaseAreaCase,
) *BaseAreaService {
	var ss = BaseAreaService{
		baseAreaCase: baseAreaCase,
	}
	return &ss
}

// TreeBaseArea 查询行政区域树形列表
func (s *BaseAreaService) TreeBaseArea(ctx context.Context, req *emptypb.Empty) (*common.AppTreeOptionResponse, error) {
	tree, err := s.baseAreaCase.TreeBaseArea(ctx)
	if err != nil {
		log.Error("TreeBaseArea err:", err.Error())
		return nil, errors.New("查询行政区域树形列表失败")
	}

	return tree, nil
}
