// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/base_dict.proto

package app

import (
	"context"
	"errors"

	"shop/api/gen/go/app"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseDictService 字典服务
type BaseDictService struct {
	app.UnimplementedBaseDictServiceServer
	baseDictCase *biz.BaseDictCase
}

// NewBaseDictService 创建字典服务
func NewBaseDictService(
	baseDictCase *biz.BaseDictCase,
) *BaseDictService {
	var ss = BaseDictService{
		baseDictCase: baseDictCase,
	}
	return &ss
}

// ListBaseDict 查询字典列表
func (s *BaseDictService) ListBaseDict(ctx context.Context, req *wrapperspb.StringValue) (*app.ListBaseDictResponse, error) {
	res, err := s.baseDictCase.ListBaseDict(ctx, req.GetValue())
	if err != nil {
		log.Error("ListBaseDict err:", err.Error())
		return nil, errors.New("查询失败")
	}
	return res, nil
}
