// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/goods_category.proto

package app

import (
	"context"
	"errors"

	"shop/api/gen/go/app"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsCategoryService 商品分类服务
type GoodsCategoryService struct {
	app.UnimplementedGoodsCategoryServiceServer
	goodsCategoryCase *biz.GoodsCategoryCase
}

// NewGoodsCategoryService 创建商品分类服务
func NewGoodsCategoryService(
	goodsCategoryCase *biz.GoodsCategoryCase,
) *GoodsCategoryService {
	var ss = GoodsCategoryService{
		goodsCategoryCase: goodsCategoryCase,
	}
	return &ss
}

// ListGoodsCategory 查询分类列表
func (s *GoodsCategoryService) ListGoodsCategory(ctx context.Context, req *app.ListGoodsCategoryRequest) (*app.ListGoodsCategoryResponse, error) {
	res, err := s.goodsCategoryCase.ListGoodsCategory(ctx, req)
	if err != nil {
		log.Error("ListGoodsCategory err:", err.Error())
		return nil, errors.New("查询分类列表失败")
	}
	return res, nil
}
