// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: app/app.proto

package app

import (
	"context"

	"shop/api/gen/go/app"
	"shop/pkg/errorsx"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// PayService 支付服务
type PayService struct {
	app.UnimplementedPayServiceServer
	payCase *biz.PayCase
}

// NewPayService 创建支付服务
func NewPayService(
	payCase *biz.PayCase,
) *PayService {
	var ss = PayService{
		payCase: payCase,
	}
	return &ss
}

// JsapiPay 小程序支付
func (s *PayService) JsapiPay(ctx context.Context, req *app.JsapiPayRequest) (*app.JsapiPayResponse, error) {
	res, err := s.payCase.JsapiPay(ctx, req)
	if err != nil {
		log.Errorf("JsapiPay %v", err)
		return nil, errorsx.WrapInternal(err, "支付失败")
	}
	return res, nil
}

// H5Pay H5支付
func (s *PayService) H5Pay(ctx context.Context, req *app.H5PayRequest) (*app.H5PayResponse, error) {
	res, err := s.payCase.H5Pay(ctx, req)
	if err != nil {
		log.Errorf("H5Pay %v", err)
		return nil, errorsx.WrapInternal(err, "支付失败")
	}
	return res, nil
}

// PayNotify 支付通知。
func (s *PayService) PayNotify(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	err := s.payCase.PayNotify(ctx)
	if err != nil {
		log.Errorf("PayNotify %v", err)
		return nil, errorsx.WrapInternal(err, "通知失败")
	}
	return new(emptypb.Empty), nil
}
