// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/shop_service.proto

package app

import (
	"context"
	"errors"

	"shop/api/gen/go/app"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// ShopServiceService 商城服务说明服务
type ShopServiceService struct {
	app.UnimplementedShopServiceServiceServer
	shopServiceCase *biz.ShopServiceCase
}

// NewShopServiceService 创建商城服务说明服务
func NewShopServiceService(
	shopServiceCase *biz.ShopServiceCase,
) *ShopServiceService {
	var ss = ShopServiceService{
		shopServiceCase: shopServiceCase,
	}
	return &ss
}

// ListShopService 查询商城服务列表
func (s *ShopServiceService) ListShopService(ctx context.Context, req *emptypb.Empty) (*app.ListShopServiceResponse, error) {
	res, err := s.shopServiceCase.ListShopService(ctx)
	if err != nil {
		log.Error("ListShopService err:", err.Error())
		return nil, errors.New("查询商城服务列表失败")
	}
	return res, nil
}
