// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/shop_banner.proto

package app

import (
	"context"

	appv1 "shop/api/gen/go/app/v1"
	"shop/pkg/errorsx"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

// ShopBannerService 商城轮播图服务
type ShopBannerService struct {
	appv1.UnimplementedShopBannerServiceServer
	shopBannerCase *biz.ShopBannerCase
}

// NewShopBannerService 创建商城轮播图服务
func NewShopBannerService(
	shopBannerCase *biz.ShopBannerCase,
) *ShopBannerService {
	var ss = ShopBannerService{
		shopBannerCase: shopBannerCase,
	}
	return &ss
}

// ListShopBanners 查询商城轮播图列表
func (s *ShopBannerService) ListShopBanners(ctx context.Context, req *appv1.ListShopBannersRequest) (*appv1.ListShopBannersResponse, error) {
	res, err := s.shopBannerCase.ListShopBanners(ctx, req)
	if err != nil {
		log.Errorf("ListShopBanners %v", err)
		return nil, errorsx.WrapInternal(err, "查询商城轮播图列表失败")
	}
	return res, nil
}
