// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/user_address.proto

package app

import (
	"context"

	"shop/api/gen/go/app"
	"shop/pkg/errorsx"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// UserAddressService 用户地址管理服务
type UserAddressService struct {
	app.UnimplementedUserAddressServiceServer
	userAddressCase *biz.UserAddressCase
}

// NewUserAddressService 创建用户地址管理服务
func NewUserAddressService(
	userAddressCase *biz.UserAddressCase,
) *UserAddressService {
	var ss = UserAddressService{
		userAddressCase: userAddressCase,
	}
	return &ss
}

// ListUserAddress 查询用户地址列表
func (s *UserAddressService) ListUserAddress(ctx context.Context, req *emptypb.Empty) (*app.ListUserAddressResponse, error) {
	res, err := s.userAddressCase.ListUserAddress(ctx)
	if err != nil {
		log.Errorf("ListUserAddress %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户地址列表失败")
	}

	return res, nil
}

// GetUserAddress 查询用户地址
func (s *UserAddressService) GetUserAddress(ctx context.Context, req *wrapperspb.Int64Value) (*app.UserAddressForm, error) {
	userAddress, err := s.userAddressCase.GetUserAddress(ctx, req.GetValue())
	if err != nil {
		log.Errorf("GetUserAddress %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户地址失败")
	}

	return userAddress, nil
}

// CreateUserAddress 创建用户地址
func (s *UserAddressService) CreateUserAddress(ctx context.Context, req *app.UserAddressForm) (*emptypb.Empty, error) {
	err := s.userAddressCase.CreateUserAddress(ctx, req)
	if err != nil {
		log.Errorf("CreateUserAddress %v", err)
		return nil, errorsx.WrapInternal(err, "创建用户地址失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateUserAddress 更新用户地址
func (s *UserAddressService) UpdateUserAddress(ctx context.Context, req *app.UserAddressForm) (*emptypb.Empty, error) {
	err := s.userAddressCase.UpdateUserAddress(ctx, req)
	if err != nil {
		log.Errorf("UpdateUserAddress %v", err)
		return nil, errorsx.WrapInternal(err, "更新用户地址失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteUserAddress 删除用户地址
func (s *UserAddressService) DeleteUserAddress(ctx context.Context, req *wrapperspb.Int64Value) (*emptypb.Empty, error) {
	err := s.userAddressCase.DeleteUserAddress(ctx, req.GetValue())
	if err != nil {
		log.Errorf("DeleteUserAddress %v", err)
		return nil, errorsx.WrapInternal(err, "删除用户地址失败")
	}
	return new(emptypb.Empty), nil
}
