// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/user_store.proto

package app

import (
	"context"

	appv1 "shop/api/gen/go/app/v1"
	"shop/pkg/errorsx"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// UserStoreService 用户门店管理服务
type UserStoreService struct {
	appv1.UnimplementedUserStoreServiceServer
	userStoreCase *biz.UserStoreCase
}

// NewUserStoreService 创建用户门店管理服务
func NewUserStoreService(
	userStoreCase *biz.UserStoreCase,
) *UserStoreService {
	var ss = UserStoreService{
		userStoreCase: userStoreCase,
	}
	return &ss
}

// GetUserStore 查询用户门店
func (s *UserStoreService) GetUserStore(ctx context.Context, req *appv1.GetUserStoreRequest) (*appv1.UserStore, error) {
	res, err := s.userStoreCase.GetUserStore(ctx)
	if err != nil {
		log.Errorf("GetUserStore %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户门店失败")
	}
	return res, nil
}

// CreateUserStore 创建用户门店
func (s *UserStoreService) CreateUserStore(ctx context.Context, req *appv1.CreateUserStoreRequest) (*emptypb.Empty, error) {
	userStore := req.GetUserStore()
	// 请求体未携带门店表单时，使用空表单交由业务层按原有校验处理。
	if userStore == nil {
		userStore = &appv1.UserStoreForm{}
	}
	err := s.userStoreCase.CreateUserStore(ctx, userStore)
	if err != nil {
		log.Errorf("CreateUserStore %v", err)
		return nil, errorsx.WrapInternal(err, "创建用户门店失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateUserStore 更新用户门店
func (s *UserStoreService) UpdateUserStore(ctx context.Context, req *appv1.UpdateUserStoreRequest) (*emptypb.Empty, error) {
	userStore := req.GetUserStore()
	// 请求体未携带门店表单时，使用空表单交由业务层按原有校验处理。
	if userStore == nil {
		userStore = &appv1.UserStoreForm{}
	}
	// 路径中的门店编号优先作为本次更新目标，避免 body 漏传 ID。
	if userStore.GetId() == 0 {
		userStore.Id = req.GetId()
	}
	err := s.userStoreCase.UpdateUserStore(ctx, userStore)
	if err != nil {
		log.Errorf("UpdateUserStore %v", err)
		return nil, errorsx.WrapInternal(err, "更新用户门店失败")
	}
	return new(emptypb.Empty), nil
}
