// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/user_address.proto

package app

import (
	"context"

	appv1 "shop/api/gen/go/app/v1"
	"shop/pkg/errorsx"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// UserAddressService 用户地址管理服务
type UserAddressService struct {
	appv1.UnimplementedUserAddressServiceServer
	userAddressCase *biz.UserAddressCase
}

// NewUserAddressService 创建用户地址管理服务
func NewUserAddressService(
	userAddressCase *biz.UserAddressCase,
) *UserAddressService {
	var ss = UserAddressService{
		userAddressCase: userAddressCase,
	}
	return &ss
}

// ListUserAddresses 查询用户地址列表
func (s *UserAddressService) ListUserAddresses(ctx context.Context, req *appv1.ListUserAddressesRequest) (*appv1.ListUserAddressesResponse, error) {
	res, err := s.userAddressCase.ListUserAddresses(ctx)
	if err != nil {
		log.Errorf("ListUserAddresses %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户地址列表失败")
	}

	return res, nil
}

// GetUserAddress 查询用户地址
func (s *UserAddressService) GetUserAddress(ctx context.Context, req *appv1.GetUserAddressRequest) (*appv1.UserAddressForm, error) {
	userAddress, err := s.userAddressCase.GetUserAddress(ctx, req.GetId())
	if err != nil {
		log.Errorf("GetUserAddress %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户地址失败")
	}

	return userAddress, nil
}

// CreateUserAddress 创建用户地址
func (s *UserAddressService) CreateUserAddress(ctx context.Context, req *appv1.CreateUserAddressRequest) (*emptypb.Empty, error) {
	userAddress := req.GetUserAddress()
	// 请求体未携带地址时，使用空表单交由业务层按原有校验处理。
	if userAddress == nil {
		userAddress = &appv1.UserAddressForm{}
	}
	err := s.userAddressCase.CreateUserAddress(ctx, userAddress)
	if err != nil {
		log.Errorf("CreateUserAddress %v", err)
		return nil, errorsx.WrapInternal(err, "创建用户地址失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateUserAddress 更新用户地址
func (s *UserAddressService) UpdateUserAddress(ctx context.Context, req *appv1.UpdateUserAddressRequest) (*emptypb.Empty, error) {
	userAddress := req.GetUserAddress()
	// 请求体未携带地址时，使用空表单交由业务层按原有校验处理。
	if userAddress == nil {
		userAddress = &appv1.UserAddressForm{}
	}
	// 路径中的地址编号优先作为本次更新目标，避免 body 漏传 ID。
	if userAddress.GetId() == 0 {
		userAddress.Id = req.GetId()
	}
	err := s.userAddressCase.UpdateUserAddress(ctx, userAddress)
	if err != nil {
		log.Errorf("UpdateUserAddress %v", err)
		return nil, errorsx.WrapInternal(err, "更新用户地址失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteUserAddress 删除用户地址
func (s *UserAddressService) DeleteUserAddress(ctx context.Context, req *appv1.DeleteUserAddressRequest) (*emptypb.Empty, error) {
	err := s.userAddressCase.DeleteUserAddress(ctx, req.GetId())
	if err != nil {
		log.Errorf("DeleteUserAddress %v", err)
		return nil, errorsx.WrapInternal(err, "删除用户地址失败")
	}
	return new(emptypb.Empty), nil
}
