// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: app/user_cart.proto

package app

import (
	"context"

	"shop/api/gen/go/app"
	"shop/pkg/errorsx"
	"shop/service/app/biz"

	"github.com/go-kratos/kratos/v2/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// UserCartService 用户购物车管理服务
type UserCartService struct {
	app.UnimplementedUserCartServiceServer
	userCartCase *biz.UserCartCase
}

// NewUserCartService 创建用户购物车管理服务
func NewUserCartService(
	userCartCase *biz.UserCartCase,
) *UserCartService {
	var ss = UserCartService{
		userCartCase: userCartCase,
	}
	return &ss
}

// CountUserCart 查询用户购物车数量
func (s *UserCartService) CountUserCart(ctx context.Context, req *emptypb.Empty) (*wrapperspb.Int32Value, error) {
	count, err := s.userCartCase.CountUserCart(ctx)
	if err != nil {
		log.Errorf("CountUserCart %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户购物车数量失败")
	}
	return &wrapperspb.Int32Value{
		Value: int32(count),
	}, nil
}

// ListUserCart 查询用户购物车列表
func (s *UserCartService) ListUserCart(ctx context.Context, req *emptypb.Empty) (*app.ListUserCartResponse, error) {
	res, err := s.userCartCase.ListUserCart(ctx)
	if err != nil {
		log.Errorf("ListUserCart %v", err)
		return nil, errorsx.WrapInternal(err, "查询用户购物车列表失败")
	}
	return res, nil
}

// CreateUserCart 创建用户购物车
func (s *UserCartService) CreateUserCart(ctx context.Context, req *app.CreateUserCartRequest) (*emptypb.Empty, error) {
	err := s.userCartCase.CreateUserCart(ctx, req)
	if err != nil {
		log.Errorf("CreateUserCart %v", err)
		return nil, errorsx.WrapInternal(err, "加入购物车失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateUserCart 更新用户购物车
func (s *UserCartService) UpdateUserCart(ctx context.Context, req *app.UserCartForm) (*emptypb.Empty, error) {
	err := s.userCartCase.UpdateUserCart(ctx, req)
	if err != nil {
		log.Errorf("UpdateUserCart %v", err)
		return nil, errorsx.WrapInternal(err, "更新购物车失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteUserCart 删除用户购物车
func (s *UserCartService) DeleteUserCart(ctx context.Context, req *wrapperspb.Int64Value) (*emptypb.Empty, error) {
	err := s.userCartCase.DeleteUserCart(ctx, req.GetValue())
	if err != nil {
		log.Errorf("DeleteUserCart %v", err)
		return nil, errorsx.WrapInternal(err, "删除用户购物车失败")
	}
	return new(emptypb.Empty), nil
}

// SetUserCartStatus 设置购物车选中状态
func (s *UserCartService) SetUserCartStatus(ctx context.Context, req *app.SetUserCartStatusRequest) (*emptypb.Empty, error) {
	err := s.userCartCase.SetUserCartStatus(ctx, req)
	if err != nil {
		log.Errorf("SetUserCartStatus %v", err)
		return nil, errorsx.WrapInternal(err, "更新购物车失败")
	}
	return new(emptypb.Empty), nil
}

// SetUserCartSelection 设置购物车全选状态
func (s *UserCartService) SetUserCartSelection(ctx context.Context, req *app.SetUserCartSelectionRequest) (*emptypb.Empty, error) {
	err := s.userCartCase.SetUserCartSelection(ctx, req.GetIsChecked())
	if err != nil {
		log.Errorf("SetUserCartSelection %v", err)
		return nil, errorsx.WrapInternal(err, "设置全选失败")
	}
	return new(emptypb.Empty), nil
}
