// Code generated by protoc-gen-go-service.
// versions:
// - protoc-gen-go-service v0.0.1
// - protoc             (unknown)
// source: admin/goods_category.proto

package admin

import (
	"context"
	"fmt"

	commonv1 "shop/api/gen/go/common/v1"
	shopadminv1 "shop/api/gen/go/shop/admin/v1"
	"shop/pkg/errorsx"
	"shop/service/shop/admin/biz"

	"github.com/go-kratos/kratos/v3/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsCategoryService Admin商品分类服务
type GoodsCategoryService struct {
	shopadminv1.UnimplementedGoodsCategoryServiceServer
	goodsCategoryCase *biz.GoodsCategoryCase
}

// NewGoodsCategoryService 创建Admin商品分类服务
func NewGoodsCategoryService(
	categoryCase *biz.GoodsCategoryCase,
) *GoodsCategoryService {
	return &GoodsCategoryService{
		goodsCategoryCase: categoryCase,
	}
}

// TreeGoodsCategory 查询商品分类树形列表
func (s *GoodsCategoryService) TreeGoodsCategory(ctx context.Context, req *shopadminv1.TreeGoodsCategoryRequest) (*shopadminv1.TreeGoodsCategoryResponse, error) {
	tree, err := s.goodsCategoryCase.TreeGoodsCategory(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("TreeGoodsCategory %v", err))
		return nil, errorsx.WrapInternal(err, "查询商品分类树形列表失败")
	}

	return tree, nil
}

// OptionGoodsCategory 查询商品分类树形选择
func (s *GoodsCategoryService) OptionGoodsCategory(ctx context.Context, req *shopadminv1.OptionGoodsCategoryRequest) (*commonv1.TreeOptionResponse, error) {
	tree, err := s.goodsCategoryCase.OptionGoodsCategory(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("OptionGoodsCategory %v", err))
		return nil, errorsx.WrapInternal(err, "查询商品分类树形选择失败")
	}
	return tree, nil
}

// GetGoodsCategory 查询商品分类
func (s *GoodsCategoryService) GetGoodsCategory(ctx context.Context, req *shopadminv1.GetGoodsCategoryRequest) (*shopadminv1.GoodsCategoryForm, error) {
	goodsCategory, err := s.goodsCategoryCase.GetGoodsCategory(ctx, req.GetId())
	if err != nil {
		log.Error(fmt.Sprintf("GetGoodsCategory %v", err))
		return nil, errorsx.WrapInternal(err, "查询商品分类失败")
	}
	return goodsCategory, nil
}

// CreateGoodsCategory 创建商品分类
func (s *GoodsCategoryService) CreateGoodsCategory(ctx context.Context, req *shopadminv1.CreateGoodsCategoryRequest) (*emptypb.Empty, error) {
	err := s.goodsCategoryCase.CreateGoodsCategory(ctx, req.GetGoodsCategory())
	if err != nil {
		log.Error(fmt.Sprintf("CreateGoodsCategory %v", err))
		return nil, errorsx.WrapInternal(err, "创建商品分类失败")
	}
	return new(emptypb.Empty), nil
}

// UpdateGoodsCategory 更新商品分类
func (s *GoodsCategoryService) UpdateGoodsCategory(ctx context.Context, req *shopadminv1.UpdateGoodsCategoryRequest) (*emptypb.Empty, error) {
	err := s.goodsCategoryCase.UpdateGoodsCategory(ctx, req.GetGoodsCategory())
	if err != nil {
		log.Error(fmt.Sprintf("UpdateGoodsCategory %v", err))
		return nil, errorsx.WrapInternal(err, "更新商品分类失败")
	}
	return new(emptypb.Empty), nil
}

// DeleteGoodsCategory 删除商品分类
func (s *GoodsCategoryService) DeleteGoodsCategory(ctx context.Context, req *shopadminv1.DeleteGoodsCategoryRequest) (*emptypb.Empty, error) {
	err := s.goodsCategoryCase.DeleteGoodsCategory(ctx, req.GetIds())
	if err != nil {
		log.Error(fmt.Sprintf("DeleteGoodsCategory %v", err))
		return nil, errorsx.WrapInternal(err, "删除商品分类失败")
	}
	return new(emptypb.Empty), nil
}

// SetGoodsCategoryStatus 设置状态
func (s *GoodsCategoryService) SetGoodsCategoryStatus(ctx context.Context, req *shopadminv1.SetGoodsCategoryStatusRequest) (*emptypb.Empty, error) {
	err := s.goodsCategoryCase.SetGoodsCategoryStatus(ctx, req)
	if err != nil {
		log.Error(fmt.Sprintf("SetGoodsCategoryStatus %v", err))
		return nil, errorsx.WrapInternal(err, "设置状态失败")
	}
	return new(emptypb.Empty), nil
}
