authn:
  jwt:
    secret: Admin@Server
    access_token_expires: 3600s
    refresh_token_expires: 2592000s
    white_list:
      prefix:
      regex:
      path:
      match:
        - "/base.v1.ConfigService/GetConfig"
        - "/base.v1.LoginService/Captcha"
        - "/base.v1.LoginService/VerifyCaptcha"
        - "/base.v1.LoginService/PasswordPublicKey"
        - "/base.v1.LoginService/RefreshToken"
        - "/base.v1.LoginService/Login"
        - "/base.v1.OauthService/ListOauthProvider"
        - "/base.v1.OauthService/CreateOauthAuthorization"
        - "/base.v1.OauthService/HandleOauthCallback"
        - "/base.v1.OauthService/ExchangeOauthTicket"
        - "/base.v1.OauthService/CreateOauthSession"
        - "/base.v1.OauthService/HandleOauthBindingCallback"
        - "/base.v1.SseService/SubscribeSse"
    optional_auth:
      prefix:
      regex:
      path:
      match:
